### ISSUE TITLE
Implement replay recording

### ISSUE THREAD

**Issue by basro** [haxball/haxball-issues#1]
Feature exists in flash version but isn't implemented in html5.

**Comment by Lidorx** [comment]
wait so there will not be a replay feature in html haxball? or only in the alpha version?

**Comment by basro** [comment]
It will definitely be implemented, this issue is here to track that.
All flash features will be implemented, the flash-feature tag is for them.

**Comment by Lidorx** [comment]
aight ok! ty for answering really fast!. btw I just wanted to say that the new sound when u shoot the ball is pretty annoying idk if u changed it on purpose but it sounds pretty bad . overall I really like it. :+1:

**Comment by basro** [comment]
Sound change is a valid complaint but not related to this issue. Feel free to open an new issue about it.

**Comment by Lidorx** [comment]
ok.. so about the replays.. can u add it to the alpha? because if people wanted to play this version of haxball in leagues they wouldnt be able to.. because u have to rec everygame u play..

**Comment by basro** [comment]
This is now implemented.
