### ISSUE TITLE
Issues with Connection to the room

### ISSUE THREAD

**Issue by shaxlele** [haxball/haxball-issues#10]
I can't join any room, I tried that a lot and it didn't happen nothing, I hope you can fix it as faster as you can, thanks!

**Comment by saviola777** [comment]
It's useful to include information like which browser you used etc. in such a report, otherwise it will be hard to reproduce / fix.

**Comment by basro** [comment]
Please check if players can join you when you are the room host.

**Comment by shaxlele** [comment]
Yes, I tried and players joined to me

**Comment by saviola777** [comment]
http://html5.haxball.com/reverse_setting.html Try this then.

**Comment by shaxlele** [comment]
Alright, I tried and it helped, thanks :)

**Comment by basro** [comment]
@saviola777: I appreciate your help, thanks
