### ISSUE TITLE
Admins unable to move players

### ISSUE THREAD

**Issue by saviola777** [haxball/haxball-issues#100]
In some situations, people with admin rights in a room are unable to move players (as seen [here](https://gyazo.com/620864af635fdcdd3e38454009a2608d)). It works fine in other rooms. In this case it occured in Firefox.

Has anyone else encountered this problem?

I have not found a way to reproduce it.

**Comment by basro** [comment]
Do you know if you were still able to right-click on the users to get the admin menu?

**Comment by basro** [comment]
Also:
Did this affect all admins in the room or just one?
Did this ever correct itself while inside of the room?

**Comment by saviola777** [comment]
It affected only that one user, not the other admins in the room.

It did not correct itself – I'm not sure if re-joining the room would have fixed it and I'm not sure if the right-click menu was still there (since it did not happen to me personally), I will try to get a hold of the person it happened to and ask them.

**Comment by saviola777** [comment]
The right-click menu still worked. He hosted his own room after that (without refreshing the page) and the problem was the same. I seems the problem does not persist after refreshing / re-opening the page though.

**Comment by basro** [comment]
Did this bug continue to happen?

**Comment by saviola777** [comment]
Not to me, but I haven't played a lot since then.

Since nobody else reported similar problems I will just close this and chalk it up to some old browser version or other issue specific to that user's system.
