### ISSUE TITLE
Haxball uses GPU or CPU?

### ISSUE THREAD

**Issue by spr1907** [haxball/haxball-issues#1002]
Hey Basro just wondered this. I'm planning to upgrade my computer in order to get better experience in Haxball and I was wondering about which one I should upgrade. The game renders stuff on GPU or CPU?

**Comment by ivanfeli** [comment]
My GPU usage goes from ~6% to ~12% when I open an empty haxball room and CPU usage jumps from ~20% to ~30%.

So it uses both but any decent computer should be able to run Haxball fine, it's just a 2d game.
