### ISSUE TITLE
haxball linux vps

### ISSUE THREAD

**Issue by orenball** [haxball/haxball-issues#1013]
today i bought an israeli vps on linux and opened an headless host room from the vps and when i tried joining from my main remote it didnt work
no one can join the room not only me
is there someone who might know what do i need to do?

**Comment by basro** [comment]
Recently most browsers have released a privacy feature that breaks WebRTC if your computer is not behind a NAT. It's probable that this is the cause of your problem.

There's a section added to the headless host documentation that explains how to solve it in chrome:
https://github.com/haxball/haxball-issues/wiki/Headless-Host#connectivity-warning

**Comment by orenball** [comment]
> 
> 
> Recently most browsers have released a privacy feature that will break WebRTC if your computer is not behind a NAT. It's probable that this is the cause of your problem.
> 
> There's a section added to the headless host documentation that explains how to solve it in chrome:
> https://github.com/haxball/haxball-issues/wiki/Headless-Host#connectivity-warning

do u know how do i do that in linux?
when i enter the properties theres no such thing as the target

**Comment by orenball** [comment]
nvm what u said worked
thanks much appreciated :D
