### ISSUE TITLE
Captcha for joining the room

### ISSUE THREAD

**Issue by syrnique** [haxball/haxball-issues#1014]
Hi, Bastro.
One guy with a high frequency constantly connects to our rooms and makes it impossible to use chat. [https://imgur.com/50hIu3P](https://imgur.com/50hIu3P)
It's useless to ban him, because each time he has different public id and ip address.
One of the possible solutions for us would be the ability to enable captcha for joining the room. Is it possible to implement this?

**Comment by usmth** [comment]
@basro so yeah. This is a very annoying thing and the chat becomes unusable.

**Comment by raoglu** [comment]
For temproray solution, add password then clear in a few minutes later. They mostly give up.

**Comment by dixtel** [comment]
yeah, captcha is good idea

**Comment by usmth** [comment]
@basro Hi! Any news, any plans? Syrnique tried room with password-captcha, which frequently updates in Discord channel, but it didn't work at all.

**Comment by basro** [comment]
I completely agree with this feature and I've already implemented some of it.

It will come soon-ish.

**Comment by basro** [comment]
This feature is now released: https://blog.haxball.com/2020/03/20/update.html

**Comment by syrnique** [comment]
@basro Thanks, I think it will be a really useful feature.
But he continues to connect, maybe with a slightly lower frequency. I don’t know how, he’s just crazy. Is it possible to show only recaptcha with pictures or adjust the recaptcha difficulty from headless host?
