### ISSUE TITLE
Whisper

### ISSUE THREAD

**Issue by willianhf** [haxball/haxball-issues#1025]
Would be nice a command to whisper to other players in room

**Comment by Raamyy** [comment]
what do you mean by whisperring?

**Comment by saviola777** [comment]
Personal message I guess, that is only visible to the other player. This is pretty easy to implement using headless scripts.

**Comment by willianhf** [comment]
@saviola777 and why don't make this feature native?

**Comment by saviola777** [comment]
I don't know, but a quick search through the issues shows that this was suggested back in 2017, so implementing this ourselves is the prudent approach at this point, even if the feature may be added in the future.

**Comment by willianhf** [comment]
@saviola777 I see your point, but there's some rooms that I go into that doesn't have headless script, so making it native would be great
