### ISSUE TITLE
duplicate or not updated IP connection.

### ISSUE THREAD

**Issue by Sielinton** [haxball/haxball-issues#1028]
let conn = connections.find (a => a [1] === player.conn);

The player enters the room, generates the connection, but when leaving, sometimes an error occurs and he is kicked out of the room, accusing another player with the same Ip.
Is there a way to update the connections or update the '' conn '' list to avoid bug this?

Sorry for spelling mistakes and concordance, I don't speak English.

**Comment by Wazarr94** [comment]
Do you update connections correctly when a player leaves ?
Or maybe it's players using VPN, but it's very doubtful.

Need more information.

otherwise, assuming the first element in the arrays is the playerID (adapt if it's not that):

```js
room.onPlayerLeave = function (player) {
    connections = connections.filter(array => room.getPlayer(array[0]) !== null);
}
```

**Comment by Sielinton** [comment]
> Do you update connections correctly when a player leaves ?
> Or maybe it's players using VPN, but it's very doubtful.
> 
> Need more information.
> 
> otherwise, assuming the first element in the arrays is the playerID (adapt if it's not that):
> 
> ```js
> room.onPlayerLeave = function (player) {
>     connections = connections.filter(array => room.getPlayer(array[0]) !== null);
> }
> ```

I did it that way

connections = connections.filter(a => a[0] !== player.id);

Isn't that right?

It is not about Vpn, because it happened to me too.

**Comment by Wazarr94** [comment]
It should work normally.

I think you need to post every part so we can see the error better

**Comment by Sielinton** [comment]
Resolved, this problem no longer occurs. Thanks a lot for the help.
