### ISSUE TITLE
Error loading the key.

### ISSUE THREAD

**Issue by Sielinton** [haxball/haxball-issues#1048]
When loading the key, I see that some recent players, of recently generated ID, are not able to load the old key.
It happened with more than 3 players, and I also took the test, there was an error.

* Error loading the key.

@basro

**Comment by Sielinton** [comment]
I am sending you two examples with keys that I no longer use.
One I generated and the other a player from my room.

idkey.TySjeeI29ibnAAUSnkc3shDuGx-aTRmqn0QsSoBHti0.zni2lhJLrsE_-4MCJkNOvShiYi6RmSvHTUoGL4bKtxg.K1fnf6L5L5VpQQLLVVLQLLVRXLQLVRXLVRJRXLVRJX

........

idkey.DZfYUzvw3HEaoDE-RZpkZ6JI69VPV1Vj-YvhlK2yCzw.ojaYAh6FLbBoW7S_pdY7Mc_RUSbeciIEkDI1P0-JF0k.nj7ufBF6s0H3L6wzvwqq7

There are other keys that the error occurs, I believe that the key was generated with insufficient or incomplete character.

**Comment by basro** [comment]
Both these keys are missing characters. I don't think they would ever work like that.

It is likely they were lost when originally making the backup, probably user error. There could be a bug in the key display page, but I've checked the code and I've seen nothing suspicious there.

If you can find a way to reproduce the short keys it would be helpful, otherwise this is probably just user error when copying the keys.

**Comment by Sielinton** [comment]
It was not a user error, I guarantee it!  I managed to load the first key only once, but after that I was unable to recover it!

I'll try to reproduce this again, and send you the screenshot.

**Comment by Sielinton** [comment]
I just generated this key, took a screenshot and there is an error when recovering it.

https://prnt.sc/ruji3b

idkey.6KB9RsSl2uRI_EEE8taFrW17v7Bbl_mPf8PJ9eVuQMc.IXhTN5ATF9Udnvu2ddgiGx-QD3sZ17NU2pQK8SjQ0xw.cJfU6-ettIe1V01FclO3

**Comment by pilaf** [comment]
@Sielinton Since it seems you're using some translation service (maybe Google Translate?) it's possible that it's is messing with the keys as well. Try disabling translation and viewing the original page.

**Comment by Sielinton** [comment]
@pilaf How much lack of attention on my part, apparently that is what happened. Thank you, I will warn the players in my room to be aware of this.

**Comment by pilaf** [comment]
@Sielinton No problem, glad I could help.
