### ISSUE TITLE
Multiple events - error

### ISSUE THREAD

**Issue by dizajnero** [haxball/haxball-issues#1056]
Hello! I want to run multiple events like room.onPlayerChat(), but only second event runs:

```
function xx2 (player, message) {
room.onPlayerChat = function (player, message) {
	let spacePos = message.search(" ");
	let command = message.substr(0, spacePos !== -1 ? spacePos : message.length);
	if (commands.hasOwnProperty(command) == true) {
		return commands[command](player, message);
	}
	

	//Display data of a player which sent a message in the console
	console.log(`**MESSAGE COUNTER (  ${messageCounter} )**  Player ID: ${player.id}; Nickname: ${player.name}; Message: ${message}`);
};




var Guest = "Guest >> ";
var Admin = "Admin >> ";
var AdminColor = "0x1288DF";
var GuestColor = "0xE69138";

room.onPlayerChat = function(player, message) {
    if (player.admin){
    room.sendAnnouncement(
          Admin + player.name + ": " + message,undefined,AdminColor,"bold"
        );
    return false;
    }
   else {

    room.sendAnnouncement(
          Guest + player.name + ": " + message,undefined,GuestColor,"bold");
    return false;
    }
}}


xx2();
```

Can you help me with code? How to run multiple events with no ignoration with each other?

**Comment by Sielinton** [comment]
There is no need to have 2 distinct functions.
Place the code within just one function

**Comment by saviola777** [comment]
The simplest way would be to define two functions and execute them in a third. Like

```
function firstHandler() { /* code */ }
function secondHandler() { /* code */ }
room.onPlayerChat() {
  firstHandler();
  secondHandler();
}
```
If that is not enough, you may want to check out plugin systems which allow you to separate your headless script into several independent units.

**Comment by dizajnero** [comment]
> 
> 
> The simplest way would be to define two functions and execute them in a third. Like
> 
> ```
> function firstHandler() { /* code */ }
> function secondHandler() { /* code */ }
> room.onPlayerChat() {
>   firstHandler();
>   secondHandler();
> }
> ```
> 
> If that is not enough, you may want to check out plugin systems which allow you to separate your headless script into several independent units.

Thank you very much :)
