### ISSUE TITLE
How to get the names of the players.

### ISSUE THREAD

**Issue by Sielinton** [haxball/haxball-issues#1057]
How to return the names of the members of the red team and the blue team separately?

I have a project in mind and I need to understand how to get the name of each player on the team.
so I did a test with sendChat.

I tried as follows..

function esttimeFun(redTeam, blueTeam){

	room.sendChat("Team red .");

	room.sendChat("Name." + redTeam[1].name + ".");
	room.sendChat("Name." + redTeam[2].name + ".");
	room.sendChat("Name." + redTeam[3].name + ".");

	room.sendChat("Team blue .");
         room.sendChat("Name." + blueTeam[1].name + ".");
	room.sendChat("Name." + blueTeam[2].name + ".");
	room.sendChat("Name." + blueTeam[3].name + ".");
}

I called the function like this ...
esttimeFun(redTeam, blueTeam);
inside the room.onGameStart.

The team contains 3 players on each side.
That was the return.

ʙᴏᴛ: Team red.
ʙᴏᴛ: Name.undefined.
ʙᴏᴛ: Name.undefined.
ʙᴏᴛ: Name.undefined.

ʙᴏᴛ: Team blue.
ʙᴏᴛ: Name.undefined.
ʙᴏᴛ: Name.undefined.
ʙᴏᴛ: Name.undefined.

**Comment by Sielinton** [comment]
I did it, I turned around here.

**Comment by Sielinton** [comment]
I thought I could have done it with the filter, but it didn't work.

**Comment by Raamyy** [comment]
```js
function getBlueTeamNames() {
 
 var blueTeam = room .getPlayerList().filter(player => player.team == 2).map(p => p.name).toString();
 return blueTeam;
}
 
//returns string of players names in red team

 function getRedTeamNames() {
 var redTeam = room .getPlayerList().filter(player => player.team == 1).map(p => p.name).toString();
 return redTeam;
}
```

**Comment by Sielinton** [comment]
That way does not serve, I want the individual name of each one of the team.
My project makes the addition a saved value, example .. calculate the red team's goal value based on the status.
then make a comparison. @Raamyy

**Comment by Sielinton** [comment]
function getRedTeamNames(){
 var redTeam = room .getPlayerList().filter(player => player.team == 1).map(p => p.name);

	room.sendChat("Nome." + redTeam[0].name + ".");
	room.sendChat("Nome." + redTeam[1].name + ".");
	room.sendChat("Nome." + redTeam[2].name + ".");

}


Thus, the individual name of each player was not returned.

**Comment by Sielinton** [comment]
forgot to remove the .name
It worked now!
Thank you!
