### ISSUE TITLE
Haxball Replay Analyzer

### ISSUE THREAD

**Issue by TurboFalafel** [haxball/haxball-issues#1071]
Hi,

I would like to show you my another project, Haxball Replay Analyzer - 
https://haxball-replay-analyzer.github.io/ , program which let user parse hbr2 file and receive game stats, like score, goals, assists, individual and team statistics, like possession and kicks. Ofc program will be developed, as it's my first version of the analyzer.
Would be great to see your feedback ;p

![replay_analyzer](https://user-images.githubusercontent.com/40662510/81603032-ebb04d00-93cd-11ea-9069-fa241f47e951.png)

EDIT: I've received info that for some users button "Start" is unclickable, working on fix

**Comment by Raamyy** [comment]
Hello Falafel :D

Why don't you share the source code and make it as an open source project ?
