### ISSUE TITLE
haxball headless host anonymous and colorful writing

### ISSUE THREAD

**Issue by SaNaTKaR04** [haxball/haxball-issues#1078]
https://prnt.sc/slt5n8
How do i do this

**Comment by Logersx** [comment]
var Guest = "Guest | ";
var Admin = "Admin | ";
var AdminColor = "0x1288DF";
var GuesteColor = "0xE69138";

room.onPlayerChat = function(player, message) {
    if (player.admin){
    room.sendAnnouncement(
          Admin + player.name + ": " + message,
          undefined,
          AdminColor,
          "bold"
        );
    return false;
    }
   else {

    room.sendChat(
          Guest + player.name + ": " + message
        );
    return false;
    }
}

**Comment by Logersx** [comment]
bu atılan mesajları renklendiriyor konulardan buldum biraz kurcalayarak kendine uyarlayabilirsin

**Comment by SaNaTKaR04** [comment]
teşekkürler kanka
