### ISSUE TITLE
I cant join rooms in HTML

### ISSUE THREAD

**Issue by Mentosaa** [haxball/haxball-issues#108]
I can not join rooms in html and other players cant join my room. I tried to stop the add blocker and reverse_settings enable but no result. I need help

**Comment by Mentosaa** [comment]
Can someone give me an answer???

**Comment by Mentosaa** [comment]
still cant join, only 1 evening i joined but the next day the same shitty message... Solution??!?!?!!?!

**Comment by basro** [comment]
I just released a new version which could fix this issue for you, please tell me if you still can't connect.
