### ISSUE TITLE
HELP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by SaNaTKaR04** [haxball/haxball-issues#1085]
function banTeam(teamID)
			{
			  var team = room.getPlayerList().filter((player) => player.team == teamID);
			  
			  for(var i = 0; i < team.length; i++){
				room.setPlayerTeam(team[i].id, 0);
			  room.kickPlayer(team[i].id, "3-0)", true);
			  }
			}

if(score.red == 3 && score.blue == 0)
				banTeam(2);
			
			if(score.red == 0 && score.blue == 3)
				banTeam(1);
How do I set this command so as not to ban the admin??

**Comment by Raamyy** [comment]
```
 for(var i = 0; i < team.length; i++){
    room.setPlayerTeam(team[i].id, 0);
    if(!team[i].admin)
        room.kickPlayer(team[i].id, "3-0)", true);
}
```

**Comment by SaNaTKaR04** [comment]
@Raamyy 
function filter(message){
    message = message.toLowerCase();
    message = message.replace(/\s/g, '');
    message = message.replace(/\./g,' ')
    if(message.includes("oç") ){
        return true;
    }else {return false;
    }
}
How do I set this command so as not to ban the admin??

**Comment by Raamyy** [comment]
@SaNaTKaR04  There is no ban in the provided code

**Comment by SaNaTKaR04** [comment]
@Raamyy 
if(filter(message)) {
bannnFun(player);
return false;
}
function bannnFun(player){
    room.kickPlayer(player.id, "BB)", true);
}

**Comment by Raamyy** [comment]
@SaNaTKaR04 

if(filter(message)) {
bannnFun(player);
return false;
}
function bannnFun(player){
if(!player.admin)
room.kickPlayer(player.id, "BB)", true);
}

**Comment by SaNaTKaR04** [comment]
I was writing exactly "I did it myself. Thanks for your help"

**Comment by Raamyy** [comment]
@SaNaTKaR04 great nice work :+1:

**Comment by Raamyy** [comment]
Next time please write descriptive issue titles

**Comment by SaNaTKaR04** [comment]
@Raamyy 
room.onPlayerJoin = function(player) {
				clonekick(player);
				CreateOyuncu(player);
				room.sendAnnouncement("Hoşgeldin " + player.name + " !komutlar Yazarak Kullanabileceğin Komutları Öğrenebilirsin!", undefined, OyuncuColor, "bold")
				 if(room.getPlayerList().length <= 3)
			  {
				room.setPlayerTeam(player.id, vacancy());
				if(room.getPlayerList().length == 3)
				{
				  room.stopGame();
				  setTimeout(function(){
					room.startGame();
				  }, 300);    }
			  }
			}
How do I ensure that the first player is not redeemed until the second player arrives?
