### ISSUE TITLE
Add option to configure or disable gamepad

### ISSUE THREAD

**Issue by saviola777** [haxball/haxball-issues#11]
People who used gamepads to play so far (mapping Gamepad key input to keyboard keys) can't do so anymore (with their own button configuration) because their gamepad is picked up by the game. Would be nice to be able to change the button settings or at least disable the gamepad completely so that it can be used like before.

**Comment by basro** [comment]
hah, I never thought anyone would be playing with gamepad..
I'll do something about it eventually. Very low priority though, sorry.

**Comment by MrP0123** [comment]
I play this game for many years now with a gamepad. Now i cant use my pad tool anymore and this brings the following problems:
- i cant set my death zones for the sticks anymore
- on every button i kick/shot the ball (thats a big problem, when i make a direction change and click at my left stick i kick:/ + at select (my old entry for the menu), at start at all triggers i kick. it rly sucks :( )

**Comment by basro** [comment]
Ok, I guess at least I can disable the half baked gamepad support for now..
Next update will have the gamepad disabled.

**Comment by basro** [comment]
I've released an update with gamepad disabled. I might implement key mappings in the future and in that scenario I'll reenable gamepad support.
