### ISSUE TITLE
Disappearing Players Bug

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1110]
Hello! I would like to share an issue with you. About 3 months ago, when we were playing in a Turkish 7-Man room (Turkish: Japon Kale), all the discs (including the players) were suddenly disappeared after I (the unnamed player on blue) have scored a certain amount of goals to the red's goal. But interestingly the all the discs act like if they were existing. After seeing this bug, I have asked it to the developer of that bot and he told that he could not do anything to fix this bug and told that this bug was a bug of HaxBall. So, it will be good if this bug can be fixed. Thanks in advance.

Here is the record: https://thehax.pl/forum/powtorki.php?nagranie=c8e1f77b58bb4a4ca56ad7dcf2de339f

**Comment by iAmLuks** [comment]
This is only possible if creator of bot scripts it this way,

Setting players disc properties or any kind of disc properties radius to 0 causes this effect.
So this was caused artificially.

**Comment by thenorthstar** [comment]
I know that players' radiuses were slowly going down to zero as they concede a goal in that room. But I don't know why the other discs were set of radius of 0. OK, I will talk this at the creator of the bot and see what happens.
