### ISSUE TITLE
Admin registration system

### ISSUE THREAD

**Issue by Tower02** [haxball/haxball-issues#1125]
Hi guys.
I have 4 bot rooms and I have set admins for these rooms.But managers can log in on my behalf and ban people on my behalf.
What should I do? Can you help me?

**Comment by andrea1337** [comment]
Research this "auth"

**Comment by thenorthstar** [comment]
I think that this will be helpful for you.

```
var administrators = [["admin1","auth1"],["admin2","auth2"],["admin3","auth3"]]; //Please look at haxball.com/playerauth so as to add auth (or public ID) strings here. First entry: Name of administrator, second entry: his/her auth.

room.onPlayerJoin = function(player){
    for(var i=0; i<administrators.length; i++){
	if(player.name == administrators[i][0] && player.auth == administrators[i][1]){ //If administrator is joining the room with correct username and auth, then he/she will given admin rights.
	    room.setPlayerAdmin(player.id,true);
	    room.sendAnnouncement(player.name + " the admin has joined.",null,0x00FF00,"bold",1);
	}
	else if((player.name == administrators[i][0] && player.auth != administrators[i][1]) || (player.name != administrators[i][0] && player.auth == administrators[i][1])){ //If not, he/she will be banned due to impersonating a registered administrator.
	    room.kickPlayer(player.id,"You were banned due to impersonating a registered administrator.",true);
	}
    }
}
```

**Comment by Tower02** [comment]
> I think that this will be helpful for you.
> 
> ```
> var administrators = [["admin1","auth1"],["admin2","auth2"],["admin3","auth3"]]; //Please look at haxball.com/playerauth so as to add auth (or public ID) strings here. First entry: Name of administrator, second entry: his/her auth.
> 
> room.onPlayerJoin = function(player){
>     for(var i=0; i<administrators.length; i++){
> 	if(player.name == administrators[i][0] && player.auth == administrators[i][1]){ //If administrator is joining the room with correct username and auth, then he/she will given admin rights.
> 	    room.setPlayerAdmin(player.id,true);
> 	    room.sendAnnouncement(player.name + " the admin has joined.",null,0x00FF00,"bold",1);
> 	}
> 	else if((player.name == administrators[i][0] && player.auth != administrators[i][1]) || (player.name != administrators[i][0] && player.auth == administrators[i][1])){ //If not, he/she will be banned due to impersonating a registered administrator.
> 	    room.kickPlayer(player.id,"You were banned due to impersonating a registered administrator.",true);
> 	}
>     }
> }
> ```

Thank you ♥
