### ISSUE TITLE
 How do I decrease this code?

### ISSUE THREAD

**Issue by MoisesAsafi** [haxball/haxball-issues#1130]
I wanted to create an array for the name of the player and for the player auth. But I can't get it to work ...

`var room = HBInit({
	roomName: "Survival by Moisés",
  public: false,
  maxPlayers: 16,
	noPlayer: true 
});
room.setTeamColors(1, 60, 0xFFFFFF, [0x005CB8]) //Uniforme RED
room.setTeamColors(2, 60, 0xFFFFFF, [0x005CB8]) // Uniforme BLUE
room.setScoreLimit(0);
room.setTimeLimit(0);

function updateAdmins() { 
  var players = room.getPlayerList();
  if ( players.length == 0 ) return; 
  if ( players.find((player) => player.admin) != null ) return; 
  room.setPlayerAdmin(players[0].id, true); 
}

room.onPlayerJoin = function(player) {
  if(player.name === "Moisés Asafi" && player.auth !== "wsbX3WVjp1klq-wmqKcp2wuqfno_1oP7zoeh-k-uo9I") {
    room.kickPlayer(player.id, "Coloque seu nick", false);
} 
	if(player.name === "𝐒ꮻ🇳 𝕵𝖚𝖇𝖎𝖘" && player.auth !== "uhgCsYlQ7BDL0tdCFo4v8Jg7oA1KVNRVFb8y3gYWJw8") {
	  	room.kickPlayer(player.id, "Coloque seu nick", false);
}
  
  if(player.name === "Moisés Asafi"){
    room.setPlayerAdmin()
    room.sendAnnouncement('Olha o melhor de todos entrando!!', undefined, botCor)
  }
  if(player.name === "𝐒ꮻ🇳 𝕵𝖚𝖇𝖎𝖘"){
    room.setPlayerAdmin()
    room.sendAnnouncement('Olha o segundo melhor de todos entrando!!')
  }  
  
  updateAdmins();

  console.log(player)
}
`

**Comment by dixtel** [comment]
```javascript
var room = HBInit({
  roomName: "Survival by Moisés",
  public: false,
  maxPlayers: 16,
  noPlayer: true
});

room.setTeamColors(1, 60, 0xFFFFFF, [0x005CB8]) // Uniforme RED
room.setTeamColors(2, 60, 0xFFFFFF, [0x005CB8]) // Uniforme BLUE
room.setScoreLimit(0);
room.setTimeLimit(0);

function updateAdmins() {
  var players = room.getPlayerList();
  if (players.length == 0) return;
  if (players.find((player) => player.admin) != null) return;
  room.setPlayerAdmin(players[0].id, true);
}

const TRUSTED_PLAYERS = [
  {
    name: "Moisés Asafi",
    auth: "wsbX3WVjp1klq-wmqKcp2wuqfno_1oP7zoeh-k-uo9I"
  },
  {
    name: "𝐒ꮻ🇳 𝕵𝖚𝖇𝖎𝖘",
    auth: "uhgCsYlQ7BDL0tdCFo4v8Jg7oA1KVNRVFb8y3gYWJw8"
  },
];

room.onPlayerJoin = function (player) {
  let trusted_player = TRUSTED_PLAYERS.find((el) => el.name == player.name);

  if (trusted_player != undefined) {
    if (trusted_player.auth != player.auth) {
      room.kickPlayer(player.id, "Coloque seu nick", false);
      return
    }
    else {
      room.setPlayerAdmin(player.id, true)
      room.sendAnnouncement('Olha o melhor de todos entrando!!')
    }
  }

  updateAdmins();
  console.log(player)
}
```

**Comment by supernatural88** [comment]
Better;

`
var room = HBInit({roomName:"Survival by Mois\u00e9s", "public":!1, maxPlayers:16, noPlayer:!0});
room.setTeamColors(1, 60, 16777215, [23736]);
room.setTeamColors(2, 60, 16777215, [23736]);
room.setScoreLimit(0);
room.setTimeLimit(0);
function updateAdmins() {
  var a = room.getPlayerList();
  0 != a.length && null == a.find(function(b) {
    return b.admin;
  }) && room.setPlayerAdmin(a[0].id, !0);
}
var TRUSTED_PLAYERS = [{name:"Mois\u00e9s Asafi", auth:"wsbX3WVjp1klq-wmqKcp2wuqfno_1oP7zoeh-k-uo9I"}, {name:"\ud835\udc12\uabbb\ud83c\uddf3 \ud835\udd75\ud835\udd9a\ud835\udd87\ud835\udd8e\ud835\udd98", auth:"uhgCsYlQ7BDL0tdCFo4v8Jg7oA1KVNRVFb8y3gYWJw8"}, ];
room.onPlayerJoin = function(a) {
  var b = TRUSTED_PLAYERS.find(function(c) {
    return c.name == a.name;
  });
  if (void 0 != b) {
    if (b.auth != a.auth) {
      room.kickPlayer(a.id, "Coloque seu nick", !1);
      return;
    }
    room.setPlayerAdmin(a.id, !0);
    room.sendAnnouncement("Olha o melhor de todos entrando!!");
  }
  updateAdmins();
  console.log(a);
};
`
