### ISSUE TITLE
Joints

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#1148]
@basro 
Is it possible to make joints have cMask and cGroup? I have a lot of ideas to create maps but they would require the joints to colide with objects, and is very very bad using a lot of disc together to create a surface, because they will never create a perfect linear surface which spoil my ideas of the maps as i need perfect collision with the normal vector of the surface

**Comment by thenorthstar** [comment]
Duplicate of #1064.

**Comment by Leo-MapCreator** [comment]
Closed
Duplicate of #1064
