### ISSUE TITLE
Grito de la "hinchada"

### ISSUE THREAD

**Issue by rsk19** [haxball/haxball-issues#115]
En realidad a lo que me dirijo no es un error, sino que como en la versión Flash cuando hay jugada peligrosa digamos, se escucha ese "murmullo de la hinchada" y veo que no está puesta en la versión HTML5,  estaría bueno que si esté el mismo sonido o alguno parecido ya que en mi opinión era un lindo detalle, un saludo!
rskkkkkkkk

**Comment by basro** [comment]
Duplicate of  #16
