### ISSUE TITLE
Continuously Moving Bot-Controlled Disc

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1153]
Hello there! I had shared a video and codes 2 months ago (#1062), it was about a ball which is following the player disc. But it's moving once per a tick (1/60 of a second). So I have decided to make its move continuous. In order to do it, I have firstly tried **room.onPlayerActivity()** event to control that ball and saw that the ball moves more continuous than in the **room.onGameTick()** event but its not called when the player continues to press the same direction key. Now, I have two different questions.

The first one is for you, @basro:
Could the **room.onPlayerActivity()** event be called continuously if a player continues to press the key which he/she pressed?

And the second one is here:
Do you have any idea to make the ball's moves continuous?

The function is working so in the **room.onPlayerActivity()** event: https://thehax.pl/forum/powtorki.php?nagranie=32a2ad740c64b1626669df391400b2d1

And the function is working so in the **room.onGameTick()** event: https://thehax.pl/forum/powtorki.php?nagranie=2e574e68c1fdc604743a1ecd949d8f76

Thank you for helps from right now!

**Comment by xRoos3velt** [comment]
Hi, may I take your discord name?
