### ISSUE TITLE
'Game is running' indicator

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#116]
Hi Basro, there is a flash feature that is missing from the menu, it indicates either if the game is being played or if it's stopped, contrary to what is seems, its a very useful feature, i've used it a lot in the past, my ESC button wasnt working properly and it helped me to not be stuck on the menu while the game was being played

Flash:
Game is running: https://gyazo.com/b69fda272082ea6ebe09de85b947837b
Game is stopped: https://gyazo.com/e692aa101b0a5b5e5ed08534ee62d6c3
Notice that the 'Menu (Esc)' button changes color

HTML5:
Game is running: https://gyazo.com/99c66cfbdfcf168e213cae07cd64b0fc
Game is stopped: https://gyazo.com/586cf0e22d9aaf81cb81dc56fdc28486

Please put a more visible indicator in HTML5, something like a dot that is either red or green, with green indicating the game is running

Thx. in advance
Leo ß

**Comment by basro** [comment]
This is now fixed.
