### ISSUE TITLE
I have a problem on vps host distance

### ISSUE THREAD

**Issue by dapucita** [haxball/haxball-issues#1173]
I made a host at Seoul, Korea (IP address also located at Seoul)

I tested headless bot, and I got mysterious result that my host's distance is Japan

usually, in Korea, we are only 0~300km but my host shows me 1000km far..

what happend? do you have any idea?

**Comment by basro** [comment]
The geolocation is autodetected but it can fail, you'll have to override it using the [geo property](https://github.com/haxball/haxball-issues/wiki/Headless-Host#geo--code-string-lat--float-lon--float) when initializing the server.

**Comment by dapucita** [comment]
thx I will try it
