### ISSUE TITLE
Could someone write "! Admin required" in chat and type "Administrator Required Room" on Discord Channel?

### ISSUE THREAD

**Issue by kontrolsuzkalemTR** [haxball/haxball-issues#1174]

**Comment by Raamyy** [comment]
Yes you can use discord web hooks

**Comment by kontrolsuzkalemTR** [comment]
but i dont know how i can do it, can you help me

**Comment by kontrolsuzkalemTR** [comment]
> Yes you can use discord web hooks

but i dont know how i can do, can you help me?

**Comment by thenorthstar** [comment]
> Yes you can use discord web hooks

@Raamyy And some people use their discord bots as web hooks. How is it possible? I have my own room and my own discord bot but I still log my data in room by another web hook. Please look at below image.

![4](https://user-images.githubusercontent.com/68077608/98461909-264e4300-21c1-11eb-8593-2443166b617e.PNG)

@kontrolsuzkalemTR Ben bu HaxRoomie denen API'yı kurmuştum bilgisayarıma, odada olanı senin ayarladığın şekilde discord'a loglayabiliyor ama onun için ayriyeten web hook falan oluşturman gerekiyor. Benim kendi botum var, kendi odam da var ama yukarıda attığım resimdeki gibi yapamadım henüz.

**Comment by ghost** [comment]
@thenorthstar 
function sendAnnouncementToDiscord(message) {

  var request = new XMLHttpRequest();
  request.open("POST", yourwebhookURL);

  request.setRequestHeader('Content-type', 'application/json');

  var params = message;

  request.send(JSON.stringify(params));
} :=)

Örnek: 
sendAnnouncementToDiscord({ username: 'Bildirim',
    avatar_url: '',
    content: `${playername}, odaya bağlandı.`});

**Comment by kontrolsuzkalemTR** [comment]
> @thenorthstar `function sendAnnouncementToDiscord(message) {
> 
> var request = new XMLHttpRequest();
> request.open("POST", yourwebhookURL);
> 
> request.setRequestHeader('Content-type', 'application/json');
> 
> var params = message;
> 
> request.send(JSON.stringify(params));
> }` :=)
> 
> Örnek:
> sendAnnouncementToDiscord({ username: 'Bildirim',
> avatar_url: '',
> content: `${playername}, odaya bağlandı.`});

discordun varmı acaba?

**Comment by thenorthstar** [comment]
> @thenorthstar
> function sendAnnouncementToDiscord(message) {
> 
> var request = new XMLHttpRequest();
> request.open("POST", yourwebhookURL);
> 
> request.setRequestHeader('Content-type', 'application/json');
> 
> var params = message;
> 
> request.send(JSON.stringify(params));
> } :=)
> 
> Örnek:
> sendAnnouncementToDiscord({ username: 'Bildirim',
> avatar_url: '',
> content: `${playername}, odaya bağlandı.`});

Öncelikle paylaşımın için çok teşekkür ederiz. Bu arada bir durum var, benim istediğim şey bunu kendi oluşturduğum discord botuna yaptırmak, webhook'a değil. Çünkü bu attığım resimdeki botun sahibine ulaşıp sorduğumda web server'a ondan sonra discord botu ile discord'a gönderiyorsun dedi bana.

**Comment by kontrolsuzkalemTR** [comment]
> > @thenorthstar
> > function sendAnnouncementToDiscord(message) {
> > var request = new XMLHttpRequest();
> > request.open("POST", yourwebhookURL);
> > request.setRequestHeader('Content-type', 'application/json');
> > var params = message;
> > request.send(JSON.stringify(params));
> > } :=)
> > Örnek:
> > sendAnnouncementToDiscord({ username: 'Bildirim',
> > avatar_url: '',
> > content: `${playername}, odaya bağlandı.`});
> 
> Öncelikle paylaşımın için çok teşekkür ederiz. Bu arada bir durum var, benim istediğim şey bunu kendi oluşturduğum discord botuna yaptırmak, webhook'a değil. Çünkü bu attığım resimdeki botun sahibine ulaşıp sorduğumda web server'a ondan sonra discord botu ile discord'a gönderiyorsun dedi bana.

ben bi kanala webhook oluşturdum, gizli bi bot geldi ve link vardı, yerleştirdim linki gerekli yere. çalıştırdım konsole da şu hata var 
Post <webhooklinkim> 400

**Comment by ghost** [comment]
@kontrolsuzkalemTR Discordum budur: 00100110#6044 
@thenorthstar Dostum, dediğin şeyi discord.js kullanarak yapma şansı olabilir bot üzerinden Webhook kurarak. Bi' kontrol ettikten sonra dönüş yapayım.

**Comment by ghost** [comment]
@kontrolsuzkalemTR  Dostum kodu güncelledim. 
```javascript
function sendAnnouncementToDiscord(message) {

    var request = new XMLHttpRequest();
    request.open("POST", yourwebhookURL);

    request.setRequestHeader('Content-type', 'application/json');

    var params = {
        avatar_url: '',
        username: 'Bildirim',
        content: message
    };

    request.send(JSON.stringify(params));
}
```

**Comment by kontrolsuzkalemTR** [comment]
> @kontrolsuzkalemTR Dostum kodu güncelledim.
> function sendAnnouncementToDiscord(message) {
> 
> ```
> var request = new XMLHttpRequest();
> request.open("POST", yourwebhookURL);
> 
> request.setRequestHeader('Content-type', 'application/json');
> 
> var params = {
>     avatar_url: '',
>     username: 'Bildirim',
>     content: message
> };
> 
> request.send(JSON.stringify(params));
> ```
> 
> }

ne kdr teşekküğr etsem azdır

**Comment by tanercanbilgin** [comment]
peki discord üzerinden yazdıklarımızı odaya gönderebilme şansımız var mı?
mesela !ban #12 yazınca oyundan nasıl banlayabiliriz?
ve gol attıklarında belirtilen yazıyı nasıl yansıtabilirim?
teşekkürler

**Comment by ghost** [comment]
> peki discord üzerinden yazdıklarımızı odaya gönderebilme şansımız var mı?
> mesela !ban 12 yazınca oyundan nasıl banlayabiliriz?
> ve gol attıklarında belirtilen yazıyı nasıl yansıtabilirim?
> teşekkürler

Henuz discord uzerinden yazma isine bakmadim, denemek istemedim acikcasi. Ama musait oldugum zaman bakarim. Ayrica,
> ve gol attıklarında belirtilen yazıyı nasıl yansıtabilirim?

bunu derken neyi kastettiginizi anlayamadim.

**Comment by tanercanbilgin** [comment]
gol atıldıktan sonra çıkan yazı "oyuncu gol attı!"
bunu discorda aktarmak istiyorum nasıl yapabilirim

**Comment by tanercanbilgin** [comment]
ayrıca zamanın varsa bunu kullandığım bi bota uygulamak istiyorum ama yapamadım, bakabilir misin?

**Comment by thenorthstar** [comment]
> gol atıldıktan sonra çıkan yazı "oyuncu gol attı!"
> bunu discorda aktarmak istiyorum nasıl yapabilirim

@tanercanbilgin Şöyle bir kod işini görecektir:

```js
var room = HBInit({roomName: "",playerName:"",noPlayer:true,public:false,maxPlayers:12});

var WebHookURL = "" //Buraya discord'da bildirim gönderilmesini istediğin kanal için oluşturduğun WebHook'un URL'ini gireceksin.

var lastPlayerTouched = "";
var lastTeamTouched = 0;
var previousPlayerTouched;

var radiusBall = 10;
var radiusPlayer = 15;
var triggerDistance = radiusBall + radiusPlayer + 0.01;

function getLastTouchTheBall(){
    var ballPosition = room.getBallPosition();
    var players = room.getPlayerList();
    for(var i=0; i<players.length; i++){
        if(players[i].position != null){
            var distanceToBall = pointDistance(players[i].position,ballPosition);
            if(distanceToBall < triggerDistance){
                if(lastPlayerTouched!=players[i].name){
                    if(lastTeamTouched==players[i].team){
                        assistingTouch = lastPlayerTouched;
                    }
		    else{
			assistingTouch = "";
		    }
                }
                lastTeamTouched = players[i].team;
                previousPlayerTouched == lastPlayerTouched;
                lastPlayerTouched = players[i];
            }
        }
    }
    return lastPlayerTouched;
}

function pointDistance(p1,p2){
    var d1 = p1.x-p2.x;
    var d2 = p1.y-p2.y;
    return Math.sqrt(d1*d1 + d2*d2);
}

room.onPlayerBallKick = function(player){
    lastPlayerTouched = player;
}

room.onTeamGoal = function(team){
    team = room.getPlayer(lastPlayerTouched.id).team == 1 ? "kırmızı" : room.getPlayer(lastPlayerTouched.id).team == 2 ? "mavi" : "izleyici";
    room.sendAnnouncement(lastPlayerTouched.name + " " + team + " takım adına gol attı! Durum şimdi: " + room.getScores().red + " - " + room.getScores().blue,null,0xFFFFFF,"normal",1);

    var request = new XMLHttpRequest();
    request.open("POST",WebHookURL);

    request.setRequestHeader('Content-type', 'application/json');

    var params = {
        avatar_url: '', //Buraya bir URL girmen gerekiyor, istemiyorsan kaldırabilirsin.
        username: 'Discord WebHook Name', //Buraya discord webhook'un için oluşturduğun adı gireceksin.
        content: lastPlayerTouched.name + " " + team + " takım adına gol attı! Durum şimdi: " + room.getScores().red + " - " + room.getScores().blue
    };

    request.send(JSON.stringify(params));
}
```

**Comment by Lui0409** [comment]
@ikramimamoglu odada yazılan mesajları dc de görmek istiyorum ve dc den ban atmak istiyorum yardımcı olurmusunuz örnek verim odada [1] Falcao adlı bi kişi var ben dc de !ban 1 yazdığımda odada bot onu banlasın yardımcı olursanız sevinirim ve teşekkürler

**Comment by tanercanbilgin** [comment]
@thenorthstar çok teşekkür ederim, mayın tarlası botunu çok başarılı buldum eline sağlık. isterseniz türk haxball bot geliştirileri için bi destek discordu açabiliriz. potansiyelimizin yüksek olduğunu düşünüyorum ve polonyalılardan korelilerden daha başarılı botlar yapabiliriz

**Comment by tanercanbilgin** [comment]
> > gol atıldıktan sonra çıkan yazı "oyuncu gol attı!"
> > bunu discorda aktarmak istiyorum nasıl yapabilirim
> 
> @tanercanbilgin Şöyle bir kod işini görecektir:
> 
> ```
> var room = HBInit({roomName: "",playerName:"",noPlayer:true,public:false,maxPlayers:12});
> 
> var WebHookURL = "" //Buraya discord'da bildirim gönderilmesini istediğin kanal için oluşturduğun WebHook'un URL'ini gireceksin.
> 
> var lastPlayerTouched = "";
> var lastTeamTouched = 0;
> var previousPlayerTouched;
> 
> var radiusBall = 10;
> var radiusPlayer = 15;
> var triggerDistance = radiusBall + radiusPlayer + 0.01;
> 
> function getLastTouchTheBall(){
>     var ballPosition = room.getBallPosition();
>     var players = room.getPlayerList();
>     for(var i=0; i<players.length; i++){
>         if(players[i].position != null){
>             var distanceToBall = pointDistance(players[i].position,ballPosition);
>             if(distanceToBall < triggerDistance){
>                 if(lastPlayerTouched!=players[i].name){
>                     if(lastTeamTouched==players[i].team){
>                         assistingTouch = lastPlayerTouched;
>                     }
> 		    else{
> 			assistingTouch = "";
> 		    }
>                 }
>                 lastTeamTouched = players[i].team;
>                 previousPlayerTouched == lastPlayerTouched;
>                 lastPlayerTouched = players[i];
>             }
>         }
>     }
>     return lastPlayerTouched;
> }
> 
> function pointDistance(p1,p2){
>     var d1 = p1.x-p2.x;
>     var d2 = p1.y-p2.y;
>     return Math.sqrt(d1*d1 + d2*d2);
> }
> 
> room.onPlayerBallKick = function(player){
>     lastPlayerTouched = player;
> }
> 
> room.onTeamGoal = function(team){
>     team = room.getPlayer(lastPlayerTouched.id).team == 1 ? "kırmızı" : room.getPlayer(lastPlayerTouched.id).team == 2 ? "mavi" : "izleyici";
>     room.sendAnnouncement(lastPlayerTouched.name + " " + team + " takım adına gol attı! Durum şimdi: " + room.getScores().red + " - " + room.getScores().blue,null,0xFFFFFF,"normal",1);
> 
>     var request = new XMLHttpRequest();
>     request.open("POST",WebHookURL);
> 
>     request.setRequestHeader('Content-type', 'application/json');
> 
>     var params = {
>         avatar_url: '', //Buraya bir URL girmen gerekiyor, istemiyorsan kaldırabilirsin.
>         username: 'Discord WebHook Name', //Buraya discord webhook'un için oluşturduğun adı gireceksin.
>         content: lastPlayerTouched.name + " " + team + " takım adına gol attı! Durum şimdi: " + room.getScores().red + " - " + room.getScores().blue
>     };
> 
>     request.send(JSON.stringify(params));
> }
> ```

peki mesaj yazanların adını webhook usernameine nasıl koyabilirim

**Comment by vaejoviade** [comment]
> 

Merhba dostum discord'un var mı ulaşabilir miyim sana, bende discord üzerinden işlem yapmayı istiyorum. 
Bu sorunu çözdüysen, Yardımcı olabilirsen sevinirim.
Kolay gelsin
