### ISSUE TITLE
Perceiving the Difference of Giving and Removing Admin Rights Clearly

### ISSUE THREAD

**Issue by jessaenn** [haxball/haxball-issues#1185]
As it can be understood from the title, how to make the bot perceive the difference between of them? 

I know that the function "onPlayerAdminChange" has 2 parameters named "changedPlayer" and "byPlayer", the first one represents player who is given admin rights and the second one represents admin who gives admin rights. Everything is clear until here **but the problem is that when I want to remove admin rights of a specified player that was given by one of few of special admins**, **it can’t be happened**. 

Is there any function or code which starts to work when the button "Remove Admin" is pressed by someone? I took a look at some code lines which are about this subject as far as I found but there is nothing, the below quadruple codes show what I’ve been trying to do about this as it is the only sensible possibility I think but none of them works.

1st:

`changedPlayer.admin ? room.setPlayerAdmin(changedPlayer.id, false) : null;`

2nd:

`if(changedPlayer.admin) { room.setPlayerAdmin(changedPlayer.id, false); }`

3rd:

`if(changedPlayer.admin == true) { room.setPlayerAdmin(changedPlayer.id, false); }`

4th:

`if(room.getPlayerList().find((changedPlayer) => changedPlayer.admin) != null) { room.setPlayerAdmin(changedPlayer.id, false);  }`

Any ideas? Thanks in advance for those who want to be interested with this.

**Comment by Wazarr94** [comment]
The problem seems to be that `changedPlayer` doesn't have admin as he should. I believe all of the snippets you pasted should work otherwise.

For your code to work, you'd need to update the players objects.

```js
room.onPlayerAdminChange = function (changedPlayer, byPlayer) {
	updateTeams();
        if (changedPlayer.admin) room.setPlayerAdmin(changedPlayer.id, false);
}
```

**Comment by jessaenn** [comment]
Ah, I just added deeper queries that perceive the logic of my system as it should be by handling PlayerObject better and it’s done! Thank you. By the way, the above codes were written by me if you think I shared them copying from different script files. They just weren’t intelligible enough for my own bot to be worked directly how I have planned as they had weak conditions.
