### ISSUE TITLE
Haxball - discord webhook entegration?

### ISSUE THREAD

**Issue by hamburgstaller** [haxball/haxball-issues#1196]
Could someone write "! Admin required" in chat on haxball (web game) and type "Administrator Required Room" on Discord Channel? is it possible. please help me :)

**Comment by ghost** [comment]
I solved this problem recently.
#1174

**Comment by hamburgstaller** [comment]
> I solved this problem recently.
> #1174

Peki bunun için herhangi bir API, js vs. kurmam gerekmiyor mu? Düz olarak headless host console 'una mı yapıştıracağım? Çözmüş olmana çok sevindim bu arada :) Diğer forumlarda da görmüştüm sorununu.

**Comment by ghost** [comment]
> > I solved this problem recently.
> > #1174
> 
> Peki bunun için herhangi bir API, js vs. kurmam gerekmiyor mu? Düz olarak headless host console 'una mı yapıştıracağım? Çözmüş olmana çok sevindim bu arada :) Diğer forumlarda da görmüştüm sorununu.

Gerekmiyor, sadece fonksiyonu kodunun içine yerleştirmen yeterli. Nerelerde kullanacağın sana ve senin yaratıcılığına kalmış.

**Comment by nas0s** [comment]
> > > I solved this problem recently.
> > > #1174
> > 
> > 
> > Peki bunun için herhangi bir API, js vs. kurmam gerekmiyor mu? Düz olarak headless host console 'una mı yapıştıracağım? Çözmüş olmana çok sevindim bu arada :) Diğer forumlarda da görmüştüm sorununu.
> 
> Gerekmiyor, sadece fonksiyonu kodunun içine yerleştirmen yeterli. Nerelerde kullanacağın sana ve senin yaratıcılığına kalmış.

merhaba, discord kullanıcı adınızı verebilir misiniz?

**Comment by ghost** [comment]
> > > > I solved this problem recently.
> > > > #1174
> > > 
> > > 
> > > Peki bunun için herhangi bir API, js vs. kurmam gerekmiyor mu? Düz olarak headless host console 'una mı yapıştıracağım? Çözmüş olmana çok sevindim bu arada :) Diğer forumlarda da görmüştüm sorununu.
> > 
> > 
> > Gerekmiyor, sadece fonksiyonu kodunun içine yerleştirmen yeterli. Nerelerde kullanacağın sana ve senin yaratıcılığına kalmış.
> 
> merhaba, discord kullanıcı adınızı verebilir misiniz?

dGF5eWliaXNpa2V5aW0=#6044

**Comment by hamburgstaller** [comment]
@ikramimamoglu Hocam selam Discord adresinize ulaşamadım size nasıl ulaşabilirim? Hata veriyor da kod.

**Comment by ghost** [comment]
@yusufemirxd ZEdGNWVXbGlhWE5wYTJWNWFXMD0=#6044

**Comment by Desto2000** [comment]
@ikramimamoglu merhaba webhook u nereye yazıcam yourwebhookURL kısmınamı

**Comment by thenorthstar** [comment]
> @ikramimamoglu merhaba webhook u nereye yazıcam yourwebhookURL kısmınamı

![image](https://user-images.githubusercontent.com/68077608/102867830-63595680-444a-11eb-8335-58bfccd83073.png)

@DESTO2000 Discord sunucunda oluşturduğun webhook'un URL'ini sol alttaki **Copy Webhook URL** butonundan elde edip **tırnak içerisinde** yourwebhookURL yazan yere yapıştıracaksın. Hatta bunu başta ön tanımlı olarak yaparsan kodun ilerleyen bölümlerinde birden fazla kez kullanmak durumunda kaldığında işin kolay olur. Yani şöyle:

```var yourwebhookURL = "https://discord.com/api/webhooks/790861843266011177/uN3xuSyZJB-MzJs9ZWy8189syqWcVuZBxcR6reylt0aXH25NELWZcR7ZkIEWTtRWaUhA";```

Yukarıdaki kodu örnek olsun diye attım, bunu direkt kopyalayıp yapıştırmayın. Webhook'unuzun URL'sini kopyaladığınızda yukarıdaki URL sizde farklı olacaktır.

**Comment by hamburgstaller** [comment]
Teşekkürler @ikramimamoglu  konu çözüldü.
