### ISSUE TITLE
Map Content Couldn't be Displayed Properly

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1209]
I have explained a little bit in the previous issue (#1208), the map content and player names cannot be displayed properly on the following recording:

https://thehax.pl/forum/powtorki.php?nagranie=534d36c0f48ff0977e23367fda4a93e6

I'm also thinking that these error maybe map related but I remember that I had watched the same map with the content was played properly.

**Comment by basro** [comment]
The replay file is corrupted, but I can't easily tell you why it's corrupted from just the replay.
If you think the map is the cause it would be helpful if you could share the .hbs file.

**Comment by thenorthstar** [comment]
Sorry for late reply. Frankly, I cannot share it here because it's a private map. But I can send you if you give me an e-mail address which I can contact with you.
