### ISSUE TITLE
Admins can read muted players message 

### ISSUE THREAD

**Issue by nas0s** [haxball/haxball-issues#1212]
Hi, I want to read muted players message on chat. But other players shouldn't see this also muted player. Here my example on "OnPlayerChat";

	if (getMute(player)) {
        room.sendChat("You are muted.", player.id);
         admin = players.find((player) => player.admin);
        room.sendChat(message, parseInt(admin.id)); // tried with both sendChat and sendAnnouncement
        room.sendAnnouncement(`${player.name}: ${message}`, null, 0xff0000, "bold", parseInt(admin.id));
		return false;
	}

It didn't work. btw admin defined as empty before

**Comment by ghost** [comment]
```javascript
if (getMute(player)) {
    room.sendChat("You are muted.", player.id);
     admin = players.filter((player) => player.admin && player.id !=0 );
    
   for(let i = 0; i < admin.length; i++){
     room.sendAnnouncement(`${player.name}: ${message}`, admin[i].id, 0xff0000, "bold");
}
	return false;
}
```
Didn't test it. If there is an error occurred. Send it here.

**Comment by nas0s** [comment]
It''s fixed now, thanks
