### ISSUE TITLE
onPlayerTeamChange 

### ISSUE THREAD

**Issue by furkanardagul** [haxball/haxball-issues#1213]
Hello, important to good day :)

If he is trying to start working with onPlayerTeamChange, I want him to have a warning. I manage this, but since the bot does not allow it, it throws double features and sends messages. How can I avoid this?

![image](https://user-images.githubusercontent.com/45922246/103460145-17998d80-4d25-11eb-8900-5c6573c247d2.png)

Code: 

`js
    function specat(player){
        room.setPlayerTeam(player.id, 0);
    }
setTimeout(function(){
    kontrolEt(player)
    }, 30000); 
`

**Comment by Raamyy** [comment]
Hello

Can you illustrate more the problem I can't understand it

**Comment by furkanardagul** [comment]
Sorry for bad english. I give the user 30 seconds to log in. If he logs in, he does not kick the game. No problem here. But if he doesn't, it will be discarded after 30 seconds. No problem here either. In those 30 seconds I don't want him to join any team if he didn't confirm it. So I tried to prevent it. When I succeeded, it gives a warning when I get a team, and the bot allows it to detect a new event for technical information and send a message again. If you want, you can write from discord Vevampire # 1788

**Comment by Raamyy** [comment]
Can your describe your problem in this way:

## What should happen
you describe here the expected behaviour of the room.

## What actually happens
you describe here the problem that exists

**Comment by furkanardagul** [comment]
**What should happen**

If x is not true, a player is banned from being taken to the other team by anyone and sends back a message to the room. If it's true, then don't get in the way.

What actually happens

When x is not true, it does not allow the player to join the team. However, after that, the bot gives the warning message twice because it specs again.

**Comment by Raamyy** [comment]
Okay now i understand the double message warning. in the `onPlayerTeamChange` function you shouldn't send the warning message if the movedPlayer teams is specs team.

```js
function onPlayerTeamChange(movedPlayer, moverPlayer){
...
if(movedPlayer.team != 0) // team 0 is specs team
    room.sendChat("WARNING MESSAGE"); 
}
```

**Comment by furkanardagul** [comment]
Thank you friends, have a good day :)))
