### ISSUE TITLE
Avatar System

### ISSUE THREAD

**Issue by furkanardagul** [haxball/haxball-issues#1215]
Hello, I want the avatar to be automatic and the avatar information to be written when the sequence goes to the desired place. How can I do that?

![image](https://user-images.githubusercontent.com/45922246/103518674-3dd63f00-4e85-11eb-9296-622eb3e04345.png)

**Comment by ghost** [comment]
```javascript
room.onGameTick = () => {
  var p = room.getPlayerList();
  for (let i = 0; i < p.length; i++) {
    const player = p[i];
     if(player.team === 0 ) continue;
    if (player.position.x === 100 && player.position.y === 100) {
      room.setPlayerAvatar(player.id, "Avatar");
    }
  }
};

```
You should change the position properties' value (x,y) that i typed random. This is just an example.

**Comment by furkanardagul** [comment]
```js
room.onGameTick = function() {


    isThrowInCorrect();
    getLastTouchTheBall();
    checkBallPosition();
    isBackRequired();
    getPlayersNotWithinLine();
    hasBallLeftTheLine();
    isBallGoingUp();
    if(!officialRSHLHost)
    {
        checkLineCrosses();
    }
}
room.onGameTick = () => {
    var p = room.getPlayerList();
    for (let i = 0; i < p.length; i++) {
      const player = p[i];
      if (player.position.x === '-144.0219261491482' && player.position.y === '178.42780620961284') {
        room.setPlayerAvatar(player.id, "3");
      }
    }
  };
```


I combined it with my previous codes, so I did it this way to avoid getting confused. But this time it gave a different error. Logs:

```
VM2204:622 Uncaught TypeError: Cannot read property 'x' of null
    at room.onGameTick (<anonymous>:622:27)
    at u.Ag (headless-min.js:formatted:2376)
    at J.Ba (headless-min.js:formatted:2559)
    at Aa.Ba (headless-min.js:formatted:3848)
    at Fa.dg (headless-min.js:formatted:1544)
    at Fa.Ba (headless-min.js:formatted:1623)
    at headless-min.js:formatted:2283
```

**Comment by saviola777** [comment]
You have to exclude spectators, they have no position attribute.

**Comment by furkanardagul** [comment]
These errors come when I start the room for the first time, so I cannot enter the room.

**Comment by furkanardagul** [comment]
```js
room.onGameTick = () => {
    var p = GetTeam(1);
    for (let i = 0; i < p.length; i++) {
      const player = p[i];
      if (player.position.x === -144.22795573014741 && player.position.y === 178.37386573566167) {
        room.setPlayerAvatar(player.id, "3");
      }
    }
  };
```


I am not getting an error right now, but the avatar does not change, there is no log.

**Comment by furkanardagul** [comment]
Up

**Comment by furkanardagul** [comment]
Up

**Comment by dixtel** [comment]
` if (player.position.x === -144.22795573014741 && player.position.y === 178.37386573566167)`
This will be always false because its impossible to someone be in the exact position as above.
You must create areas on map to detect where player are:
```js
if (player.position.x > 100 && player.position.x < 200 && player.position.y > 100 && player.position.y < 200)  {
        // player in  (100 < x < 200 ) and (100 < y < 200 ) 
        room.setPlayerAvatar(player.id, "3");
}
```

**Comment by furkanardagul** [comment]
Hi, although I did this, I did not get any results. The deadline of the project is approaching, is there a place where I can talk to you live if I ask?

**Comment by augus99** [comment]
The position of the player changes so fast that you cant rely on just comparing it with a single position. You should check if the player position is near to the other position. You can define the `near(a, b, radius)` function as follows:

```ts
const near = (a: Position, b: Position, radius: number = 3.5): boolean => {
    return (a.x - b.x)**2 + (a.y - b.y)**2 < radius**2
}
```

If you dont use typescript here is the javascript version
```js
function near(a, b, radius = 3.5) {
    return (a.x - b.x)**2 + (a.y - b.y)**2 < radius**2
}
```

Then you can use it
```ts
room.onGameTick = () => {
    room.getPlayerList().filter(player => player.team !== 0).forEach(player => {
        if(near(player.position, {x: 100, y: 100})) room.setPlayerAvatar(player.id, "Avatar");
        else room.setPlayerAvatar(player.id, undefined);
    })
};

// This function is only for testing purposes
// Displays the position of every player on the room.
setInterval(() => {
    room.getPlayerList().filter(player => player.position).forEach(player => {
        const x = Math.floor(player.position.x);
        const y = Math.floor(player.position.y);
        room.sendAnnouncement(`${player.name} position = (x: ${x}, y: ${y})`)
    })
}, 1000);
```

**Comment by furkanardagul** [comment]
First of all, thank you very much my friend. What you did worked and it works. However, that avatar disappears immediately after leaving that location. How can I fix this? I guess by subtracting if not right?

**Comment by augus99** [comment]
> First of all, thank you very much my friend. What you did worked and it works. However, that avatar disappears immediately after leaving that location. How can I fix this? I guess by subtracting if not right?

You need to remove the following line:
```ts
else room.setPlayerAvatar(player.id, undefined);
```

**Comment by furkanardagul** [comment]
Thank you friends thank you <3
