### ISSUE TITLE
Possibility of Starting the Game Time without Touching the Ball

### ISSUE THREAD

**Issue by jessaenn** [haxball/haxball-issues#1218]
As you know, there are some different costume maps that can be played without the ball. I’m a player who likes to play with these kind of maps and wanna do something with them by adding the game time into my bot, but the map that I use doesn’t have a ball in itself so it is not possible to get the value of the game time. Is there a solution anyone knows? I have tried something but my solutions didn’t work well.

**Comment by jessaenn** [comment]
Seems like there’s no any solution which might fix this problem by using JavaScript unless the creator of HaxBall does something, the problem has been fixed after the map that I’ve chosen to use was edited on HaxPucks.com by me.

**Comment by iAmLuks** [comment]
I believe there is a way to do it by modifying map file. 

Racing maps use same method no?

**Comment by jessaenn** [comment]
Yes, that’s how I fixed it.

**Comment by Wazarr94** [comment]
game time starts when xspeed or yspeed of the ball is > 0. you could set xspeed of ball to 0.0001 in your file
