### ISSUE TITLE
Time mm:ss

### ISSUE THREAD

**Issue by revolrepaid** [haxball/haxball-issues#1227]
Hello!
I really hope you can help me with this

**Example:**
```
room.onPlayerBallKick = function(player) {
	room.sendAnnouncement(player.name + " hits a ball. Time = " + room.getScores().time, undefined, 0xFFFF00, "small", 1);
}
```
gives this:

> PLAYER hits a ball. Time = 62.133333333333446

**My question/problem is:**
How to change the code so it will display that elapsed time in a standard haxball form (mm:ss)?

> PLAYER hits a ball. Time = 01:02

**Comment by saviola777** [comment]
The answers to many questions are but [one Internet search away](https://stackoverflow.com/questions/3733227/javascript-seconds-to-minutes-and-seconds).

**Comment by revolrepaid** [comment]
@saviola777 Before posting here my issue I swear I've found that already, but the thing is I still don't know how to use it my my code. I don't know how to combine it with room.getScores().time

**Comment by revolrepaid** [comment]
```
var minutes = Math.floor('room.getScores().time' / 60);
var seconds = 'room.getScores().time' - minutes * 60;

function str_pad_left(string,pad,length) {
    return (new Array(length+1).join(pad)+string).slice(-length);
}

var finalTime = str_pad_left(minutes,'0',2)+':'+str_pad_left(seconds,'0',2);


room.onPlayerBallKick = function(player) {
	room.sendAnnouncement(player.name + " hits a ball. Time = " + finalTime, undefined, 0xFFFF00, "small", 1);
}
```
gives this:

> PLAYER hits a ball. Time = aN:aN

:/

**Comment by revolrepaid** [comment]
Before posting here my issue I've also found the same [website](https://stackoverflow.com/questions/3733227/javascript-seconds-to-minutes-and-seconds), but the thing is I still don't know how to use it in my (presented above) code. I don't know how to combine it with `room.getScores().time` (it gives me errors...) and I found nothing about the same thing among other issues here (maybe in future my issue will be helpful for someone else if there will be a solution). :( 
How to combine `function fmtMSS(s){return(s-(s%=60))/60+(9<s?':':':0')+s}` from that website with `room.getScores().time`? Or maybe there's an easier solution?

For example:
```
var minutes = Math.floor('room.getScores().time' / 60);
var seconds = 'room.getScores().time' - minutes * 60;

function str_pad_left(string,pad,length) {
    return (new Array(length+1).join(pad)+string).slice(-length);
}

var finalTime = str_pad_left(minutes,'0',2)+':'+str_pad_left(seconds,'0',2);


room.onPlayerBallKick = function(player) {
	room.sendAnnouncement(player.name + " hits a ball. Time = " + finalTime, undefined, 0xFFFF00, "small", 1);
}
```
gives this:

> PLAYER hits a ball. Time = aN:aN

Eh... :(

**Comment by revolrepaid** [comment]
Before posting here my issue I've also found the same [website](https://stackoverflow.com/questions/3733227/javascript-seconds-to-minutes-and-seconds), but the thing is I still don't know how to use it in my (presented above) code. I don't know how to combine it with `room.getScores().time` _(I'm a newbie, I'm trying different options and I'm getting errors like in an example below...)_ and I found nothing about the same thing among other issues here _(so maybe in the future my issue will be helpful for someone else if there will be a simple solution)_. :( 
How to combine `function fmtMSS(s){return(s-(s%=60))/60+(9<s?':':':0')+s}` from that website with `room.getScores().time`? Or maybe there's an easier solution?

For example:
```
var minutes = Math.floor('room.getScores().time' / 60);
var seconds = 'room.getScores().time' - minutes * 60;

function str_pad_left(string,pad,length) {
    return (new Array(length+1).join(pad)+string).slice(-length);
}

var finalTime = str_pad_left(minutes,'0',2)+':'+str_pad_left(seconds,'0',2);


room.onPlayerBallKick = function(player) {
	room.sendAnnouncement(player.name + " hits a ball. Time = " + finalTime, undefined, 0xFFFF00, "small", 1);
}
```
gives this:

> PLAYER hits a ball. Time = aN:aN

Eh...
**Please help me if you know how to do it ;(**


_//EDIT:_
```
let timeString = `${'room.getScores().time'/60|0}:${'room.getScores().time'%60}`

room.onPlayerBallKick = function(player) {
	room.sendAnnouncement(player.name + " hits a ball. Time = " + timeString, undefined, 0xFFFF00, "small", 1);
}
```
gives this:

> PLAYER hits a ball. Time = 0:NaN

(even after 61 seconds)

**Comment by dixtel** [comment]
@revolrepaid Check this:
````js
function parseTime(time) {
    const min = Math.floor(time / 60);
    const sec = Math.floor(time % 60);

    let res = "";

    if (min < 10) res += "0" + min;
    else res += min;

    res += ":";

    if (sec < 10) res += "0" + sec;
    else res += sec;

    return res;
}

room.onPlayerBallKick = function(player) {
    room.sendAnnouncement(`${player.name} hits a bal. Time = ${parseTime(room.getScores().time)}`, undefined, 0xFFFF00, "small", 1);
}

**Comment by revolrepaid** [comment]
@dixtel HA! It works PERFECTLY! I love you! <3 Thank you sooooo much! :D
