### ISSUE TITLE
sendAnnouncement + player.admin (targetId)

### ISSUE THREAD

**Issue by revolrepaid** [haxball/haxball-issues#1229]
Hello Devs!

```
room.onPlayerJoin = function(player) {
	room.sendAnnouncement("Hello " + player.name + "!", player.id, 0xFF0000, "normal", 0);
	room.sendAnnouncement("message only for admins", player.admin, 0x808080, "normal", 0);
}
```
Why it doesn't want to send that second announcement only for admins? (it works with `player.id` and `undefined`). There's always a host "player" with admin rights. When I join and get admin rights, it still doesn't work when somebody joins the room after me. Does it need some function to update admins every time someone joins the room? I've tried to implement `updateAdmins();` but I'm getting an error in console `headless-min.js:50 ReferenceError: updateAdmins is not defined` and it's impossible to join the room.
**Do you know how to fix it? :(**

**Comment by augus99** [comment]
Whats wrong?
---
The signature of the `sendAnnouncement` method is:
```ts
sendAnnouncement(msg: string, targetId?: number, color?: number, style?: string, sound?: number): void;
```

And you are passing a `boolean` as the second argument instead of a `number`.

Solution
---
If you want to send a message only to the `admins connected` you can define the following function
```ts
const sendToAdmins = (text) => {
    room.getPlayerList().filter(player => player.admin).forEach(player => {
        room.sendAnnouncement(text, player.id, 0x808080, "normal", 0);
    });
}
```
And then you can call it with any text you want

Example
---
```ts
sendToAdmins("message only for admins");
```

**Comment by augus99** [comment]
To fix the `updateAdmins is not defined` error you need to declare the function first, it isn't included in the headless api, so you must write it yourself or copy the one in the [example pages](https://github.com/haxball/haxball-issues/wiki/Headless-Host). I recommend you to first learn the basic of the javascript programming language :)

**Comment by revolrepaid** [comment]
**Thank you VERY much @augus99! <3** Also for your explanation, because now I understand it. You are right about learning the basics, because only analyzing sample codes (and google'ing things) is not enough to understand everything for a newbie like me, so yeah, it's pretty hard to create my own function rn, but I don't want to give up. Such helpful people like you and dixtel really motivate me a lot, so thank you again ^^
