### ISSUE TITLE
Getting the Coordinates of a Map

### ISSUE THREAD

**Issue by jessaenn** [haxball/haxball-issues#1235]
How can I get the coordinates of a map correctly? I tried to do something by opening the map whom I wanna learn the coordinate values on HaxPucks.com but it is too confusing to understand the logic of it for me. The numerical values that appear when I use mouse cursor change faster than I thought at the first place. I am not really interested with this kind of deep issues about coding, but I believe that I can do what I want if I will get to learn something sensible. Thanks in advance.

**Comment by Raamyy** [comment]
I think map files are actually JSON text, So you can load it into a variable and get your values through that JSON object.

**Comment by jessaenn** [comment]
That’s exactly what I did, but the map that I use has 99 coordinate values so it’s a little bit hard to distinguish them to determine the points I want for a person like me who takes a look at it for the first time. I thought there was an easier way to do this but it seems like to be that there is not. I’ll do it carefully this way.
