### ISSUE TITLE
Normal admin vs MASTER ADMİN

### ISSUE THREAD

**Issue by hamburgstaller** [haxball/haxball-issues#1236]
There is an admin received by entering a code in the room. And there is a normal admin. Received without entering the code. Normal admin, I want to not be able to ban the admin of the master. How can I do it?

**Comment by hamburgstaller** [comment]
If Normal admin tries to ban the Master admin, it blocks it.
Master admin = giving admin by code ( i own this system )
Normal admin = giving admin by master admin

**Comment by thenorthstar** [comment]
@yusufemirxd You can use the following code:

```
var MasterAdmins = [];
var NormalAdmins = [];

room.onPlayerAdminChange = function(changedPlayer,byPlayer){
    if(byPlayer==null){ //Scenario without the host player
	if(changedPlayer.admin==true){
	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights");
	
	    if(MasterAdmins.includes(changedPlayer.name) == false){
		MasterAdmins.push(changedPlayer.name); //If the host admin gives anyone admin rights, then it is called as a master admin.
	    }
	}
	else{
	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away");
	}
    }
    else if(byPlayer!=null){ //Scenario with the host player or someone gives admin rights to another
	if(changedPlayer.admin==true){
	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights by " + byPlayer.name + " [" + byPlayer.id + "]");

	    if(byPlayer.id == 0){
		if(MasterAdmins.includes(changedPlayer.name) == false){
		    MasterAdmins.push(changedPlayer.name); //Scenario with the host player
		}
	    }
	    else{
		if(NormalAdmins.includes(changedPlayer.name) == false){
		    NormalAdmins.push(changedPlayer.name); //If a human admin gives anyone admin rights, then it is called as a normal admin.
		}
	    }
	}
	else{
	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away by " + byPlayer.name + " [" + byPlayer.id + "]");
	}
    }
}

room.onPlayerKicked = function(kickedPlayer,reason,ban,byPlayer){
    if(byPlayer==null){ //Scenario without the host player
	if(ban==0){
	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked (" + reason + ")");
	}
	else if(ban==1){
	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned (" + reason + ")");
	}
    }
    else if(byPlayer!=null){ //Scenario with the host player or someone bans another
	if(ban==0){
	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
	}
	else if(ban==1){
	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
	}

	if(byPlayer.id == 0){ //Scenario with the host player
	    return false;
	}
	else if(byPlayer.id != 0){
	    if(MasterAdmins.includes(kickedPlayer.name) == true && NormalAdmins.includes(byPlayer.name) == true){ //A normal admin bans a master admin
		room.kickPlayer(byPlayer.id,"You were banned due to banning a master admin",true);
	    }
	}
    }
}
```
With the above code, you can track the admin right changes and ban traffic through your console. I wish it would be helpful.

**Comment by hamburgstaller** [comment]
> @yusufemirxd You can use the following code:
> 
> ```
> var MasterAdmins = [];
> var NormalAdmins = [];
> 
> room.onPlayerAdminChange = function(changedPlayer,byPlayer){
>     if(byPlayer==null){ //Scenario without the host player
> 	if(changedPlayer.admin==true){
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights");
> 	
> 	    if(MasterAdmins.includes(changedPlayer.name) == false){
> 		MasterAdmins.push(changedPlayer.name); //If the host admin gives anyone admin rights, then it is called as a master admin.
> 	    }
> 	}
> 	else{
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away");
> 	}
>     }
>     else if(byPlayer!=null){ //Scenario with the host player or someone gives admin rights to another
> 	if(changedPlayer.admin==true){
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights by " + byPlayer.name + " [" + byPlayer.id + "]");
> 
> 	    if(byPlayer.id == 0){
> 		if(MasterAdmins.includes(changedPlayer.name) == false){
> 		    MasterAdmins.push(changedPlayer.name); //Scenario with the host player
> 		}
> 	    }
> 	    else{
> 		if(NormalAdmins.includes(changedPlayer.name) == false){
> 		    NormalAdmins.push(changedPlayer.name); //If a human admin gives anyone admin rights, then it is called as a normal admin.
> 		}
> 	    }
> 	}
> 	else{
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away by " + byPlayer.name + " [" + byPlayer.id + "]");
> 	}
>     }
> }
> 
> room.onPlayerKicked = function(kickedPlayer,reason,ban,byPlayer){
>     if(byPlayer==null){ //Scenario without the host player
> 	if(ban==0){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked (" + reason + ")");
> 	}
> 	else if(ban==1){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned (" + reason + ")");
> 	}
>     }
>     else if(byPlayer!=null){ //Scenario with the host player or someone bans another
> 	if(ban==0){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
> 	}
> 	else if(ban==1){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
> 	}
> 
> 	if(byPlayer.id == 0){ //Scenario with the host player
> 	    return false;
> 	}
> 	else if(byPlayer.id != 0){
> 	    if(MasterAdmins.includes(kickedPlayer.name) == true && NormalAdmins.includes(byPlayer.name) == true){ //A normal admin bans a master admin
> 		room.kickPlayer(byPlayer.id,"You were banned due to banning a master admin",true);
> 	    }
> 	}
>     }
> }
> ```
> 
> With the above code, you can track the admin right changes and ban traffic through your console. I wish it would be helpful.

it's helpful. thank you :)

**Comment by qoksel00** [comment]
> @yusufemirxd You can use the following code:
> 
> ```
> var MasterAdmins = [];
> var NormalAdmins = [];
> 
> room.onPlayerAdminChange = function(changedPlayer,byPlayer){
>     if(byPlayer==null){ //Scenario without the host player
> 	if(changedPlayer.admin==true){
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights");
> 	
> 	    if(MasterAdmins.includes(changedPlayer.name) == false){
> 		MasterAdmins.push(changedPlayer.name); //If the host admin gives anyone admin rights, then it is called as a master admin.
> 	    }
> 	}
> 	else{
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away");
> 	}
>     }
>     else if(byPlayer!=null){ //Scenario with the host player or someone gives admin rights to another
> 	if(changedPlayer.admin==true){
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "] was given admin rights by " + byPlayer.name + " [" + byPlayer.id + "]");
> 
> 	    if(byPlayer.id == 0){
> 		if(MasterAdmins.includes(changedPlayer.name) == false){
> 		    MasterAdmins.push(changedPlayer.name); //Scenario with the host player
> 		}
> 	    }
> 	    else{
> 		if(NormalAdmins.includes(changedPlayer.name) == false){
> 		    NormalAdmins.push(changedPlayer.name); //If a human admin gives anyone admin rights, then it is called as a normal admin.
> 		}
> 	    }
> 	}
> 	else{
> 	    console.log(changedPlayer.name + " [" + changedPlayer.id + "]'s admin rights were taken away by " + byPlayer.name + " [" + byPlayer.id + "]");
> 	}
>     }
> }
> 
> room.onPlayerKicked = function(kickedPlayer,reason,ban,byPlayer){
>     if(byPlayer==null){ //Scenario without the host player
> 	if(ban==0){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked (" + reason + ")");
> 	}
> 	else if(ban==1){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned (" + reason + ")");
> 	}
>     }
>     else if(byPlayer!=null){ //Scenario with the host player or someone bans another
> 	if(ban==0){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was kicked by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
> 	}
> 	else if(ban==1){
> 	    console.log(kickedPlayer.name + " [" + kickedPlayer.id + "] was banned by " + byPlayer.name + " [" + byPlayer.id + "] (" + reason + ")");
> 	}
> 
> 	if(byPlayer.id == 0){ //Scenario with the host player
> 	    return false;
> 	}
> 	else if(byPlayer.id != 0){
> 	    if(MasterAdmins.includes(kickedPlayer.name) == true && NormalAdmins.includes(byPlayer.name) == true){ //A normal admin bans a master admin
> 		room.kickPlayer(byPlayer.id,"You were banned due to banning a master admin",true);
> 	    }
> 	}
>     }
> }
> ```
> 
> With the above code, you can track the admin right changes and ban traffic through your console. I wish it would be helpful.

merhaba ben bunu botuma eklemedım çalısıyor tek istedigim master ile normal adminni yazılarını ayırmak
