### ISSUE TITLE
could someone pass a registration script? ç:

### ISSUE THREAD

**Issue by holyss** [haxball/haxball-issues#1237]

**Comment by thenorthstar** [comment]
@holyss You can use this code.

```js
let players = new Map();

room.onPlayerJoin = (player) =>  {
    players.set(player.id,
        {...player, authenticated: false, superAdmin: false});
    setTimeout(() => {
        let p = players.get(player.id);
        if (p && !p.authenticated) {
            room.kickPlayer(player.id, `You have not logged in`, false);
        }
    }, 30_000);
    updateAdmins();
    room.sendChat(`Welcome @${player.name}, please login in 30 seconds. If you are not registered, type !register <password> and register. Else type !confirm <password>.`);
}

room.onPlayerChat = (player, message) => {
    if(message.startsWith("!confirm")) {
        let [password, error] = extractPassword(message);
        if (error) {
            room.sendChat(`@${player.name}, ${error}`);
            return false;
        }
        login(player.id, player.name, password);
        return false;
    }
    else if(message.startsWith("!register")) {
        let [password, error] = extractPassword(message);
        if (error) {
            room.sendChat(`@${player.name}, ${error}`);
            return false;
        }
        register(player.name, password);
        return false;
    }
}

let extractPassword = (message) => {
    let split = message.split(" ");
    if (split.length !== 2) {
        return [undefined, "Password is wrong"];
    }
    return [split[1], undefined];
}

let mapToJson = (map) => {
    return JSON.stringify([...map]);
}

let jsonToMap = (jsonStr) => {
    return new Map(JSON.parse(jsonStr));
}

let register = (username, password) => {
    let db = jsonToMap(localStorage.getItem(USER_DATABASE));
    if (db.get(username)) {
        return room.sendChat(`@${username}, you are already registered`);
    }

    let map = db.set(username, password);
    localStorage.setItem(USER_DATABASE, mapToJson(map))
    return room.sendChat(`@${username}, you have registered. Do not forget to login by using !confirm <password> `);
}

let login = (id, username, password) => {
    let player = players.get(id);
    if (player.authenticated) {
        return room.sendChat(`@${username}, you are already logged in.`);
    }

    let db = jsonToMap(localStorage.getItem(USER_DATABASE));
    if (!db.get(username)) {
        return room.sendChat(`@${username}, you are not registered. Use "!register <password>" to register`);
    }
    if (db.get(username) !== password) {
        return room.sendChat(`@${username}, password is wrong`);
    }
    else {
        player.authenticated = true;
        players.set(id, player);
        return room.sendChat(`@${username}, you have logged in successfully, welcome!`);
    }
}
```

Source: https://github.com/FarukKaradeniz/SpaceHax-client/blob/master/src/room.js

Content has been simplified and translated to English. Thanks to Ömer Faruk Karadeniz for his scripts.

**Comment by holyss** [comment]
thanks c:

**Comment by thenorthstar** [comment]
You're welcome.

**Comment by hamburgstaller** [comment]
> You're welcome.

are u have online time system entegration with registration system?

**Comment by Enesbey635** [comment]
> @holyss Bu kodu kullanabilirsiniz.
> 
> ```
> let players = new Map();
> 
> room.onPlayerJoin = (player) =>  {
>     players.set(player.id,
>         {...player, authenticated: false, superAdmin: false});
>     setTimeout(() => {
>         let p = players.get(player.id);
>         if (p && !p.authenticated) {
>             room.kickPlayer(player.id, `You have not logged in`, false);
>         }
>     }, 30_000);
>     updateAdmins();
>     room.sendChat(`Welcome @${player.name}, please login in 30 seconds. If you are not registered, type !register <password> and register. Else type !confirm <password>.`);
> }
> 
> room.onPlayerChat = (player, message) => {
>     if(message.startsWith("!confirm")) {
>         let [password, error] = extractPassword(message);
>         if (error) {
>             room.sendChat(`@${player.name}, ${error}`);
>             return false;
>         }
>         login(player.id, player.name, password);
>         return false;
>     }
>     else if(message.startsWith("!register")) {
>         let [password, error] = extractPassword(message);
>         if (error) {
>             room.sendChat(`@${player.name}, ${error}`);
>             return false;
>         }
>         register(player.name, password);
>         return false;
>     }
> }
> 
> let extractPassword = (message) => {
>     let split = message.split(" ");
>     if (split.length !== 2) {
>         return [undefined, "Password is wrong"];
>     }
>     return [split[1], undefined];
> }
> 
> let mapToJson = (map) => {
>     return JSON.stringify([...map]);
> }
> 
> let jsonToMap = (jsonStr) => {
>     return new Map(JSON.parse(jsonStr));
> }
> 
> let register = (username, password) => {
>     let db = jsonToMap(localStorage.getItem(USER_DATABASE));
>     if (db.get(username)) {
>         return room.sendChat(`@${username}, you are already registered`);
>     }
> 
>     let map = db.set(username, password);
>     localStorage.setItem(USER_DATABASE, mapToJson(map))
>     return room.sendChat(`@${username}, you have registered. Do not forget to login by using !confirm <password> `);
> }
> 
> let login = (id, username, password) => {
>     let player = players.get(id);
>     if (player.authenticated) {
>         return room.sendChat(`@${username}, you are already logged in.`);
>     }
> 
>     let db = jsonToMap(localStorage.getItem(USER_DATABASE));
>     if (!db.get(username)) {
>         return room.sendChat(`@${username}, you are not registered. Use "!register <password>" to register`);
>     }
>     if (db.get(username) !== password) {
>         return room.sendChat(`@${username}, password is wrong`);
>     }
>     else {
>         player.authenticated = true;
>         players.set(id, player);
>         return room.sendChat(`@${username}, you have logged in successfully, welcome!`);
>     }
> }
> ```
> 
> Kaynak: https://github.com/FarukKaradeniz/SpaceHax-client/blob/master/src/room.js
> 
> İçerik basitleştirildi ve İngilizce'ye çevrildi. Senaryoları için Ömer Faruk Karadeniz'e teşekkürler.

**Comment by Enesbey635** [comment]
> @holyss Bu kodu kullanabilirsiniz.
> 
> ```
> let players = new Map();
> 
> room.onPlayerJoin = (player) =>  {
>     players.set(player.id,
>         {...player, authenticated: false, superAdmin: false});
>     setTimeout(() => {
>         let p = players.get(player.id);
>         if (p && !p.authenticated) {
>             room.kickPlayer(player.id, `You have not logged in`, false);
>         }
>     }, 30_000);
>     updateAdmins();
>     room.sendChat(`Welcome @${player.name}, please login in 30 seconds. If you are not registered, type !register <password> and register. Else type !confirm <password>.`);
> }
> 
> room.onPlayerChat = (player, message) => {
>     if(message.startsWith("!confirm")) {
>         let [password, error] = extractPassword(message);
>         if (error) {
>             room.sendChat(`@${player.name}, ${error}`);
>             return false;
>         }
>         login(player.id, player.name, password);
>         return false;
>     }
>     else if(message.startsWith("!register")) {
>         let [password, error] = extractPassword(message);
>         if (error) {
>             room.sendChat(`@${player.name}, ${error}`);
>             return false;
>         }
>         register(player.name, password);
>         return false;
>     }
> }
> 
> let extractPassword = (message) => {
>     let split = message.split(" ");
>     if (split.length !== 2) {
>         return [undefined, "Password is wrong"];
>     }
>     return [split[1], undefined];
> }
> 
> let mapToJson = (map) => {
>     return JSON.stringify([...map]);
> }
> 
> let jsonToMap = (jsonStr) => {
>     return new Map(JSON.parse(jsonStr));
> }
> 
> let register = (username, password) => {
>     let db = jsonToMap(localStorage.getItem(USER_DATABASE));
>     if (db.get(username)) {
>         return room.sendChat(`@${username}, you are already registered`);
>     }
> 
>     let map = db.set(username, password);
>     localStorage.setItem(USER_DATABASE, mapToJson(map))
>     return room.sendChat(`@${username}, you have registered. Do not forget to login by using !confirm <password> `);
> }
> 
> let login = (id, username, password) => {
>     let player = players.get(id);
>     if (player.authenticated) {
>         return room.sendChat(`@${username}, you are already logged in.`);
>     }
> 
>     let db = jsonToMap(localStorage.getItem(USER_DATABASE));
>     if (!db.get(username)) {
>         return room.sendChat(`@${username}, you are not registered. Use "!register <password>" to register`);
>     }
>     if (db.get(username) !== password) {
>         return room.sendChat(`@${username}, password is wrong`);
>     }
>     else {
>         player.authenticated = true;
>         players.set(id, player);
>         return room.sendChat(`@${username}, you have logged in successfully, welcome!`);
>     }
> }
> ```
> 
> Kaynak: https://github.com/FarukKaradeniz/SpaceHax-client/blob/master/src/room.js
> 
> İçerik basitleştirildi ve İngilizce'ye çevrildi. Senaryoları için Ömer Faruk Karadeniz'e teşekkürler.

I got errors, can you help?

Discord: FearLesS#6514

**Comment by Obsesiff66** [comment]
> Rica ederim.

maalesef wazarr 94 botuna uyunlu deil heralde

**Comment by Obsesiff66** [comment]
> Rica ederim.

dostum wazarr94 botuna olmuyor room.onplayeri oraya filan ekliyorum maalsef olmuyor uygun hale getirmeye çalıştım işte startwistleri falanda yine olmadı
