### ISSUE TITLE
fps-change

### ISSUE THREAD

**Issue by axtellclose8** [haxball/haxball-issues#124]
Hello! Now I want to retranslate my friend's idea (his English isn't okay, xD)
So, pls return the beautiful option of changing fps (30 or 60) because in HTML-5 may be hard to play, if you have some cheep notebook or netbook. For example, if you don't have top-PC, it's really hard to play with fps about 45-55

Thx-2 ))

**Comment by slavel** [comment]
Yes. This is a very important option. At me at 30 fps the perfect ball control...at 45-60 fps (and 60 fps in flash-haxball) the sensation of the rink and the non-synchronization of actions. And I have a pretty good laptop HP Pavilion G6 (AMD Radeon).

And many people complain about it...BASRO PLEASE!!!

**Comment by isotopie** [comment]
I also join the problem

**Comment by slavel** [comment]
if in the html-version will make a choice of 30 fps I will donat and play 24/7)))

**Comment by Otamendi30** [comment]
I also join the problem

**Comment by Kalyuzhniy** [comment]
Yes, it's very important to have a possibility to change FPS. I also join the problem.

**Comment by RusPal** [comment]
I also join the problem

**Comment by eazw** [comment]
yes, this is very important problem)
i agree

**Comment by slavel** [comment]
gogogo

**Comment by KTUFFH** [comment]
My man SlaveL is damn right!

**Comment by basro** [comment]
Well, this is harder to implement in html5 than in flash, but I'll give it a try anyway..

**Comment by slavel** [comment]
@basro Thank you, bro. This will help a lot of players get full pleasure from the game. So players will be more likely to go into the game = they will see more targeted ads = more monetization

**Comment by slavel** [comment]
@basro more monetization = a new level of investment.
And I hope to see in the future the game in Steam, because Haxball must be there, not Ball 3d)))

**Comment by slavel** [comment]
@basro I'm ready to personally test the update of the FPS option at all stages

**Comment by Haxballing** [comment]
@slavel Yea i know i want to thats why i posted this post and we also need Country Changer.

**Comment by basro** [comment]
30 FPS option is now implemented and released.

**Comment by slavel** [comment]
@basro Bravo! Thank you, now I have a perfectly smooth game! This is a great update!

**Comment by basro** [comment]
That's nice to hear

**Comment by slavel** [comment]
@basro go colorize the form in html5 version) ( /colors )
