### ISSUE TITLE
Player Movement Error

### ISSUE THREAD

**Issue by mirsaiddev** [haxball/haxball-issues#1247]
I'am playing this game very long time, and never faced this issue. but now I changed my PC and my players movement has changed too. It is like more gravity, different. I can't play with that player controls

**Comment by hamburgstaller** [comment]
/extrapolation x

x= {-200,200}

**Comment by ghost** [comment]
I also encounter the same situation since I switched from win7 laptop to win10 one. As a solution, I started playing with 65 extrapolation.

**Comment by ghost** [comment]
Did you ever try to change your screen's display resolution? It might be helpful for you.

**Comment by mirsaiddev** [comment]
@yusufemirxd 's comment worked perfectly, i used to play with extrapolation but i didn't know this is effecting that much, thanks everyone!
