### ISSUE TITLE
Discord integration 

### ISSUE THREAD

**Issue by Teteule** [haxball/haxball-issues#1258]
Hello coders. I found a code to call admin through discord, but I don't know how to use it. Can someone help me?

function sendAnnouncementToDiscord(message) {

var request = new XMLHttpRequest();
request.open("POST", yourwebhookURL);

request.setRequestHeader('Content-type', 'application/json');

var params = {
    avatar_url: '',
    username: 'Bildirim',
    content: message
};

request.send(JSON.stringify(params));
}

**Comment by ghost** [comment]
Don't share your webhook, you should delete it and create new one.
```javascript
function sendAnnouncementToDiscord(message) {

var request = new XMLHttpRequest();
request.open("POST", "https://discord.com/api/webhooks/812522038173499413/gWKlrsZwgNwn_oqzR7qlh-_xTn3ZiMksL1SdIObbS0uQ9dnbm-GPKk9w9_JtW1TgaT0M");

request.setRequestHeader('Content-type', 'application/json');

var params = {
avatar_url: '',
username: 'Bildirim',
content: message
};

request.send(JSON.stringify(params));
}
room.onPlayerChat = (player,message) =>{
sendAnnouncementToDiscord(`${player.name}: ${message}`)
}
```

**Comment by Teteule** [comment]
> ```js
> function sendAnnouncementToDiscord(message) {
> 
> var request = new XMLHttpRequest();
> request.open("POST", "https://discord.com/api/webhooks/812522038173499413/gWKlrsZwgNwn_oqzR7qlh-_xTn3ZiMksL1SdIObbS0uQ9dnbm-GPKk9w9_JtW1TgaT0M");
> 
> request.setRequestHeader('Content-type', 'application/json');
> 
> var params = {
> avatar_url: '',
> username: 'Bildirim',
> content: message
> };
> 
> request.send(JSON.stringify(params));
> }
> room.onPlayerChat = (player,message) =>{
> sendAnnouncementToDiscord(`${player.name}: ${message}`)
> ```

thanks friend. is it possible to make only one specific word appear in the discord? !calladmin for example. @ikramimamoglu

**Comment by ghost** [comment]
```javascript
function sendAnnouncementToDiscord(message) {

var request = new XMLHttpRequest();
request.open("POST", "https://discord.com/api/webhooks/812522038173499413/gWKlrsZwgNwn_oqzR7qlh-_xTn3ZiMksL1SdIObbS0uQ9dnbm-GPKk9w9_JtW1TgaT0M");

request.setRequestHeader('Content-type', 'application/json');

var params = {
avatar_url: '',
username: 'Bildirim',
content: message,
  allowed_mentions: {
    parse: []
  }
};

request.send(JSON.stringify(params));
}
room.onPlayerChat = (player,message) =>{
if(message == "!calladmin"){
sendAnnouncementToDiscord(`${player.name}  used  !calladmin command! <@adminroleID>` )
}
}
```

**Comment by Teteule** [comment]
thankss

**Comment by Teteule** [comment]
@ikramimamoglu Hello again :). Do you have a discord where we can talk? I still have some questions that I can't resolve. If you can't, no problem

**Comment by ghost** [comment]
dGF5eWliaXNpa2V5aW0=#1337

**Comment by byenice** [comment]
@ikramimamoglu Merhaba kardeşim, burada kullanıcıya  !calladmin komutundan sonra bir mesaj iletmesini istiyorum. Bu noktada komutu nasıl kodlayabilirim yanına.

**Comment by ghost** [comment]
> @ikramimamoglu Merhaba kardeşim, burada kullanıcıya !calladmin komutundan sonra bir mesaj iletmesini istiyorum. Bu noktada komutu nasıl kodlayabilirim yanına.

```
room.onPlayerChat = (player,message) =>{
if(message == "!calladmin"){
sendAnnouncementToDiscord(`${player.name}  used  !calladmin command! <@adminroleID>` )
room.sendAnnouncement("Adminlere Mesaj İletildi", player.id, null, 'bold',2)
}
}
```
