### ISSUE TITLE
HAXBALL SCREEN BUG

### ISSUE THREAD

**Issue by PERKNINE** [haxball/haxball-issues#1259]
![image](https://user-images.githubusercontent.com/79411598/108629777-cc1c7980-7461-11eb-883a-da95ebb2a3b6.png)

**Comment by jessaenn** [comment]
Sharing a screenshot without typing one word is not enough to find a solution for this problem. You should have explained something such as when this happens, how long it takes to disappear if it is disappeared after a while or what also you encounter with when it starts happening.

All I can say for now is, if the problem just happens on only one map, the map that you use may have a problem which causes this as I have never seen this problem in my 9 years of HaxBall experience.

**Comment by thenorthstar** [comment]
@PERKNINE Try to turn your screen on and off quickly by pressing **esc** button on your keyboard. I sometimes encounter with the same error and it's usually fixed when I did what I have said.

**Comment by PERKNINE** [comment]
No, everyone see this bug.

**Comment by jessaenn** [comment]
@PERKNINE, you should do what @thenorthstar told you. If the solution which was written above won’t work, please do what I asked you to do. Then perhaps we may be able to produce something sensible by the steps that you could sort when needed.

**Comment by Utruka** [comment]
I have this problem too. The ESC button does not help.

**Comment by basro** [comment]
Please give more details, does it happen always? what browser? what version of the browser?

**Comment by thenorthstar** [comment]
> Please give more details, does it happen always? what browser? what version of the browser?

Personally, I had encountered with his bug in Google Chrome (current version is 88.0.4324.190 but the there is long time past after I have encountered that bug) when more than one AFK players have been kicked from the room. And interestingly it was being fixed when I had pressed **ESC** button twice quickly.

**Comment by Flinch101** [comment]
> Por favor, dé más detalles, ¿sucede siempre? que navegador ¿Qué versión del navegador?

Hola basro. Es un mapa que se llama bugadao. No sucede siempre, solo con ese mapa. Y pasa que cuando abres un mapa despues de bugadao, se bugea, por ejemplo si pongo ese, y dps cualquier otro (con el mismo tamaño), también se bugea.

![image](https://user-images.githubusercontent.com/72756232/110251149-f1c77980-7f5d-11eb-855d-6218ea3dbe9b.png)
Cuando toco la pelota, se pone todo raro:
![image](https://user-images.githubusercontent.com/72756232/110251190-29cebc80-7f5e-11eb-9e7f-4bf3c770aea7.png)
![image](https://user-images.githubusercontent.com/72756232/110251196-33f0bb00-7f5e-11eb-968a-9a6276b58e28.png)

Cuando toco la pelota, no me deja mover, pero si me pongo denuevo, pasa lo que puso Perk
![image](https://user-images.githubusercontent.com/72756232/110251213-54b91080-7f5e-11eb-8e19-e02e6d78ecf1.png)

Cambiando de camara, se hace mas grande o mas pequeño el jugador, para mi depende de la pantalla, y no del juego, ahora cambio de mapa y pasa esto:
![image](https://user-images.githubusercontent.com/72756232/110251250-7b774700-7f5e-11eb-9bba-c9cfa3bb2923.png)

Ahi puse como pasa, y dando ESC no funciona.

Espero haber ayudado Flinch.

**Comment by basro** [comment]
Tenés un link para descargar el mapa?

**Comment by Flinch101** [comment]
Realmente no, pero te puedo pasar el mapa en HBS. Y una pregunta que no tiene nada que ver, jugas haxball? Y si es asi, como te llamas?

**Comment by Flinch101** [comment]
[mapa.zip](https://github.com/haxball/haxball-issues/files/6097849/mapa.zip)

**Comment by basro** [comment]
Gracias, pude reproducir el bug, lo debuguearé pronto.
Si juego de vez en cuando pero voy a permanecer anónimo.

In english for those interested in the status of this issue: I was able to reproduce the bug, I'll be debugging it soon.

**Comment by Flinch101** [comment]
Bueno genial! Gracias por seguir con haxball, algunos piensan que desapareciste, como lo hacia yo antes, pero gracias!

**Comment by Skarmunds** [comment]
> 
> 
> Gracias, pude reproducir el bug, lo debuguearé pronto.
> Si juego de vez en cuando pero voy a permanecer anónimo.
> 
> In english for those interested in the status of this issue: I was able to reproduce the bug, I'll be debugging it soon.

Hey, @basro ! How it's going with this thing? Or how to contact you. I could trigger it each time with self-constructed map too.

**Comment by basro** [comment]
This bug is now fixed.
