### ISSUE TITLE
Haxball feels like the game moves for me and ball doesn't stick (NEW PC)

### ISSUE THREAD

**Issue by scottballa** [haxball/haxball-issues#1267]
So I got a new PC almost a month ago and have struggled to find a reason why the game feels like I have less control of my dot and the ball does not stick nearly as well as it did on my old PC. 

I have tried half a dozen different browsers and extrapolation and they all have the same sort of swaying feeling where I don't feel like I have full control of my dot and it might move too far in a certain direction or not far enough at all. It is hard to describe. The original browser settings I used on my old PC were Firefox on uncapped FPS and when I do that on this new PC it's like I get a way higher FPS number but the game visually is choppy, also the gameplay still has that weird swaying feeling where it's like it over/undercompensates movement. I am currently using Microsoft Edge uncapped as it has had the best visual smoothness of all the browsers I've tried but the swaying, sometimes uncontrolable movement still remains.

I've been playing this game for a long time and on that old PC for a long time as well, this does not feel right at all. The specs on my new PC are infinitely better than my old one but for some reason the game feels worse on all browsers, extrapolation, GPU settings. Also, my ping is lower in every single room than it was with my old PC, so it is really confusing. 

If there are any reasons as to why there would be a difference or any advice as to how I can get a gameplay experience that would be similar to my old PC, or better than it feels right now, I'd love to hear it. Thanks!

**Comment by theOneAndOnly120** [comment]
@scottballa You're just mad bad at the game. Get better

**Comment by scottballa** [comment]
Thanks for the help!

**Comment by scottballa** [comment]
Toxic and no replies
