### ISSUE TITLE
Sending messages from discord to haxball chat

### ISSUE THREAD

**Issue by wohSi** [haxball/haxball-issues#1269]
I saw a lot of examples to display chat room to discord, but how i can send a message from discord to haxball chat being the host?

**Comment by nas0s** [comment]
It is possible with the discord.js library, but I have no idea how to put it in vanilla javascript.

**Comment by ikramimamoglu** [comment]
> I saw a lot of examples to display chat room to discord, but how i can send a message from discord to haxball chat being the host?

### I think you can do it by using [Haxroomie](https://www.npmjs.com/package/haxroomie-core) and [discord.js](https://www.npmjs.com/package/discord.js) libraries on node.js.
