### ISSUE TITLE
Information who banned or kicked players

### ISSUE THREAD

**Issue by pandorin1488** [haxball/haxball-issues#127]
Hey man. There are situations when admin rights are many players of different teams. And find out who did it. Starts srach

Example. **Wenomka was banned by Massik**
or
**Wenomka was banned (Massik)**

**Comment by hypehaxx** [comment]
Actually there is already such kind of feature. Panda stop drinking

**Comment by pandorin1488** [comment]
Ебать. Внатуре я лоханулся. Delete issue

**Comment by Leo-MapCreator** [comment]
Does it show to the player who got banned? I think it would be good to put that
