### ISSUE TITLE
discussion about different aspects and requests

### ISSUE THREAD

**Issue by marshall12341** [haxball/haxball-issues#128]
A lot of people are enjoying haxball the way it is. For now, I saw enough topics to make "different power shots" or something kind of "curling the ball" and etc. The thing is that haxball is meant to be a simple game, which has pretty high skill ceiling and meanwhile you have to play only with 5 buttons, that makes it very hard to play it good. So imo nothing should be changed in this area - leave it like it is.

**Registration system**
I have heard a lot of discussion about this topic since html5 was announced. Many people suggest doing this, but they don't realize the main thing. Someone just could register all the nicknames ( of good players ) and that'd be not nice. Also there should be bigger database to save all the info. Personally I'd like to see this feature in the newer versions of haxball and turning it to beta testing, but I'd suggest letting to register only 3 nicknames from one ip address. Ofcourse that's the most simple way which can be easily bypassed, but at least I gave the main idea.

**Sounds**
Damn... Not only I had a lot of "triggering" when someone is chatting non-stop in some good public room, can it be admin or just a player, that's still annoying. Personally I'd like to have an option disabling different sounds - game's or chat's. I guess it'd also let players to concentrate better while playing. P.S. there should be an option to hide the whole chat too then!

**Totally clear avatar**
As much as I saw, now haxball "/avatar" function takes any kind of symbols. That's really nice and I do enjoy it as much as any other passionate player. But... I have always enjoyed playing "avatarless" ( nothing on the avatar, totally nothing.. ), so it'd be nice if there was some kind of "function" that could make it this way.

**Switching team sides**
Not that important. From now what I can say, there should be a feature which would let admins to change "team sides" just by one click. Now you need to put it on ur own and while it's taking much time, it'd be nice to have possibility changing it by one click! ( Red Team is moves to Blue automatically and vice versa )

**Training mode**
Now that's the thing. I'm not talking about bots and etc. The few aspects there should be are : up to 10 balls in a room ; no goals are allowed. There are many maps who are some kind of "training", but they can't produce any more balls. Imo this should be really cool and improve the satisfaction of training in this game.

**Flag changing**
Uhm, many people are more like "trolling" on this and that's totally ok, but imo there shouldn't be such option. Other people start "faking" each other while changing the flag. There are some other problems which contain this "flag swap" as well, but let's keep it quiet for now.

To be honest, before writting this I had a lot more ideas and discussion aspects, but now I have "forgotten"'em. Sorry for my english as it's not my native language. ^^ Feel free to discuss!

**Comment by marshall12341** [comment]
Ah also forgot to mention I haven't read any other threads in this "issues" topic so sorry if it's a duplicate of some other idea.

**Comment by BrazilHax** [comment]
beautiful topic

**Comment by Leo-MapCreator** [comment]
First of all, different strengh of the shots will higher the skill ceiling at pro level, cause you have better control of the ball, the normal X, with 100% of the kicking strengh, and another key, C, with around 60%, that is better for passes, basro have that in mind, but he is still deciding if he will put this feature #106 

**Registration System**
This system will prevent people faking your name and trolling the room, and later when you join the room you are banned even though you did nothing, the option to only register 3 accounts per IP isnt bad, as it will prevent someone to create a lot of accounts with other peoples name

**Sounds**
This idea is good, so you can mute chat spammers, but the option to hide the chat in my opnion isnt the best option, cause sometimes you lag, or whatever, and you need to ask the admin to pause the game, how is he going to pause the game if his chat is disabled and he cant see it?

**Totally clear avatar**
Not the most important thing here, but isnt a bad idea either, it could be "/avatar [space]" with '[space]' being the space key of the keyboard

**Switching team sides**
Agreed

**Training mode**
In my opnion it just need to allow 'discs' from custom map to be kicked, not that hard to do

**Flag changing**
Sometimes Haxball recognizes your country wrongly, if you dont allow people to correct it, you will be playing with a different flag that doesnt represent your country, sometimes it can unmotivate you to play #78

**Comment by helppe** [comment]
not agree with registration system.
i don't want to be restricted.

if someone create before you an account with the name you wanted it's up to you to register it the 1st..., 
when i created a gmail account i wanted a nickname that was already taken, i just accepted it and created an other one...
you can create an other nickname and keep it and make your reputation with this nickname. where is the problem with that?

or why not having a registration mode **and** a guest mode (without authentification) to play with any nickname but written in an other color to show it is a guest account.

**Comment by Leo-MapCreator** [comment]
I agree with @helppe on the Guest Part, HaxArena have that and it works fine without a problem

**Comment by helppe** [comment]
just one precision when i wrote "not agree with registration system" i talked about the limit by ip address.
i didn't talk about the fact that we can register. ^^

**Comment by Leo-MapCreator** [comment]
I think it needs limit by IP, cause if some tard decide to troll haxball and create 200 account it will waste space on haxball server storage

**Comment by basro** [comment]
I appreciate the feedback but this is not the way to use an issue tracker. It's not a forum.
Issues need to focus on a single thing so I'm closing this issue. Feel free to create issues for each individual point (but please do search before you create one to avoid duplicates).

> Ah also forgot to mention I haven't read any other threads in this "issues" topic so sorry if it's a duplicate of some other idea.
It's pretty bad that you didn't, I ask that you avoid creating duplicates since it creates more work for me.

**Comment by Haxballing** [comment]
I think the training mode its good idea.
the X 100% Power shot and C 60% i dont think its gonna be so good this can confuse many players.
and The flag changer we need this also fast same as we need the fps changer.
but hopefully flag changer gonna be now not only 30 or 60 instead let us decide which fps we want from  0-60.
