### ISSUE TITLE
How do i use this i found it in a reply on issues

### ISSUE THREAD

**Issue by IgnacioBlade** [haxball/haxball-issues#1285]
const idToAuth = {};

room.onPlayerJoin = (player) => {
    if (localStorage.getItem(player.auth) === "autoAdmin") {
        room.setPlayerAdmin(player.id, true);
    }
    
    idToAuth[player.id] = player.auth;
};

room.onPlayerChat = (player, message) => {
    if (message === "!password") {
        room.setPlayerAdmin(player.id, true);
        const playerauth = idToAuth[player.id];
        localStorage.setItem(playerauth, "autoAdmin");
    }
    return false;
};

**Comment by IgnacioBlade** [comment]
i found on somewhere but idk where to put it in the console with the script, im new with coding so idk

**Comment by IgnacioBlade** [comment]
and how do i make it so my room is public?
thanks

**Comment by IgnacioBlade** [comment]
s

**Comment by csvergaraa** [comment]
You should put these functions on your room script.

It seems like you don't know how to code. You should ask someone to help you or watch some lessons of javascript. It's pretty easy to learn.

Pay attention to the wiki's page. There are some explanation of room attributes.

**Comment by IgnacioBlade** [comment]
ok!
