### ISSUE TITLE
The outline around the ball.

### ISSUE THREAD

**Issue by RennSoo** [haxball/haxball-issues#129]
Please, do it removable. It confuses me when selecting the output of the gate.

**Comment by basro** [comment]
I have no idea of what you are asking

**Comment by RennSoo** [comment]
Circle around player!

**Comment by RennSoo** [comment]
Look now pls. I have edited that.

**Comment by basro** [comment]
ok, I understand what you mean now.

**Comment by RennSoo** [comment]
Aaaaaannnnnnddd????
