### ISSUE TITLE
game is not same windows 7 and windows 8/10

### ISSUE THREAD

**Issue by spammeurfou** [haxball/haxball-issues#130]
hello i play in windows 7 and i'm best with, but when i play with other computer in windows 8, and other with windows 10 i'm very bad because game is not same, game is not fast, i cant trick good play good idk, i'm best with windows 7 and noob with windows 8/windows 10

it's problem since long time in haxball, and now with haxball html 5, u need REALLY change this basro

**Comment by Leo-MapCreator** [comment]
Its probably you PC that is slow on Wind8/10, i dunno

**Comment by haxballer** [comment]
Unfortunately, I have same problem. I've tested some browsers on the new haxball, and the ball is getting heavier, the controls are changing, reflections are not easy as a few minutes before, even though I have a solid 60fps. What this is about?

**Comment by spammeurfou** [comment]
No Leo it's not my pc, i know all best players in game and have same problem, with windows 7 game is very good but windows 8 and windows 10 is bad idk why...

**Comment by Leo-MapCreator** [comment]
I play on Windows 10 + Chrome and i have no problem with lag, the only thing i would complain is the ping that when i lag it doesnt go up like it did with flash version, so its hard to people in the room believe i lagged, other than that the game is smooth and have no problem at all

**Comment by basro** [comment]
I've ran html5 HaxBall in windows 7 8 and 10 without issues. The windows version is not the problem.
Your issue description is too vague, I can't fix anything if I don't know what's wrong.
I'm closing this issue.
