### ISSUE TITLE
Possible to change buttons for controls

### ISSUE THREAD

**Issue by Wenomka** [haxball/haxball-issues#132]
(press for Kick) X \ space \ shift \ ctrl to C \ V \ Z or any button
(press for move) arrows \ WASD - to any buttons

Feature could be changed in game settings like "enable sound \  ping graph \ etc"

**Comment by slavel** [comment]
+

**Comment by slavel** [comment]
++++ go

**Comment by haxballer** [comment]
I would like to be able to disable a particular key in the game options, because by regularly pressing the up arrow I also push the right shift, which is terribly annoying.

**Comment by basro** [comment]
This is implemented.
