### ISSUE TITLE
Player can kick himself

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#134]
Why someone can kick itself?
https://gyazo.com/48f7e98d61581fc84595e908b7a4de15

**Comment by Leo-MapCreator** [comment]
He was the only 'Nautico' on the room

**Comment by cr0ndor** [comment]
This is just an HTML feature.

**Comment by Leo-MapCreator** [comment]
Thinking better about this, it doesnt change anything in haxball and it's better because you can remove your own admin

**Comment by Leo-MapCreator** [comment]
I closed because it doesnt affect anything in the game, plus the reason i've opened it, was because it was different from the flash, but not in fact a ''bug'', and thinking about it, if you fix it there will be threads asking to put it back because some players use this 'feature'
