### ISSUE TITLE
can anyone help me about 3 defender rule?

### ISSUE THREAD

**Issue by tanercanbilgin** [haxball/haxball-issues#1349]
i have a code from 2 years ago but its not working, i tried to update it but still not working :( this rule is so important for every game so if you know how to do it, it would make me so happy. thanks

**Comment by thenorthstar** [comment]
> i have a code from 2 years ago but its not working, i tried to update it but still not working :( this rule is so important for every game so if you know how to do it, it would make me so happy. thanks

@tanercanbilgin You most probably have these scripts.

[3_def_warning_sys.txt](https://github.com/haxball/haxball-issues/files/6603167/3_def_warning_sys.txt)

I remember that I had posted these scripts to somewhere a long time ago, after finding on GitHub (but don't remember where did I found lol)

Anyway, I have such a bot for 3-def rule. You and others who search for such a thing can use it.

[3deflines.txt](https://github.com/haxball/haxball-issues/files/6603166/3deflines.txt)

**Comment by tanercanbilgin** [comment]
thank you so much, can you give your discord. i have some codes but i cant manage to use them in my bot

**Comment by tanercanbilgin** [comment]
@thenorthstar kanka botu deniyorum ama

```
VM460:28 Uncaught TypeError: Cannot read property 'id' of undefined
    at adjustDefLines (<anonymous>:28:46)
    at room.onGameTick (<anonymous>:110:9)
    at u.Ag (headless-min.js:65)
    at J.Ba (headless-min.js:69)
    at Aa.Ba (headless-min.js:100)
    at Fa.dg (headless-min.js:44)
    at Fa.Ba (headless-min.js:46)
    at Fa.wh (headless-min.js:50)
    at Na.a.$e (headless-min.js:47)
    at RTCDataChannel.Na.e.onmessage
```

hatası alıyorum

hata verdiği kısım 

   ```
 if(room.getPlayerDiscProperties(mfp_red.id).cGroup === cf.red){
        room.setPlayerDiscProperties(mfp_red.id,{cGroup:cf.red | cf.c0});
    }
    if(room.getPlayerDiscProperties(mfp_blue.id).cGroup === cf.blue){
        room.setPlayerDiscProperties(mfp_blue.id,{cGroup:cf.blue | cf.c1});
    }
```
ve 
        `adjustDefLines();`

**Comment by thenorthstar** [comment]
> @thenorthstar kanka botu deniyorum ama
> 
> ```
> VM460:28 Uncaught TypeError: Cannot read property 'id' of undefined
>     at adjustDefLines (<anonymous>:28:46)
>     at room.onGameTick (<anonymous>:110:9)
>     at u.Ag (headless-min.js:65)
>     at J.Ba (headless-min.js:69)
>     at Aa.Ba (headless-min.js:100)
>     at Fa.dg (headless-min.js:44)
>     at Fa.Ba (headless-min.js:46)
>     at Fa.wh (headless-min.js:50)
>     at Na.a.$e (headless-min.js:47)
>     at RTCDataChannel.Na.e.onmessage
> ```
> 
> hatası alıyorum
> 
> hata verdiği kısım
> 
> ```
> if(room.getPlayerDiscProperties(mfp_red.id).cGroup === cf.red){
>      room.setPlayerDiscProperties(mfp_red.id,{cGroup:cf.red | cf.c0});
>  }
>  if(room.getPlayerDiscProperties(mfp_blue.id).cGroup === cf.blue){
>      room.setPlayerDiscProperties(mfp_blue.id,{cGroup:cf.blue | cf.c1});
>  }
> ```
> 
> ve
> `adjustDefLines();`

@tanercanbilgin Oyunu başlatmadan önce 3v3 haritası otomatik açılmıyorsa haritayı kendin manuel açmayı deneyebilirsin. Gerçi bende her türlü hatasız çalışıyor ama senin bot kodlarından kaynaklı olarak öyle bir durum olmuş olabilir. Bu arada aynı hatayı bir kişi daha almış, ona da aynı durumu izah ettim.

Link: https://thehax.pl/forum/powtorki.php?nagranie=d13e6e184e9a2a422df6ee3bc0dbc0dd

**Comment by tanercanbilgin** [comment]
> > @thenorthstar kanka botu deniyorum ama
> > ```
> > VM460:28 Uncaught TypeError: Cannot read property 'id' of undefined
> >     at adjustDefLines (<anonymous>:28:46)
> >     at room.onGameTick (<anonymous>:110:9)
> >     at u.Ag (headless-min.js:65)
> >     at J.Ba (headless-min.js:69)
> >     at Aa.Ba (headless-min.js:100)
> >     at Fa.dg (headless-min.js:44)
> >     at Fa.Ba (headless-min.js:46)
> >     at Fa.wh (headless-min.js:50)
> >     at Na.a.$e (headless-min.js:47)
> >     at RTCDataChannel.Na.e.onmessage
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > hatası alıyorum
> > hata verdiği kısım
> > ```
> > if(room.getPlayerDiscProperties(mfp_red.id).cGroup === cf.red){
> >      room.setPlayerDiscProperties(mfp_red.id,{cGroup:cf.red | cf.c0});
> >  }
> >  if(room.getPlayerDiscProperties(mfp_blue.id).cGroup === cf.blue){
> >      room.setPlayerDiscProperties(mfp_blue.id,{cGroup:cf.blue | cf.c1});
> >  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ve
> > `adjustDefLines();`
> 
> @tanercanbilgin Oyunu başlatmadan önce 3v3 haritası otomatik açılmıyorsa haritayı kendin manuel açmayı deneyebilirsin. Gerçi bende her türlü hatasız çalışıyor ama senin bot kodlarından kaynaklı olarak öyle bir durum olmuş olabilir. Bu arada aynı hatayı bir kişi daha almış, ona da aynı durumu izah ettim.
> 
> Link: https://thehax.pl/forum/powtorki.php?nagranie=d13e6e184e9a2a422df6ee3bc0dbc0dd

evet harita açılmıyor, kendim ekliyorum fakat aynı hatayı alıyorum. attığın botun aynısını kullandım, kendi botuma da aktardım id hatası alıyorum. daha sonra başka bi 3 defans botu buldum onu denedim işe yaradı fakat biraz yanlış ve buglı duruyor. zamanın varsa gösterebilir miyim

**Comment by thenorthstar** [comment]
> > > @thenorthstar kanka botu deniyorum ama
> > > ```
> > > VM460:28 Uncaught TypeError: Cannot read property 'id' of undefined
> > >     at adjustDefLines (<anonymous>:28:46)
> > >     at room.onGameTick (<anonymous>:110:9)
> > >     at u.Ag (headless-min.js:65)
> > >     at J.Ba (headless-min.js:69)
> > >     at Aa.Ba (headless-min.js:100)
> > >     at Fa.dg (headless-min.js:44)
> > >     at Fa.Ba (headless-min.js:46)
> > >     at Fa.wh (headless-min.js:50)
> > >     at Na.a.$e (headless-min.js:47)
> > >     at RTCDataChannel.Na.e.onmessage
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > hatası alıyorum
> > > hata verdiği kısım
> > > ```
> > > if(room.getPlayerDiscProperties(mfp_red.id).cGroup === cf.red){
> > >      room.setPlayerDiscProperties(mfp_red.id,{cGroup:cf.red | cf.c0});
> > >  }
> > >  if(room.getPlayerDiscProperties(mfp_blue.id).cGroup === cf.blue){
> > >      room.setPlayerDiscProperties(mfp_blue.id,{cGroup:cf.blue | cf.c1});
> > >  }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ve
> > > `adjustDefLines();`
> > 
> > 
> > @tanercanbilgin Oyunu başlatmadan önce 3v3 haritası otomatik açılmıyorsa haritayı kendin manuel açmayı deneyebilirsin. Gerçi bende her türlü hatasız çalışıyor ama senin bot kodlarından kaynaklı olarak öyle bir durum olmuş olabilir. Bu arada aynı hatayı bir kişi daha almış, ona da aynı durumu izah ettim.
> > Link: https://thehax.pl/forum/powtorki.php?nagranie=d13e6e184e9a2a422df6ee3bc0dbc0dd
> 
> evet harita açılmıyor, kendim ekliyorum fakat aynı hatayı alıyorum. attığın botun aynısını kullandım, kendi botuma da aktardım id hatası alıyorum. daha sonra başka bi 3 defans botu buldum onu denedim işe yaradı fakat biraz yanlış ve buglı duruyor. zamanın varsa gösterebilir miyim

@tanercanbilgin Dostum merbaha, bot kodlarını güncelledim. Uzun bir uğraşın ardından bota hata verdirmeyi başardım. Takımlardan herhangi birinde oyuncu kalmadığında veriyormuş hatayı. Son güncellediğim hâlinde o hatayı da vermedi bir daha bende. Bu arada öbür arkadaşa söyledim sana da söylemiş olayım, **findDefLines()** fonksiyonunu (ve tabiî ki bağladığı yerleri) işine yaramıyorsa silebilirsin çünkü kullandığın haritaya göre hata verme olasılığı bulunan bir fonksiyon.

[3deflines.txt](https://github.com/haxball/haxball-issues/files/6618780/3deflines.txt)

**Comment by tanercanbilgin** [comment]
@thenorthstar çok teşekkür ederim, şu an typescript botuma uyarlamaya çalışıyorum. elimde bi de scoreboard var, yardımcı olabilir misin müsaitsen?

**Comment by azagni** [comment]
> > > > @thenorthstar kanka botu deniyorum ama
> > > > ```
> > > > VM460:28 Uncaught TypeError: Cannot read property 'id' of undefined
> > > >     at adjustDefLines (<anonymous>:28:46)
> > > >     at room.onGameTick (<anonymous>:110:9)
> > > >     at u.Ag (headless-min.js:65)
> > > >     at J.Ba (headless-min.js:69)
> > > >     at Aa.Ba (headless-min.js:100)
> > > >     at Fa.dg (headless-min.js:44)
> > > >     at Fa.Ba (headless-min.js:46)
> > > >     at Fa.wh (headless-min.js:50)
> > > >     at Na.a.$e (headless-min.js:47)
> > > >     at RTCDataChannel.Na.e.onmessage
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > hatası alıyorum
> > > > hata verdiği kısım
> > > > ```
> > > > if(room.getPlayerDiscProperties(mfp_red.id).cGroup === cf.red){
> > > >      room.setPlayerDiscProperties(mfp_red.id,{cGroup:cf.red | cf.c0});
> > > >  }
> > > >  if(room.getPlayerDiscProperties(mfp_blue.id).cGroup === cf.blue){
> > > >      room.setPlayerDiscProperties(mfp_blue.id,{cGroup:cf.blue | cf.c1});
> > > >  }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ve
> > > > `adjustDefLines();`
> > > 
> > > 
> > > @tanercanbilgin Oyunu başlatmadan önce 3v3 haritası otomatik açılmıyorsa haritayı kendin manuel açmayı deneyebilirsin. Gerçi bende her türlü hatasız çalışıyor ama senin bot kodlarından kaynaklı olarak öyle bir durum olmuş olabilir. Bu arada aynı hatayı bir kişi daha almış, ona da aynı durumu izah ettim.
> > > Link: https://thehax.pl/forum/powtorki.php?nagranie=d13e6e184e9a2a422df6ee3bc0dbc0dd
> > 
> > 
> > evet harita açılmıyor, kendim ekliyorum fakat aynı hatayı alıyorum. attığın botun aynısını kullandım, kendi botuma da aktardım id hatası alıyorum. daha sonra başka bi 3 defans botu buldum onu denedim işe yaradı fakat biraz yanlış ve buglı duruyor. zamanın varsa gösterebilir miyim
> 
> @tanercanbilgin Dostum merbaha, bot kodlarını güncelledim. Uzun bir uğraşın ardından bota hata verdirmeyi başardım. Takımlardan herhangi birinde oyuncu kalmadığında veriyormuş hatayı. Son güncellediğim hâlinde o hatayı da vermedi bir daha bende. Bu arada öbür arkadaşa söyledim sana da söylemiş olayım, **findDefLines()** fonksiyonunu (ve tabiî ki bağladığı yerleri) işine yaramıyorsa silebilirsin çünkü kullandığın haritaya göre hata verme olasılığı bulunan bir fonksiyon.
> 
> [3deflines.txt](https://github.com/haxball/haxball-issues/files/6618780/3deflines.txt)

Map not loading when first opened.

**Comment by thenorthstar** [comment]
Yes, I know. I have not added such a code on purpose. You can add **room.setCustomStadium(Map)** below the map codes if you want.

**Comment by tanercanbilgin** [comment]
gerçekten şaka gibi adam yazdığı mesajı sildi... bunlar yüzünden insanın yardım edesi gelmiyo, bazıları da sayende aldığı kodları başkalarına parayla satıyolar gerçekten çok üzücü

**Comment by thenorthstar** [comment]
Ben bu işi insanlara yardım etmek için yapıyorum, bunlardan para kazanmak gibi bir kaygım olsa işi gücü bırakır bot yapar satarım burada. O arkadaşın amacı da zaten yardım almak falan değil, emek hırsızlığı yapmak.

**Comment by ghost** [comment]
> Ben bu işi insanlara yardım etmek için yapıyorum, bunlardan para kazanmak gibi bir kaygım olsa işi gücü bırakır bot yapar satarım burada. O arkadaşın amacı da zaten yardım almak falan değil, emek hırsızlığı yapmak.

Bir tane arkadas vardi gecen gun her seye seni, beni ve baskalarini etiketleyip en basit seyde bile yardim istiyordu. O arkadas mi? @thenorthstar

**Comment by ghost** [comment]
> gerçekten şaka gibi adam yazdığı mesajı sildi... bunlar yüzünden insanın yardım edesi gelmiyo, bazıları da sayende aldığı kodları başkalarına parayla satıyolar gerçekten çok üzücü

Gecen gun dedigin seyi yapan birisiyle karsilastim. [Bu kodu satiyordu](https://github.com/haxball/haxball-issues/issues/1174#issuecomment-726744090) hahaha :D

**Comment by thenorthstar** [comment]
> > Ben bu işi insanlara yardım etmek için yapıyorum, bunlardan para kazanmak gibi bir kaygım olsa işi gücü bırakır bot yapar satarım burada. O arkadaşın amacı da zaten yardım almak falan değil, emek hırsızlığı yapmak.
> 
> Bir tane arkadas vardi gecen gun her seye seni, beni ve baskalarini etiketleyip en basit seyde bile yardim istiyordu. O arkadas mi? @thenorthstar

@ikramimamoglu Evet, tam olarak o arkadaş, istediğini alamayınca hesabını silmiş herhalde. **Ghost** yazıyordu çünkü hesabında.

**Comment by thenorthstar** [comment]
> > gerçekten şaka gibi adam yazdığı mesajı sildi... bunlar yüzünden insanın yardım edesi gelmiyo, bazıları da sayende aldığı kodları başkalarına parayla satıyolar gerçekten çok üzücü
> 
> Gecen gun dedigin seyi yapan birisiyle karsilastim. [Bu kodu satiyordu](https://github.com/haxball/haxball-issues/issues/1174#issuecomment-726744090) hahaha :D

@ikramimamoglu Merak ettim, kaça satıyordu acaba. 😒

**Comment by ghost** [comment]
> > > gerçekten şaka gibi adam yazdığı mesajı sildi... bunlar yüzünden insanın yardım edesi gelmiyo, bazıları da sayende aldığı kodları başkalarına parayla satıyolar gerçekten çok üzücü
> > 
> > 
> > Gecen gun dedigin seyi yapan birisiyle karsilastim. [Bu kodu satiyordu](https://github.com/haxball/haxball-issues/issues/1174#issuecomment-726744090) hahaha :D
> 
> @ikramimamoglu Merak ettim, kaça satıyordu acaba. 😒

Hic sormak istemedim acikcasi. Ama cok guzel yalan soyluyordu "Ben yaptim, benim kodum." diyerek ahahahah. Biraz daha oyaladiktan 5dk. sonra "Bana bunu **** verdi" dedi. 😄  @thenorthstar

**Comment by tanercanbilgin** [comment]
evet evet botları kendi yaptıklarını iddia ediyolar, mesela ne kadar detaylıysa fiyatı artıyomuş. renkli yazı 5, 4 defans 65 :DD
botlar konusunda insanlar şu son 2-3 senedir paylaşıma kapalılar, kodlarını incelediğimde aslında hepsinin aynı kodları kullandığını gördüm. githubta sayenizde öğrendiğim şeylerle bayağı geliştirdim kendimi, insanlara yardım falan ediyorum ama ben yardım istediğimde fiyatlarla karşılaşıyorum, tekrardan teşekkür ederim ikinize de

**Comment by thenorthstar** [comment]
Bu bütün yazılım dünyasında böyle zaten, coder'ım yazılımcıyım diye geçinenlerin %90'u copy-paste çalışıyor ve benzer kodlar kullanıyor zaten. 😒
