### ISSUE TITLE
Ideas to improve Haxball based on HaxArena

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#136]
Hi Basro, i'll point some things that HaxArena has that would be good to Haxball have

It would be nice if the pause slowly faded away when someone unpaused the match, like it happens here, it gives you the sensations that you are slowly entering immersion again: https://gyazo.com/450d6060625cf1677e4687def046286b
  PS: keep the bar that indicates the time left until the unpause

When the game is being played, the menu could look like this, so that if the admin is playing in the match, he can look at others people ping without losing track of the game:
https://gyazo.com/377b1215dfed70e8d9df9422a6c64bf2

I dont think you are interested in this feature, but many people ask for bots, do you plan to implement them anytime soon? What is your opinion on the subject?

Another thing that looks like you wont pay much attetion and a lot of players ask is the account system, do you have anything in mind? You will implement it in the future, or you already decided that you dont want it?

Thx. in advance
Leo ß

**Comment by basro** [comment]
I appreciate the feedback but this is not the way to use an issue tracker. It's not a forum.
Issues need to focus on a single thing so I'm closing this issue. Feel free to create issues for each individual point (but please do search before you create one to avoid duplicates).
