### ISSUE TITLE
website and database sync things..

### ISSUE THREAD

**Issue by tanercanbilgin** [haxball/haxball-issues#1368]
for the new game modes i was thinking, i need some help. i want to have a working database on my bot, every time i open a new room it can sync all the stats. i have some codes for it but i dont know how to sync with a website, do you have any suggestions or examples for it. thanks

**Comment by ghost** [comment]
I've created an API (written in Node.js) a few months ago.  If you want it I'll send it from Discord. You know the reason why I don't want to post it here.

**Comment by ghost** [comment]
> I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.

It was using MySQL DBMS but I'll switch it to MongoDB soon. I was too lazy to set up the MongoDB environment lol.

**Comment by metalingus666** [comment]
@ikramimamoglu Can u share your discord nickname? I want to talk about something.

**Comment by tanercanbilgin** [comment]
> I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.

that would be so nice, you work so clear thats why i love your codes. `discord: bT-iwnl#0001`

**Comment by tanercanbilgin** [comment]
> > I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.
> 
> It was using MySQL DBMS but I'll switch it to MongoDB soon. I was too lazy to set up the MongoDB environment lol.

that would be so easy for websites, good choice

**Comment by ghost** [comment]
> > I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.
> 
> that would be so nice, you work so clear thats why i love your codes. `discord: bT-iwnl#0001`

FR sent.

**Comment by ghost** [comment]
> @ikramimamoglu Can u share your discord nickname? I want to talk about something.

About what?

**Comment by mobitr** [comment]
> I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.

Merhaba @ikramimamoglu 
Yardımlarınız için herkes adına çok teşekkür ediyorum.
Sizin gibi paylaşmayı bilenlerin artması dileğiyle, emeğinize sağlık. 
Bahsettiğiniz yapıyı acaba benimle de paylaşabilir misiniz?
Dc adresim mobi#9577

**Comment by ghost** [comment]
> > I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.
> 
> Merhaba @ikramimamoglu
> Yardımlarınız için herkes adına çok teşekkür ediyorum.
> Sizin gibi paylaşmayı bilenlerin artması dileğiyle, emeğinize sağlık.
> Bahsettiğiniz yapıyı acaba benimle de paylaşabilir misiniz?
> Dc adresim mobi#9577

Rica ederim, su anda yapiyi hosuma gitmedigi icin guncelliyorum. Guncelleme bittigi zaman acik kaynak olarak paylasma ihtimalim var. Paylasirsam eger GitHub sayfamdan alabilirsiniz.

**Comment by mobitr** [comment]
> > > I've created an API (written in Node.js) a few months ago. If you want it I'll send it from Discord. You know the reason why I don't want to post it here.
> > 
> > 
> > Merhaba @ikramimamoglu
> > Yardımlarınız için herkes adına çok teşekkür ediyorum.
> > Sizin gibi paylaşmayı bilenlerin artması dileğiyle, emeğinize sağlık.
> > Bahsettiğiniz yapıyı acaba benimle de paylaşabilir misiniz?
> > Dc adresim mobi#9577
> 
> Rica ederim, su anda yapiyi hosuma gitmedigi icin guncelliyorum. Guncelleme bittigi zaman acik kaynak olarak paylasma ihtimalim var. Paylasirsam eger GitHub sayfamdan alabilirsiniz.

Tekrardan Merhaba @ikramimamoglu 
Merakla takipte olacağım. 
Umarım gitmek istediğiniz noktaya ulaşırsınız. 
Ayrıca DC üzerinden de iletişim kurarsanız memnun olurum.

**Comment by mobitr** [comment]
İyi akşamlar @ikramimamoglu .
Umarım iyisinizdir ve her şey yolundadır.
Yeni sürümde galiba mongoDb teknolojisi kullanılıyor?

**Comment by ghost** [comment]
> It was using MySQL DBMS but I'll switch it to MongoDB soon. 

Ustte bunu demisim zaten, galiba demenize gerek yok. Yani, MongoDB kullaniliyor.

**Comment by mobitr** [comment]
🤣🤣👍👍

**Comment by mobitr** [comment]
Ne zaman yayınlamayı düşünüyorsunuz?

**Comment by rocosttaa** [comment]
can you pass me this api? @ikramimamoglu
