### ISSUE TITLE
Should this error have been catched by headless-min.js?

### ISSUE THREAD

**Issue by nuji3** [haxball/haxball-issues#1369]
Hi guys,
I recently experienced a (from my perspective) strange error while testing a script for headless host, which unfortunately is not easy to reproduce.

I am using puppeteer, having set dumpio to true, to see stdout and stderr. Therefore errors are displayed when they occur, including filename and row.

But this time there was no reference to my script at all but only to the headless-min.js.

Now I am a bit confused if the error is caused by me (what it probably is) or by headless-min.js itself. 

Maybe you can help me. The error message is as follows:
```
[0613/214313.163529:INFO:CONSOLE(13)] "Uncaught (in promise) TypeError: Cannot read property 'length' of undefined", source: https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js (13)
TypeError: Cannot read property 'length' of undefined
    at Function.H.pb (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:13:263)
    at U.P (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:103:411)
    at Function.g.ke (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:42:132)
    at Fa.bf (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:48:99)
    at Fa.Cd (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:48:20)
    at Fa.ec (https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:46:191)
    at https://html5.haxball.com/hiF05fAx/__cache_static__/g/headless-min.js:55:488
```

It may well be that the value is undefined on my part (a mistake that I would like to fix then) - however i have no idea
what is calculated internally in headless-min.js and, to be honest, I do not want to reverse engineer it. 
Is this an error that should have been catched by headless-min.js?

Thanks in advance,

nuji3

**Comment by saviola777** [comment]
Well, it may be a case of you violating the "contract" of the Headless API by passing undefined to a function expecting a string/array. Not sure if these are usually caught, maybe Basro forgot this for one of the newer functions (maybe `reorderPlayers`, it's the only function expecting an `Array` as far as I can see).

**Comment by nuji3** [comment]
> Well, it may be a case of you violating the "contract" of the Headless API by passing undefined to a function expecting a string/array. Not sure if these are usually caught, maybe Basro forgot this for one of the newer functions (maybe `reorderPlayers`, it's the only function expecting an `Array` as far as I can see).

Thank you for your answer saviola.

The function is defined as:
```
H.pb = function (a, b) {
    return a.length <= b ? a : G.substr(a, 0, b)
};
```

Therefore it is for limiting a string to a specific length. I have the feeling hat you are right, that there is a try/catch missing. It seems to me that if it was there the I would have got an error message as usual.

The problem right now is just to find that error in my code without getting the filename and row. As i said earlier the error not easy to reproduce and I am having 20+ class files to find the error in :/


Kind regards,

nuji3

**Comment by basro** [comment]
You are sending an announcement with undefined text.
Put null-checks on all your sendAnnouncement calls and you should be able to find the problem.

Sorry for the shoddy error messages, I agree it's not good :P

**Comment by nuji3** [comment]
Many thanks for your response, basro.
Fortunately I wrapped sendAnnouncement so it should be pretty easy to do.

> Sorry for the shoddy error messages, I agree it's not good :P

I would never complain about anything - this game changed my life. Thanks a lot for this :)
