### ISSUE TITLE
Why don't webkit browsers support haxball?

### ISSUE THREAD

**Issue by nick19123** [haxball/haxball-issues#1371]
Load safari or any other WebKit browser and you'll notice that that haxball can't run on it. Since Safari supports WebRTC shouldn't this be a non-issue in 2021? What is preventing haxball from being played on web browsers better suited for people using MacOS?

**Comment by basro** [comment]
You are right, it seems safari does have support for WebRTC datachannels now. I'm not sure why the capabilities tests is still failing for it, it might be a bug in it.

I don't own any apple devices so testing is cumbersome, but I'll see if I can fix the capability test anyway.

**Comment by basro** [comment]
Update on this issue: The capability test was indeed buggy, I have already fixed this (not released yet).
Unfortunately there's some issues with webrtc failing to establish connections, I'll investigate more later.

**Comment by nick19123** [comment]
Godspeed basro.

**Comment by csvergaraa** [comment]
Looking forward to it.

**Comment by nick19123** [comment]
Wondering if there's been any progress made on this.

**Comment by basro** [comment]
Not yet, sorry. I haven't been able to borrow a macbook. It will happen eventually.

**Comment by nick19123** [comment]
poke

**Comment by basro** [comment]
Sorry, I haven't been able to give this issue enough time yet. I still plan to do so in the future.

**Comment by nick19123** [comment]
poking for an update if there is one :)

**Comment by basro** [comment]
Sorry, not yet.

**Comment by mirko991** [comment]
@basro Sorry for resurrecting this old post.

Has this issue been resolved? I'm thinking of buying a Mac and maybe playing games through Safari. Thank you!

**Comment by basro** [comment]
No, it has not been resolved yet. I did get to borrow a mac at some point but failed to do debug it in the few hours that I had it. You've now reminded me of this issue, I guess I'll try again soon.

Keep in mind that this only affects safari, so even if you buy a mac you'd be able to play by installing Firefox or Chrome.

**Comment by basro** [comment]
A kind friend lent me his mac book for a week and I've now been able to properly debug this issue. HaxBall now works on safari.

Performance was not very good, it worked fine only using the restricted view mode, but to be fair chrome also didn't fare too well. The mac I borrowed was a 2015 model so hopefully newer ones run better.

There was also an issue with sounds. Since safari has no support for the .ogg format which I was using, I've changed most sounds to wav. The crowd sound would be too large so for now that specific sound will not work in safari.

**Comment by csvergaraa** [comment]
> A kind friend lent me his mac book for a week and I've now been able to properly debug this issue. HaxBall now works on safari.
> 
> Performance was not very good, it worked fine only using the restricted view mode, but to be fair chrome also didn't fare too well. The mac I borrowed was a 2015 model so hopefully newer ones run better.
> 
> There was also an issue with sounds. Since safari has no support for the .ogg format which I was using, I've changed most sounds to wav. The crowd sound would be too large so for now that specific sound will not work in safari.

Incredible news! 🎉 Thank you for this update!
