### ISSUE TITLE
Problems with !me

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1376]
Helo! My room was working fine, but now it's not counting the goals and assists in the !me command anymore. Can someone help me?

**Comment by wohSi** [comment]
> Helo! My room was working fine, but now it's not counting the goals and assists in the !me command anymore. Can someone help me?

wowo#1665 <- discord

**Comment by rocosttaa** [comment]
I added you to discord!


> > Olá! Minha sala estava funcionando bem, mas agora não está contando mais os gols e assistências no comando! Me. Alguém pode me ajudar?
> 
> wowo # 1665 <- discórdia
