### ISSUE TITLE
Dedicated "application" for HaxBall

### ISSUE THREAD

**Issue by haxballer** [haxball/haxball-issues#138]
Hey @basro, I recently read the message that you are not planning on a downloadable version, which made me a little sad, although I thought I would post an idea, I will add in advance that I'm not a programmer and I don't know if it is difficult to do. To the core, I mean a special "mini browser" that would launch only HaxBall and which would be available for download for everyone on the site. On the flash version of Haxball there are many such applications if I can call it that. The best and most popular window how i know was created by Kuma, player from New Zealand, which is called HaxWindow. I'm sure you heard about it. I think that such a light and pleasant browser is something great for Haxball, all new browsers are terribly memory-hungry and have senseless features. What do you think about this idea and is it possible to implement it?

**Comment by basro** [comment]
The html5 version of haxball requires a modern browser to run, there's no lighter way to run it than in a browser.

Also HaxBall is a browser game, meant to be played in a browser. The site has ads which pay for the hosting costs. Standalone applications such as that bypass the ads and break whenever I make a change. I do not approve of the making or using of such apps.

**Comment by haxballer** [comment]
You're right, I forgot about the commercials, but please don't forget that if HaxBall break "mainstream" in the new version again, the chance is that the game will be able to make a profit in different ways, not just advertising. Anybody who said that in such an application would not be advertising? The point here is to maybe think of a browser that will only launch our favorite game. Maybe someday your approach in this area will change, we will see. Thanks for the answer.
