### ISSUE TITLE
too big circle

### ISSUE THREAD

**Issue by loveuhaxball** [haxball/haxball-issues#139]
this circle ; too big http://www.imgim.com/qwqwq.jpg

add small option or http://www.imgim.com/ececeecc.jpg yellow,red,grey,brown bla bla option

**Comment by r2308145** [comment]
I think its ok for you to better recognize/identify yourself from an opponent and regarding the colors idea I really dont like it.

**Comment by loveuhaxball** [comment]
http://www.imgim.com/ececeecc.jpg
this colorful circle for ourselves. dont see opponent

**Comment by loveuhaxball** [comment]
hey @basro

**Comment by basro** [comment]
I don't like this idea, I wont be implementing this.
