### ISSUE TITLE
player message

### ISSUE THREAD

**Issue by Enesbey635** [haxball/haxball-issues#1397]
I have a wazarr94 bot but I added a player font to my bot and the mute system didn't work. Can you help me?

**Comment by Obsesiff66** [comment]
> wazarr94 botum var ama botuma player fontu ekledim mute sistemi çalışmadı. Bana yardımcı olabilir misiniz?

wazarr94 level4 botunda mute sistemi vardır !mute süre #id    örnek olarak !mute 3 #3

**Comment by thenorthstar** [comment]
Duplicate of #1286. Close this one.

**Comment by Enesbey635** [comment]
> > wazarr94 botum var ama botuma player fontu ekledim mute sistemi çalışmadı. Bana yardımcı olabilir misiniz?
> 
> wazarr94 level4 botunda mute sistemi vardır !mute süre #id örnek olarak !mute 3 #3

içerisindeki sisteme normal oyuncu için yazı tipi vb. eklediğinde oyuncu muteleniyor olarak gösteriliyor ancak yazabiliyor.

**Comment by Obsesiff66** [comment]
> > > wazarr94 botum var ama botuma player fontu mute sistemi çalışmadı. Bana yardim edebilir misin?
> > 
> > 
> > wazarr94 level4 botunda mute sistemi vardır !mute süre #id örnek olarak !mute 3 #3
> 
> sistem sistemi normal oyuncu için yazı vb. eklenebilecek oyuncu muteleniyor olarak gösteriliyor ancak yazabiliyor.

mute sisteminin altına      ekle üstüne eklersen mutenin çalışmaz tabi

**Comment by Obsesiff66** [comment]
altına ekle

**Comment by Enesbey635** [comment]
> > > > wazarr94 botum var ama botuma player fontu mute sistemi çalışmadı. Bana yardim edebilir misin?
> > > 
> > > 
> > > wazarr94 level4 botunda mute sistemi vardır !mute süre #id örnek olarak !mute 3 #3
> > 
> > 
> > sistem sistemi normal oyuncu için yazı vb. eklenebilecek oyuncu muteleniyor olarak gösteriliyor ancak yazabiliyor.
> 
> mute sisteminin altına ekle üstüne eklersen mutenin çalışmaz tabi

deneyeceğim.

**Comment by Enesbey635** [comment]
sorunu çözdüm teşekkürler.
