### ISSUE TITLE
ball hold

### ISSUE THREAD

**Issue by Enesbey635** [haxball/haxball-issues#1398]
sniper botum var ve odamda çok fazla top bekleten oyuncular var. 12 saniye içerisinde topu karşıya atın aksi takdirde(Kick) gibi bir kodu olan varmı? Sniper botuma ekleyeceğim. Yardım edermisiniz?

**Comment by Obsesiff66** [comment]
githubda gezen sniper botlarını incelemeni öneririm dostum konu açmadan önce

**Comment by Enesbey635** [comment]
> githubda gezen sniper botlarını incelemeni öneririm dostum konu açmadan önce

elinde iyi bir top bekletme engel sistemi olan varsa atabilirmi? Botlu odamda çok top bekleten vs. oluyor buna karşılık bir koruma gerçekten çok gerekli.

**Comment by Enesbey635** [comment]
@Obsesiff66 bu arada tekrardan açıklamak istiyorum: Amacım insanların kodlarını çalarak biryerlere gelmek değil, zaten böyle bir hedefim asla olmadı. Satmaya çalıştığım kodlarında internette paylaşıldığını bilsem böyle birşey yapmazdım. Yapmıyorum zaten artık, özeldende engellemişsin beni git kendi çöplüğünde takıl diye fakat amacım sizlerle düşman olmak değil kesinlikle engeli kaldırıp kaldırmamak senin kararın istersen kaldırabilirsin fakat benim amacım başkalarının kodlarıyla bir yerlere gelmek değil hakkı geçen varsa hakkınızı helal edin.

**Comment by Enesbey635** [comment]
> > githubda gezen sniper botlarını incelemeni öneririm dostum konu açmadan önce
> 
> elinde iyi bir top bekletme engel sistemi olan varsa atabilirmi? Botlu odamda çok top bekleten vs. oluyor buna karşılık bir koruma gerçekten çok gerekli.

elinde olan varsa atabilirmi acaba??
