### ISSUE TITLE
CAPS PROBLEM

### ISSUE THREAD

**Issue by Obsesiff66** [haxball/haxball-issues#1399]
Hello Friends, I Have Rooms With Bots And There Are Many Toxic People And They Write In Capital Letters. No matter how many bots I searched, I could not find a caps blocker.

**Comment by Obsesiff66** [comment]
For example, user will write "HELLO" but say "hello"

**Comment by thenorthstar** [comment]
> For example, user will write "HELLO" but say "hello"

@Obsesiff66 You can use this code. But this code also prevents you to type players' name by tagging them (and doesn't warn you when you used Turkish or Cyrillic characters. It has to be adjusted specifically by increasing the depth of if's).

```
var room = HBInit({roomName:"CAPS CONTROL",playerName: "",noPlayer:true,public:true,maxPlayers:12});

room.onPlayerChat = function(player,msg){
    if(player.admin == true){
	room.sendAnnouncement(player.name + ": " + msg,null,0x97FFFF,"bold",1);
	return false;
    }
    else{
	room.sendAnnouncement(player.name + ": " + msg.toLowerCase(),null,0xFFFFFF,"normal",1);
	for(var m=0; m<msg.length; m++){
	    if(msg[m].charCodeAt() >= 65 && msg[m].charCodeAt() <= 90){
		room.sendAnnouncement("Your message cannot contain upper case characters!",player.id,0xFFFF00,"bold",2);
		break; //This break is stand to stop the loop in the first encounter with an upper case character.
	    }
	}
	return false;
    }
}
```

**Comment by Obsesiff66** [comment]
> > Örneğin, kullanıcı "HELLO" yazacak ancak "merhaba" diyecektir.
> 
> @ Obsesiff66 Bu kodu kullanabilirsiniz. Ancak bu kod aynı zamanda oyuncuların isimlerini etiketleyerek yazmanızı da engeller (ve Türkçe veya Kiril karakterlerini kullandığınızda sizi uyarmaz. if'lerin derinliğini artırarak özel olarak ayarlanması gerekir).
> 
> ```
> var room = HBInit({roomName:"CAPS CONTROL",playerName: "",noPlayer:true,public:true,maxPlayers:12});
> 
> room.onPlayerChat = function(player,msg){
>     if(player.admin == true){
> 	room.sendAnnouncement(player.name + ": " + msg,null,0x97FFFF,"bold",1);
> 	return false;
>     }
>     else{
> 	room.sendAnnouncement(player.name + ": " + msg.toLowerCase(),null,0xFFFFFF,"normal",1);
> 	for(var m=0; m<msg.length; m++){
> 	    if(msg[m].charCodeAt() >= 65 && msg[m].charCodeAt() <= 90){
> 		room.sendAnnouncement("Your message cannot contain upper case characters!",player.id,0xFFFF00,"bold",2);
> 		break; //This break is stand to stop the loop in the first encounter with an upper case character.
> 	    }
> 	}
> 	return false;
>     }
> }
> ```

çok sağol bi soru olucaktı bu spam sorunu ile ilgili bir şet atmıssın #1290 ben onu anlayamadım anlatabilme şansın varmı birde burda Mesela Merhaba Kanka Yazınca normal Kalıcak Sadece MERHABA KANKALARI filan küçültecek tam dediğinizi anlayamadım beni aydınlatırmısınız

**Comment by thenorthstar** [comment]
> > > Örneğin, kullanıcı "HELLO" yazacak ancak "merhaba" diyecektir.
> > 
> > 
> > @ Obsesiff66 Bu kodu kullanabilirsiniz. Ancak bu kod aynı zamanda oyuncuların isimlerini etiketleyerek yazmanızı da engeller (ve Türkçe veya Kiril karakterlerini kullandığınızda sizi uyarmaz. if'lerin derinliğini artırarak özel olarak ayarlanması gerekir).
> > ```
> > var room = HBInit({roomName:"CAPS CONTROL",playerName: "",noPlayer:true,public:true,maxPlayers:12});
> > 
> > room.onPlayerChat = function(player,msg){
> >     if(player.admin == true){
> > 	room.sendAnnouncement(player.name + ": " + msg,null,0x97FFFF,"bold",1);
> > 	return false;
> >     }
> >     else{
> > 	room.sendAnnouncement(player.name + ": " + msg.toLowerCase(),null,0xFFFFFF,"normal",1);
> > 	for(var m=0; m<msg.length; m++){
> > 	    if(msg[m].charCodeAt() >= 65 && msg[m].charCodeAt() <= 90){
> > 		room.sendAnnouncement("Your message cannot contain upper case characters!",player.id,0xFFFF00,"bold",2);
> > 		break; //This break is stand to stop the loop in the first encounter with an upper case character.
> > 	    }
> > 	}
> > 	return false;
> >     }
> > }
> > ```
> 
> çok sağol bi soru olucaktı bu spam sorunu ile ilgili bir şet atmıssın #1290 ben onu anlayamadım anlatabilme şansın varmı birde burda Mesela Merhaba Kanka Yazınca normal Kalıcak Sadece MERHABA KANKALARI filan küçültecek tam dediğinizi anlayamadım beni aydınlatırmısınız

#1290 Bununla alâkası olan konu değil. Spam filtresi. 0.6 saniye içerisinde arka arkaya 3 kez yazı yazarsan ban yersin.

İkinci cümlene istinaden şunu söyleyeceğim. Benim yaptığım şey, mesajı komple küçültmek için. Belirli harfleri küçültmüyor yani, toptan küçültüyor. Onun için koşulları daha derinleştirerek yapman lâzım. Meselâ, javascript'in **split** özelliğini kullanarak ayırdığın parçaların ilk indisli elemanları dışında geri kalan tüm elemanları seçip küçültebilirsin.

**Comment by Obsesiff66** [comment]
> > > > Örneğin, "merhaba" yazacak ama "merhaba" diyecektir.
> > > 
> > > 
> > > @ Obsesiff66 Bu kodu kullanabilirsiniz. Ancak bu kod yazma da tanımlamalarını etiketleyebilmeniz.
> > > ```
> > > var room = HBInit({roomName:"CAPS CONTROL",playerName: "",noPlayer:true,public:true,maxPlayers:12});
> > > 
> > > room.onPlayerChat = function(player,msg){
> > >     if(player.admin == true){
> > > 	room.sendAnnouncement(player.name + ": " + msg,null,0x97FFFF,"bold",1);
> > > 	return false;
> > >     }
> > >     else{
> > > 	room.sendAnnouncement(player.name + ": " + msg.toLowerCase(),null,0xFFFFFF,"normal",1);
> > > 	for(var m=0; m<msg.length; m++){
> > > 	    if(msg[m].charCodeAt() >= 65 && msg[m].charCodeAt() <= 90){
> > > 		room.sendAnnouncement("Your message cannot contain upper case characters!",player.id,0xFFFF00,"bold",2);
> > > 		break; //This break is stand to stop the loop in the first encounter with an upper case character.
> > > 	    }
> > > 	}
> > > 	return false;
> > >     }
> > > }
> > > ```
> > 
> > 
> > çok sağol sorunu ile ilgili bir şecaktı bu spam sorunu ile ilgili bir şecaktı #1290 ben onu gördım anlatabilmet atı varmı burada mesela Kanka Yazınca normal bi sorucaktı MERHABA KANKALARI filan küçültünüzü tam olarak göstermedim beni aydınlatırmısınız
> 
> #1290 belirli. alâkası olan konu değil Spam dansı. 0.6 saniye içinde yazar içinde arkaya 3 kez yazısan ban yersin.
> 
> İkinci cümlene istinadan söyleyeceğim. Benim için şey, mesajı komple küçültmek. Sayfada yazılanlar küçültülüyor yani, toptan küçültülüyor. Onun için daha fazla derinleştirerek yapman lâzım. Meselâ,javascript'in **split** kullanımıyla ayırmadığın ilk uygulamada geri kalan tüm elemanları seçip küçültebilirsin.



buraya yazdığım için pardon ama oraya da yazmıştım rahatsız ettiğim için özür dilerim
