### ISSUE TITLE
Mute chat in choosing teams

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1403]
Guys, when choosing the time I want to change the chat and only the person who prefers the time can speak. Does anyone know how I do this?

Thanks!

**Comment by Enesbey635** [comment]
> Guys, when choosing the time I want to change the chat and only the person who prefers the time can speak. Does anyone know how I do this?
> 
> Thanks!

I don't understand what you said contact me

Discord: FearLesS#6514

**Comment by guguxh** [comment]
I think u can do a mute all when is choosing time and after this u disable the mute, it's very simple way.
