### ISSUE TITLE
Link Block

### ISSUE THREAD

**Issue by Enesbey635** [haxball/haxball-issues#1405]
Hello friends, does anyone have the link block code?

**Comment by gabrielbrunop** [comment]
You can achieve this using regex.

```js
const linkRegex = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
```

Then just block them:
```js
room.onPlayerChat = (player, message) => {
    if (linkRegex.test(message)) return false;
};
```

**Comment by Enesbey635** [comment]
> You can achieve this using regex.
> 
> ```js
> const linkRegex = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
> ```
> 
> Then just block them:
> 
> ```js
> room.onPlayerChat = (player, message) => {
>     if (linkRegex.test(message)) return false;
> };
> ```

thanks i will try.

**Comment by Enesbey635** [comment]
> You can achieve this using regex.
> 
> ```js
> const linkRegex = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
> ```
> 
> Then just block them:
> 
> ```js
> room.onPlayerChat = (player, message) => {
>     if (linkRegex.test(message)) return false;
> };
> ```

thank you it worked.

Can you reach me on Discord?

Discord: FearLesS#6514

**Comment by gabrielbrunop** [comment]
> > You can achieve this using regex.
> > 
> > ```js
> > const linkRegex = /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/;
> > ```
> > 
> > Then just block them:
> > 
> > ```js
> > room.onPlayerChat = (player, message) => {
> >     if (linkRegex.test(message)) return false;
> > };
> > ```
> 
> thank you it worked.
> 
> Can you reach me on Discord?
> 
> Discord: FearLesS#6514

Message me: Gab#9912

**Comment by rocosttaa** [comment]
Why does this block only some types of sites and not all?
