### ISSUE TITLE
problem with setplayeravatar

### ISSUE THREAD

**Issue by Amstrong009** [haxball/haxball-issues#1412]
I would like to create a container to differentiate different reactions for different players, but when I run this prototype, the reaction with the "ball" always prevails over everything and if I try to remove it, it does not give the reaction requested in Vip.includes

room.onTeamGoal = function (team) {
      let players = room.getPlayerList();
      var Vip = ["x"];

      for (let i = 0; i < players.length; i++) {
        if (players[i].team == team) room.setPlayerAvatar(players[i].id, "⚽️");
      }   
        for (let i = 0; i < players.length; i++) {
      if (Vip.includes(playerAuth[players[i].id])==true && players[i].team == team ) room.setPlayerAvatar(players[i].id, "a");
    }
      setTimeout(() => {
        for (let i = 0; i < players.length; i++) {
           room.setPlayerAvatar(players[i].id, null);
        }
    }, secondsToResetAvatar * 1000);

**Comment by gabrielbrunop** [comment]
`setPlayerAvatar` is a little bit buggy.

Try this:

```js
for (let i = 0; i < players.length; i++) {
    if (players[i].team == team) {
        if (Vip.includes(playerAuth[players[i].id]) room.setPlayerAvatar(players[i].id, "a");
        else room.setPlayerAvatar(players[i].id, "⚽️");
    }
}
```

**Comment by Amstrong009** [comment]
hello sorry I'm late but I was working, it gives me an error in `room`.setPlayerAvatar(players[i].id, "a");
@gabrielbrop

**Comment by Amstrong009** [comment]
sorry bro but I was working, thank you very much it worked in the end I even found the real problem and it was my carelessness but I still appreciate the easier way to write the code you gave me
