### ISSUE TITLE
I also want to add the time a person is in the room

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1416]
Does anyone know how I do this by putting !me in command?

**Comment by Raamyy** [comment]
You can have an object that stores for every `player.id` the moment he joined the room. and when he uses the `!me` command you can subtract the current time from the joining time in the object.

**Comment by thenorthstar** [comment]
> Does anyone know how I do this by putting !me in command?

@rocosttaa Maybe this script would help you: https://github.com/ikramimamoglu/futsal-bot-script/blob/master/index.js

**Comment by rocosttaa** [comment]
Couldn't.. Could you please help me with this? @Raamyy @thenorthstar

**Comment by Raamyy** [comment]
@rocosttaa How do you want me to help you ?

**Comment by rocosttaa** [comment]
I tried with the method below but I couldn't.
``var startDate = new Date();
// Do your operations
var endDate   = new Date();
var seconds = (endDate.getTime() - startDate.getTime()) / 1000;``

Can you help me? @Raamyy

**Comment by Raamyy** [comment]
@rocosttaa contact me on discord `Raamyy#1111`

**Comment by rocosttaa** [comment]
I forwarded you request @Raamyy
