### ISSUE TITLE
pause the game

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1425]
Can anyone tell me how to get the team captains only to type !p and pause the game 1x?

**Comment by Enesbey635** [comment]
if (message == "!p") {
   room.sendAnnouncement("Game paused by " + player.name);
   room.pauseGame(true);
}

**Comment by Enesbey635** [comment]
I hope it works for you.

**Comment by guguxh** [comment]
if u want to pause only 1 time in a game I think u need other script but is like this ^

**Comment by rocosttaa** [comment]
> How to make the game pause after that? I did this but it's not working:

 if` (message == "!p") {

		if (player.id == teamR[0].id || player.id == teamB[0].id) {
			room.sendAnnouncement(`${player.name} pausou o jogo por 10 segundos.`, null, 0xDE5533, "bold", 1);
			room.pauseGame(true);
		}
		setTimeout(() => {
			room.resumeGame(true);
		}, 2000);
}
