### ISSUE TITLE
New message look

### ISSUE THREAD

**Issue by Gabri04** [haxball/haxball-issues#1433]
Hello, How can I set a new different message look like this ones? Of course it must be valid for all type of messages:

𝟏✦║Panda:

┋lvl 50┋ Panda:

I would really appreciate an answer, thanks.

**Comment by JollyRock** [comment]
you need to print a sendannouncements including player.name $ {message} etc etc, but if you want to do a layered system it gets more difficult, and I don't think anyone will come to your rescue

**Comment by Gabri04** [comment]
> you need to print a sendannouncements including player.name $ {message} etc etc, but if you want to do a layered system it gets more difficult, and I don't think anyone will come to your rescue

It's ok if nobody can't help me with the second one, so for the first I just have to call the function which describes that for every message u send an Announcement with that? And how to remove the classic message? With return false (?)

**Comment by Raamyy** [comment]
Can you elaborate more? 

> 𝟏✦║Panda:
> 
> ┋lvl 50┋ Panda:

How are these considered `different message looks` for you ?

**Comment by Gabri04** [comment]
> Can you elaborate more?
> 
> > 𝟏✦║Panda:
> > ┋lvl 50┋ Panda:
> 
> How are these considered `different message looks` for you ?

Yes (?)

**Comment by JollyRock** [comment]
yes you can remove the return message with `return false;`

you could do it just like that

```
} else if message.match(/^\S+/)){
    messageSplit = message.split(/ +/);
    room.sendAnnouncement(
      `[Player] ${message.replace("","")}`,
      player.id,
      0xcccccc,
      "bold",
      1
    );
```

**Comment by Gabri04** [comment]
> yes you can remove the return message with `return false;`
> 
> you could do it just like that
> 
> ```
> } else if message.match(/^\S+/)){
>     messageSplit = message.split(/ +/);
>     room.sendAnnouncement(
>       `[Player] ${message.replace("","")}`,
>       player.id,
>       0xcccccc,
>       "bold",
>       1
>     );
> ```

what do the first and the second lines mean?

**Comment by JollyRock** [comment]
if you write any message that message will be printed as written in the sendannouncements

**Comment by JollyRock** [comment]
you can change the input in the middle of /^ type `/^!s test`

**Comment by Gabri04** [comment]
> you can change the input in the middle of /^ type `/^!s test`

Can it be done without any input? Only by typing normally?

**Comment by JollyRock** [comment]
as I did you on writing a message it will be replaced as you wish

**Comment by Gabri04** [comment]
> as I did you on writing a message it will be replaced as you wish

Yes sorry for bothering but I'm not that good at that. If I don't want any input should I type like this?

function (message, player) {
		if (message.match(/^\+/)){
			messageSplit = message.split(/ +/);
			room.sendAnnouncement(
			  `[Player] ${message.replace("","")}`,
			  player.id,
			  0xcccccc,
			  "bold",
			  1
			);
	}

**Comment by JollyRock** [comment]
just try it by writing any message and you will see the result dude.
but you better print as I sent you the code in `onplayerchat`

**Comment by Gabri04** [comment]
> just try it by writing any message and you will see the result dude.
> but you better print as I sent you the code in `onplayerchat`

Man i tried, thanks so much! Where should I put the return false? A the end of the function before closing the brackets?

**Comment by genals** [comment]
> > just try it by writing any message and you will see the result dude.
> > but you better print as I sent you the code in `onplayerchat`
> 
> Man i tried, thanks so much! Where should I put the return false? A the end of the function before closing the brackets?

See [`onPlayerChat`](https://github.com/haxball/haxball-issues/wiki/Headless-Host#onplayerchat).

**Comment by Gabri04** [comment]
> > > just try it by writing any message and you will see the result dude.
> > > but you better print as I sent you the code in `onplayerchat`
> > 
> > 
> > Man i tried, thanks so much! Where should I put the return false? A the end of the function before closing the brackets?
> 
> See [`onPlayerChat`](https://github.com/haxball/haxball-issues/wiki/Headless-Host#onplayerchat).

Thanks so much, you're the best!

**Comment by Gabri04** [comment]
> > > just try it by writing any message and you will see the result dude.
> > > but you better print as I sent you the code in `onplayerchat`
> > 
> > 
> > Man i tried, thanks so much! Where should I put the return false? A the end of the function before closing the brackets?
> 
> See [`onPlayerChat`](https://github.com/haxball/haxball-issues/wiki/Headless-Host#onplayerchat).

Man I tried but still the "original" message appears. How can I solve? This is the situation:

![Screenshot (18)](https://user-images.githubusercontent.com/88116151/129572552-aae5b1be-bf0d-4f4f-8618-0b19c5d18d00.png)

I want to remove the lower message, which is actually the original one.

**Comment by genals** [comment]
I don't get your point. Try this:

```
var room = HBInit({
	public: false,
});

room.onPlayerChat = function(player, message) {
	room.sendAnnouncement(player.name+': '+message);
	return false;
}
```

**Comment by Gabri04** [comment]
> I don't get your point. Try this:
> 
> ```
> var room = HBInit({
> 	public: false,
> });
> 
> room.onPlayerChat = function(player, message) {
> 	room.sendAnnouncement(player.name+': '+message);
> 	return false;
> }
> ```

That's exactly what I wanted. Thanks so much, mate. Have a good day!
