### ISSUE TITLE
Get Player's auth when he joins

### ISSUE THREAD

**Issue by Gabri04** [haxball/haxball-issues#1437]
Hello guys, is there a way to get the Auth of a player's when it joins? Maybe in the console log like this example: 

`player.name: auth`

Any format is ok, I just wanna know how to see and get the auth.
I hope you can help me!

**Comment by guguxh** [comment]
You can use the Haxball-extended-room, and in the onPlayerJoin put:
`console.log(player.auth)`

**Comment by Gabri04** [comment]
> You can use the Haxball-extended-room, and in the onPlayerJoin put:
> `console.log(player.auth)`

Is there a way to do it with the headless?

**Comment by Obsesiff66** [comment]
> > Haxball-genişletilmiş odasını kullanabilir ve onPlayerJoin'de şunları koyabilirsiniz:
> > `console.log(player.auth)`
> 
> Başsız yapmanın bir yolu var mı?

başsız derken
?

**Comment by Gabri04** [comment]
> > > Haxball-genişletilmiş odasını kullanabilir ve onPlayerJoin'de şunları koyabilirsiniz:
> > > `console.log(player.auth)`
> > 
> > 
> > Başsız yapmanın bir yolu var mı?
> 
> başsız derken
> ?

English bro

**Comment by gabrielbrunop** [comment]
It's just `player.auth`.

```js
room.onPlayerJoin = function(player) {
    console.log(player.name, player.auth);
}
```

**Comment by JollyRock** [comment]
```room.getPlayerList().filter((p) => p.admin).forEach((p) => room.sendAnnouncement(` Auth of ${player.name}: ${getAuth (player)} `, p.id, 0xcccccc," bold ", 2));```
this might help you. who is admin receives the auth of who has just entered

**Comment by Gabri04** [comment]
> It's just `player.auth`.
> 
> ```js
> room.onPlayerJoin = function(player) {
>     console.log(player.name, player.auth);
> }
> ```

Thanks man!

**Comment by Gabri04** [comment]
> `` room.getPlayerList().filter((p) => p.admin).forEach((p) => room.sendAnnouncement(` Auth of ${player.name}: ${getAuth (player)} `, p.id, 0xcccccc," bold ", 2)); ``
> this might help you. who is admin receives the auth of who has just entered

Shall I put this on the `onPlayerJoin` funtion? Because I tried and don't see anything

**Comment by Gabri04** [comment]
> It's just `player.auth`.
> 
> ```js
> room.onPlayerJoin = function(player) {
>     console.log(player.name, player.auth);
> }
> ```

By the way, I think I'm okay with this solution, so I'm going to close the issue. Thanks!
