### ISSUE TITLE
room.sendAnnouncement problemi

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1456]
**merhabalar ben bu kodu uyguladığımda** 

if (player.name == "test"){
        superadminMessage = message;
        var superadminChatColor = 0x000000;
        room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
        return false
    }

**test isimli kullanıcı mesaj gönderirken renkli ve başında tag olarak gidiyor fakat ben bunu komut ile yapmak istersem olmuyor**

if (message == "!renk"){
        superadminMessage = message;
        var superadminChatColor = 0x000000;
        room.sendAnnouncement ("[VIP] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
        return false
    }

**sadece !renk yazdığımda tek bir yazı  oluyor bunu nasıl o komutu yazdığımda sürekli olarak başında tag  ve renk olarak devam ettirebilirim çözümü var mıdır**

**Comment by EmirhanOlgn** [comment]
Merhaba bu şekilde komut kullanmak isterseniz kodu en üste veya en alta alın. Eğer işe yaramazsa geri dönün ve size hazır komut sistemi ile chat sistemi veriyim. İyi günler!

**Comment by metalingus666** [comment]
> Merhaba bu şekilde komut kullanmak isterseniz kodu en üste veya en alta alın. Eğer işe yaramazsa geri dönün ve size hazır komut sistemi ile chat sistemi veriyim. İyi günler!

that didn't work. can you send me what you said ? @EmirhanOlgn

**Comment by EmirhanOlgn** [comment]
```js
var commands = {
    "!ping": pingFun,
}
function pingFun(player) {
    room.sendAnnouncement(player.name + " pong!");
}
var admins = ["player.conn"]
room.onPlayerChat = function(player, message) {
    var spacePos = message.search(" ");
    var command = message.substr(0, spacePos !== -1 ? spacePos : message.length);
    if (commands.hasOwnProperty(command) == true) return commands[command](player, message);
    if (admins.includes(player.conn)) {
        room.sendAnnouncement("[🔰] " + player.name + ": " + message, null, 'bold', 0x00000, 2);
        return false;
}
}
```
Please reply if my article helps! Write me if you have a problem

**Comment by metalingus666** [comment]
thanks for sharing, but that's not what I'm talking about. after entering with the command, i want to constantly write in color. @EmirhanOlgn

**Comment by EmirhanOlgn** [comment]
Where are you from for easier communication?

**Comment by metalingus666** [comment]
i can speak english @EmirhanOlgn

**Comment by EmirhanOlgn** [comment]
I understood what you mean and found a solution. "!command": how many letters, "!" Equalize the 9th letter from the 8th "message" sentence, including, to a variable. Replace "superadminMessage" and try. Let me know if it works!
`Note: I took the 9th letter after the 'Nick:' because we don't want any extra spaces in it.`

**Comment by metalingus666** [comment]
I don't know much about it, can you write the code for me ?

**Comment by EmirhanOlgn** [comment]
I don't understand exactly what you want. Could you please give your discord address for easier communication? @EmirhanOlgn#5976

**Comment by ghost** [comment]
> I understood what you mean and found a solution. "!command": how many letters, "!" Equalize the 9th letter from the 8th "message" sentence, including, to a variable. Replace "superadminMessage" and try. Let me know if it works!
> `Note: I took the 9th letter after the 'Nick:' because we don't want any extra spaces in it.`

Ne dediğini tam olarak anlamadım Türkçe yazabilir misin yeni yeni başladım kod yazmaya ve bunu nasıl yapılacağını öğrenmem lazım @EmirhanOlgn

**Comment by EmirhanOlgn** [comment]
Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?

**Comment by emret2** [comment]
> Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?

Şimdi bak if (player.name == t

**Comment by ghost** [comment]
> Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?

Şimdi bak

if (player.name == "test"){
superadminMessage = message;
var superadminChatColor = 0x000000;
room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
return false
}

Ben bu kodu yaptığımda test isimli kullanıcı renkli mesaj gönderebiliyor fakat ben bunu bir komut girildiğinde yapılmasını istiyorum fakat olmuyor yani !renk yazıldığında o kullanıcı da renkli yazabilsin fakat bunu yapamadım @EmirhanOlgn

**Comment by ghost** [comment]
> Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?

@EmirhanOlgn

**Comment by EmirhanOlgn** [comment]
> > Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?
> 
> Şimdi bak
> 
> if (player.name == "test"){
> superadminMessage = message;
> var superadminChatColor = 0x000000;
> room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
> return false
> }
> 
> Ben bu kodu yaptığımda test isimli kullanıcı renkli mesaj gönderebiliyor fakat ben bunu bir komut girildiğinde yapılmasını istiyorum fakat olmuyor yani !renk yazıldığında o kullanıcı da renkli yazabilsin fakat bunu yapamadım @EmirhanOlgn

Yapmak istediğiniz !kirmizi mesaj komutunu kullandığımda chate kırmızı renkte "mesaj" mesajınımı göndersin?

**Comment by ghost** [comment]
> > > Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?
> > 
> > 
> > Şimdi bak
> > if (player.name == "test"){
> > superadminMessage = message;
> > var superadminChatColor = 0x000000;
> > room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
> > return false
> > }
> > Ben bu kodu yaptığımda test isimli kullanıcı renkli mesaj gönderebiliyor fakat ben bunu bir komut girildiğinde yapılmasını istiyorum fakat olmuyor yani !renk yazıldığında o kullanıcı da renkli yazabilsin fakat bunu yapamadım @EmirhanOlgn
> 
> Yapmak istediğiniz !kirmizi mesaj komutunu kullandığımda chate kırmızı renkte "mesaj" mesajınımı göndersin?

hayır !kırmızı yazdığında chatteki ismi sürekli kırmızı renkte olsun bunu istiyorum yani admin olduğumda renkli mesaj olduğu gibi binevi VIP rolü bu lazım bana

**Comment by EmirhanOlgn** [comment]
> > > > Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?
> > > 
> > > 
> > > Şimdi bak
> > > if (player.name == "test"){
> > > superadminMessage = message;
> > > var superadminChatColor = 0x000000;
> > > room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
> > > return false
> > > }
> > > Ben bu kodu yaptığımda test isimli kullanıcı renkli mesaj gönderebiliyor fakat ben bunu bir komut girildiğinde yapılmasını istiyorum fakat olmuyor yani !renk yazıldığında o kullanıcı da renkli yazabilsin fakat bunu yapamadım @EmirhanOlgn
> > 
> > 
> > Yapmak istediğiniz !kirmizi mesaj komutunu kullandığımda chate kırmızı renkte "mesaj" mesajınımı göndersin?
> 
> hayır !kırmızı yazdığında chatteki ismi sürekli kırmızı renkte olsun bunu istiyorum yani admin olduğumda renkli mesaj olduğu gibi binevi VIP rolü bu lazım bana

Buna bir örnek çıkarmak istiyorum player.name conn id gibi şeyleri biliyormusunuz?

**Comment by ghost** [comment]
> > > > > Merhaba @emret2, öncelikle çıktığın bu yolda başarılar diyorum ve tam olarak ne istediğini öğrenmek istiyorum. Daha detaylı bir şekilde anlatırmısın?
> > > > 
> > > > 
> > > > Şimdi bak
> > > > if (player.name == "test"){
> > > > superadminMessage = message;
> > > > var superadminChatColor = 0x000000;
> > > > room.sendAnnouncement ("[ADMIN] " + player.name + ": " + superadminMessage, null, superadminChatColor, 'bold', 2);
> > > > return false
> > > > }
> > > > Ben bu kodu yaptığımda test isimli kullanıcı renkli mesaj gönderebiliyor fakat ben bunu bir komut girildiğinde yapılmasını istiyorum fakat olmuyor yani !renk yazıldığında o kullanıcı da renkli yazabilsin fakat bunu yapamadım @EmirhanOlgn
> > > 
> > > 
> > > Yapmak istediğiniz !kirmizi mesaj komutunu kullandığımda chate kırmızı renkte "mesaj" mesajınımı göndersin?
> > 
> > 
> > hayır !kırmızı yazdığında chatteki ismi sürekli kırmızı renkte olsun bunu istiyorum yani admin olduğumda renkli mesaj olduğu gibi binevi VIP rolü bu lazım bana
> 
> Buna bir örnek çıkarmak istiyorum player.name conn id gibi şeyleri biliyormusunuz?

conn id message substr gibi şeyleri bilmiyorum fakat bi örnek yaparsanız güzel olur

**Comment by EmirhanOlgn** [comment]
```js
var vipler = new Map (); // burda map oluşturduk ve vip olanların isimlerini ve kullandıklari renkleri buraya yazdık
```
Birisine vip vermek için odayı başlatmış olabilirsin yada kodların içine yazabilirsin.
```js
vipler.set("oyuncu adı", "default");
```
Şimdide renklendirmeleri chate uygulayalım.
```js
room.onPlayerChat = function(player, message) {
if (vipler.has(player.name)) { //oyuncu adı vipler mapinde varmı
if (vipler.get(player.name) == "default") { // rengi default mu, kendin değişebilirsin. Blue Red
room.sendAnnouncement(player.name + ": " + message);
return false;
} else if (vipler.get(player.name) == "blue") {
room.sendAnnouncement("⭕" + player.name + ": " + message);
return false;
}
}
}
```
Sen istersen announcement kullanmayı biliyorsan renk kodları vs. kullanabilirsin.

**Comment by ghost** [comment]
> ```js
> var vipler = new Map (); // burda map oluşturduk ve vip olanların isimlerini ve kullandıklari renkleri buraya yazdık
> ```
> 
> Birisine vip vermek için odayı başlatmış olabilirsin yada kodların içine yazabilirsin.
> 
> ```js
> vipler.set("oyuncu adı", "default");
> ```
> 
> Şimdide renklendirmeleri chate uygulayalım.
> 
> ```js
> room.onPlayerChat = function(player, message) {
> if (vipler.has(player.name)) { //oyuncu adı vipler mapinde varmı
> if (vipler.get(player.name) == "default") { // rengi default mu, kendin değişebilirsin. Blue Red
> room.sendAnnouncement(player.name + ": " + message);
> return false;
> } else if (vipler.get(player.name) == "blue") {
> room.sendAnnouncement("⭕" + player.name + ": " + message);
> return false;
> }
> }
> }
> ```
> 
> Sen istersen announcement kullanmayı biliyorsan renk kodları vs. kullanabilirsin.

sağolun da başta yaptığınız şeyi tam olarak anlamadım nasıl komut olarak yapacağım bunu yani !vip yazdığında olmasını istiyorum

**Comment by ghost** [comment]
> ```js
> var vipler = new Map (); // burda map oluşturduk ve vip olanların isimlerini ve kullandıklari renkleri buraya yazdık
> ```
> 
> Birisine vip vermek için odayı başlatmış olabilirsin yada kodların içine yazabilirsin.
> 
> ```js
> vipler.set("oyuncu adı", "default");
> ```
> 
> Şimdide renklendirmeleri chate uygulayalım.
> 
> ```js
> room.onPlayerChat = function(player, message) {
> if (vipler.has(player.name)) { //oyuncu adı vipler mapinde varmı
> if (vipler.get(player.name) == "default") { // rengi default mu, kendin değişebilirsin. Blue Red
> room.sendAnnouncement(player.name + ": " + message);
> return false;
> } else if (vipler.get(player.name) == "blue") {
> room.sendAnnouncement("⭕" + player.name + ": " + message);
> return false;
> }
> }
> }
> ```
> 
> Sen istersen announcement kullanmayı biliyorsan renk kodları vs. kullanabilirsin.

hocam anlamadım bunu daha basite dönüştüremezmiyiz komut olarak

**Comment by EmirhanOlgn** [comment]
Komut ekleyebilirsiniz hocam oda şu şekil olur nasıl komut sistemi kullanıyosunuz bilemem ben direk komut kullanıldığında yapılması gerekeni yazıcam.
```js
var vipler = new Map();
vipler.set("emret2", "default");
var renkler = ["mavi", "sarı", "siyah", "kırmızı"]
var commands = {
    "!renk": renkFun,
}
function renkFun(player, message) {
var girilenRenk = message.substr(6);
if(vipler.has(player.name)) {
if(girilenRenk === null) {
room.sendAnnouncement("Örnek Kullanım: !renk beyaz");
return false;
} else if (renkler.includes(girilenRenk)) {
vipler.set(player.name, girilenRenk);
return false;
} else {
room.sendAnnouncement("Örnek Kullanım: (!renk siyah): Kullanılabilecek renkler: " + renkler);
return false;
}
} else {
room.sendAnnouncement("Bu komutu kullanabilmek için vip olmanız gerek");
return false;
}
}
room.onPlayerChat = function(player, message) {
    var spacePos = message.search(" ");
    var command = message.substr(0, spacePos !== -1 ? spacePos : message.length);
    if (commands.hasOwnProperty(command) == true) return commands[command](player, message);
if (vipler.has(player.name)) { //oyuncu adı vipler mapinde varmı
if (vipler.get(player.name) === "default") { // rengi default mu, kendin değişebilirsin. Blue Red
room.sendAnnouncement(player.name + ": " + message);
return false;
} else if (vipler.get(player.name) === "mavi") {
room.sendAnnouncement("⭕" + player.name + ": " + message);
return false;
}
}
```

**Comment by ghost** [comment]
Sorun çözülmüştür.

**Comment by emret2** [comment]
> > Merhaba bu şekilde komut kullanmak isterseniz kodu en üste veya en alta alın. Eğer işe yaramazsa geri dönün ve size hazır komut sistemi ile chat sistemi veriyim. İyi günler!
> 
> that didn't work. can you send me what you said ? @EmirhanOlgn

@metalingus666 
Add me on discord: emr2#3670 i will show you how to do this command.
