### ISSUE TITLE
Set Position

### ISSUE THREAD

**Issue by EmirhanOlgn** [haxball/haxball-issues#1457]
I can take the position of the player and the ball in the room, but I cannot change it. What I mean is this:
```js
room.setBallPosition();
room.setPlayerPosition();
```
I would be very grateful if someone could help and reply.

**Comment by saviola777** [comment]
I think you can use `setDiscProperties` / `setPlayerDiscProperties` to set the positions.

**Comment by EmirhanOlgn** [comment]
I dont know how can i use. Can you give sample

**Comment by saviola777** [comment]
It's documented [here](https://github.com/haxball/haxball-issues/wiki/Headless-Host). Just pass the disc / player ID and an object with `x` / `y` properties for the position I think.

**Comment by EmirhanOlgn** [comment]
I'll try that tomorrow. I'll answer if it helps. Thanks for your response.

**Comment by EmirhanOlgn** [comment]
Problem solved!

**Comment by GONGERRR** [comment]
Can you give sample, please

> It's documented [here](https://github.com/haxball/haxball-issues/wiki/Headless-Host). Just pass the disc / player ID and an object with `x`/ `y` properties for the position I think.
Can you give sample, please

**Comment by GONGERRR** [comment]
> Problem solved!

Can you give sample with player, please

**Comment by KubawGaming** [comment]
Example usage:

```java
var player;
room.setPlayerDiscProperties(player.id, {"x": -30, "y": 0})
```
