### ISSUE TITLE
Gameplay has been fundamentally changed.

### ISSUE THREAD

**Issue by mrhaxball** [haxball/haxball-issues#147]
Ive been playing in HTML 3v3 and 1v1 pubs since its been released, and its clear that the gameplay has changed from the Flash version.

Whats changed? The first touch has changed completely, and the control on the ball when you are turning with it stuck onto your player. In html you can move onto the ball with very bad movement but the ball will still stick nicely into your player, but on flash you need good movement off the ball and to slow down to the right pace, to get the nice touch. Then once the ball is on my player, its extremely easy to turn sharply, which in Flash was much harder because you needed really sharp and pro movement to do it at the fastest possible speed.

So for me this has made the game much more simple and easy, you could compare it to Counter-Striker: so an AK47 has a set recoil pattern and it takes a lot of skill and practice to control the recoil, so that you can spray accurately, but then if you took away all the recoil and made the gun shoot accurately even with spray, then you take away all the skill and make the game much less rewarding for long-term.

This is what it feels like with this HTML update, you don't need so much skill now and it really simplifies the game, because that was one of the hardest things to do in Flash Haxball, to have a perfect first touch and turn fast and sharply with the ball, since it was always different balls coming to you, always a different angle and different speed, so you had to be really experience or talented to master it and get the just perfect movement before the ball came to get a great first touch.

So once I realised the gameplay was so much different, I tried to figure out why because the physics all feel the same. Then I noticed the ball and player shape is slightly different, so I zoomed in the same amount with a picture of the ball and the player, and now I see why the gameplay changed so much, on the left side of both pictures is HTML version and on the right side Flash version:

Player shape - https://i.imgur.com/mVPFXVx.png
Ball shape - https://i.imgur.com/5vrIsQp.png

So since the update they are both more round, so it makes sense why the first touch and turning with the ball has changed so much from the Flash version. Please fix it back to normal to make the game more skillful again and a serious long-term game like it is on Flash, more than a short term easy game for beginners to play 1 week then stop because there’s not enough depth to the game.

**Comment by Fabrice169** [comment]
please fix, the game has changed a lot from flash for the worse. GK also can't pressure strikers from behind anymore because the players slip off each other too easily with the new player shape..

**Comment by LRC13** [comment]
i agree, new haxball is too easy with new ball and player shape, doesnt take skill anymore

**Comment by basro** [comment]
The physics are unchanged, if anything the visuals now are now slightly more accurate. But I don't agree that this affects the skill level of the game at all.

Are you going to complain about ping being lower too?
Lower ping => Easier to play => Under your logic that's a bad thing.

**Comment by gliptic** [comment]
Frame rate is also too smooth. You should add a freeze every two seconds. That's how I played in the flash version back in the day, and it's too easy otherwise.

**Comment by mrhaxball** [comment]
The physics are unchanged but the player and ball shape are different, this affects the first touch and movement on the ball a lot.

Also lower ping being easier to play is not the same as this, i didn't say anything that is easier to play is automatically worse, higher pings make the game more random, not more skilled. this is just about the skill ceiling of the game, and in a simple game like haxball, removing the hardest part of it has made the skill ceiling much lower.

This is exactly like if you took away the recoil pattern on guns in counter-strike, the max ability is the same in that you can have 0 recoil in both versions, but now everybody gets 0 recoil without any skill to achieve it, whereas if you keep the recoil, only the top players can control the gun well enough to make it with 0 recoil, which is a good thing because it makes the game harder but more rewarding.

**Comment by haxballer** [comment]
Unfortunately, I have to agree with that. The html5 game is no longer so demanding and hard, and by this perfectly round ball shape many of the tricks are not as effective as before, even the biggest noobs are able to defend themselves against the best players because the dynamics have changed. You really should think about it, because HaxBall has lost a little of time, the game is getting casuals, and such people will soon forget this game, it is really worth listening to some experienced and faithful old school HaxBall fans. I know it's alpha, so I believe that you will try to improve a bit more, which will be a laureate for those who play for years in Haxball.

**Comment by basro** [comment]
The two platforms (flash and html5) have a tiny difference in their renderers, the difference is *minuscule* and you'll never get me to believe it's enough to change the gameplay in any meaningful way.

Regardless, even if I wanted to, there's nothing I can do to make that minuscule difference disappear. Each platform draw circles the way they do.

I'm closing this issue.

**Comment by pilaf** [comment]
> The physics are unchanged but the player and ball shape are different, this affects the first touch and movement on the ball a lot.

> The html5 game is no longer so demanding and hard, and by this perfectly round ball shape many of the tricks are not as effective as before, even the biggest noobs are able to defend themselves against the best players because the dynamics have changed.

@mrhaxball @haxballer 

You seem to believe that the physics are somehow affected by the fact that the rendering is slightly different in the HTML5 version. That's not the case. Rendering and physics are handled separately, the ball and players could be rendered as bananas and the physics still be that of circles just as in the Flash version.

I think what's happening is that the slight difference in rendering and FPS is causing your brain to react a little different, since it's too used to the quirks of the Flash version. That will eventually go away as you grow used to it. In the meantime there's nothing basro can do about it.

**Comment by haxballer** [comment]
@pilaf I hope I get used to it. I am looking forward to the full version of the game, which will be free of bugs and more elaborate than flash.
