### ISSUE TITLE
Physic question

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1484]
Hi, can you tell me how the speed with acceleration is calculated?
`newSpeed = oldSpeed * damping + acceleration` ?

**Comment by thenorthstar** [comment]
> Hi, can you tell me how the speed with acceleration is calculated? `newSpeed = oldSpeed * damping + acceleration` ?

@BrigandRo 

```
distance = initial_ballspeed * [1/(1-ball_damping)] ; (for damping<1)

distance = ballspeed * time ; (for damping = 1)

distance = initial_ballspeed * [(Math.pow(damping,0)) + (Math.pow(damping,1)) + (Math.pow(damping,2)) + ... + (Math.pow(damping,frame_number-1))] (for damping>1)
	   initial_ballspeed * [(Math.pow(damping,frame_number)-1) / (damping-1)]

final_ballspeed = initial_ballspeed * Math.pow(damping,frame_number)

for ball_speed : 1 speed = 60 units/sec


maximum_speed = acceleration * damping / (1-damping) ; (for damping < 1)

for damping: 0.96 & for acceleration: 0.15 → |maximum speed|: 3.6 or 216 units/sec
```

For your issue and more, you can read the following.

**Comment by thenorthstar** [comment]
@BrigandRo You deleted your reply and closed the issue. So did you understand what going on is? And what formula helps you? If not, let me tell with an example.

There's such a formula on the code:

**initial_ballspeed * [(Math.pow(damping,frame_number)-1) / (damping-1)]**

Interestingly, this formula can also estimate player speed when damping < 1. So, before sending a code, let me share a screenshot with you:

Player speeds are logged so on the console:
![image](https://user-images.githubusercontent.com/68077608/137768471-e1f2ea5a-3c62-4c58-9d44-d5b3bef878ef.png)

And this is the move of the player:
https://gyazo.com/66d2f11dc2b6a0cf826c9c7ce4175db3

```js
function logPlayerSpeed(){
    var redTeam = room.getPlayerList().filter(p => p.team == 1);
    if(redTeam.length > 0){
	if(room.getPlayerDiscProperties(redTeam[0].id) != null){
	    console.log(gameTick,Math.hypot(room.getPlayerDiscProperties(redTeam[0].id).xspeed,room.getPlayerDiscProperties(redTeam[0].id).yspeed));
	}
    }
}

room.onPlayerJoin = function(player){console.log(player.name + " has joined.");}
room.onPlayerLeave = function(player){console.log(player.name + " has left.");}
room.onPlayerChat = function(player, message){console.log(player.name + ": " + message);};

room.onGameTick = function(){
    logPlayerSpeed();
    gameTick++;
};

room.onGameStart = function(byPlayer){
    gameTick = 0;
}
```

After sharing the code, now, let me explain how the formula works in practice. With 0.96 of damping and 0.15 of acceleration, we get:

* Frame 0: | Player Speed: 0.144 * ((0.96 ^ 0) - 1) / (0.96 - 1) = 0 (Frame means one of the 60 pieces of a second)
* Frame 1: | Player Speed: 0.144 * ((0.96 ^ 1) - 1) / (0.96 - 1) = 0.144
* Frame 2: | Player Speed: 0.144 * ((0.96 ^ 2) - 1) / (0.96 - 1) = 0.28224
* Frame 3: | Player Speed: 0.144 * ((0.96 ^ 3) - 1) / (0.96 - 1) = 0.4149504 (On console it was 0.41495039999999994)
* Frame 4: | Player Speed: 0.144 * ((0.96 ^ 4) - 1) / (0.96 - 1) = 0.542352384

And so on... You get the same values with the ones above when you put the frame numbers on the following formula:

```js
0.144 * (Math.pow(0.96,frame_number)-1) / (0.96-1)
```

**Comment by ghost** [comment]
@thenorthstar
Thanks for the help.

**Comment by thenorthstar** [comment]
You're welcome.
