### ISSUE TITLE
block if the player log in from 2 browsers

### ISSUE THREAD

**Issue by metalingus666** [haxball/haxball-issues#1485]
playerAuth[player.id] = player.auth;
    if (room.getPlayerList().filter((p) => playerAuth[p.id] == player.auth).length > 1) 
    room.kickPlayer(room.getPlayerList().filter((p) => playerAuth[p.id] == player.auth)[1].id, "you can't log in from 2 tabs", false); 

I'm using this code so that they can't log in from two tabs, so how can I block players from entering from a different browser?

**Comment by ghost** [comment]
use conn instead of auth

**Comment by metalingus666** [comment]
> use conn instead of auth

but I'm getting this error playerConn is not defined

**Comment by thenorthstar** [comment]
> playerAuth[player.id] = player.auth; if (room.getPlayerList().filter((p) => playerAuth[p.id] == player.auth).length > 1) room.kickPlayer(room.getPlayerList().filter((p) => playerAuth[p.id] == player.auth)[1].id, "you can't log in from 2 tabs", false);
> 
> I'm using this code so that they can't log in from two tabs, so how can I block players from entering from a different browser?

@metalingus666 You have to make the same code also for **player.conn**. That is:

```js
playerConn[player.id] = player.conn; if (room.getPlayerList().filter((p) => playerConn[p.id] == player.conn).length > 1) room.kickPlayer(room.getPlayerList().filter((p) => playerConn[p.id] == player.conn)[1].id, "you can't log in from 2 tabs", false);
```

But you have to know is that the above code will also block two players on the same network to join the room with the same because of their **conn** will be the same.

**Comment by metalingus666** [comment]
> ```js
> ```js
> playerConn[player.id] = player.conn; if (room.getPlayerList().filter((p) => playerConn[p.id] == player.conn).length > 1) room.kickPlayer(room.getPlayerList().filter((p) => playerConn[p.id] == player.conn)[1].id, "you can't log in from 2 tabs", false);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Thanks for sharing but i get this error 
ReferenceError: playerConn is not defined
How can i fix it ? @thenorthstar

**Comment by thenorthstar** [comment]
> > ```js
> > ```js
> > playerConn[player.id] = player.conn; if (room.getPlayerList().filter((p) => playerConn[p.id] == player.conn).length > 1) room.kickPlayer(room.getPlayerList().filter((p) => playerConn[p.id] == player.conn)[1].id, "you can't log in from 2 tabs", false);
> > ```
> 
> Thanks for sharing but i get this error ReferenceError: playerConn is not defined How can i fix it ? @thenorthstar

@metalingus666 Just add an array with the name of **playerConn**.
