### ISSUE TITLE
3 Gk block

### ISSUE THREAD

**Issue by Alwush** [haxball/haxball-issues#1488]
3Def çizgisi için mapte hangi ayarları yapmam gerekiyor hazır koda nasıl entegre edebilirim

**Comment by thenorthstar** [comment]
> 3Def çizgisi için mapte hangi ayarları yapmam gerekiyor hazır koda nasıl entegre edebilirim

@Alwush #1385 numaralı issue'yu incelemeni tavsiye ederim, orada neler yapman gerektiği detaylı bir şekilde izah edilmiş.

**Comment by Alwush** [comment]
> > 3Def hazırlanmak için mapte hangi ayarlamayı yapmak zorunda olan koda nasıl entegre olacak
> 
> @Alwush #1385 issue'yu incelemeni tavsiye ederim, orada neler yapman kapsamlı bir şekilde anlatılmış.

Yardımın için Teşekkürler detaylı bir şekilde inceliyorum :)
