### ISSUE TITLE
Help with this problem? All players in the same team

### ISSUE THREAD

**Issue by Gabri04** [haxball/haxball-issues#1497]
Hello guys, I'm programming a room and I need help. All players go in the same team, in a big map with many nets, and I want to program that when a player scores in someone's net the player who received the gol in his net is moved in spec because he lost and so on. How can I do that?
Remember, all players are in the same team (red), I would really appreciate your help

**Comment by thenorthstar** [comment]
> Hello guys, I'm programming a room and I need help. All players go in the same team, in a big map with many nets, and I want to program that when a player scores in someone's net the player who received the gol in his net is moved in spec because he lost and so on. How can I do that? Remember, all players are in the same team (red), I would really appreciate your help

@Gabri04 It's called **X-Man** (or we call **Japon Kale** in Turkish) and I have three separate scripts for it. You can check them out and fit in your script.

[XMan_Bot_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586740/XMan_Bot_Room_Source_Code.txt)
[XMan_Bot_2_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586738/XMan_Bot_2_Room_Source_Code.txt)
[XMan_Bot_3_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586739/XMan_Bot_3_Room_Source_Code.txt)

**Comment by Gabri04** [comment]
> > Hello guys, I'm programming a room and I need help. All players go in the same team, in a big map with many nets, and I want to program that when a player scores in someone's net the player who received the gol in his net is moved in spec because he lost and so on. How can I do that? Remember, all players are in the same team (red), I would really appreciate your help
> 
> @Gabri04 It's called **X-Man** (or we call **Japon Kale** in Turkish) and I have three separate scripts for it. You can check them out and fit in your script.
> 
> [XMan_Bot_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586740/XMan_Bot_Room_Source_Code.txt) [XMan_Bot_2_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586738/XMan_Bot_2_Room_Source_Code.txt) [XMan_Bot_3_Room_Source_Code.txt](https://github.com/haxball/haxball-issues/files/7586739/XMan_Bot_3_Room_Source_Code.txt)

Thank you so much. I really appreciate your help!
