### ISSUE TITLE
Touchs

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1498]
Hi guys..

How can i use last player touch in game tick function? 

Like room.setPlayerDiscProperties(last player touch, ?

**Comment by thenorthstar** [comment]
> Hi guys..
> 
> How can i use last player touch in game tick function?
> 
> Like room.setPlayerDiscProperties(last player touch, ?

@byoxygen You can check it out through the following: https://github.com/haxball/haxball-issues/blob/master/headless/examples/ballTouchExample.js
