### ISSUE TITLE
Bu sorunla ilgili yardım? Tüm oyuncular aynı takımda

### ISSUE THREAD

**Issue by Gabri04** [haxball/haxball-issues#1499]
Merhaba arkadaşlar, bir oda programlıyorum ve yardıma ihtiyacım var. Tüm oyuncular aynı takımda, birçok fileli büyük bir haritada gider ve bir oyuncu birinin ağında gol attığında, ağında golü alan oyuncunun kaybettiği için spesifikasyona göre hareket etmesini programlamak istiyorum. Bunu nasıl yapabilirim?
Unutma, tüm oyuncular aynı takımda (kırmızı), yardımın için gerçekten minnettar olurum.

**Comment by thenorthstar** [comment]
> Merhaba arkadaşlar, bir oda programlıyorum ve yardıma ihtiyacım var. Tüm oyuncular aynı takımda, birçok fileli büyük bir haritada gider ve bir oyuncu birinin ağında gol attığında, ağında golü alan oyuncunun kaybettiği için spesifikasyona göre hareket etmesini programlamak istiyorum. Bunu nasıl yapabilirim? Unutma, tüm oyuncular aynı takımda (kırmızı), yardımın için gerçekten minnettar olurum.

@Gabri04 #1497
