### ISSUE TITLE
Failed to Connect Sorunu | Acil

### ISSUE THREAD

**Issue by 4gny** [haxball/haxball-issues#1501]
Selamlar.
VDS'e scripti kurunca odaya kimse giremiyor.
Failed to Connect hatası veriyor.
Bu lanet sorunun çözümü nedir?

**Comment by MoonLight61** [comment]
![image](https://user-images.githubusercontent.com/94144712/141371904-472704f2-6d7e-4dc6-a35b-064e3cc122f2.png)

I guess this is the solution to the problem. You can try by doing the default disabled that says there.

good luck...

**Comment by 4gny** [comment]
Thx

**Comment by 4gny** [comment]
Çözüldü
