### ISSUE TITLE
Haxball internal logic still runs at 60hz?

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1503]
Someone asked you a question (which can be found in the image) and you say that Haxball's internal logic runs at 60hz even its HTML5. 

So I was wondering is that updated in time or it's still 60hz? If so why 60hz? Most of the players have now 144hz and some players like me has 240hz and 360hz monitors. And is it possible to uncap this limit or make it work on 240hz maybe? Will this effect gameplay? Even though we play on high refresh rated monitors do we play on 60hz? (due to your answer back in 2017).

![image](https://user-images.githubusercontent.com/69965335/141672933-8fa93da7-1a52-4809-86c7-91f85c369bd9.png)

**Comment by ViegoHAX** [comment]
And I'd like to mention that I get 280 FPS (which same as my monitor's hertz) and I get more FPS when I use uncapped frame limit command. But here I don't talk about them, I talk about internal logic of the game, how the physics are handled and more on. I don't want to be misunderstood.

**Comment by chrxmvtik** [comment]
@ViegoHAX Sadly for us - yes, it still does operate at 60 ticks per second.
As an example here is a result of using getPlayerList function which prints players coordinates on map:
BOT - operates every 1 milisecond
TICK - operates every 1/60 of second (16 miliseconds)

> info: TICK: -154.8496704172579 28.452188963006506   
> info: TICK: -154.79744983565897 28.455867639577615   
> info: TICK: -154.747318077324 28.45939916908588   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: BOT: -154.69919158932242 28.462789437413818   
> info: TICK: -154.69919158932242 28.462789437413818   
> info: TICK: -154.65299016084091 28.466044095008638   
> info: TICK: -154.60863678949866 28.469168566299665   

Results are pretty clear, there is no way to do anything faster than onGameTick - value will only change once tick happens.

**Comment by haxball-app** [comment]
@ViegoHAX Sadly for us - yes, it still does operate at 60 ticks per second.
As an example here is a result of using getPlayerList function which prints players coordinates on map:
BOT - operates every 1 milisecond
TICK - operates every 1/60 of second (16 miliseconds)

> info: TICK: -154.8496704172579 28.452188963006506
> info: TICK: -154.79744983565897 28.455867639577615
> info: TICK: -154.747318077324 28.45939916908588
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: BOT: -154.69919158932242 28.462789437413818
> info: TICK: -154.69919158932242 28.462789437413818
> info: TICK: -154.65299016084091 28.466044095008638
> info: TICK: -154.60863678949866 28.469168566299665

Results are pretty clear, there is no way to do anything faster than onGameTick - value will only change once tick happens.

**Comment by ViegoHAX** [comment]
So if @basro increases this we will get better performance and better handling on game physics rights? That randomly coming slow feeling won't be a deal anymore right? Just wondering if this can save Haxball's dying gameplay Waiting for Mario's answer tho.

**Comment by Mirac35** [comment]
Movement and ball control would be feel fluid and makes your placebo go away for a little but same slow-mo feeling would be come back right after when your brain has done with the currents and ask it for more. You are caughting in a loop.

e: on a 2d browser based game, Hardware-Advantage S U C K S
