### ISSUE TITLE
Cannot Join Rooms (13.12.2021)

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1521]
@basro Right now we're facing on a problem on joining rooms. In most of trials (excluding my own room) I'm getting the same screen below.

Waiting...
![1](https://user-images.githubusercontent.com/68077608/145866595-37c83cec-fe12-4da7-81c0-8d41520fbebe.PNG)

And then getting failed.
![2](https://user-images.githubusercontent.com/68077608/145866593-312ecf52-8ccd-4ac2-af5f-ca195fdfd696.PNG)

Edit: Now, headless hosted rooms are reachable but neutral ones are not.

**Comment by basro** [comment]
I've not done any changes recently, the most likely things that could cause this is a change in your network or a change in the browser.
Make sure to test with multiple browsers.

**Comment by thenorthstar** [comment]
> I've not done any changes recently, the most likely things that could cause this is a change in your network or a change in the browser. Make sure to test with multiple browsers.

@basro Anyway, I don't know the reason but now the things are OK in my part (both on GC and Firefox it works very well) but apparently some people who from different parts of the world are still suffering from the problem. That's, the problem isn't related to my internet connection imo. 👍

Some examples:
![image](https://user-images.githubusercontent.com/68077608/145882205-e691f2ac-f842-4ff5-b959-ec837ea54b15.png)

In Turkish:
![image](https://user-images.githubusercontent.com/68077608/145882457-ab223f2c-1e6c-4994-9050-2eecccd0d96a.png)

**Comment by AmberJC** [comment]
we also find this problem in some Italian connections, if you find a solution please post here

**Comment by ghost** [comment]
It's all about open ports. When player's router refuses to connect some kind of ports they can't join. Best solution is opening all range of TCP and UDP ports from your router panel. I mean whoever having this issue when connecting to rooms. Not the room host.
