### ISSUE TITLE
Stadium object limit

### ISSUE THREAD

**Issue by migudmigu** [haxball/haxball-issues#1542]
Why is the number of segments (and other objects too) limited?

I've been working on some personal projects with haxball and I just added automatic writing on the stadiums but with the 255 limit it is almost useless :/

It would be great if the limit was higher/there was no limit

**Comment by thenorthstar** [comment]
> Why is the number of segments (and other objects too) limited?
> 
> I've been working on some personal projects with haxball and I just added automatic writing on the stadiums but with the 255 limit it is almost useless :/
> 
> It would be great if the limit was higher/there was no limit

@migudmigu As thinking simple, you can easily understood higher amount of objects cause higher amount of ping.

https://haxmaps.com/map/1118
https://haxmaps.com/map/6598
https://haxmaps.com/map/6974

For example, these maps have a lot of objects like discs, walls and etc. so you get higher amount of pings if you aren't host maps like the above ones. But we still need some implementations for better quality maps under this current limit as they told on the following issues:

#1064 #1340 #1365

**Comment by migudmigu** [comment]
Thanks for the answer! 

I'm using segments to draw the letters on the map. Maybe the solution would be to make it possible to write html text. I'm not sure if that's possible/interesting for the devs.

**Comment by migudmigu** [comment]
Actually, I think the segments limit is 128, because it makes 256 vertexes.

Could we have the option to have more segments? ;)

**Comment by thenorthstar** [comment]
> Actually, I think the segments limit is 128, because it makes 256 vertexes.
> 
> Could we have the option to have more segments? ;)

@migudmigu No, limits are just in your head. If you connect one segment to another, then you can make up to 255 segments. Like this, let the numbers show vertexes. So: 0 → 1, 1 → 2, 2 → 3, ..., 253 → 254 and 254 → 0. The same logic is also valid for joints.
