### ISSUE TITLE
Turkish Haxball copycat - Mamoball - is milking money without crediting this game at all

### ISSUE THREAD

**Issue by bartakabstina** [haxball/haxball-issues#1559]
Edit : I changed my mind

**Comment by LuciferGRE** [comment]
And what's your issue about this? haxball is abandoned anyway, and all our communities are totally naked in haxball limitations.  At least they made an app to provide haxball on their own view. I really hope another refreshed haxball PC version from someone comes to the light sometime. This game is abandoned and lack of updates.
