### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LexWe** [haxball/haxball-issues#1567]
It sends a goal message when a goal is scored, then it sends an Out message, how can I make it not to send an Out message?

**Comment by Raamyy** [comment]
It seems that you are using a ready-made code. look for the code owner and ask him for the bug.

**Comment by thenorthstar** [comment]
> It sends a goal message when a goal is scored, then it sends an Out message, how can I make it not to send an Out message?

@LexWe You can check out if it's goal or just leaving the pitch, by putting a boolean. Let me explain briefly in code:

```js
var isAnnounced = false;
var isGoalScored = false;

var width = 1400;
var height = 660;

function checkOut(ballPosition){
    return isGoalScored == false && (ballPosition.x > width || ballPosition.x < -width);
}

function checkIn(ballPosition){
    return isGoalScored == false && (ballPosition.x < width && ballPosition.x > -width && ballPosition.y < height && ballPosition.y > -height);
}

function announceOutAndIn(){
    if(checkOut(room.getBallPosition()) == true && isAnnounced == false){
	room.sendAnnouncement("GK.",null,0xFFFFFF,"bold",2);
	announced = true;
    }
    if(checkIn(room.getBallPosition()) == true && isAnnounced == true){
	room.sendAnnouncement("It was used the GK.",null,0xFFFFFF,"bold",2);
	announced = false;
    }
}

room.onTeamGoal = function(team){
    if(isGoalScored == false){
	isGoalScored = true;
    }
    room.sendAnnouncement("Goal scored.",null,0xFFFFFF,"bold",2);
}

room.onPositionsReset = function(){
    if(isGoalScored == true){
	isGoalScored = false;
    }
}

room.onGameTick = function(){
    checkOut();
    announceOutAndIn();
}
```
You can change this code according to your preference.

**Comment by LexWe** [comment]
@thenorthstar 
Ok thanks, I have another question. How can I message or ban a member in the game via discord?
I don't understand how to do this, is there an easy method? https://www.npmjs.com/package/haxball-server

**Comment by thenorthstar** [comment]
> @thenorthstar Ok thanks, I have another question. How can I message or ban a member in the game via discord? I don't understand how to do this, is there an easy method? https://www.npmjs.com/package/haxball-server

@LexWe I also don't know. You can ask one of them: **beta#3136**, **Zlam+Recep#2563**.
