### ISSUE TITLE
Putting the spectators on a random team when the game is stopped

### ISSUE THREAD

**Issue by JolafEx** [haxball/haxball-issues#1568]
I have a bot but I want put spectators to red or blue team when i stopped the game

**Comment by thenorthstar** [comment]
> I have a bot but I want put spectators to red or blue team when i stopped the game

@JolafEx You can use the following code:

```js
var spectator_ids = [];
var redMax = 3; //A scenario in 3 vs 3 room. You can decrease or increase these variables.
var blueMax = 3;

var room = HBInit({roomName:"TEST",noPlayer:true,public:true,maxPlayers:10});

function putPlayersToRandomTeams(){ //Puts the spectators who don't play in the previous match, to the teams randomly. Then equates the teams if there's a difference greater than 1.
    var spectators = room.getPlayerList().filter(p => p.team == 0);
    spectators.forEach(p => {
	if(spectator_ids.includes(p.id) == false){
	    spectator_ids.push(p.id); //Since room.getPlayerList() works asynchronusly, you cannot use it to distribute the players.
	}
    });

    var non_spectators = room.getPlayerList().filter(p => p.team != 0);
    non_spectators.forEach(p => {
	room.setPlayerTeam(p.id,0); //Before putting the spectators to random teams, we have to move the players who played in the previous match, to spectators.
    });

    var randomTeams = [1,2];

    spectator_ids.forEach(p => {
	room.setPlayerTeam(p,randomTeams[Math.random()*randomTeams.length]);
    });

    equateTeams();
}

function equateTeams(){ //Equation means you have to transfer the players to rival team by looking at the counts. If 3 vs 1, one red to blue; if 2 vs 5, then one blue to red; if 6 vs 2, then two reds to blue etc...
    var reds = room.getPlayerList().filter(p => p.team == 1);
    var blues = room.getPlayerList().filter(p => p.team == 2);

    var redCount = reds.length;
    var blueCount = blues.length;

    var difference = Math.abs(redCount - blueCount); //If 1, then no need to transfer; if 2 or 3, then 1...
    var playerAmountToTransfer = Math.floor(difference/2);

    if(difference > 1){
	if(redCount > blueCount){
	    for(var i=1; i<=playerAmountToTransfer; i++){
		room.setPlayerTeam(reds[redCount-i].id,2);
	    }
	}
	else{
	    for(var i=1; i<=playerAmountToTransfer; i++){
		room.setPlayerTeam(blues[blueCount-i].id,1);
	    }
	}
    }
}

room.onGameStart = function(byPlayer){ //We reset this at the start of every match to prevent confusions.
    spectator_ids = [];
}

room.onGameStop = function(byPlayer){ //Your function will work in this event handler.
    putPlayersToRandomTeams();
}
```

**Comment by JolafEx** [comment]
> > I have a bot but I want put spectators to red or blue team when i stopped the game
> 
> @JolafEx You can use the following code:
> 
> ```js
> var spectator_ids = [];
> var redMax = 3; //A scenario in 3 vs 3 room. You can decrease or increase these variables.
> var blueMax = 3;
> 
> var room = HBInit({roomName:"TEST",noPlayer:true,public:true,maxPlayers:10});
> 
> function putPlayersToRandomTeams(){ //Puts the spectators who don't play in the previous match, to the teams randomly. Then equates the teams if there's a difference greater than 1.
>     var spectators = room.getPlayerList().filter(p => p.team == 0);
>     spectators.forEach(p => {
> 	if(spectator_ids.includes(p.id) == false){
> 	    spectator_ids.push(p.id); //Since room.getPlayerList() works asynchronusly, you cannot use it to distribute the players.
> 	}
>     });
> 
>     var non_spectators = room.getPlayerList().filter(p => p.team != 0);
>     non_spectators.forEach(p => {
> 	room.setPlayerTeam(p.id,0); //Before putting the spectators to random teams, we have to move the players who played in the previous match, to spectators.
>     });
> 
>     var randomTeams = [1,2];
> 
>     spectator_ids.forEach(p => {
> 	room.setPlayerTeam(p,randomTeams[Math.random()*randomTeams.length]);
>     });
> 
>     equateTeams();
> }
> 
> function equateTeams(){ //Equation means you have to transfer the players to rival team by looking at the counts. If 3 vs 1, one red to blue; if 2 vs 5, then one blue to red; if 6 vs 2, then two reds to blue etc...
>     var reds = room.getPlayerList().filter(p => p.team == 1);
>     var blues = room.getPlayerList().filter(p => p.team == 2);
> 
>     var redCount = reds.length;
>     var blueCount = blues.length;
> 
>     var difference = Math.abs(redCount - blueCount); //If 1, then no need to transfer; if 2 or 3, then 1...
>     var playerAmountToTransfer = Math.floor(difference/2);
> 
>     if(difference > 1){
> 	if(redCount > blueCount){
> 	    for(var i=1; i<=playerAmountToTransfer; i++){
> 		room.setPlayerTeam(reds[redCount-i].id,2);
> 	    }
> 	}
> 	else{
> 	    for(var i=1; i<=playerAmountToTransfer; i++){
> 		room.setPlayerTeam(blues[blueCount-i].id,1);
> 	    }
> 	}
>     }
> }
> 
> room.onGameStart = function(byPlayer){ //We reset this at the start of every match to prevent confusions.
>     spectator_ids = [];
> }
> 
> room.onGameStop = function(byPlayer){ //Your function will work in this event handler.
>     putPlayersToRandomTeams();
> }
> ```

Thanks

**Comment by thenorthstar** [comment]
> > > I have a bot but I want put spectators to red or blue team when i stopped the game
> > 
> > 
> > @JolafEx You can use the following code:
> > ```js
> > var spectator_ids = [];
> > var redMax = 3; //A scenario in 3 vs 3 room. You can decrease or increase these variables.
> > var blueMax = 3;
> > 
> > var room = HBInit({roomName:"TEST",noPlayer:true,public:true,maxPlayers:10});
> > 
> > function putPlayersToRandomTeams(){ //Puts the spectators who don't play in the previous match, to the teams randomly. Then equates the teams if there's a difference greater than 1.
> >     var spectators = room.getPlayerList().filter(p => p.team == 0);
> >     spectators.forEach(p => {
> > 	if(spectator_ids.includes(p.id) == false){
> > 	    spectator_ids.push(p.id); //Since room.getPlayerList() works asynchronusly, you cannot use it to distribute the players.
> > 	}
> >     });
> > 
> >     var non_spectators = room.getPlayerList().filter(p => p.team != 0);
> >     non_spectators.forEach(p => {
> > 	room.setPlayerTeam(p.id,0); //Before putting the spectators to random teams, we have to move the players who played in the previous match, to spectators.
> >     });
> > 
> >     var randomTeams = [1,2];
> > 
> >     spectator_ids.forEach(p => {
> > 	room.setPlayerTeam(p,randomTeams[Math.random()*randomTeams.length]);
> >     });
> > 
> >     equateTeams();
> > }
> > 
> > function equateTeams(){ //Equation means you have to transfer the players to rival team by looking at the counts. If 3 vs 1, one red to blue; if 2 vs 5, then one blue to red; if 6 vs 2, then two reds to blue etc...
> >     var reds = room.getPlayerList().filter(p => p.team == 1);
> >     var blues = room.getPlayerList().filter(p => p.team == 2);
> > 
> >     var redCount = reds.length;
> >     var blueCount = blues.length;
> > 
> >     var difference = Math.abs(redCount - blueCount); //If 1, then no need to transfer; if 2 or 3, then 1...
> >     var playerAmountToTransfer = Math.floor(difference/2);
> > 
> >     if(difference > 1){
> > 	if(redCount > blueCount){
> > 	    for(var i=1; i<=playerAmountToTransfer; i++){
> > 		room.setPlayerTeam(reds[redCount-i].id,2);
> > 	    }
> > 	}
> > 	else{
> > 	    for(var i=1; i<=playerAmountToTransfer; i++){
> > 		room.setPlayerTeam(blues[blueCount-i].id,1);
> > 	    }
> > 	}
> >     }
> > }
> > 
> > room.onGameStart = function(byPlayer){ //We reset this at the start of every match to prevent confusions.
> >     spectator_ids = [];
> > }
> > 
> > room.onGameStop = function(byPlayer){ //Your function will work in this event handler.
> >     putPlayersToRandomTeams();
> > }
> > ```
> 
> Thanks

@JolafEx You're welcome.
