### ISSUE TITLE
about to collision

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1583]
I want players not to collide with each other, but collide with objects

what code can i use for this?

**Comment by thenorthstar** [comment]
> I want players not to collide with each other, but collide with objects
> 
> what code can i use for this?

@mydestiny185 Firstly I have to tell you that it's still impossible to do it through the map scripts so you have to use bot scripts to change player collision groups in mid-game. Also you have to make walls able for players to collide with (this one is made through map scripts). And here's an example of the code on following:

```js
var Map = `Map scripts here`; //The objects which you want players to collide with must have the same cGroup in their cMask. For example, if players have c0 in cGroup, then walls must have c0 in their cMask.
var cf = room.CollisionFlags;

function changePlayerCollisionGroup(player){
    if(room.getPlayerDiscProperties(player.id) != null){
	if(room.getPlayerDiscProperties(player.id).cGroup === cf.c0){
	    room.setPlayerDiscProperties(player.id,{cGroup:cf.c0}); //This can make players transparent also to the puck so you have check also it.
	}
    }
}

room.onGameStart = function(byPlayer){
    var players = room.getPlayerList();
    players.forEach(p => changePlayerCollisionGroup(p));
}

room.onPlayerTeamChange = function(changedPlayer,byPlayer){
    changePlayerCollisionGroup(changedPlayer);
}

room.onPositionsReset = function(){
    var players = room.getPlayerList();
    players.forEach(p => changePlayerCollisionGroup(p));
}
```
See how the collision logic is working fundamentally: https://github.com/haxball/haxball-issues/wiki/Collision-Flags
