### ISSUE TITLE
spam - mute 

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1584]
I want to mute spammers and kick them if they continue. 

Ik this topic has been opened before. #1516 but I failed to run that code 

Pls help me :(

**Comment by thenorthstar** [comment]
> I want to mute spammers and kick them if they continue.
> 
> Ik this topic has been opened before. #1516 but I failed to run that code
> 
> Pls help me :(

@mydestiny185 It's been updated on #1516. You can check it out with the output.
