### ISSUE TITLE
about ban

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1589]
I want a code that automatically bans ppl with bad words in their username when they enter the room.

can u help me ?

**Comment by thenorthstar** [comment]
> I want a code that automatically bans ppl with bad words in their username when they enter the room.
> 
> can u help me ?

@mydestiny185 You can use the following code. The bad words here are a collection from my own scripts btw:

```js
var badwords = [/[a4@][s$5][s$5]h[o0][l1][e€]+/,/[bß][a4@]rm[iy7]+/,/[bß][a4@][s$5][t₺][a4@]rd+/,/[bß][ıi1][t₺][cç¢]h+/,/[c¢]un[t₺]+/,/f[uü][cç¢]k+/,/[l1]m[a4@][o0]+/,/[l1]mf[a4@][o0]+/,/pu[s5$][s5$][y7]+/,/r[e€][t₺][a4@]rd+/,/[s$5][t₺]fu+/,/wh[o0]r[e€]+/,/w[t₺]f+/];

function isBadword(str){
    return badwords.filter(b => str.match(b)).length > 0;
}

room.onPlayerJoin = function(player){
    if(isBadword(player.name) == true){
	room.kickPlayer(player.id,"You cannot join this room with such a name.",true);
    }
}
```

**Comment by ghost** [comment]
@thenorthstar I wasn't able to run this code. Is there any other alternative?

**Comment by thenorthstar** [comment]
> @thenorthstar I wasn't able to run this code. Is there any other alternative?

@mydestiny185 But why? Isn't it so simple code to run?
