### ISSUE TITLE
Tactical timeout

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1590]
Hi all. 
Teams can use call vote in-game to call a tactical timeout. 
How can I do that?

**Comment by thenorthstar** [comment]
> Hi all. Teams can use call vote in-game to call a tactical timeout. How can I do that?

@byoxygen Could you briefly explain what a tactical timeout is? And why to vote?

**Comment by byoxygen** [comment]
> > Hi all. Teams can use call vote in-game to call a tactical timeout. How can I do that?
> 
> @byoxygen Could you briefly explain what a tactical timeout is? And why to vote?

Hello,
When a team mate is down due to technical problems we may want to use vote for pause game. 
That's can be tactical talk between teammates.
I want to add option to vote for a timeout(pause) in-game.

**Comment by byoxygen** [comment]
I hope you understand what I say @thenorthstar.

**Comment by thenorthstar** [comment]
> > > Hi all. Teams can use call vote in-game to call a tactical timeout. How can I do that?
> > 
> > 
> > @byoxygen Could you briefly explain what a tactical timeout is? And why to vote?
> 
> Hello, When a team mate is down due to technical problems we may want to use vote for pause game. That's can be tactical talk between teammates. I want to add option to vote for a timeout(pause) in-game.

@byoxygen You can use the following code:

```js
var playerList = {};

var room = HBInit({roomName:"TEST",noPlayer:true,public:true,maxPlayers:16});

var tacticalTimeoutLimit = 5;
var playerLeft = false;
var voteCommand = "p";

var redAskedForPause = [];
var blueAskedForPause = [];

var teamAskedForPause = [redAskedForPause,blueAskedForPause];
var teams = ["Red","Blue"];

var gamePauseState = false;

room.onGamePause = function(byPlayer){
    gamePauseState = !gamePauseState;
}

room.onGameStart = function(byPlayer){
    redAskedForPause = [];
    blueAskedForPause = [];
}

room.onGameStop = function(byPlayer){
    redAskedForPause = [];
    blueAskedForPause = [];
}

room.onGameUnpause = function(byPlayer){
    gamePauseState = !gamePauseState;
}

room.onPlayerChat = function (player, message) {
    if (message.toLowerCase() == voteCommand) {
        if (player.team != 0) {
            if (playerList[player.name].votedForTacticalTimeout == false && teamAskedForPause[player.team - 1].includes(player.name) == false) {
                room.sendAnnouncement(`${player.name} has asked for pause!`, player.id, 0xFFFF00, "bold", 2); //If player is able to use his right, then his message will appear on chat to make others witnessed.
                playerList[player.name].votedForTacticalTimeout = true;
                teamAskedForPause[player.team - 1].push(player.name);
            }
            if(gamePauseState == true){
                room.sendAnnouncement("You cannot use this command during the paused mode!", player.id, 0xFF0000, "bold", 2);
            }
            else {
                room.sendAnnouncement("Your right for asking pauses has expired!", player.id, 0xFF0000, "bold", 2);
                return false;
            }

            for (var t in teamAskedForPause) {
                if (teamAskedForPause[t].length == tacticalTimeoutLimit && gamePauseState == false) {
                    room.pauseGame(true);
                    room.sendAnnouncement(`${teams[t]} has asked for a pause and game paused!`, null, 0xFF0000, "bold", 2);
                    var team = teams[t];
                    setTimeout(function () {
                        room.pauseGame(false);
                        room.sendAnnouncement(`The pause time for ${team} team has been expired!`, null, 0xFFFF00, "bold", 2);
                        redAskedForPause = [];
                        blueAskedForPause = [];
                    }, 15000);
                }
            }
        }
        else{
            room.sendAnnouncement("Spectators cannot ask for a pause!", player.id, 0xFF0000, "bold", 2); //If used in a abusive manner, then administrators can ban the player.
        }
    }
}

room.onPlayerJoin = function(player){
    if(playerList[player.name] == undefined){
	playerList[player.name] = {name: player.name, votedForTacticalTimeout: false};
    }
}
```
Edit: Update at **48:26**
Edit: Game pause state check added at **58:64**
Output: https://thehax.pl/forum/powtorki.php?nagranie=77f29155fad2cc340873e9d5cf41bd42

**Comment by byoxygen** [comment]
Thanks @thenorthstar. Well, what conditions are required to pause?
Maybe related to [ ] because 5 is not?

**Comment by thenorthstar** [comment]
> Thanks @thenorthstar. Well, what conditions are required to pause? Maybe related to [ ] because 5 is not?

@byoxygen Here, the condition is that if 5 different people from the same team asks for a pause. You can change it of course.

**Comment by byoxygen** [comment]
> > Thanks @thenorthstar. Well, what conditions are required to pause? Maybe related to [ ] because 5 is not?
> 
> @byoxygen Here, the condition is that if 5 different people from the same team asks for a pause. You can change it of course.

@thenorthstar, yes but when given condition game isn't paused.

**Comment by thenorthstar** [comment]
> > > Thanks @thenorthstar. Well, what conditions are required to pause? Maybe related to [ ] because 5 is not?
> > 
> > 
> > @byoxygen Here, the condition is that if 5 different people from the same team asks for a pause. You can change it of course.
> 
> @thenorthstar, yes but when given condition game isn't paused.

@byoxygen Now is paused, you can try yourself.

**Comment by byoxygen** [comment]
> > > > Thanks @thenorthstar. Well, what conditions are required to pause? Maybe related to [ ] because 5 is not?
> > > 
> > > 
> > > @byoxygen Here, the condition is that if 5 different people from the same team asks for a pause. You can change it of course.
> > 
> > 
> > @thenorthstar, yes but when given condition game isn't paused.
> 
> @byoxygen Now is paused, you can try yourself.

@thenorthstar UPDATE: This issue has now been resolved. Thank you for your support.

**Comment by thenorthstar** [comment]
> > > > > Thanks @thenorthstar. Well, what conditions are required to pause? Maybe related to [ ] because 5 is not?
> > > > 
> > > > 
> > > > @byoxygen Here, the condition is that if 5 different people from the same team asks for a pause. You can change it of course.
> > > 
> > > 
> > > @thenorthstar, yes but when given condition game isn't paused.
> > 
> > 
> > @byoxygen Now is paused, you can try yourself.
> 
> @thenorthstar UPDATE: This issue has now been resolved. Thank you for your support.

@byoxygen You're welcome.

**Comment by byoxygen** [comment]
@thenorthstar Hello, I have encountered some bugs. When game is paused using this, ever someone try to send a message to chat becomes a bug.

Output: https://thehax.pl/forum/powtorki.php?nagranie=bc446f1ec2f367351ea6e05561ade1c1

**Comment by thenorthstar** [comment]
> @thenorthstar Hello, I have encountered some bugs. When game is paused using this, ever someone try to send a message to chat becomes a bug.
> 
> Output: https://thehax.pl/forum/powtorki.php?nagranie=bc446f1ec2f367351ea6e05561ade1c1

@byoxygen It's done.

**Comment by Matteussz** [comment]
@thenorthstar Hello, I want to add this system to my bot, but it makes more sense for each player to have 1 vote to use the command in each match, not once a day. I failed in my attempts, can you help?

#1549 I tried to do something by looking here but I had a hard time.

**Comment by byoxygen** [comment]
> > @thenorthstar Hello, I have encountered some bugs. When game is paused using this, ever someone try to send a message to chat becomes a bug.
> > Output: https://thehax.pl/forum/powtorki.php?nagranie=bc446f1ec2f367351ea6e05561ade1c1
> 
> @byoxygen It's done.

Thank you for your prompt action @thenorthstar.

**Comment by thenorthstar** [comment]
> @thenorthstar Hello, I want to add this system to my bot, but it makes more sense for each player to have 1 vote to use the command in each match, not once a day. I failed in my attempts, can you help?
> 
> #1549 I tried to do something by looking here but I had a hard time.

@Matteussz Just what you have to do is the following:

```js
room.onGameStop = function(byPlayer){
    redAskedForPause = [];
    blueAskedForPause = [];

    var players = room.getPlayerList().filter(playerList[p.name].votedForTacticalTimeout == true && teamAskedForPause[p.team-1].includes(p.name) == true);

    players.forEach(p => {
	if(playerList[p.name].votedForTacticalTimeout == true && teamAskedForPause[p.team-1].includes(p.name) == true){
	    var index = teamAskedForPause[p.team-1].indexOf(p.name);
	    if(index !== -1) teamAskedForPause[p.team-1].splice(index,1);
	    playerList[p.name].votedForTacticalTimeout = false;
	}
    });
}
```
Frankly it's not hard to do I think but I don't know.
Output: https://thehax.pl/forum/powtorki.php?nagranie=d3f4ca5b01b94cdf8d08a39365d4aa43

**Comment by Matteussz** [comment]
@thenorthstar Well, I do as you say and here is the result: 
![false](https://user-images.githubusercontent.com/101899380/159311242-cc36cf12-44db-4509-a774-36d165d1c2f1.PNG)

**Comment by thenorthstar** [comment]
> @thenorthstar Well, I do as you say and here is the result: ![false](https://user-images.githubusercontent.com/101899380/159311242-cc36cf12-44db-4509-a774-36d165d1c2f1.PNG)

@Matteussz In what conditions you're getting this result? You have asked **p** with the player **eee** and then the match finished, so tried to ask again and got this result?

**Comment by Matteussz** [comment]
@thenorthstar No, that's the result I got on my first try. I used the direct script without changing anything.

**Comment by thenorthstar** [comment]
> @thenorthstar No, that's the result I got on my first try. I used the direct script without changing anything.

@Matteussz It's weird, it shouldn't have given you such a result. 😒

**Comment by Matteussz** [comment]
@Matteussz It doesn't stop after using the command, it just sends the messages. I don't understand either, but thank you anyway for your help.
