### ISSUE TITLE
Names history

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1594]
Hello,
Is there a way to see all previous display names of players on join?

**Comment by thenorthstar** [comment]
> Hello, Is there a way to see all previous display names of players on join?

@byoxygen You can use the following code:

```js
var playerList = {};
var _playerList = [];

var room = HBInit({roomName:"TEST",noPlayer:true,public:true,maxPlayers:12,password:"123456"});

room.onPlayerJoin = function(player){
    var players = room.getPlayerList();

    if(playerList[player.name] == undefined){
	playerList[player.name] = {name: player.name, auth: player.auth, conn: player.conn};
    }
    _playerList.push(playerList[player.name]);

    var set = _playerList.filter(x => playerList[x.name].auth == player.auth || playerList[x.name].conn == player.conn);

    room.sendAnnouncement(`Hello ${player.name}. The list of your old names is the following:\n${set.map(s => (1+set.indexOf(s)) + "-) " + s.name).join('\n')}`,player.id,0xFFFFFF,"normal",0); //Bounded as many as the bound of sendAnnouncement
    /*set.forEach(s => {
	room.sendAnnouncement(`${1+set.indexOf(s)}-) ${s.name}`,player.id,0xFFFFFF,"normal",0); //An alternative way, bounded as many as the player count corresponding with player auth or conn
    });*/
}
```

![image](https://user-images.githubusercontent.com/68077608/158859131-de0bcf15-f4eb-4709-a718-0d23392a3421.png)

**Comment by byoxygen** [comment]
Hi @thenorthstar. It doesn't work for me playerList.filter is not a func.

**Comment by byoxygen** [comment]
Hi @thenorthstar. After you've updated that's just keeping recent name.

**Comment by thenorthstar** [comment]
> Hi @thenorthstar. It doesn't work for me playerList.filter is not a func.

@byoxygen Yes, it's working now as you see on the first comment.

**Comment by byoxygen** [comment]
> > Hi @thenorthstar. It doesn't work for me playerList.filter is not a func.
> 
> @byoxygen Yes, it's working now as you see on the first comment.

It's just exactly what I wanted, thank you @thenorthstar.

**Comment by thenorthstar** [comment]
> > > Hi @thenorthstar. It doesn't work for me playerList.filter is not a func.
> > 
> > 
> > @byoxygen Yes, it's working now as you see on the first comment.
> 
> It's just exactly what I wanted, thank you @thenorthstar.

@byoxygen You're welcome.
