### ISSUE TITLE
Password enter room, [bot]

### ISSUE THREAD

**Issue by scriptspi** [haxball/haxball-issues#1595]
what is the command of this code that puts a password in the room with bot? Sorry but I tried several times and I couldn't, can you help me?

**Comment by scriptspi** [comment]
var room = HBInit({
  roomName: "password in the room",
  playerName: "",
  maxPlayers: 3,
  public: false,
  password = '00',
  token: "",
  noPlayer: true
});

i try this but no working

**Comment by guguxh** [comment]
u don't use = to append value in key. Use password: ""

**Comment by scriptspi** [comment]
thank so much, its work now using
  password: '00',
  you are the best

**Comment by ghost** [comment]
> 
You can use the following code:

```fix 
var room = HBInit({
roomName: "password in the room",
playerName: "",
maxPlayers: 3,
public: false,
noPlayer: true
});

room.setPassword("password");

room.onPlayerChat = function(player,message) {
if (message == "!setpass" && player.admin) { //password set
room.setPassword(null);
}
}
```

**Comment by scriptspi** [comment]
Thanks

**Comment by ghost** [comment]
> 

You're welcome.
