### ISSUE TITLE
character limit

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1598]
I want to block long messages. For example, players can't send messages longer than 10 characters. (But admins can)

I need this code. Can you help me?

**Comment by guguxh** [comment]
let limitChar = 10;

room.onPlayerChat = (player, message) => {
  if (message.length > limitChar && !player.admin) return false;
}

**Comment by mydestiny185** [comment]
Thanks but
How do I get users to receive a warning message when they send messages longer than 10 characters?

**Comment by ghost** [comment]
> let limitChar = 10;
> 
> room.onPlayerChat = (player, message) => { if (message.length > limitChar && !player.admin) return false; }

@guguxh 

Thanks but
How do I get players to receive a warning message when they send messages longer than 10 characters?

**Comment by thenorthstar** [comment]
> > let limitChar = 10;
> > room.onPlayerChat = (player, message) => { if (message.length > limitChar && !player.admin) return false; }
> 
> @guguxh
> 
> Thanks but How do I get players to receive a warning message when they send messages longer than 10 characters?

@mydestiny185 You can use the following code:

```js
var limit = 10;

room.onPlayerChat = function(player,message){
    if(message.length > limit && player.admin == false){
	room.sendAnnouncement(`Your message length must be equal or less than ${limit} (${message})`,player.id,0xFFFF00,"bold",2);
	return false;
    }
}
```

**Comment by ghost** [comment]
> > > let limitChar = 10;
> > > room.onPlayerChat = (player, message) => { if (message.length > limitChar && !player.admin) return false; }
> > 
> > 
> > @guguxh
> > Thanks but How do I get players to receive a warning message when they send messages longer than 10 characters?
> 
> @mydestiny185 You can use the following code:
> 
> ```js
> var limit = 10;
> 
> room.onPlayerChat = function(player,message){
>     if(message.length > limit && player.admin == false){
> 	room.sendAnnouncement(`Your message length must be equal or less than ${limit} (${message})`,player.id,0xFFFF00,"bold",2);
> 	return false;
>     }
> }
> ```

@thenorthstar  Thank you, this is exactly what i wanted

**Comment by thenorthstar** [comment]
> > > > let limitChar = 10;
> > > > room.onPlayerChat = (player, message) => { if (message.length > limitChar && !player.admin) return false; }
> > > 
> > > 
> > > @guguxh
> > > Thanks but How do I get players to receive a warning message when they send messages longer than 10 characters?
> > 
> > 
> > @mydestiny185 You can use the following code:
> > ```js
> > var limit = 10;
> > 
> > room.onPlayerChat = function(player,message){
> >     if(message.length > limit && player.admin == false){
> > 	room.sendAnnouncement(`Your message length must be equal or less than ${limit} (${message})`,player.id,0xFFFF00,"bold",2);
> > 	return false;
> >     }
> > }
> > ```
> 
> @thenorthstar Thank you, this is exactly what i wanted

@mydestiny185 You're welcome.
