### ISSUE TITLE
Who has won in the room most?

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1602]
Hi all. 

I want to see total wins for R and B.

**Comment by ghost** [comment]
@byoxygen You can use the following the code:

```
var red = 0;
var blue = 0;
var teamsMatchWins = ["!teamsmatchwins"];

room.onTeamVictory = function(scores) {
if (scores.red > scores.blue) {
red += 1;
}
if (scores.blue > scores.red) {
blue += 1;
}
}

room.onPlayerChat = function(player,message) {
if (message == teamsMatchWins) {
room.sendAnnouncement("Red wins: " + red, player.id);
room.sendAnnouncement("Blue wins: " + blue, player.id);
return false;
}
}
```

**Comment by byoxygen** [comment]
Thank you @developmentstar.

**Comment by mtkcnl** [comment]
> @byoxygen You can use the following the code:
> 
> ```
> var red = 0;
> var blue = 0;
> var teamsMatchWins = ["!teamsmatchwins"];
> 
> room.onTeamVictory = function(scores) {
> if (scores.red > scores.blue) {
> red += 1;
> }
> if (scores.blue > scores.red) {
> blue += 1;
> }
> }
> 
> room.onPlayerChat = function(player,message) {
> if (message == teamsMatchWins) {
> room.sendAnnouncement("Red wins: " + red, player.id);
> room.sendAnnouncement("Blue wins: " + blue, player.id);
> return false;
> }
> }
> ```

Are you sure that this code will work? 
> message == teamsMatchWins

this part of your code is wrong.

> teamsMatchWins.includes(message)

it should be like as above

**Comment by ghost** [comment]
> 



> > @byoxygen You can use the following the code:
> > ```
> > var red = 0;
> > var blue = 0;
> > var teamsMatchWins = ["!teamsmatchwins"];
> > 
> > room.onTeamVictory = function(scores) {
> > if (scores.red > scores.blue) {
> > red += 1;
> > }
> > if (scores.blue > scores.red) {
> > blue += 1;
> > }
> > }
> > 
> > room.onPlayerChat = function(player,message) {
> > if (message == teamsMatchWins) {
> > room.sendAnnouncement("Red wins: " + red, player.id);
> > room.sendAnnouncement("Blue wins: " + blue, player.id);
> > return false;
> > }
> > }
> > ```
> 
> Are you sure that this code will work?
> 
> > message == teamsMatchWins
> 
> this part of your code is wrong.
> 
> > teamsMatchWins.includes(message)
> 
> it should be like as above

@0x532e Yes, I tested it myself.

**Comment by byoxygen** [comment]
@developmentstar Can we keep it on localStorage?

**Comment by mtkcnl** [comment]
> > 
> 
> > > @byoxygen You can use the following the code:
> > > ```
> > > var red = 0;
> > > var blue = 0;
> > > var teamsMatchWins = ["!teamsmatchwins"];
> > > 
> > > room.onTeamVictory = function(scores) {
> > > if (scores.red > scores.blue) {
> > > red += 1;
> > > }
> > > if (scores.blue > scores.red) {
> > > blue += 1;
> > > }
> > > }
> > > 
> > > room.onPlayerChat = function(player,message) {
> > > if (message == teamsMatchWins) {
> > > room.sendAnnouncement("Red wins: " + red, player.id);
> > > room.sendAnnouncement("Blue wins: " + blue, player.id);
> > > return false;
> > > }
> > > }
> > > ```
> > 
> > 
> > Are you sure that this code will work?
> > > message == teamsMatchWins
> > 
> > 
> > this part of your code is wrong.
> > > teamsMatchWins.includes(message)
> > 
> > 
> > it should be like as above
> 
> @0x532e Yes, I tested it myself.

Wow, it's working :D. But, if a user wants to use multiple string for a command, it won't work. Also, the better way to check a value in array is using includes() method. 
For example:
```js
"!teamsmatchwins" == ["!teamsmatchwins", "!asdada"] 
// Returns false
["!teamsmatchwins", "!asdada"].includes("!teamsmatchwins")
// Returns true.
```

**Comment by ghost** [comment]
> 

Hmmmm, yes it can be used in this method and is healthier than what I did. @byoxygen you can also use it if you want.

**Comment by thenorthstar** [comment]
> Hi all.
> 
> I want to see total wins for R and B.

@byoxygen You can use the following code:

```js
var scoresObject = {"red": 0, "blue": 0};
var teamsObject = ["red","blue"]
var command = "!wins";
var isRoomSet = false;

var colors = {
    Info: 0x00FFFF,
    Team: [0xE56E56,0x5689E5]
};

var fonts = {
    Info: "normal",
    Team: ["normal","normal"]
};

var sounds = {
    Info: 1,
    Team: [1,1]
};

var room = HBInit({roomName: "TEST", noPlayer:true, public:true, maxPlayers:12});

room.onPlayerChat = function(player,message){
    if(message.toLowerCase() == command){
	var _scoresObject = JSON.parse(localStorage.getItem("wins"));

	room.sendAnnouncement("Total wins for teams below:",player.id,colors.Info,fonts.Info,sounds.Info);
	teamsObject.forEach(t => {
	    room.sendAnnouncement(`${t}: ${_scoresObject[t]} wins`,player.id,colors.Team[teamsObject.indexOf(t)],fonts.Team[teamsObject.indexOf(t)],sounds.Team[teamsObject.indexOf(t)]);
	});
	return false;
    }
}

room.onRoomLink = function(url){
    if(isRoomSet == false){
	if(localStorage.getItem("wins") == null){
	    localStorage.setItem("wins",JSON.stringify(scoresObject));
	    isRoomSet = true;
	}
    }
}

room.onTeamVictory = function(scores){
    scores.red > scores.blue ? scoresObject.red++ : scoresObject.blue++;
    localStorage.setItem("wins",JSON.stringify(scoresObject));
}
```
Output: https://thehax.pl/forum/powtorki.php?nagranie=ed3182404f6b8e8043c70ae41c3de1fb

**Comment by developmentstar** [comment]
> @developmentstar Can we keep it on localStorage?

@byoxygen That is your homework. If you can't, write again and we'll try to help. 👍

**Comment by thenorthstar** [comment]
> > @developmentstar Can we keep it on localStorage?
> 
> @byoxygen That is your homework. If you can't, write again and we'll try to help. 👍

@developmentstar He doesn't must to do it, it's already done above. 😒

**Comment by ghost** [comment]
> > > @developmentstar Can we keep it on localStorage?
> > 
> > 
> > @byoxygen That is your homework. If you can't, write again and we'll try to help. 👍
> 
> @developmentstar He doesn't must to do it, it's already done above. 😒

@thenorthstar Sorry, I didn't see it posted already. ☹️

**Comment by byoxygen** [comment]
Many thanks to both of you. That's really nice work @thenorthstar.

**Comment by thenorthstar** [comment]
> Many thanks to both of you. That's really nice work @thenorthstar.

@byoxygen You're welcome.
