### ISSUE TITLE
ID

### ISSUE THREAD

**Issue by Matteussz** [haxball/haxball-issues#1604]
![resim_2022-03-30_015552](https://user-images.githubusercontent.com/101899380/160719919-2d71e64e-79c1-428a-a531-8edaa9c6d5e3.png)
This is how my id was displayed at the beginning of my nickname in a room I saw. How can i do that?

**Comment by guguxh** [comment]
What room is this?

**Comment by thenorthstar** [comment]
> What room is this?

@guguxh This room.

![image](https://user-images.githubusercontent.com/68077608/160797618-42e48fb4-2679-4353-86dc-62b5b839d9b4.png)

> This is how my id was displayed at the beginning of my nickname in a room I saw. How can i do that?

@Matteussz You should read and edit the obfuscated code of HH API.
