### ISSUE TITLE
Emoji ban

### ISSUE THREAD

**Issue by truekick** [haxball/haxball-issues#1607]
I want the person with the emoji on their nick to be kicked out when they try to enter the room. How can I do it?

**Comment by guguxh** [comment]
Only changing the Headless API.

**Comment by byoxygen** [comment]
@guguxh Can you share one changed version to give an opinion and how should we define it?

**Comment by guguxh** [comment]
> @guguxh Can you share one changed version to give an opinion and how should we define it?

I don't have the code and don't know how to do

**Comment by ghost** [comment]
This doesn't requires changing Headless API client etc.

Just get player.name in onPlayerJoin and then A-Z & 1-9 filter check, if player.name has something else than that filter simply kick.

**Comment by truekick** [comment]
@ocbpaper Thank you for your opinion, I was finally able to do it.
