### ISSUE TITLE
Sounds continue after leaving the room [bug]

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#1609]
Hey @basro! I have such a problem about sounds. If I'm trying to join a room and getting kicked instantly after joining when smth with sound is being performed (ball kick or goal), then this sound continues until I close that window. This mostly happen when trying to join headless rooms with slot protection; and rarely happen when leaving rooms in normal manner.

As you see on the image, even though there's no active sound on the window, the sound continues.
![image](https://user-images.githubusercontent.com/68077608/161375597-9f6aa768-53e1-4804-8f22-8171543823ee.png)

Note: Please don't recommend me to turn off the sounds. I'm looking for a permanent solution. Thanks from right now.

**Comment by basro** [comment]
In what way does the sound continue to play? Does it get stuck in a loop?
How often does this happen?

**Comment by thenorthstar** [comment]
> In what way does the sound continue to play? Does it get stuck in a loop? How often does this happen?

@basro It gets stuck in loop, yes. It happens every time when I got kicked from a room on joining if the ball is being kicked or a goal is being scored.
