### ISSUE TITLE
Prediction game

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1610]
Hi guys,

I want earn XP points predicting a match result. Can someone help me with this?

**Comment by thenorthstar** [comment]
> Hi guys,
> 
> I want earn XP points predicting a match result. Can someone help me with this?

@byoxygen Here's simple XP system on the following link: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/XPSystem_v1.js

I wish it would be helpful for you.

Edit: I have found another script with betting system, on GitHub. You can also try it through the script on the following link: https://github.com/Elinous-Electra/another-haxball-bot-script/blob/master/index.js

**Comment by byoxygen** [comment]
@thenorthstar I appreciate your help so much. How to keep names and xp in local?

I also got the following errors when I try to voting. 
```
at Array.chat_bet (<anonymous>:317:43)
at room.onPlayerChat (<anonymous>:513:48)
```

**Comment by thenorthstar** [comment]
> @thenorthstar I appreciate your help so much. How to keep names and xp in local?
> 
> I also got the following errors when I try to voting.
> 
> ```
> at Array.chat_bet (<anonymous>:317:43)
> at room.onPlayerChat (<anonymous>:513:48)
> ```

@byoxygen How did you get this error then? Interestingly I haven't gotten such an error even though creating this code step by step.

Edit: Code updated and a **null** control added, try again please?

**Comment by byoxygen** [comment]
@thenorthstar It's solved, thanks. How to we keep names and xp in local?

**Comment by thenorthstar** [comment]
> @thenorthstar It's solved, thanks. How to we keep names and xp in local?

@byoxygen Data transfer with the localStorage is as follows:

**Set**: localStorage.setItem("playerList",JSON.stringify(playerList))
**Get**: JSON.parse(localStorage.getItem("playerList"))

But don't worry I have done it myself for you for the last time. Further ones will be homework for you anymore. Here's the code: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/XPSystem_v2.js

**Comment by qoksel00** [comment]
> > @thenorthstar It's solved, thanks. How to we keep names and xp in local?
> 
> @byoxygen Data transfer with the localStorage is as follows:
> 
> **Set**: localStorage.setItem("playerList",JSON.stringify(playerList)) **Get**: JSON.parse(localStorage.getItem("playerList"))
> 
> But don't worry I have done it myself for you for the last time. Further ones will be homework for you anymore. Here's the code: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/XPSystem_v2.js
![resim_2022-04-05_152521](https://user-images.githubusercontent.com/72311803/161754370-64a50110-9060-4579-abbb-efe20427d093.png)
Bu Hatayı alıyoruz @thenorthstar

**Comment by thenorthstar** [comment]
> > > @thenorthstar It's solved, thanks. How to we keep names and xp in local?
> > 
> > 
> > @byoxygen Data transfer with the localStorage is as follows:
> > **Set**: localStorage.setItem("playerList",JSON.stringify(playerList)) **Get**: JSON.parse(localStorage.getItem("playerList"))
> > But don't worry I have done it myself for you for the last time. Further ones will be homework for you anymore. Here's the code: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/XPSystem_v2.js
> > ![resim_2022-04-05_152521](https://user-images.githubusercontent.com/72311803/161754370-64a50110-9060-4579-abbb-efe20427d093.png)
> > Bu Hatayı alıyoruz @thenorthstar

@qoksel00 Ben öyle bir hata almıyorum?

**Comment by byoxygen** [comment]
@thenorthstar, can you add xp transfer feature between players? In addition, usage may be restrained for under 0 xp players.

**Comment by thenorthstar** [comment]
> @thenorthstar, can you add xp transfer feature between players? In addition, usage may be restrained for under 0 xp players.

@byoxygen It has been updated on the following code: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/XPSystem_v2.js

**Comment by byoxygen** [comment]
@thenorthstar Hi, 

I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command. 

```
 at Array.chat_xpSending (<anonymous>:494:91)
 at room.onPlayerChat (<anonymous>:638:48)
```

**Comment by qoksel00** [comment]
> I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.

Merhaba @thenorthstar ben bu kodları rs botuna eklemeye çalısıyorum bu hatayı alıyorum
![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161922271-3707db1f-ebc8-4b16-b027-1a2cb872ca29.png)

**Comment by thenorthstar** [comment]
> @thenorthstar Hi,
> 
> I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> 
> ```
>  at Array.chat_xpSending (<anonymous>:494:91)
>  at room.onPlayerChat (<anonymous>:638:48)
> ```

@byoxygen I have updated the code, it's working now.

**Sending:**
![image](https://user-images.githubusercontent.com/68077608/161957665-a517e18c-19ac-45da-84f9-d98c89396687.png)

**Getting:**
![image](https://user-images.githubusercontent.com/68077608/161957736-399f7c39-7729-4bb0-ad6d-0a8724d0d035.png)


> > I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> 
> Merhaba @thenorthstar ben bu kodları rs botuna eklemeye çalısıyorum bu hatayı alıyorum ![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161922271-3707db1f-ebc8-4b16-b027-1a2cb872ca29.png)

@qoksel00 Bir yerleri değiştirmiş ya da bozmuş olabilirsin. Bir diğer ihtimal **localStorage**'ı temizlemiş olabilirsin. Bunları kontrol et, sonra konuşalım tekrar.

**Comment by qoksel00** [comment]
> > @thenorthstar Hi,
> > I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> > ```
> >  at Array.chat_xpSending (<anonymous>:494:91)
> >  at room.onPlayerChat (<anonymous>:638:48)
> > ```
> 
> @byoxygen I have updated the code, it's working now.
> 
> **Sending:** ![image](https://user-images.githubusercontent.com/68077608/161957665-a517e18c-19ac-45da-84f9-d98c89396687.png)
> 
> **Getting:** ![image](https://user-images.githubusercontent.com/68077608/161957736-399f7c39-7729-4bb0-ad6d-0a8724d0d035.png)
> 
> > > I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> > 
> > 
> > Merhaba @thenorthstar ben bu kodları rs botuna eklemeye çalısıyorum bu hatayı alıyorum ![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161922271-3707db1f-ebc8-4b16-b027-1a2cb872ca29.png)
> 
> @qoksel00 Bir yerleri değiştirmiş ya da bozmuş olabilirsin. Bir diğer ihtimal **localStorage**'ı temizlemiş olabilirsin. Bunları kontrol et, sonra konuşalım tekrar.

merhaba en baştan ekledım sizin için biryerde hatamı yaptım diye 
öncelikle ilk eklediğimde aynı bu hatayı alıyorum
![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161968551-f026620e-5abd-4373-bbcd-e0fa4897e976.png)

daha sonra specte boş duran botu yani noplayer kısmını botu specten kaldırınca hata buna dönüşüyor
![resim_2022-04-06_144242](https://user-images.githubusercontent.com/72311803/161968741-5d99737e-45a2-4646-a4d1-6696ce956d3b.png)

**Comment by byoxygen** [comment]
@thenorthstar I am grateful for your forbearance as you've worked through the issue.

**Comment by thenorthstar** [comment]
> > > @thenorthstar Hi,
> > > I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> > > ```
> > >  at Array.chat_xpSending (<anonymous>:494:91)
> > >  at room.onPlayerChat (<anonymous>:638:48)
> > > ```
> > 
> > 
> > @byoxygen I have updated the code, it's working now.
> > **Sending:** ![image](https://user-images.githubusercontent.com/68077608/161957665-a517e18c-19ac-45da-84f9-d98c89396687.png)
> > **Getting:** ![image](https://user-images.githubusercontent.com/68077608/161957736-399f7c39-7729-4bb0-ad6d-0a8724d0d035.png)
> > > > I got the following errors when I try to send xp. Sometimes, i am getting won is not appearing on stats command.
> > > 
> > > 
> > > Merhaba @thenorthstar ben bu kodları rs botuna eklemeye çalısıyorum bu hatayı alıyorum ![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161922271-3707db1f-ebc8-4b16-b027-1a2cb872ca29.png)
> > 
> > 
> > @qoksel00 Bir yerleri değiştirmiş ya da bozmuş olabilirsin. Bir diğer ihtimal **localStorage**'ı temizlemiş olabilirsin. Bunları kontrol et, sonra konuşalım tekrar.
> 
> merhaba en baştan ekledım sizin için biryerde hatamı yaptım diye öncelikle ilk eklediğimde aynı bu hatayı alıyorum ![161754370-64a50110-9060-4579-abbb-efe20427d093](https://user-images.githubusercontent.com/72311803/161968551-f026620e-5abd-4373-bbcd-e0fa4897e976.png)
> 
> daha sonra specte boş duran botu yani noplayer kısmını botu specten kaldırınca hata buna dönüşüyor ![resim_2022-04-06_144242](https://user-images.githubusercontent.com/72311803/161968741-5d99737e-45a2-4646-a4d1-6696ce956d3b.png)

@qoksel00 Resimlerden hataları nerelerde aldığını anlayabiliyorum. O konuda sorun yok da ilk attığın hatayı ben hiçbir şekilde almadım. Çok büyük ihtimalle sen **noPlayer: true** olayını kullanmadığın için alıyorsun o hatayı. İkinci hatayı neden aldığını ise henüz çözemedim ama ilki için iki çözüm var:

- **room.getPlayerList()** kullandığın her yeri **room.getPlayerList().filter(p => p.id != 0)** olarak değiştirmek; ya da
- **room.onRoomLink** event handler'ının içerisine 0 ID'li oyuncunun (yani spectators'taki bot arkadaşımızın) bilgilerini şu şekilde eklemek:

```js
var isRoomSet = false;

room.onRoomLink = function(url){
    if(isRoomSet == false){
        playerList["Host"] = { name: "Host", id: 0, auth: "Auth, conn: "Conn", xp: 0, xpMultiplier: 1, bet: { red: 0, blue: 0 }, hasBet: false, canSendXP: true }; //Auth ve Conn yazılı yerlere odayı kuran kişinin bilgileri geliyor. Name yerine de oda kurulduğunda gelen botun adı gelecek.
        isRoomSet = true;
    }
}
```

> @thenorthstar I am grateful for your forbearance as you've worked through the issue.

@byoxygen You're welcome. It's a pleasure for me.👍

**Comment by byoxygen** [comment]
@thenorthstar Hi again, 
Ive managed to put elsewhere without showing error code but xp values don't changing even using console. 
I always get session is unavailable message with multiple players.

**Comment by thenorthstar** [comment]
> @thenorthstar Hi again, Ive managed to put elsewhere without showing error code but xp values don't changing even using console. I always get session is unavailable message with multiple players.

@byoxygen Make sure if **roomObject.xpSessionFeatureActive** is set to **true** and check the player amount in both for the red and blue teams. At least one player must be in both of the red and blue teams.

**Comment by byoxygen** [comment]
@thenorthstar, Objects has the same structure as you sent but object is not working as expected when moved to another script.

**Comment by idk123yeah** [comment]
Why are the statistics not saved? If I open the room again, all the xp I collected while playing is lost.

**Comment by thenorthstar** [comment]
> Why are the statistics not saved? If I open the room again, all the xp I collected while playing is lost.

@idk123yeah Using a **localStorage** mechanism you can save the data.

**Comment by idk123yeah** [comment]
> > Why are the statistics not saved? If I open the room again, all the xp I collected while playing is lost.
> 
> [@idk123yeah](https://github.com/idk123yeah) Using a **localStorage** mechanism you can save the data.

Do you have a script with localStorage?
