### ISSUE TITLE
about mute

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1616]
Hey ! I have a code that kicks players when they say bad words. 

But, i want to change it. I want to automatically mute code for 10 minutes when players use bad words.

This is the code I have : 

else if (["somebadwords"].includes(message[0].toLowerCase())) {
		room.kickPlayer(player.id, "DON'T BE RUDE!", false); 
                                    return false;

Who can help me turn this code into the code I want?

**Comment by scriptspi** [comment]
```js
var room = HBInit({
  roomName: "by Ranger#6017",
  maxPlayers: 5,
  public: false,
  token: "none",
  noPlayer: true
});

let colors = {
    red: 0xFA5646,
    orange: 0xFFC12F,
    green: 0x7DFA89,
}

var message;

const bannedwords = ["banned words", "words", "words", "words", "words", "123"] // write bannedwords here
var muteforbannedwords = [] // muteds here
var timebannedwords = 600000; // time for unnmuted players

function endtimebannedwords(player){
	setTimeout(() => {
    var remove = muteforbannedwords.indexOf(message);
    muteforbannedwords.splice(remove)
	room.sendAnnouncement("you've been unnmuted don't talk offenses", player.id, colors.green, "bold", 2);
    }, timebannedwords);
}

room.onPlayerChat = function (player, message) {
	message = message;
	if (bannedwords.includes(message.toLowerCase())) {
		muteforbannedwords.push(player.name)
		room.sendAnnouncement("you are muted, reason: you are tôxic player", player.id, colors.red, "bold")
		endtimebannedwords(player)
		return false;
	}
	if (muteforbannedwords.includes(player.name) == true) {
	room.sendAnnouncement("wait teen minutes to write again.'", player.id, colors.orange, "bold")
	return false;
	}
}
```

**Comment by thenorthstar** [comment]
> Hey ! I have a code that kicks players when they say bad words.
> 
> But, i want to change it. I want to automatically mute code for 10 minutes when players use bad words.
> 
> This is the code I have :
> 
> else if (["somebadwords"].includes(message[0].toLowerCase())) { room.kickPlayer(player.id, "DON'T BE RUDE!", false); return false;
> 
> Who can help me turn this code into the code I want?

@mydestiny185 You can use the following script: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Intermediate/Badwords.js

Output: https://thehax.pl/forum/powtorki.php?nagranie=04ee95eaf89a1d28fa7f03d2feaf6b4b

**Comment by alexvins1** [comment]
@thenorthstar could you send me your discord i would like to talk to you in private

**Comment by scriptspi** [comment]
@thenorthstar :+1:

**Comment by hbenormous** [comment]
para tornar o delay mais fácil de entender, pode ser feito multiplicando
ex:
`2820000` = 47 minutos
`1000 * 60 * 47` = 47 minutos

não fica mais fácil de entender?

**Comment by scriptspi** [comment]
@hbenormous realmente e muito melhor rsrs, eu ate pensei em usar o multiplicador só que não consegui preciso treinar mais.
