### ISSUE TITLE
player points

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1621]
I have fun contests in my room. When someone wins the competition, I want to be able to add a point to the competitor, to be able to change the point of the competitors and display them in the score list. I want the contestants in the room to see who has how many points with a code. ( for example !ptslist )

i hope i could explain

i need this code please help me

**Comment by thenorthstar** [comment]
> I have fun contests in my room. When someone wins the competition, I want to be able to add a point to the competitor, to be able to change the point of the competitors and display them in the score list. I want the contestants in the room to see who has how many points with a code. ( for example !ptslist )
> 
> i hope i could explain
> 
> i need this code please help me

@mydestiny185 Hello bro. I had implemented a script for the following issue: #1627. As I don't have too much time I have followed the same script and done a thing which can meet your needs as well. Here's the script: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/RockPaperScissors_v3.js

I wish it will be helpful for you.
