### ISSUE TITLE
Level system

### ISSUE THREAD

**Issue by Patrycjja** [haxball/haxball-issues#1628]
https://github.com/hbenormous/haxball-headless-help/blob/main/scripts/sistema-de-levels.js

**English:**
Can you help me add local storage to this system and see how many XP I need to jump to the next level when I type !me?

**Português:**

Podes ajudar-me a adicionar armazenamento local a este sistema e ver quantos XP preciso para saltar para o próximo nível quando escrevo !me?

**Comment by hbenormous** [comment]
Pegar:
```js
room.onRoomLink = () => {
	if (localStorage.getItem("player_levels") == null) return;
	else {
		for ( let [ key , value ] of Object.entries(JSON.parse(localStorage["player_levels"]))) PlayerLevel[key] = value;
	}
}
```

Adicionar:
```js
localStorage.setItem("player_levels", JSON.stringify( Object.assign({}, PlayerLevel) ));
```

Ver quantos XP que falta: ( !me )
```js
PlayerLevel[player.name].xp - maxXp
```

**Comment by Patrycjja** [comment]
@hbenormous Obrigado. 🙏
