### ISSUE TITLE
What is wrong with this code?

### ISSUE THREAD

**Issue by agurll** [haxball/haxball-issues#1634]
I want to do a team chat but it fails

var roomConfig = {
	roomName : "Mini",
	playerName : "Bote",
	maxPlayers : 18,
	//password : contrasena_sala,
	public : true,
	noPlayer : true,
	//geo : {"code":"AR", "lat":-35, "lon":-65}
};

var room = HBInit(roomConfig); //permite controlar la sala//
//Spect 0 Rojo 1 Azul 2//

var  redteam  = room.getPlayerList().filter(d => d.team == 1);
var  blueteam  = room.getPlayerList().filter(p => p.team == 2);
var  teamMessageCommand  =  "!t" ;

room.onPlayerChat  =  function  ( player ,  message )  { 
    if  ( message.startsWith( teamMessageCommand ))  { 
        if  ( player.team  ==  1 )  { 
            redteam.forEach ( d  => room.sendAnnouncement ( player.id  +  " 🟥 | "  +  player.name  +  ": "  +  message.substring( 4 ),  k.id,  0x19FFBA ,  "bold",  2) ) ; 
            return  false; 
        } 
        else  if  ( player.team  ==  2 )  { 
            blueteam.forEach ( p  =>   room.sendAnnouncement ( player.id +  " 🟥 | "  +  player. name  +  ": "  +  message.substring ( 4 ),  p.id,  0x19FFBA ,  "bold",  2) ) ; 
            return  false; 
        } 
    } 
}

**Comment by Raamyy** [comment]
I think this `k.id` should be `d.id`
![image](https://user-images.githubusercontent.com/29176293/165199336-d9cd2eb0-a7e9-4c2b-9b10-30c6bd28d29e.png)

Anyways, to get better help please describe what error you face when you try to run your code.

**Comment by agurll** [comment]
When I try to do the command, the message is not displayed, it is as if the send announcement did not work and only the return false would work

**Comment by Raamyy** [comment]
Check your console in the browser, you will find the error in red.

**Comment by agurll** [comment]
I don't get anything

**Comment by agurll** [comment]
![capture](https://user-images.githubusercontent.com/104403227/165200330-e95dcddc-203d-4879-b34b-9cd2c2927483.png)

**Comment by hbenormous** [comment]
```js
let room = HBInit({});

let prefixTeamChatString = "!t ";

room.onPlayerChat = (player, message) => {
	if (message.substr(0, prefixTeamChatString.length) == prefixTeamChatString) {
		room.getPlayerList()
		.filter(callback => callback.team == player.team)
		.forEach(callback => {
			room.sendAnnouncement(`TEAM > ${player.name}: ${message.substr(prefixTeamChatString.length)}`, callback.id, player.team == 1 ? 0xff7b73 : player.team == 0 ? 0xe4ffb6 : 0x38b5ff);
		});
		return false;
	}
}
```

**Comment by agurll** [comment]
Thank you very much, it works
