### ISSUE TITLE
[FEATURE REQUEST] Please implement/add the /store command.

### ISSUE THREAD

**Issue by ishangore** [haxball/haxball-issues#164]
The /store command to store user-made maps in the default map section was highly useful and convenient in my opinion. Just made things smooth. It also aligns with your goal of reaching feature-parity with the Flash version of HaxBall. Please implement this command ASAP! Thanks a lot for your work :)

**Comment by Haxballing** [comment]
Yea we really need this

**Comment by basro** [comment]
The reason why the /store command is not yet implemented is that there's stricter limitations in html5 about storing data locally in the user's computers compared to flash.

There's a possible work-around that could be done but it's fairly complex so it'll take some time.

**Comment by saviola777** [comment]
Would it be simpler to provide a download button to save the current map locally, much like a rec file? Not quite as comfortable as using `/store` maybe, but it should be sufficient.

**Comment by basro** [comment]
Both map downloading and /store command are now implemented
