### ISSUE TITLE
Format map

### ISSUE THREAD

**Issue by rocosttaa** [haxball/haxball-issues#1645]
My host map has `\` before each word (ex: `{\"name\":\"X3\",....`), I made a new map and I need to put this if not the host hangs. Is there a possibility to do this automatically or just manually?

**Comment by thenorthstar** [comment]
> My host map has "" before each word (ex: "{"name":"X3",...."), I made a new map and I need to put this if not the host hangs. Is there a possibility to do this automatically or just manually?

@rocosttaa It's made by **stringifying** the map object. To make it automatically you have to pass two steps:

* **Save** the map on https://haxball-stadium-editor.github.io/
* And then click to **Copy All** in **text mode**.

Or you can **stringify** it by typing **JSON.stringify** in a simple way.

**Comment by rocosttaa** [comment]
> > My host map has "" before each word (ex: "{"name":"X3",...."), I made a new map and I need to put this if not the host hangs. Is there a possibility to do this automatically or just manually?
> 
> @rocosttaa It's made by **stringifying** the map object. To make it automatically you have to pass two steps:
> 
> * **Save** the map on https://haxball-stadium-editor.github.io/
> * And then click to **Copy All** in **text mode**.
> 
> Or you can **stringify** it by typing **JSON.stringify** in a simple way.

I got the question wrong. It has "bars" before it. Ex: `""{\"name\":\"X3\"".`
