### ISSUE TITLE
F1 DRS Mode

### ISSUE THREAD

**Issue by cockerelhub** [haxball/haxball-issues#1649]
Hello everyone! I have an important problem and I need your help. I want DRS enabled after lap 3 in F1 race. This situation must be active with a difference of less than 1 second between you and your opponent. So if our normal speed is 80, it will increase to 85 when DRS is active. Thank you from now

**Comment by cockerelhub** [comment]
``

**Comment by velazquez91196** [comment]
hello, did you manage to implement this functionality?
