### ISSUE TITLE
Haxball Mail

### ISSUE THREAD

**Issue by Peleinho** [haxball/haxball-issues#166]
Hello Basro,

I've sent you an mail 1-2 weeks ago, but still I don't get any answer. I would know you read our mails or if it's useless ^^ 

Peleinho

**Comment by basro** [comment]
Don't open issues for this kind of thing...
I receive a lot of emails and I don't answer all of them, I don't know which one is yours.

**Comment by Peleinho** [comment]
Hi,
Sorry I didn’t know where to post it, by the way, I have some suggestions ( in addition to to mail I already sent) :
In the futur, you culd add the link to the haxball communities with website link and discord and TS3.
Maybe also a tag with Champions League winner and Nacion Cup winner ; which could make this game more competitive for newest players and keep them playing haxball.

Other thing would be a chat like /team to speak only with his own team.

Whatever I see you’re working on haxball html and hope you’ll continue until we reach new players and not let haxball die just slower than it is.
Good night
Peleinho

________________________________

**Comment by rbabcock99** [comment]
Is the email still up? I sent an email and It's an urgent problem.

**Comment by Peleinho** [comment]
Ye ?

________________________________
De : rbabcock99 <notifications@github.com>
Envoyé : Wednesday, March 6, 2019 4:11:44 AM
À : haxball/haxball-issues
Cc : Peleinho; Author
Objet : Re: [haxball/haxball-issues] Haxball Mail (#166)


Is the email still up? I sent an email and It's an urgent problem.
