### ISSUE TITLE
How to get the player id based on the position the player is on a team

### ISSUE THREAD

**Issue by HertzIssue** [haxball/haxball-issues#1664]
Hey,

I would like to know how to obtain the player id from a specific player based on the position in a team they are then store it in a variable. For example I want to know the ID of the player in the first slot of the red team at the end of the game. I'd appreciate it if anyone can help, thanks!

**Comment by guguxh** [comment]
let redTeam = room.getPlayerList().filter(p => p.team == 1);
let blueTeam = room.getPlayerList().filter(p => p.team == 2);

After declaring this two variables you need to update after all time when a player change from team, so you create a function and call inside onPlayerTeamChange. To get the ID you can use blueTeam[0] or redTeam[0], respectively first player of each team in slots.

**Comment by saviola777** [comment]
Or without caching:
```
function getPlayerIdByPositionOnTeam(team, position) {
  return room.getPlayerList().filter(p => p.team === team)[position].id;
}

// get top player of red team
getPlayerIdByPositionOnTeam(1, 0);

// get third player of blue team
getPlayerIdByPositionOnTeam(2, 2);
```

**Comment by HertzIssue** [comment]
You guys are the goats, thanks very much for your assistance I appreciate it.
