### ISSUE TITLE
odadaki !info komutları hakkında yardım

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1671]
Bir odada !info komutunu kullandığımda bilgilerin anlık olarak değil de yavaş ve sıralı şekilde geldiğini gördüm.

Yani bir info komutunda 2 madde var diyelim : 

1) .....
2) ,,,,,
Normalde info yazdığımızda direkt 2 bilgiyi de görürüz fakat benim gördüğüm odada önce 1) .....

sonra basamak basamak 

2) ,,,,,

2. infoyu gösteriyordu. 

Bunu kendi botumda yapmak istiyorum. Kodlarda yardımcı olan var mı? Umarım anlatabilmişimdir.

**Comment by hbenormous** [comment]
> Bir odada !info komutunu kullandığımda bilgilerin anlık olarak değil de yavaş ve sıralı şekilde geldiğini gördüm.
> 
> Yani bir info komutunda 2 madde var diyelim : 
> 
> 1) .....
> 2) ,,,,,
> Normalde info yazdığımızda direkt 2 bilgiyi de görürüz fakat benim gördüğüm odada önce 1) .....
> 
> sonra basamak basamak 
> 
> 2) ,,,,,
> 
> 2. infoyu gösteriyordu. 
> 
> Bunu kendi botumda yapmak istiyorum. Kodlarda yardımcı olan var mı? Umarım anlatabilmişimdir. 
> 

Async await

**Comment by mtkcnl** [comment]
setTimeout fonksiyonu ile yapabilirsin. 
Ornek kullanim:
```javascript
setTimeout(() => {
console.log("Hello")
}, 1E3);
setTimeout(() => {
console.log("World!");
}, 1E3 + 500)
```

**Comment by vaejoviade** [comment]
> setTimeout fonksiyonu ile yapabilirsin. Ornek kullanim:
> 
> ```js
> setTimeout(() => {
> console.log("Hello")
> }, 1E3);
> setTimeout(() => {
> console.log("World!");
> }, 1E3 + 500)
> ```

Benimde afk kalma süresini uzatmam gerekiyor, yardımcı olabilir misiniz ?
