### ISSUE TITLE
ppl counter

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#1677]
When someone enters the room, I want a counter code that indicates how many people are in the room. For example, 
mydestiny joined the room ( 5/22 )  can you give this code? I am very novice at this job. Thanks.

**Comment by Patrycjja** [comment]
`room.sendAnnouncement(`[#${player.id}]${player.name}, joined the room. (` + room.getPlayerList().length + `/22)`)`

**Comment by Patrycjja** [comment]
```room.sendAnnouncement(`[#${player.id}]${player.name}, joined the room. (` + room.getPlayerList().length + `/22)`)```
