### ISSUE TITLE
Help (When the red player kick off)

### ISSUE THREAD

**Issue by Rayit0** [haxball/haxball-issues#1683]
When the red player kick off, change his position, like in the photo.
![image](https://user-images.githubusercontent.com/111201854/184510109-f304d6bb-786a-448f-b2a3-4ad91d6d4935.png)
![image](https://user-images.githubusercontent.com/111201854/184510161-12c65d3a-8ba9-4bcb-9a08-ac7fb516fd9c.png)

**Comment by thenorthstar** [comment]
> When the red player kick off, change his position, like in the photo. ![image](https://user-images.githubusercontent.com/111201854/184510109-f304d6bb-786a-448f-b2a3-4ad91d6d4935.png) ![image](https://user-images.githubusercontent.com/111201854/184510161-12c65d3a-8ba9-4bcb-9a08-ac7fb516fd9c.png)

@Rayit0 You can use the following script: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Intermediate/Player_Teleport_After_KickOff.js

Output: https://thehax.pl/forum/powtorki.php?nagranie=dbd1d947bbe94edb0f46c1b9466ef742

**Comment by Rayit0** [comment]
> > When the red player kick off, change his position, like in the photo. ![image](https://user-images.githubusercontent.com/111201854/184510109-f304d6bb-786a-448f-b2a3-4ad91d6d4935.png) ![image](https://user-images.githubusercontent.com/111201854/184510161-12c65d3a-8ba9-4bcb-9a08-ac7fb516fd9c.png)
> 
> @Rayit0 You can use the following script: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Intermediate/Player_Teleport_After_KickOff.js
> 
> Output: https://thehax.pl/forum/powtorki.php?nagranie=dbd1d947bbe94edb0f46c1b9466ef742
Thanks!
