### ISSUE TITLE
[Headless Code Help] Line segment collision through bounce on game tick

### ISSUE THREAD

**Issue by Skarmunds** [haxball/haxball-issues#1684]
Hi! I'm doing a variety bot with tracking rectangles, points, lines and segments for own collected maps. My approach is general functions for all types - races and eliminations. I would need help or explanation to get this working more efficiently. I have searched and used at least 3 algorithms but in all cases it skips collision 7 out of 10 times, depends if I bounce lucky or go slow speed to finish.

So I'm stuck on this Collision Team Racing finish lines. I track bottom to top first blue line but before that is red line with **bCoef at -3**. If it's not possible, I will then stick to [x, y] coordinates for one direction.
![index](https://user-images.githubusercontent.com/38059263/184774684-6735b6b1-786e-4ef2-b38c-6704ad353b4a.png)
I have put together and tidied example code.

```Javascript
const room = HBInit({noPlayer: true});
const finish = [{"x": -23, "y": -4608}, {"x": 23, "y": -4608}];
const playersFinished = new Set();

function main() {
    const players = room.getPlayerList();
    for (const player of players) {
        if (player.position == null) continue;
        if (playersFinished.has(player.id)) continue;
        const playerDiscProps = room.getPlayerDiscProperties(player.id);
        const distanceToSegment = distanceSegmentToPoint(finish[0], finish[1], playerDiscProps);
        if (distanceToSegment < playerDiscProps.radius + 0.01) {
            room.sendAnnouncement(`${player.name} finished`);
            room.setPlayerAvatar(player.id, `🏁`);
            playersFinished.add(player.id);
        }
    }
}

function distanceSegmentToPoint(lineStart, lineEnd, player) {
    let closestPoint;
    const xDelta = lineEnd.x - lineStart.x;
    const yDelta = lineEnd.y - lineStart.y;

    const u = ((player.x - lineStart.x) * xDelta + (player.y - lineStart.y) * yDelta) / (xDelta * xDelta + yDelta * yDelta);
    if (u < 0) {
        closestPoint = lineStart;
    } else if (u > 1) {
        closestPoint = lineEnd;
    } else {
        closestPoint = {x: lineStart.x + u * xDelta, y: lineStart.y + u * yDelta};
    }

    const dx = closestPoint.x - player.x;
    const dy = closestPoint.y - player.y;
    return Math.sqrt(dx * dx + dy * dy);
}

function setAvatars() {
    return room.getPlayerList().forEach(p => room.setPlayerAvatar(p.id, ''));
}

room.onGameTick = main;
room.onGameStart = setAvatars;
room.onPlayerJoin = (player) => room.setPlayerAdmin(player.id, true);
room.onGameStop = () => playersFinished.clear();
room.onRoomLink = () => fetch('https://corsproxy.io/?https://haxmaps.com/dl/1095').then(res => res.json()).then(data => room.setCustomStadium(JSON.stringify(data)));
```

**Comment by thenorthstar** [comment]
> Hi! I'm doing a variety bot with tracking rectangles, points, lines and segments for own collected maps. My approach is general functions for all types - races and eliminations. I would need help or explanation to get this working more efficiently. I have searched and used at least 3 algorithms but in all cases it skips collision 7 out of 10 times, depends if I bounce lucky or go slow speed to finish.
> 
> So I'm stuck on this Collision Team Racing finish lines. I track bottom to top first blue line but before that is red line with **bCoef at -3**. If it's not possible, I will then stick to [x, y] coordinates for one direction. ![index](https://user-images.githubusercontent.com/38059263/184774684-6735b6b1-786e-4ef2-b38c-6704ad353b4a.png) I have put together and tidied example code.
> 
> ```js
> const room = HBInit({noPlayer: true});
> const finish = [{"x": -23, "y": -4608}, {"x": 23, "y": -4608}];
> const playersFinished = new Set();
> 
> function main() {
>     const players = room.getPlayerList();
>     for (const player of players) {
>         if (player.position == null) continue;
>         if (playersFinished.has(player.id)) continue;
>         const playerDiscProps = room.getPlayerDiscProperties(player.id);
>         const distanceToSegment = distanceSegmentToPoint(finish[0], finish[1], playerDiscProps);
>         if (distanceToSegment < playerDiscProps.radius + 0.01) {
>             room.sendAnnouncement(`${player.name} finished`);
>             room.setPlayerAvatar(player.id, `🏁`);
>             playersFinished.add(player.id);
>         }
>     }
> }
> 
> function distanceSegmentToPoint(lineStart, lineEnd, player) {
>     let closestPoint;
>     const xDelta = lineEnd.x - lineStart.x;
>     const yDelta = lineEnd.y - lineStart.y;
> 
>     const u = ((player.x - lineStart.x) * xDelta + (player.y - lineStart.y) * yDelta) / (xDelta * xDelta + yDelta * yDelta);
>     if (u < 0) {
>         closestPoint = lineStart;
>     } else if (u > 1) {
>         closestPoint = lineEnd;
>     } else {
>         closestPoint = {x: lineStart.x + u * xDelta, y: lineStart.y + u * yDelta};
>     }
> 
>     const dx = closestPoint.x - player.x;
>     const dy = closestPoint.y - player.y;
>     return Math.sqrt(dx * dx + dy * dy);
> }
> 
> function setAvatars() {
>     return room.getPlayerList().forEach(p => room.setPlayerAvatar(p.id, ''));
> }
> 
> room.onGameTick = main;
> room.onGameStart = setAvatars;
> room.onPlayerJoin = (player) => room.setPlayerAdmin(player.id, true);
> room.onGameStop = () => playersFinished.clear();
> room.onRoomLink = () => fetch('https://corsproxy.io/?https://haxmaps.com/dl/1095').then(res => res.json()).then(data => room.setCustomStadium(JSON.stringify(data)));
> ```

@Skarmunds 0.01 is very small distance here. You are trying to catch if player has finished racing, in just a gap whose width is 0.02 units (0.01 from bottom and 0.01 from top of the line). Instead, you can try to widen it with respect to the y-component of player speed.

I had tried what I said in my own F1 bot to print lap times of players and get an accurate result (before it was almost never printing the results and after it was always print results but with some bias).

```js
if (distanceToSegment < playerDiscProps.radius + Math.abs(playerDiscProps.yspeed)) { //Because yspeed could less than zero.
    room.sendAnnouncement(`${player.name} finished`);
    room.setPlayerAvatar(player.id, `🏁`);
    playersFinished.add(player.id);
}
```

**Comment by Skarmunds** [comment]
@thenorthstar Thanks, tested this and seems to do the trick. I'm fine with it.
