### ISSUE TITLE
Bug Found

### ISSUE THREAD

**Issue by Simashax** [haxball/haxball-issues#169]
Hello, today I found this bug on some maps. I believe there are more maps with such issue. It's not only for me, it's the same for other players too. These maps used to work fine. Check it:
https://i.imgur.com/XQaKej3.png
https://i.imgur.com/kYuDIj8.png

Maps being used:
http://haxmaps.com/map/6240
http://haxmaps.com/map/4468

**Comment by awareofdistractions** [comment]
It's because the background type is empty.
`"bg" : { "type" : ""}`

**Comment by basro** [comment]
This will be fixed on the next release.

**Comment by Leo-MapCreator** [comment]
Fucking ProLier that copied my map and made it worse

**Comment by basro** [comment]
This should be fixed now.
