### ISSUE TITLE
is it posibble to record the game and send it to a discord channel

### ISSUE THREAD

**Issue by TweekHaxball** [haxball/haxball-issues#1703]
i can record the game and when i want i can download it with this codes:
`room.onGameStart` = function(){
    room.startRecording();
}`

in PlayerChat:
`else if (["!kayıtdurdur"].includes(message[0].toLowerCase())&& player.admin == true) {
        var data = room.stopRecording();
        downloadBlob(data, `incele.hbr2`, 'application/octet-stream')
        room.startRecording();
        return false;
    } `
 i can record and download like this but i wanna sec this rec to a discord channel
 im using:
` function sendAnnouncementToDiscord(message) {

    var request = new XMLHttpRequest();
    request.open("POST", "https://discord.com/api/webhooks/]WEBHOOK]");

    request.setRequestHeader('Content-type', 'application/json');

    var params = {
        avatar_url: '',
        username: 'Bildirim',
        content: message
    };

    request.send(JSON.stringify(params));
}` this to send messages to discord but i dont know how can i send the rec to discord.

**Comment by 09x2019** [comment]
> i can record the game and when i want i can download it with this codes: `room.onGameStart` = function(){ room.startRecording(); }`
> 
> in PlayerChat: `else if (["!kayıtdurdur"].includes(message[0].toLowerCase())&& player.admin == true) { var data = room.stopRecording(); downloadBlob(data, `incele.hbr2`, 'application/octet-stream') room.startRecording(); return false; } ` i can record and download like this but i wanna sec this rec to a discord channel im using: ` function sendAnnouncementToDiscord(message) {
> 
> ```
> var request = new XMLHttpRequest();
> request.open("POST", "https://discord.com/api/webhooks/]WEBHOOK]");
> 
> request.setRequestHeader('Content-type', 'application/json');
> 
> var params = {
>     avatar_url: '',
>     username: 'Bildirim',
>     content: message
> };
> 
> request.send(JSON.stringify(params));
> ```
> 
> }` this to send messages to discord but i dont know how can i send the rec to discord.

#1631 This place will work for you. All you have to do is fill in the webhookURL part.
