### ISSUE TITLE
dont letting player to join a room 2 times 

### ISSUE THREAD

**Issue by TweekHaxball** [haxball/haxball-issues#1704]
let connections = [];
`room.onPlayerJoin = function(player){
     let auth = connections.find(a => a[1] === player.auth);
    
    if (auth) {
        room.kickPlayer(player.id,"IP Başına 1 Oyuncu ❌",false);
    }else {
            connections.push([player.id, player.auth]);
        }
    }
}`
`room.onPlayerLeave = function(player){
     connections = connections.filter(a => a[0] !== player.id);
}`
with this code players cant join 2 times at the same time but sometimes it blocks new players

**Comment by 09x2019** [comment]
> let connections = []; `room.onPlayerJoin = function(player){ let auth = connections.find(a => a[1] === player.auth);
> 
> ```
> if (auth) {
>     room.kickPlayer(player.id,"IP Başına 1 Oyuncu ❌",false);
> }else {
>         connections.push([player.id, player.auth]);
>     }
> }
> ```
> 
> }` `room.onPlayerLeave = function(player){ connections = connections.filter(a => a[0] !== player.id); }` with this code players cant join 2 times at the same time but sometimes it blocks new players

You can use the following the code.

```js
var PlayerAuth = {};

room.onPlayerJoin = function(player) {

for (var i in PlayerAuth) {
	if(PlayerAuth[i].auth == player.auth)
		room.kickPlayer(PlayerAuth[i].id, "Tab detection is blocked. Don't! Your tab in the room: " + player.name, false);
}

PlayerAuth[player.auth] = player;

}
```

**Comment by thenorthstar** [comment]
> let connections = []; `room.onPlayerJoin = function(player){ let auth = connections.find(a => a[1] === player.auth);
> 
> ```
> if (auth) {
>     room.kickPlayer(player.id,"IP Başına 1 Oyuncu ❌",false);
> }else {
>         connections.push([player.id, player.auth]);
>     }
> }
> ```
> 
> }` `room.onPlayerLeave = function(player){ connections = connections.filter(a => a[0] !== player.id); }` with this code players cant join 2 times at the same time but sometimes it blocks new players

@TweekHaxball Or you can use this one: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/DuplicatedConnections.js

Btw, instead of using **isInTheRoom** checker you can also use a control based on **room.getPlayerList()**.
