### ISSUE TITLE
is it possible to host more than 2 rooms on one device

### ISSUE THREAD

**Issue by TweekHaxball** [haxball/haxball-issues#1708]
i wanna host more than 2 rooms, how can i?

**Comment by thenorthstar** [comment]
> i wanna host more than 2 rooms, how can i?

@TweekHaxball Check your DM on discord. I have sent a message about it.

For those who are interested in this issue: I won't share a public solution through here as it's potentially able to be abused by malevolent users.

**Comment by Joao-Vitaca** [comment]
> > eu quero hospedar mais de 2 quartos, como posso?
> 
> @TweekHaxballVerifique seu DM na discórdia. Enviei uma mensagem sobre isso.
> 
> Para aqueles que estão interessados ​​neste problema: não compartilharei uma solução pública por aqui, pois ela pode ser abusada por usuários malévolos.

help, what is your discord?
