### ISSUE TITLE
Changing Discs

### ISSUE THREAD

**Issue by byoxygen** [haxball/haxball-issues#1711]
Hi guys,

I want to change in-game discs according to goal status (see image below).

I am being able to do that event for just one disc but not many discs. 

![ss-penalty](https://user-images.githubusercontent.com/92115233/188373597-6fe6a72d-4e47-4451-a18b-46f70f653e00.jpg)

**Comment by byoxygen** [comment]
How can i do it for many disc?

**Comment by 09x2019** [comment]
> Hi guys,
> 
> I want to change in-game discs according to goal status (see image below).
> 
> I am being able to do that event for just one disc but not many discs.
> 
> ![ss-penalty](https://user-images.githubusercontent.com/92115233/188373597-6fe6a72d-4e47-4451-a18b-46f70f653e00.jpg)

Have you tried defining and pulling a **trait** to each **disc**?

**Comment by byoxygen** [comment]
> 

Yes but only first disc works.

**Comment by byoxygen** [comment]
> > Hi guys,
> > I want to change in-game discs according to goal status (see image below).
> > I am being able to do that event for just one disc but not many discs.
> > ![ss-penalty](https://user-images.githubusercontent.com/92115233/188373597-6fe6a72d-4e47-4451-a18b-46f70f653e00.jpg)
> 
> Have you tried defining and pulling a **trait** to each **disc**?

Yes but only first disc works.

**Comment by thenorthstar** [comment]
Use **.filter()** function instead of **.find()** or **.findIndex()**.

**Comment by byoxygen** [comment]
Many thanks @thenorthstar
