### ISSUE TITLE
Oto Bot Yapmak.

### ISSUE THREAD

**Issue by TweekHaxball** [haxball/haxball-issues#1715]
oto bot yapmak istiyorum, mantık olarak aklımda bişeyler var. hatta bişeylerde denedim fakat bu işlerin böyle olduğunuda sanmıyorum. ayrıca denediğim şeyde oyuncuları dağıtıyor ama map açmıyor.
`
var players = room.getPlayerList().filter((player) => player.id != 0);
var alıştırma = false;
var koyulacak = 1;
var specList = room.getPlayerList().filter((player) => player.team == 0);

function getRandomInt(max) {
	return Math.floor(Math.random() * max);
}

function takımDengele(){
	var uzunluk = players.length;
	if(uzunluk == 0 ){
		room.stopGame();
		room.setCustomStadium(hazırlık);
		room.startGame();
		alıştırma = true;
	}else if(uzunluk == 1){
		if(alıştırma = true){
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id, koyulacak);
		}else {
			room.stopGame();
			room.setCustomStadium(hazırlık);
			room.startGame();
			alıştırma = true
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id,koyulacak);
		}
	}else if(uzunluk = 2){
		if(alıştırma = true){
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id, koyulacak);
		}else {
			room.stopGame();
			room.setCustomStadium(hazırlık);
			room.startGame();
			alıştırma = true
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id,koyulacak);
		}
	}else if(uzunluk = 3){
		if(alıştırma = true){
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id, koyulacak);
		}else {
			room.stopGame();
			room.setCustomStadium(hazırlık);
			room.startGame();
			alıştırma = true
			koyulacak = getRandomInt(3);
			if(koyulacak == 0){koyulacak = 1;}
			room.setPlayerTeam(specList[0].id,koyulacak);
		}
	}else if(uzunluk = 4){
		if(alıştırma = true){
			room.stopGame();
			room.setCustomStadium(dizilim);
			room.startGame();
			room.sendAnnoucement("Yerlerinizi alın 20 Saniye Sonra Oyun Başlayacak",null,0xffffff,'bold',2);
			setInterval(function () {room.stopGame();room.setCustomStadium(rs);room.startGame();}, 20*1000);
		}
	}

}`

**Comment by kox93** [comment]
```
var players = room.getPlayerList().filter((player) => player.id != 0);
var alıştırma = false;
var koyulacak = 1;
var specList = room.getPlayerList().filter((player) => player.team == 0);

function getRandomInt(max) {
return Math.floor(Math.random() * max);
}

function takımDengele(){
var uzunluk = players.length;
if(uzunluk == 0 ){
room.stopGame();
room.setCustomStadium(hazırlık);
room.startGame();
alıştırma = true;
}else if(uzunluk == 1){
if(alıştırma = true){
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id, koyulacak);
}else {
room.stopGame();
room.setCustomStadium(hazırlık);
room.startGame();
alıştırma = true
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id,koyulacak);
}
}else if(uzunluk = 2){
if(alıştırma = true){
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id, koyulacak);
}else {
room.stopGame();
room.setCustomStadium(hazırlık);
room.startGame();
alıştırma = true
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id,koyulacak);
}
}else if(uzunluk = 3){
if(alıştırma = true){
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id, koyulacak);
}else {
room.stopGame();
room.setCustomStadium(hazırlık);
room.startGame();
alıştırma = true
koyulacak = getRandomInt(3);
if(koyulacak == 0){koyulacak = 1;}
room.setPlayerTeam(specList[0].id,koyulacak);
}
}else if(uzunluk = 4){
if(alıştırma = true){
room.stopGame();
room.setCustomStadium(dizilim);
room.startGame();
room.sendAnnoucement("Yerlerinizi alın 20 Saniye Sonra Oyun Başlayacak",null,0xffffff,'bold',2);
setInterval(function () {room.stopGame();room.setCustomStadium(rs);room.startGame();}, 20*1000);
}
}

}
```

bu şekilde atarsan daha verimli ve düzgün olur

**Comment by thenorthstar** [comment]
> oto bot yapmak istiyorum, mantık olarak aklımda bişeyler var. hatta bişeylerde denedim fakat bu işlerin böyle olduğunuda sanmıyorum. ayrıca denediğim şeyde oyuncuları dağıtıyor ama map açmıyor. ` var players = room.getPlayerList().filter((player) => player.id != 0); var alıştırma = false; var koyulacak = 1; var specList = room.getPlayerList().filter((player) => player.team == 0);
> 
> function getRandomInt(max) { return Math.floor(Math.random() * max); }
> 
> function takımDengele(){ var uzunluk = players.length; if(uzunluk == 0 ){ room.stopGame(); room.setCustomStadium(hazırlık); room.startGame(); alıştırma = true; }else if(uzunluk == 1){ if(alıştırma = true){ koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id, koyulacak); }else { room.stopGame(); room.setCustomStadium(hazırlık); room.startGame(); alıştırma = true koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id,koyulacak); } }else if(uzunluk = 2){ if(alıştırma = true){ koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id, koyulacak); }else { room.stopGame(); room.setCustomStadium(hazırlık); room.startGame(); alıştırma = true koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id,koyulacak); } }else if(uzunluk = 3){ if(alıştırma = true){ koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id, koyulacak); }else { room.stopGame(); room.setCustomStadium(hazırlık); room.startGame(); alıştırma = true koyulacak = getRandomInt(3); if(koyulacak == 0){koyulacak = 1;} room.setPlayerTeam(specList[0].id,koyulacak); } }else if(uzunluk = 4){ if(alıştırma = true){ room.stopGame(); room.setCustomStadium(dizilim); room.startGame(); room.sendAnnoucement("Yerlerinizi alın 20 Saniye Sonra Oyun Başlayacak",null,0xffffff,'bold',2); setInterval(function () {room.stopGame();room.setCustomStadium(rs);room.startGame();}, 20*1000); } }
> 
> }`

@TweekHaxball Kodunu paylaşmadan önce bir kez daha kontrol etmeni öneririm:

![image](https://user-images.githubusercontent.com/68077608/189075041-70442d3e-d6e8-4fbc-a99a-9313c8fa81be.png)

Resimdeki sarı vurgulu yerlere baktığında ne demek istediğimi anlayacaksın.
