### ISSUE TITLE
Transparent Ball

### ISSUE THREAD

**Issue by awareofdistractions** [haxball/haxball-issues#172]
Players don't see transparent ball color (#FFFFFFFF), they see white instead.
If it is any other color like green/blue etc they see it.
The only person who can see transparent is host who uploaded map.
If other person uploaded map with transparent color then host also see it as white.

**Comment by Simashax** [comment]
+
Same in other maps:
https://i.imgur.com/EnbHQhV.png

**Comment by basro** [comment]
This should be fixed now.
