### ISSUE TITLE
Admin ekleme

### ISSUE THREAD

**Issue by kayatas** [haxball/haxball-issues#1723]
beyler sınırsız admin nasıl eklenir açıklayacak var mı.  setPlayerAdmin (1,true) yapınca oyuna girip çıkıcanca gidiyor adminlik

**Comment by 09x2019** [comment]
> beyler sınırsız admin nasıl eklenir açıklayacak var mı. setPlayerAdmin (1,true) yapınca oyuna girip çıkıcanca gidiyor adminlik

Aşağıdaki kodu kullanabilirsiniz:
https://github.com/09x2019/Haxball_Example_Scripts/blob/main/Codes/CmdSetPlayerAdmin.js

Kodun detaylarına gelirsek **adminPassword** değişkeninin içine yazdığınız şey admin şifreniz oluyor ve onu chate yazdığınız zaman otomatik admin oluyorsunuz. Odaya girdiğinizde otomatik olarak siz birşey yazmadan vermesini istiyorsanız eğer **player.auth** verinizi çekerek bu veri üzerine adminlik tanımlayabilirsiniz.

**Comment by kayatas** [comment]
> > beyler sınırsız admin nasıl eklenir açıklayacak var mı. setPlayerAdmin (1,true) yapınca oyuna girip çıkıcanca gidiyor adminlik
> 
> Aşağıdaki kodu kullanabilirsiniz: https://github.com/09x2019/Haxball_Example_Scripts/blob/main/Codes/CmdSetPlayerAdmin.js
> 
> Kodun detaylarına gelirsek **adminPassword** değişkeninin içine yazdığınız şey admin şifreniz oluyor ve onu chate yazdığınız zaman otomatik admin oluyorsunuz. Odaya girdiğinizde otomatik olarak siz birşey yazmadan vermesini istiyorsanız eğer **player.auth** verinizi çekerek bu veri üzerine adminlik tanımlayabilirsiniz.

sağol knk adamsın player auth nasıl oluyor onuda anlatırsan süper olur

**Comment by 09x2019** [comment]
> > > beyler sınırsız admin nasıl eklenir açıklayacak var mı. setPlayerAdmin (1,true) yapınca oyuna girip çıkıcanca gidiyor adminlik
> > 
> > 
> > Aşağıdaki kodu kullanabilirsiniz: https://github.com/09x2019/Haxball_Example_Scripts/blob/main/Codes/CmdSetPlayerAdmin.js
> > Kodun detaylarına gelirsek **adminPassword** değişkeninin içine yazdığınız şey admin şifreniz oluyor ve onu chate yazdığınız zaman otomatik admin oluyorsunuz. Odaya girdiğinizde otomatik olarak siz birşey yazmadan vermesini istiyorsanız eğer **player.auth** verinizi çekerek bu veri üzerine adminlik tanımlayabilirsiniz.
> 
> sağol knk adamsın player auth nasıl oluyor onuda anlatırsan süper olur

Aşağıdaki kodu kullanabilirsiniz:

```js
var adminAuth = ["write auth"]; //write player.auth haxball.com/playerauth

room.onPlayerJoin = function(player) {
if (player.auth == adminAuth) {
room.setPlayerAdmin(player.id, true);
}
}
```

Kod içerisinde yorum satırında da belirttiğim gibi https://haxball.com/playerauth sitesinden authunuzu alın ve **write auth** diye yazdığım kısmı silip onu yapıştırın ve sonrasında odanızı açıp test edin. Ben test etmedim. Birden fazla adminlik vermek için ise virgül atıp yeni tırnak açarak tırnak arasına 2. admin authu yazarak birden fazla admin de ekleyebilirsiniz.
