### ISSUE TITLE
a question about auth

### ISSUE THREAD

**Issue by selingolpek** [haxball/haxball-issues#1724]
hi, sorry if it's the wrong place but i play in one of those v6 rooms with bots, and suddenly I'm banned, mod said it's because there's auth match with another nickname that apparently cursed
I just wanted to ask if that's possible to have auth match with someone else? (or from other devices from home network, if it's my sibling -he doesn't play as far as i know, but just in case-)  should i be concerned?

**Comment by Gomezz2** [comment]
> hi, sorry if it's the wrong place but i play in one of those v6 rooms with bots, and suddenly I'm banned, mod said it's because there's auth match with another nickname that apparently cursed
> I just wanted to ask if that's possible to have auth match with someone else? (or from other devices from home network, if it's my sibling -he doesn't play as far as i know, but just in case-) should i be concerned?

if in case you passed your private id to someone else there is a chance, otherwise it is basically impossible for someone else to have the same auth as you

**Comment by selingolpek** [comment]
i didn't.. I'll have it checked again and will update here

**Comment by selingolpek** [comment]
> > hi, sorry if it's the wrong place but i play in one of those v6 rooms with bots, and suddenly I'm banned, mod said it's because there's auth match with another nickname that apparently cursed
> > I just wanted to ask if that's possible to have auth match with someone else? (or from other devices from home network, if it's my sibling -he doesn't play as far as i know, but just in case-) should i be concerned?
> 
> if in case you passed your private id to someone else there is a chance, otherwise it is basically impossible for someone else to have the same auth as you

i didn't.. I'll have it checked again and will update here

**Comment by selingolpek** [comment]
> > hi, sorry if it's the wrong place but i play in one of those v6 rooms with bots, and suddenly I'm banned, mod said it's because there's auth match with another nickname that apparently cursed
> > I just wanted to ask if that's possible to have auth match with someone else? (or from other devices from home network, if it's my sibling -he doesn't play as far as i know, but just in case-) should i be concerned?
> 
> if in case you passed your private id to someone else there is a chance, otherwise it is basically impossible for someone else to have the same auth as you

there isn't a auth match, but a conn match apparently.. it's related to ip, right?

**Comment by Gomezz2** [comment]
> there isn't a auth match, but a conn match apparently.. it's related to ip, right?

haxball only provides the public ip, the auth is to define each authentication of each player, so it is unique
