### ISSUE TITLE
Old .hbr replays support?

### ISSUE THREAD

**Issue by gandeladri** [haxball/haxball-issues#1735]
I've got tons of .hbr files in my computer that I can't watch anywhere. Flash obviously died, so what can I do instead? 

I've tried ruffle chrome extension, or the adobe flash content debug thing that you can download from the webarchive. Both didn't work. Even tried with Maxthon, because someone in Reddit said it'd work. Nothing works, I'm out of options. Guess I'll have to wait till Ruffle completes the ActionScript 3 developement. 

Adobe Flash Player 32 (Downloaded from webarchive)
![image](https://user-images.githubusercontent.com/20362322/197293579-57fc4260-557a-4d40-aec4-344325a3ede1.png)

Ruffle emulator
![image](https://user-images.githubusercontent.com/20362322/197294063-e1cf2d81-70d1-4fdc-a8aa-f130e6f680e7.png)

In the meanwhile, anyone or please someone from HaxBall team can support me?
Or maybe someone from the HaxBall team can share a swf that can be loaded locally?

Thanks

**Comment by Skarmunds** [comment]
> I've got tons of .hbr files in my computer that I can't watch anywhere. Flash obviously died, so what can I do instead?
> 
> I've tried ruffle chrome extension, or the adobe flash content debug thing that you can download from the webarchive. Both didn't work. Even tried with Maxthon, because someone in Reddit said it'd work. Nothing works, I'm out of options. Guess I'll have to wait till Ruffle completes the ActionScript 3 developement.
> 
> Adobe Flash Player 32 (Downloaded from webarchive) ![image](https://user-images.githubusercontent.com/20362322/197293579-57fc4260-557a-4d40-aec4-344325a3ede1.png)
> 
> Ruffle emulator ![image](https://user-images.githubusercontent.com/20362322/197294063-e1cf2d81-70d1-4fdc-a8aa-f130e6f680e7.png)
> 
> In the meanwhile, anyone or please someone from HaxBall team can support me? Or maybe someone from the HaxBall team can share a swf that can be loaded locally?
> 
> Thanks

Hi! I watched old replays too about 1 year ago but couldn't find article about some global block flag setting inside config file. Nvm, I found this browser just with plugin inside https://github.com/radubirsan/FlashBrowser.

Direct haxball flash URL to replayer is here http://www.haxball.com/flash/replay/12.swf?token=hax&wmode_direct=yes.

**Comment by gandeladri** [comment]
> > I've got tons of .hbr files in my computer that I can't watch anywhere. Flash obviously died, so what can I do instead?
> > I've tried ruffle chrome extension, or the adobe flash content debug thing that you can download from the webarchive. Both didn't work. Even tried with Maxthon, because someone in Reddit said it'd work. Nothing works, I'm out of options. Guess I'll have to wait till Ruffle completes the ActionScript 3 developement.
> > Adobe Flash Player 32 (Downloaded from webarchive) ![image](https://user-images.githubusercontent.com/20362322/197293579-57fc4260-557a-4d40-aec4-344325a3ede1.png)
> > Ruffle emulator ![image](https://user-images.githubusercontent.com/20362322/197294063-e1cf2d81-70d1-4fdc-a8aa-f130e6f680e7.png)
> > In the meanwhile, anyone or please someone from HaxBall team can support me? Or maybe someone from the HaxBall team can share a swf that can be loaded locally?
> > Thanks
> 
> Hi! I watched old replays too about 1 year ago but couldn't find article about some global block flag setting inside config file. Nvm, I found this browser just with plugin inside https://github.com/radubirsan/FlashBrowser.
> 
> Direct haxball flash URL to replayer is here http://www.haxball.com/flash/replay/12.swf?token=hax&wmode_direct=yes.

Thank you so much! This works perfectly. The direct url works for certain .hbr versions, which there are many along my files. I ended up opening that FlashBrowser and straight to http://www.haxball.com/flash and the HaxBall it self detects the .hbr version automatically.

Also, I've downloaded latest release for Windows x64 (0.8.1 at this time) from https://github.com/radubirsan/FlashBrowser/releases

Again, thank you!

Closing this topic because my issue was solved.

**Comment by Felfa** [comment]
Since the flash version of HaxBall can no longer be accessed from haxball.com/flash, it is no longer possible to watch old replays even using other external websites that could play them, such as [TheHax](https://replay.thehax.pl/f7156071-2472-4b0b-a854-39cdbf330663). They always end up stuck at the loading screen as seen in [this screenshot](https://i.gyazo.com/dbd2b5adb00c3e21211b34dd7619555c.png). Too bad because I also have lots of old hbr files from 2011 onwards...

Any workaround on it?
