### ISSUE TITLE
Finish Line

### ISSUE THREAD

**Issue by MoisesAsafi** [haxball/haxball-issues#1736]
Hello, I want to set up a finish line in my bot, if the player crosses the line the bot stops the game. Can someone help me?

**Comment by 09x2019** [comment]
> Hello, I want to set up a finish line in my bot, if the player crosses the line the bot stops the game. Can someone help me?

@MoisesAsafi Create a finish line on the map edit and check the **x**, **y** you defined on this line to see if the player crosses the line.

**Comment by thenorthstar** [comment]
> Hello, I want to set up a finish line in my bot, if the player crosses the line the bot stops the game. Can someone help me?

@MoisesAsafi Hello friend. I have created a script for the basic cases your issue. It may be useful for you: https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Intermediate/FinishLine.js

Output: https://thehax.pl/forum/powtorki.php?nagranie=57bc38695e9477cc2ecb01b222a465a5
