### ISSUE TITLE
Default vertex bCoef? Default disc 

### ISSUE THREAD

**Issue by alpheratz0** [haxball/haxball-issues#1748]
Hi, I'm writting a c library to parse haxball maps and I want to know which are the default values for the [vertex](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#vertex) bCoef, cGroup, cMask, and [disc](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#disc) invMass, cMask, cGroup, damping, etc, if no value is specified, are those properties required?, but I dont seem to find any information about that.

Thanks

**Comment by Skarmunds** [comment]
@alpheratz0 Some defaults but not all wrote configured before checking against stadium from haxball source:
### Vertex
bCoef: **1**, cMask: **["all"]**, cGroup: **["wall"]**
### Segment
bCoef: **1**, cMask: **["all"]**, cGroup: **["wall"]**
### Plane
bCoef: **1**, cMask: **["all"]**, cGroup: **["wall"]**
### Disc
bCoef: **0.5**, cMask: **["all"]**, cGroup: **["all"]**, invMass: **1**, damping: **0.99**, radius: **10**

### Ball physics (without "disc0" value)
pos: **[0,0]**, speed: **[0,0]**, gravity: **[0,0]**, radius: **10**, invMass: **1**, damping: **0.99**, color: **["FFFFFF"]**, bCoef: **0.5**, cMask: **["all"]**, cGroup: **["ball", "kick", "score"]**
https://github.com/haxball/haxball-issues/wiki/Collision-Flags#all

You don't need that property if you're not going to change it.

**Comment by alpheratz0** [comment]
> @alpheratz0 Some defaults but not all wrote configured before checking against stadium from haxball source:
> ...

Thank you very much!!!!
