### ISSUE TITLE
Help with the volleyball bot

### ISSUE THREAD

**Issue by hacibartu922** [haxball/haxball-issues#1751]
Hi, I'm making a volleyball bot using Osprey's volleyball map, but I have a problem. When the serve is gonna be used by a team, I want the opposing players not to cross the line I have indicated in the picture below until the ball passes the middle of the court (when I change the ball position, kick-off barriers are being disabled due to gravity and the players can block the ball). Can you help me?

[Volleyball 3D by Osprey.txt](https://github.com/haxball/haxball-issues/files/10327486/Volleyball.3D.by.Osprey.txt)

![image](https://user-images.githubusercontent.com/112348696/210142609-4b42c325-a90a-4e4c-bca5-bc5240670f03.jpg)

**Comment by Yacka03** [comment]
I don't know much about the physics of haxball but one dirty way to do this is you can add two maps (which have lines for each side with cMask on and off for other) and when the ball passes the middle of the court in first map that have cMask on you can save player discs and ball location and open second map(timer will restart or you can set the timer programmatically)

**Comment by hacibartu922** [comment]
Yeah, it makes sense but it can be annoying to pause and restart the game after every score. I found the solution by penalizing the team of the person who blocked the serve by giving the opposing team a point.
