### ISSUE TITLE
How to remove sendAnnouncement red line?

### ISSUE THREAD

**Issue by nomerang** [haxball/haxball-issues#1757]
How to remove sendAnnouncement red line? What changes do I need to make on **Headless-min.js?**

```
            sendAnnouncement: function(a, b, d, e, f) {
                e = {
                    bold: 1,
                    italic: 2,
                    small: 3,
                    "small-bold": 4,
                    "small-italic": 5
                }[e];
                null == e && (e = 0);
                null == d && (d = -1);
                null == f && (f = 1);
                var h = U.V(a, d, e, f);
                null != b ? B.then(function() {
                    A.rf(h, b)
                }) : c(h)
            },
```

**Comment by nomerang** [comment]
@furkanardagul @thenorthstar @Wazarr94

**Comment by guguxh** [comment]
You can't do this just changing the headless

**Comment by nomerang** [comment]
> You can't do this just changing the headless

Ok. What should I do?

**Comment by furkanardagul** [comment]
What exactly is your aim? Why do you want to remove it?

**Comment by nomerang** [comment]
> What exactly is your aim? Why do you want to remove it?

The purpose of the function is to make announcements. We use it for chat customization. That's why I want to remove it.

The chat box already looks complicated. It looks bad.

Edit: I saw that @Wazarr94 was also complaining about this issue in #868  - He said he'd edit headless-min.js. But how can he do this?

**Comment by Wazarr94** [comment]
I haven't done it after all. Looked a bit into it, the border property is applied on the client side and not on the server side. The lines responsible for the red border are found in the game-min.js file. When an announcement is received by the client, it applies the announcement class to the chat element that has the red border-left.

```js
Da.prototype = {
        pp: function (a, b, c) {
            var d = window.document.createElement("p");
            d.className = "announcement";
            d.textContent = a;
            0 <= b && (d.style.color = N.lc(b));
            switch (c) {
                case 1:
                case 4:
                    d.style.fontWeight = "bold";
                    break;
                case 2:
                case 5:
                    d.style.fontStyle = "italic"
            }
            switch (c) {
                case 3:
                case 4:
                case 5:
                    d.style.fontSize = "12px"
            }
            this.Ok(d)
        },
```

Players in the room without a custom css will always see this red border.

**Comment by yard1ms3v3r** [comment]
```js
sendAnnouncement: function(a, b, d, e) {
                e = {
                    bold: 1,
                    italic: 2,
                    small: 3,
                    "small-bold": 4,
                    "small-italic": 5
                }[e];
                null == e && (e = 0);
                null == d && (d = -1);
                var h = U.V(a, d, e);
                null != b ? B.then(function() {
                    A.rf(h, b)
                }) : c(h)
            }

```

**Comment by wxyz-abcd** [comment]
You can use my API to create your own haxball website. (There is a complete Haxball frontend example in examples_web folder.)
