### ISSUE TITLE
[BUG] handicap

### ISSUE THREAD

**Issue by humpyy** [haxball/haxball-issues#176]
the extra / makes it so users have to type //handicap instead of /handicap

{case "/handicap":if(2==a.length){var c=J.parseInt(a[1]);null!=c&&0<=c&&300>=c?(this.Qa.on(c),this.Aa("Ping handicap set to "+c+" msec")):this.Aa("Ping handicap must be a value between 0 and 300 milliseconds")}else this.Aa("Ping handicap requires a value in milliseconds.");break;

**Comment by basro** [comment]
This is now fixed.
