### ISSUE TITLE
Battle royale.

### ISSUE THREAD

**Issue by SLNMX** [haxball/haxball-issues#1762]
Good afternoon fellow haxballers

I am here with a conundrum, I have been trying unsuccessfully to alter the next script for a battle royale room... (https://github.com/7PH/haxball-battle-royal/blob/master/dist/bundle.js).

I wish to know if someone has ever been successful at such task, or if by any chance, has a more easily-to-modify script.

Thanks in advance

**Comment by guguxh** [comment]
Yes, have.

**Comment by SLNMX** [comment]
Oh is it possible to have it shared to me? I want to open a VPS but adding different maps...

**Comment by 7PH** [comment]
Hey @Donfau2 , the instructions from the README were not up to date, I've updated them. You need to get a token and update it in the bundle (at the end). I wasn't sure anyone was using this script, I might make things a bit better if you use it!

**Comment by SLNMX** [comment]
Oh thanks a lot 7PH, I was wondering if to contact you directly or not about this subject. My main issue with this is, can the bundle.js be altered?

Is it possible that I can change maps from the ones there or add other functions? (I ask if it's possible, as I have not been able to do it so far, however if you, the creator, mention otherwise I can give it more thought)

Sorry for an inconveniences

**Comment by 7PH** [comment]
Thank you for the questions, I'm actually happy to see that some other haxball fans are interested by this script 

It's totally possible to change the code of bundle.js but generally this is what you would want to do:
1. Fork the repository (button on the repo main page)
2. Clone your fork locally (git clone ...)
3. Install dépendencies ("npm install")
3. Modify anything in the source folder (functions, maps...)
4. Re-build the bundle (with "npm run build")

After this you'll get a fresh bundle.js locally that you can use yourself 

This assumes you have git, npm installed and basic knowledge of JavaScript 😇

Let me know if I can help more

**Comment by SLNMX** [comment]
Thanks so much Mr 7PH, I have already managed to re build it and add some changes to the maps, however there is still one thing that I do not understand quite good...

On the file RoomObject.ts, I have been trying to modify with little success the section:
onPlayerChat: (player: PlayerObject, message: string) => boolean;


I have been trying by using my previous knowledge of more traditional scripts alas:
onPlayerChat: (player: PlayerObject, message: string) => boolean;
if (message == "!password"){
room.setPlayerAdmin(player.id, true);
return false;}
else if (message == "!clearbans") {
			if (player.admin) {
				room.clearBans();
				room.sendChat("Bans removidos por " + player.name);
			}}
else if (message == "!bb") {room.kickPlayer(player.id, "Bye !", false);}
;
}


Nevertheless my best efforts, I have found that this brings errors to the build. 
Is there a specific way to write it that it's a bit different from the more traditional scripts? 
Am I writing it on the correct file?

Thanks so much for your help

**Comment by 7PH** [comment]
Hey again @SLNMX here are some tips
- The game logic is in app/src/game/GameManager.ts, that's very likely the place you want to start with if you want to add a tiny bit of logic 
- On github you can wrap your code with " ``` " to keep indentation

Here's your code put at the right place:
![image](https://user-images.githubusercontent.com/31401273/215326575-ce175a3f-ab32-4cac-beb3-f656aa6b438d.png)

Please not that I did not test this code but that's at least where it should go

I've changed quite some things in the original repo to make it easier to create rooms, if you want to update your fork you'll have to execute this (you might want to remove all your local changes before):
```bash
git remote add upstream https://github.com/7PH/haxball-battle-royal.git # track original repo locally
git pull upstream master # sync your fork locally with the original repo
git push origin master # updates your fork on github
```
