### ISSUE TITLE
async onPlayerChat function

### ISSUE THREAD

**Issue by furkanardagul** [haxball/haxball-issues#1765]
When I try to use the onPlayerChat event as async, it sends messages twice. One is plain default and the other is the way I want it. I can't share all the codes.

`
        room.onPlayerChat = async function (player, message) {
        ...
        }
`

**Comment by HishamTareq** [comment]
because the function returns a `promise` which is always `true`.

**Comment by furkanardagul** [comment]
How can I fix this man.

![Ekran Resmi 2023-02-02 00 15 37](https://user-images.githubusercontent.com/45922246/216164962-a3085fa0-f691-41a0-8d44-c5ac611cb480.png)

**Comment by HishamTareq** [comment]
In fact, I don't know. I've had this problem before and couldn't solve it.

**Comment by furkanardagul** [comment]
```js
room.onPlayerChat = async function (player, message) { 
...
             else if (message.toLowerCase() == "!grade") {
                (async () => {

                  await showGrade(player.name);
                  
              })();
                  return false;
              }
}
```

The attached code snippet solved my problem. Thank you for your interest and opinion.
