### ISSUE TITLE
About the new HTML-5

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#177]
About the 5th version of HTML:
You need to fix this again: https://gyazo.com/12aadfe95db330c9b8cc0deb96f83f5f

When you set handicap, you dont have and indicative that you have handicap on, only when you set it, but some time after this you dont have it anymore, this way the game may seem laggy but its actually the handicap that you forgot on and you dont have a feature to tell you that handicap is on, the same feature used in flash can be used, the green number beside your real ping:
[Flash with handicap on](https://gyazo.com/3d44fb80850d85dd47f2fbc39b37ee85) vs. [HTML5 with handicap on](https://gyazo.com/bd20b0828135ded19ff5351be1b0219e)

I think its time to complete [this bar](https://gyazo.com/5c5f82acabe9feaf7c08a694ffd7f365) on HTML5 aswell, cause sometimes when im in the HTML i need to unnecessarily go to the flash to check News, for example

About the non player chat messages being another color, i agree with that, but i think it needs to be another color rather than green, in my opinion it needs to be the same color as the custom map's name in the room menu, same color as the indicator that someone has admin, at least for me i think the way that is now is very colorful and gets away from the pattern with yellow color meaning special actions/persons/maps

Rather than that i think you are doing a great job, keep up the good work! 😉

Thx. in advance
Leo ß

**Comment by basro** [comment]
This is not how to use the issue tracker, I prefer if you make one issue per item. And also check for duplicates, the first bug you mention is still open.

Regarding log colors, I originally used the yellow which you suggest but it felt a bit too bright/strong, so I decided to go for something more subdued. I'll probably keep it this way.

The other things will be done eventually.

**Comment by Leo-MapCreator** [comment]
Do you have a preview of the yellow color?

**Comment by Leo-MapCreator** [comment]
I tested the yellow color using paint, i know its not the same as would be in the game but it can give a nice preview, in my opinion it would be ok
