### ISSUE TITLE
Help me the Archery haxball bot!

### ISSUE THREAD

**Issue by nguyenbinhbo** [haxball/haxball-issues#1785]
Dose anyone have Archery haxball bot!

**Comment by wxyz-abcd** [comment]
and what exactly does archery bot mean? :) do you want to kill people by shooting balls? if that's what you want, i did that 3 years ago. i will integrate this as a plugin into my new API soon, so that everyone can use it directly.

**Comment by nguyenbinhbo** [comment]
> and what exactly does archery bot mean? :) do you want to kill people by shooting balls? if that's what you want, i did that 3 years ago. i will integrate this as a plugin into my new API soon, so that everyone can use it directly.
