### ISSUE TITLE
Simple Ping Pong Bot Haxball

### ISSUE THREAD

**Issue by nguyenbinhbo** [haxball/haxball-issues#1793]
hi i'm looking for anyone has got a simple Ping Pong (table tennis) bot haxball !

**Comment by wxyz-abcd** [comment]
I can build you one, if you want. But there is a feature request queue, so it's your choice.

**Comment by nguyenbinhbo** [comment]
> I can build you one, if you want. But there is a feature request queue, so it's your choice.



> I can build you one, if you want. But there is a feature request queue, so it's your choice.

it's just like ping pong in real life.
1/ serve:
+ When red serves, red must bounce the ball on red's table once and bounce on blue's table once.
+ If the ball hits the net and still lands on blue's table, red will have to serve again and room.sendchat (`LET`)
+ If red serves the right ball, then blue must hit the ball back to red

2/ score and win:
+ Both sides can hit the ball with many ways to make the ball bounce to the opponent's table and score points when the opponent lets the ball touch the table once and fall to the ground or bounce on the table twice.
+ To win, you must achieve 5 points with a difference of at least 2 points from the opponent, if the points of both are 1 point apart, the game will continue until 15 points are reached if both sides
still 1 point apart room.sendchat (`DRAW`) and room will take them both out and will replace someone else

3/ change the serving side:
+ If one side has served 2 times, even if they score or lose points, they still have to change the serving side

4/ the player touches the ball
+ when touching the ball the player can only align and hit the ball for a fixed amount of time
+ When hitting the ball, you can only hit once, if you hit the ball twice, the player will lose points

this is my map 
https://haxmods.com/map/?id=1459

THANK YOU VERY MUCH!

**Comment by wxyz-abcd** [comment]
Can you please write these in this discord server? Thanks. See you there: https://discord.gg/ngACfJHSD6
