### ISSUE TITLE
Haxball is using the deprecated-for-a-decade, and now removed, mozRTCPeerConnection

### ISSUE THREAD

**Issue by docfaraday** [haxball/haxball-issues#1804]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1828218#c2

**Comment by basro** [comment]
Thank you for reporting this, I'll be addressing it asap.

**Comment by basro** [comment]
This should be fixed now.

**Comment by wisniewskit** [comment]
Thank you for the quick fix!
