### ISSUE TITLE
Option to disable custom avatars

### ISSUE THREAD

**Issue by saviola777** [haxball/haxball-issues#181]
Hello,

I have a small, low priority enhancement suggestion: adding an option to disable custom avatars (similar to the option to disable custom colors).

With full UTF-8 support, avatars now have a higher... *distraction potential*, that's what brought on this suggestion. If the implementation would be simple and/or other people would also like to see this, it would be a nice addition to the customization aspect of the game, otherwise feel free to reject this suggestion, it is a very minor thing after all.

**Comment by basro** [comment]
It's not a bad suggestion. But as you say, this would be fairly low priority.

**Comment by haxballer** [comment]
It's true that all colorful avatars can be distracting, but you get used to it. I think it would be more difficult with colored maps, which is rather a good option mainly for non-standard maps. I think that in the future it would be possible to make such minor adjustments, add to the rest, when everything will be finished. That's my opinion.

**Comment by basro** [comment]
This is now implemented.
