### ISSUE TITLE
Restricted View

### ISSUE THREAD

**Issue by pixelhaxballer** [haxball/haxball-issues#1815]
Hey Bas, appreciate the update. I was hoping you could bring back restricted view though as I and a few others I know use it. It helps us focus more on the game.

**Comment by basro** [comment]
I'll see if I can bring it back then... Although it's unlikely the score and timer bar are going to remain in the same place. They are going to stick to the top as with the other view modes.

**Comment by pixelhaxballer** [comment]
> I'll see if I can bring it back then... Although it's unlikely the score and timer bar are going to remain in the same place. They are going to stick to the top as with the other view modes.

Appreciate that. I just found out from a few people that it was the only way they were able to get good fps as well. So they'll be happy to hear you're seeing if you can get it back.

**Comment by basro** [comment]
This is back now, the key is now 0 instead of 4.
