### ISSUE TITLE
avatar not in the center

### ISSUE THREAD

**Issue by hosakas** [haxball/haxball-issues#182]
https://i.imgur.com/bt1tYri.png

this very important

**Comment by basro** [comment]
There's a difference between how Firefox and chrome position text vertically. Chrome renders it properly centered while in Firefox it's slightly offset..

I might look for a workaround in the future but I wouldn't call this very important.

**Comment by basro** [comment]
This should be fixed now.

**Comment by hosakas** [comment]
Great! Thank you very much.
