### ISSUE TITLE
Camera 4

### ISSUE THREAD

**Issue by Vavamitao** [haxball/haxball-issues#1821]
![FPS](https://user-images.githubusercontent.com/131720404/234131763-656146d7-acf9-4ed5-ac8e-97a3dc783099.png)

I wanted the return of camera 4, in smaller maps it is very good, in addition to helping to gain FPS. without camera 4 i can barely play haxball.

**Comment by potinho1234** [comment]
come back with camera 4 please!

**Comment by basro** [comment]
Yeah, it's coming back

**Comment by basro** [comment]
This is back now, the key is now 0 instead of 4.
