### ISSUE TITLE
camera 4 back 🙏 

### ISSUE THREAD

**Issue by besthxplayer** [haxball/haxball-issues#1823]
From the Haxball Flash that many people keep using this camera, it is good and it helps with an FPS boost. I hope this camera comes back, I don't see that it is a problem to eliminate it from the game
![Screenshot_1](https://user-images.githubusercontent.com/88322306/234135268-cc763cd0-4c1a-4bdc-b838-5a1f5c658ddb.png)
camera 4  👆

**Comment by basro** [comment]
it's been reported already, I'll be bringing it back

**Comment by basro** [comment]
This is back now, the key is now 0 instead of 4.
