### ISSUE TITLE
Choose Chat Frame Version

### ISSUE THREAD

**Issue by nguyenbinhbo** [haxball/haxball-issues#1828]
![image](https://user-images.githubusercontent.com/105974036/234185222-f4c20c55-7ed1-46b3-b8b9-94de424ce6a0.png)
Can you add a button to toggle between the new and old chat frame for those who do not like the new chat frame?

![image](https://user-images.githubusercontent.com/105974036/234182900-96536b6d-d648-4a79-821f-0a47883105ca.png)
![image](https://user-images.githubusercontent.com/105974036/234182908-a5539b32-361e-4a1a-b73a-49669773ccfe.png)
And I am unable to use the "Haxball All-in-one Tool" when I create a room.

@basro

**Comment by basro** [comment]
Closing because this is implemented.
