### ISSUE TITLE
"Show empty" filter for the rooms list

### ISSUE THREAD

**Issue by Nellty** [haxball/haxball-issues#1837]
There are filters for the rooms list, but it's definitely missing a "Show empty" one

![image](https://user-images.githubusercontent.com/83482629/234242052-f2e37c2e-cd90-4eac-9c30-a329db4d00e4.png)

**Comment by x9136** [comment]
At this point it's useful to be able to filter by a text and by a country.

**Comment by basro** [comment]
This is now implemented.
