### ISSUE TITLE
Can only host 2 games from the same network

### ISSUE THREAD

**Issue by shaylanger** [haxball/haxball-issues#184]
Hosting more than 2 games on the same network results in a issue with getting a creating a link for the game.

**Comment by gholtslander-va** [comment]
The issue seems to be that calls to the websocket at `ws://p2p2.haxball.com/host` start returning 503 Service Temporarily Unavailable until one of the game shuts down.

**Comment by basro** [comment]
There's a limit of two connections, this is intentional.

**Comment by gholtslander-va** [comment]
@basro any way you could make it three? 😄 Or will the limit be increased after alpha? Our "use case" as it were is to play as many 4v4 games as we have people for in the afternoons for about 15 minutes. Of late this has meant three games of 4v4, which hasn't been possible with us all on html5.

Just hoping you have some good news :pray: One group can use the Flash version for now I guess.

**Comment by basro** [comment]
Right, I'll implement separate limits for number of rooms hosted and rooms visible in the room list.. So I can increase the number of rooms you can host but only 2 of them will be public.

**Comment by gholtslander-va** [comment]
We currently don't show any of them in the room list anyway. But we don't use passwords (just for ease of joining) - we just share the link in Slack. Are you saying adding a password gets around this limit of two?

**Comment by basro** [comment]
Private rooms = Rooms that don't show in the room list

I'm saying that I'll change it so that you can host more rooms in a single network but only two of those will appear in the room list if you choose to make them all public.

**Comment by gholtslander-va** [comment]
@basro Awesome, that sounds great!

**Comment by basro** [comment]
The limit for non public rooms is now increased to 4.

**Comment by gholtslander-va** [comment]
@basro Many thanks!
