### ISSUE TITLE
[BUG] Wrong goal line detection

### ISSUE THREAD

**Issue by r2308145** [haxball/haxball-issues#185]
Hello, although this is not very important I would love to know whether it can be possibly fixed. I'm talking about situation, when the ball cross the goal line only by one of its half, then it is automatically counted as a scored goal. I think regular goal should only be considered when the ball went over the line entirely.

**Comment by basro** [comment]
I don't consider this a bug, those are the rules of HaxBall.
However, you have the option of making your own custom stadium with the goal lines moved back to account for the ball radius and thus have the score rules that you want.

**Comment by r2308145** [comment]
Thanks for reply @basro. I understand you, that it's not a bug but can you reopen and take it rather as feature request from my side? I wonder what others think about this as there are plenty of bothered players spamming "ref" or "VAR" after each close goal

**Comment by basro** [comment]
Well, as I said, if it bothers you that much you have the option to change it already.
I wont be changing the default maps.

**Comment by r2308145** [comment]
Allright. It doesnt bother me as I said its not that very important.. only felt that it can be considered as improvement of the gameplay for majority of players + one of those things with relatively easy fix

**Comment by usmth** [comment]
@basro, why you decided to make that kind of rule for default maps? Please explain the reason.

In most popular competitions a goal is scored when ball (or puck) entirely crosses the goal line.

**Comment by cofimaslisa** [comment]
In every sport in the world, ball most cross the line xD
