### ISSUE TITLE
Chat Problem

### ISSUE THREAD

**Issue by Hardwiredz** [haxball/haxball-issues#1857]
Hello Basro first of all thanks for updating the game. Game looks good but i have a problem. I use **haxball all in one tool** extension you know, when i press **esc** button chat doesn't close anymore. I think problem is new update called: **''Game viewport continue rendering when accesing the room's lobby menu.''** 

Maybe you can assign a button to turn on/off the chat like all in one tool or you can change this render update. These are my suggestions, i'm sure you will find the best solution.

**Comment by basro** [comment]
This is now implemented in haxball, check the input settings for the ToggleChat binding.
