### ISSUE TITLE
Pressing load freezes the game

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#1861]
When the game is stopped, if we want to load an unstored map (clicking on load) and someone else changes the map during our operation, we are left unnoticed that the map already changed, the canvas is frozen even when the game starts.

https://i.imgur.com/WwpB0ct.mp4
In this video, my mate changed map, started the game, scored a goal and I canceled the load 

I am not sure this is an expected behaviour as it should logically show that the game has started during the load

**Comment by basro** [comment]
This is not the expected behavior but I can't reproduce it, the game continues to render fine for me.

It might be a behavior of your browser or OS. I see that your file picker is fairly different to the normal windows file picker.

**Comment by AnddyAnddy** [comment]
I'm on windows 10, the video was on Opera GX and I can't reproduce it on chrome so it is probably on opera gx's end

**Comment by kingjasko** [comment]
unlocked fps tends to cause such issues frequently

**Comment by AnddyAnddy** [comment]
Ah I haven't thought of that, I guess it is the issue then thanks
