### ISSUE TITLE
chat after writing a message goes back to the beginning

### ISSUE THREAD

**Issue by kojo953** [haxball/haxball-issues#1871]
as i wrote in the topic. It doesn't matter who writes, the chat goes back to the beginning. It is very annoying, especially during the game

**Comment by basro** [comment]
what browser are you using?

**Comment by kojo953** [comment]
Chromium version 77.0.3828.0 (64 bit)

**Comment by basro** [comment]
I was able to reproduce this issue. It'll probably be fixed in the next update.

Is there a reason why you are using an old version of chrome?

**Comment by AnddyAnddy** [comment]
Newest version of chrome are bugged on haxball with--disable-frame-rate-limit, they go to a LOT of fps (>2000) but they are freezy and laggy

**Comment by basro** [comment]
I see, that is unfortunate.

I've managed to fix this (not released yet) but I really don't want to be stuck supporting chrome 77 for life...

**Comment by AnddyAnddy** [comment]
Maybe it's time to a new haxball revolution, flash->html->standalone (steam or whatever) :ppppppp

Well you know we often say that but it would be more of a major business discussion than a concern regarding development, altough it would probably take a loooot of time.

Haxball grew as browser game you could log in from anywhere, without requiring a good pc, without requiring accounts or anything user complicated and I think that was the best way to be popular in 2010, congratulation for that. 
But it's 2023 and browser games are meh, not taken "seriously" regarding e-sport, not "stable", not attracting.
No matter your decisions, we will be supporting you, especially if you are showing interest in the communities and listening to the feedbacks. I don't know how old you are but haxball is surely way more successful and active than what you were expecting when you made this game 13 years ago. It has probably became a pain over these years and we are very thankful you did not just shut down that game.

**Comment by kojo953** [comment]
> 
On firefox fps drops from 240 to 70 after 2 minutes of playing. Response to change of movement and hit is the best of all browsers, but because of the fps drop it is impossible to play. On the new chrome the response to change of movement and hit is too slow, the fps is stable. On this chromium what I play, everything is centered, it is possible to play. Its all about feeling the game

**Comment by basro** [comment]
The fix for the issue here has been released.
