### ISSUE TITLE
Room forwarding for Headless API

### ISSUE THREAD

**Issue by punisherhaxball** [haxball/haxball-issues#1884]
Many people have more than one or two rooms. 

Lets say I have 2 rooms and and one of them is 7/8 players and two player tries to connect at the same time. One of them will get “Room is full” error, so instead of that when that’s happening forward the player to the my second room by re-sending the connection state. 

Such as `room.onRoomFull(playerData, forwardRoomID, secret-thr-token)`

And to block abuses, you can create some secret token where these rooms will accept the forwarded join request only if that secret token is presented in the header.

**Comment by basro** [comment]
I don't think I'd implement this one.
