### ISSUE TITLE
Feature Request (PLEASE SEE)

### ISSUE THREAD

**Issue by Haxbalinho** [haxball/haxball-issues#1888]
First of all, good day, I'm Turkish, I started the game 5 years ago, but people didn't like the update on Turkish servers.
 I am happy with the update. My request is to have a microphone feature in the game so everyone can talk to each other. I think it's not that hard, you can do it.

**Comment by basro** [comment]
Sorry but this is rejected.

**Comment by mertushka** [comment]
> Sorry but this is rejected.

@basro Any reasons? It could be cool tho.. The game already uses WebRTC, making voice chat will be simple asf. We have to agree that one of the biggest shortcomings of Haxball is the voice chat.
