### ISSUE TITLE
More camera controls - Duplicate

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#1889]
Hi,

I'm reposting this since you are working on UI, duplicate of #378 
This was something that was added in Haxball-in-One that I can't play without. For racing maps, I use a very big zoom, but for 4v4 or 3v3 I play on a smaller zoom.

Everytime I change map, I have to go in the settings to change my zoom, and every time I want to readjust the zoom, I have to go back to the menu every time since I have a large screen.

Is it possible to add ? Players on a big screen will appreciate
(5 for 2x zoom, 6 for 2.25x zoom and 7 for 2.5x zoom)

**Comment by basro** [comment]
This is now implemented.
