### ISSUE TITLE
No feature request label means not happen?

### ISSUE THREAD

**Issue by punisherhaxball** [haxball/haxball-issues#1896]
Just see u did added feature request label on some issues and some are not. The ones you haven’t added means not gonna happen?

**Comment by basro** [comment]
Not necessarily, I could have forgotten. But it's true that if I really dislike an idea sometimes I skip adding the tag.

In that subject, having a feature request tag doesn't mean it's going to be implemented either. It's just a tag to help me later find posts related to feature requests.
