### ISSUE TITLE
Application Form - Haxball Developer

### ISSUE THREAD

**Issue by Laginga** [haxball/haxball-issues#1908]
Dear Haxball Manager,

 

Name: TRUNG NGUYEN DANG

Country: Vietnam
Age: 18
Sex: Male

Address: Ho Chi Minh City, Vietnam

 

 

I am writing this job application to express my interest in the company, organization or group that created Haxball and programs Haxball. I am expressing my desire and passion to become a Haxball developer,

 

My name is Trung Nguyen Dang, and I am an 18-year-old full-stack developer from Vietnam. I have a passion for programming in both 2D and 3D,…

I am writing this application to express my passion for my work and my interest in the experience of all players when playing Haxball. I am one of the early founders and coders in Vietnam, and have been involved in various Haxball Vietnam products such as major tournaments. Through the experience of Haxball players in Vietnam, I have realized some of their requirements. Therefore, I am applying for the position of Haxball programmer to take Haxball Vietnam further and help it grow stronger. The number of Haxball players has reached around 10,000, which is not a small or large number, but it is something that I have been working towards, and the reason why I am submitting this application,

"This application is similar to requesting a copyright from Haxball. I want to develop Haxball for Vietnamese people to make the server smoother and more convenient. I have the desire to purchase the Haxball.vn server and develop it to run parallel with Haxball.com, but only IPs from Vietnam can play on it. I hope that the developers can consider my request and provide me with some regulations, rules, and copyright sources."

 

Thanks for reading, I hope the publisher will review me and interview me.

 

Mail: punpun20837@gmail.com

Discord: bav#0970

…
I have sent it to your email, and this is the version on GitHub.
@basro

**Comment by basro** [comment]
Sorry but no.

**Comment by Laginga** [comment]
> Sorry but no.

That's too bad. If you sold the copyright to me, then Vietnam would have had haxball.vn to play on their own. Thank you for responding.

**Comment by punisherhaxball** [comment]
Stop trying to buy the game. He could already sell it in this game’s peak times if he really wanted it. For him this (Haxball) is a memory and hobby for years.  So you can’t expect people to sell their memories.

**Comment by Laginga** [comment]
> Stop trying to buy the game. He could already sell it in this game’s peak times if he really wanted it. For him this (Haxball) is a memory and hobby for years. So you can’t expect people to sell their memories.

you are too dumb for the story, can you read english? I'm buying the copyright to establish haxball.vn, not buying haxball.com, wake up now bro
