### ISSUE TITLE
Full screen button

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#1919]
Most websites have a button to toggle full screen, would it be possible to add one for HaxBall ?
Personally my function keys are not working properly so I would appreciate

**Comment by basro** [comment]
There's one thing that keeps me from adding this: Unlike when entering fullscreen by pressing F11 the fullscreen mode activated with javascript will always exit if you press the Esc key. I feel like this would be extremely annoying in HaxBall to the point of making the feature useless.

A better alternative could be to use extensions such as these: https://chrome.google.com/webstore/detail/toggle-fullscreen/ddpejemcmlhbjppfdndmonifbiaindkl

They allow you to use the same Fullscreen mode as F11 but without the need of pressing the F11 key.

**Comment by Wazarr94** [comment]
Understood, I didn't think about this point.
