### ISSUE TITLE
this version is so bad,pls delete that version plssssssss omggggg

### ISSUE THREAD

**Issue by ProHaxballPlayer** [haxball/haxball-issues#192]
im sorry to tell you basro but you this version destroyed the game,

why? cause you try to add new unwanted stuffs,for some players its good update,good ping and thats all!
the flash version was better and there everyone played,even the players that have a bad computer.
another reason that the HTML5 that you made will crush your game soon is because there is now a Distribution between the players that preffer HTML5 and players that preffer the flash version, that means pro players (or noobs player,doesnt matter) cant play with another players while both doesnt want to play in the same version, because one of them doesnt want/cant play in the html5 version, and the end of this story is players start to retired from this game.

so pls,pls basro, make us happy again and delete this horibble version (html5) and you can trust me its a smart way for you and us.
thank you

**Comment by haxballer** [comment]
I have not read more foolishness here. Come back to "ddos" in flash rooms, you will definitely leave. That's definitely what comes out you.
