### ISSUE TITLE
DDoS Attacks 

### ISSUE THREAD

**Issue by Jpjerlol** [haxball/haxball-issues#194]
Hello. 

There are plenty of DDoS attacks in Balkan rooms. You just open a room and some people DDoS it. Is there any option to sort this out? Balkan players constitute a large part of Haxball players, but we can not make rooms, because they are under constant DDoS attacks.

**Comment by basro** [comment]
Unfortunately there's not much you can do against a DDoS attack.

**Comment by Leo-MapCreator** [comment]
there are ways to prevent DDoS attack from a single PC, and you can apply them to all the PC Bots that are attacking, but the host's internet has to be good to maintain stable till the DDoS is nullified
