### ISSUE TITLE
Old version better

### ISSUE THREAD

**Issue by ca1ik** [haxball/haxball-issues#1941]
s

**Comment by kadavrahaxball** [comment]
innovation is always better. problems can be fixed. please be patient.

**Comment by punisherhaxball** [comment]
You have to use it like that, he already stated this before and explained it in the Wiki page.

--disable-frame-rate-limit --use-angle=d3d9

**Comment by punisherhaxball** [comment]
You have to use it like that, he already stated this before and explained it in the Wiki page.

`--disable-frame-rate-limit --use-angle=d3d9`
