### ISSUE TITLE
Pressing several keys at the same does not let you kick the ball

### ISSUE THREAD

**Issue by tenjiku2000** [haxball/haxball-issues#195]
If playing with arrows and kicking with X, it works perfectly: you can hold several (2-4) directions at once and you are allowed to kick the ball. However, when using the numpad (pretty useful if your keyboard's arrows are too small), X does not work if you hold more than one direction at the same time. So, if you are turning around the ball with accuracy (making you press left, right and right at the same time for a very brief moment) and want to kick the ball in that exact moment, you can't do it with X, nor with left shift. It does however work with right shift, which is not quite comfortable. There are other combinations of kicking keys not working when pressing 3+ directions on WASD.

**Comment by basro** [comment]
This is a limitation of your keyboard, and not really specific to HaxBall.
Test that same combination of keys in any other game and they wont work either.

**Comment by tenjiku2000** [comment]
Good to know, thanks! I tried it on three different keyboards and thought it was a problem of the game... It would be interesting to add a setting option where you could change the kicking key, then: players would be able to find the most suitable and comfortable way to play

**Comment by basro** [comment]
I agree
