### ISSUE TITLE
Not able to connect to any room since April 10th

### ISSUE THREAD

**Issue by botan777** [haxball/haxball-issues#1950]
Not able to connect to any room whatever the country. Before an update I was able to connect to at least every 2nd room and been playing without any problems: both ping and fps were just good. Diagnostic results have not changed since an update: yes yes and yes. VPN doesn't solve the problem at all, neither does browser changing. My router doesn't have an option to remove symmetric NAT but maybe there is just a little chance for it not to be a crucial moment? What else can I do just to return to the former "half-connected" level?

**Comment by botan777** [comment]
> Not able to connect to any room whatever the country. Before an update I was able to connect to at least every 2nd room and been playing without any problems: both ping and fps were just good. Diagnostic results have not changed since an update: yes yes and yes. VPN doesn't solve the problem at all. What else can I do just to return to the former "half-connected" level?

**Comment by Freitassss1** [comment]
i´ve got the same problem and i cant solve it...
