### ISSUE TITLE
The problem of not being able to communicate with BASRO

### ISSUE THREAD

**Issue by thecrewhaxball** [haxball/haxball-issues#1959]
First of all, greetings.

I've been trying to reach you for about 6 months. I am the owner of The Crew, Turkey's largest Haxball Community.You don't see the emails I sent. I reported inactive servers on your website, community page, and you made an update. But you still don't add a big Community like us.

The Crew : https://haxball.crewplays.com (The under construction)  /  discord.gg/crewmcn  / can.incirci@crewmcn.com

I'm waiting for your feedback.

kit.

**Comment by basro** [comment]
I'm sorry. The community page will be removed/replaced For this reason I will not be adding new links in there.

**Comment by thecrewhaxball** [comment]
Hi Basro,

If you are thinking of replaced that page we would like to be there after the update. With our team of 36 people, we spend a lot of effort for this.
