### ISSUE TITLE
HTML5: The relationship with Rec

### ISSUE THREAD

**Issue by Minion22** [haxball/haxball-issues#196]
I know how dificulty it is to update **REC** to HTML5, but HTML5 is lazy if all the maps major league can't use because it is impossible to record the games and we can only play HTML5 casually, but even so HTML5's Players already nears to 50% of Haxball. I am sure that with **REC's** update this percentage will improve 🕺 

When a player who love and wants to play HTML5 (like me) but have training to league, is heartily impossible to play HTML5 cause all the scene, camera (ping, fps too) is different (better) of Flash's. 
(Also to this dont be a completely-beg-useless topic) Im having issues with the camera's lag it is caused when I press to shoot and the ball backs (classic lag) but the camera follows the ball really fast then back this become confusing to perceive what is happening

So we beg u basrito, **REC** PLS!

**Comment by basro** [comment]
There's already an issue about replay recording: #1

I'm currently working on it, it will be released soon.
