### ISSUE TITLE
OffscreenCanvas for Haxball?

### ISSUE THREAD

**Issue by punisherhaxball** [haxball/haxball-issues#1966]
I don't know if you have heard about it but there is something called [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) which is really good for performance.

**Comment by basro** [comment]
While I was aware of them as a means of rendering in a web worker, I just took a fresh look at the docs and realized that maybe they can be used to achieve a similar result to the desynchronized canvas feature that only chrome implements.

I'll investigate this idea.

**Comment by basro** [comment]
I've tested this idea and unfortunately it doesn't work, the offscreen canvas has the same input lag as normal canvas.

**Comment by punisherhaxball** [comment]
But does it produce better performance?

**Comment by basro** [comment]
no
