### ISSUE TITLE
Is a big update coming?

### ISSUE THREAD

**Issue by kadavrahaxball** [haxball/haxball-issues#1967]
No update for 15 days. Does this mean there will be a big update?

**Comment by basro** [comment]
No, it doesn't mean that. I'm currently working on the backend, clearing some technical debt and working towards permanent room tokens.

It's not a flashy feature but it's going to be very useful to many. It will take me some time to finish.

**Comment by np-stacks** [comment]
> ...and working towards permanent room tokens.

Hey @basro, I was wondering if there's a way to get permanent tokens. I managed to retrieve a permanent token from friends, but I need more.
