### ISSUE TITLE
Replays format...

### ISSUE THREAD

**Issue by gandinaldinho** [haxball/haxball-issues#197]
Hello Basro, in this last update of the HTML5 version I noticed that the replays feature came back, and that's very good.
However, I also noticed that the format of the replays changed, now they are HBR2, so I could not open my replays in HBR format.
Does this mean that when the flash version is finished, we will not be able to see our old replays played in flash? It would be a great loss...

**Comment by basro** [comment]
You'll continue to be able to use the flash replay viewer in the haxball site to watch old replays. However most browsers will be completely removing flash support in the future, so eventually you'll need to have an older browser that still supports flash installed for when you want to watch old replays.
