### ISSUE TITLE
Here is the way to block opmode 

### ISSUE THREAD

**Issue by punisherhaxball** [haxball/haxball-issues#1977]
Basro, I have found this way before and it was %99 operational.

To block opMode all you have to do is compare host’s frame and players frame. Everytime players send input to the host they send with their current frame. And as you know opMode works like currentframe-somevalue so they always send minus value compared to what it should be.

It is easy to instantly give bad actor to the players if they replace their frameNo (not just minus value) but if they do for example frameNo - 1 and play with it the result becomes 2 or 3. A legit player never have 2 (hostframe-playerframe result). What it should be is 3 or 4 or 5. 

3 is kinda tricky because even if you dont use opmode your client can have 3 sometimes so that was blocking me to release the anticheat for that. What I ask you is please increase that difference in a way where legit players never have 3 frame difference. If you can do that I will release the anticheat codes, or even better with that logic you can create way more better version.

Trust me, we tried this with many players and it was %99 operational at blocking any kind of opMode usage. It was only having issues when players use it like frameNo-1 and all I am asking you is just make a workaround for it. Then there will be no opMode.

**Comment by punisherhaxball** [comment]
Currently I am at vacation, after 4 days I’ll reach home and I’ll send you anticheat codes from mail, then you can see what I mean.

**Comment by punisherhaxball** [comment]
Logical code: 
```

let hostFrame = 1300;
let playerFrame = some value here;
let result = hostFrame - playerFrame;

if (result == 5) {
// completely normal do nothing
}

if (result == 4){
// do nothing because it is normal
}

if (result == 3) {
check how many times this place is triggered, because if they use frame-1 their client have 3 result so its tricky 
}

if (result == 2) {
give bad actor, there is no way to have 2 frame difference
}
```

and same bad actor for 1 result too

**Comment by ghost** [comment]
This is the most important issue to solve. Instead of all these stupid cosmetic visual changes, please @basro, disable gaxball and other cheats, just focus on that, because they ruin your game.

I really appreciated Haxball cause it's the simplest and most football-like gameplay, but all these cheats kill the game and years of practice go to waste coz cheaters notoriously use "fake x" or ball shake.

Somebody please stop this...

**Comment by Anooxy** [comment]
exactly, all of those shitty changing pings to -1 or 6981923 and opmode like 5k extrapolation have to be deleted instead of changing json for stadiums..

**Comment by basro** [comment]
I'm aware of op mode, know how it works and I had already considered the solution you propose in here.
I don't want to discuss about the specifics publicly.

I will try to address it in the future.
