### ISSUE TITLE
Mention menu inaccessible

### ISSUE THREAD

**Issue by uzayyli** [haxball/haxball-issues#1991]
Hi, the pop-up menus when you type `@` or `#` are bounded by chat size, and don't scroll with arrow keys.. So some names are impossible to access. Probably needs absolute positioning or something.

Screenshot (using Firefox): [https://i.ibb.co/RhZxfZW/h.png](url)

![h](https://github.com/haxball/haxball-issues/assets/87779551/5def9f66-dcec-4483-834f-805b9a61328e)

**Comment by basro** [comment]
Thank you for reporting this!

**Comment by basro** [comment]
This should be fixed now.
