### ISSUE TITLE
Time when host want to close room

### ISSUE THREAD

**Issue by usmth** [haxball/haxball-issues#200]
Improve usability of haxball by adding optional setting in "+ Create Room" menu.

ex. Room name [End time]

**Comment by basro** [comment]
I don't think this would be useful, the host will rarely know how long they intend to keep the room online and they will often change their minds about it even if they were to set a time.

**Comment by usmth** [comment]
You're right. That's the reason, why I said about optional. But there is another important case, when host afk or left pc and keep the room for players.

I think about how hax can control empty rooms, which appear when all players left, and there is no host. So... Auto-close after n-time or give admin rights to random player (if somebody will join) without ban possibility?

That problem often happens.
