### ISSUE TITLE
How to skip recaptcha on headless??

### ISSUE THREAD

**Issue by kadavrahaxball** [haxball/haxball-issues#2001]
I'm usin puppeteer thing. But i dont know how to skip recaptcha. I put token into my bot script in HBInit but it doesnt skip recaptcha. My headless token is not expired. How can i skip recaptcha?

<img width="644" alt="Ekran Resmi 2023-06-15 19 09 07" src="https://github.com/haxball/haxball-issues/assets/128331759/d8c20647-40e4-4d9e-a97a-0e7dcd2a55cb">

**Comment by K0nfy** [comment]
I highly do not recommend you to create your own launcher from scratch. If you're planning to do any complicated stuff, you will need to communicate between node.js and bot.js, and it would be a really big mess for you. Stick to haxball.js. But if you want you can inspect the code below. It is a piece that I've made when I was in your place, and I'm using it a while already, but there are some missing parts here. Patching them is up to you

#### node.js
```js
// to avoid "HBInit is undefined" at some cases.
// default wait time is 10 seconds
const waitForHaxballApiInit = async (page, maxWaitTime = 10 * 1000) => {
  await page.evaluate(() => {
    const startTime = Date.now();

    return new Promise((resolve, reject) => {
      (function loop() {
        if (window.HBInit) return resolve();

        // retry if it's less than N miliseconds spent on retries
        if ((Date.now() - startTime) < maxWaitTime) return setTimeout(loop);

        // probably never possible, but this is better than endless loop
        reject(new Error('Hax API object does not appear'));
      }());
    });
  });
}

const applyGameBot = async (page, token) => {
  // this will make a window.botConfig object with a token inside.
  // you can pass here much more when you'll need to
  await page.evaluate((botConfig) => {
    window.botConfig = botConfig;
  }, {
    token,
  });

  // rewrite this part however you want
  await page.evaluate(
    await fs.promises.readFile('./src/script/bot.js', 'utf8')
  );
}

const getRoomLink = async (page, maxWaitTime = 10 * 1000) => {
  const frameHandle = await page.waitForSelector('iframe');
  const frame = await frameHandle.contentFrame();
  const roomLinkHandle =
    await frame.waitForSelector('div a', { timeout: maxWaitTime });

  return await roomLinkHandle.evaluate(el => el.href);
}

try {
  await page.goto('https://www.haxball.com/headless', {
    waitUntil: 'networkidle0',
    timeout: 20000,
  });

  await waitForHaxballApiInit(page);
  await applyGameBot(page, token);

  console.log(await getRoomLink(page));
} catch (e) {
  await browser.close();
  console.error(e);
}
```

#### bot.js
```js
HBInit({ roomName: "My room", maxPlayers: 16, token: window.botConfig.token });
```

**Comment by K0nfy** [comment]
Also, my first answer is not really an answer for the question. Your code problem is that your token is not being passed from `node.js` to `bot.js`. They have a two completely different contexts that you can communicate between via `page.evaluate`, `page.exposeFunction`, maybe something more, I don't remember

**Comment by kadavrahaxball** [comment]
> I highly do not recommend you to create your own launcher from scratch. If you're planning to do any complicated stuff, you will need to communicate between node.js and bot.js, and it would be a really big mess for you. Stick to haxball.js. But if you want you can inspect the code below. It is a piece that I've made when I was in your place, and I'm using it a while already, but there are some missing parts here. Patching them is up to you
> 
> #### node.js
> ```js
> // to avoid "HBInit is undefined" at some cases.
> // default wait time is 10 seconds
> const waitForHaxballApiInit = async (page, maxWaitTime = 10 * 1000) => {
>   await page.evaluate(() => {
>     const startTime = Date.now();
> 
>     return new Promise((resolve, reject) => {
>       (function loop() {
>         if (window.HBInit) return resolve();
> 
>         // retry if it's less than N miliseconds spent on retries
>         if ((Date.now() - startTime) < maxWaitTime) return setTimeout(loop);
> 
>         // probably never possible, but this is better than endless loop
>         reject(new Error('Hax API object does not appear'));
>       }());
>     });
>   });
> }
> 
> const applyGameBot = async (page, token) => {
>   // this will make a window.botConfig object with a token inside.
>   // you can pass here much more when you'll need to
>   await page.evaluate((botConfig) => {
>     window.botConfig = botConfig;
>   }, {
>     token,
>   });
> 
>   // rewrite this part however you want
>   await page.evaluate(
>     await fs.promises.readFile('./src/script/bot.js', 'utf8')
>   );
> }
> 
> const getRoomLink = async (page, maxWaitTime = 10 * 1000) => {
>   const frameHandle = await page.waitForSelector('iframe');
>   const frame = await frameHandle.contentFrame();
>   const roomLinkHandle =
>     await frame.waitForSelector('div a', { timeout: maxWaitTime });
> 
>   return await roomLinkHandle.evaluate(el => el.href);
> }
> 
> try {
>   await page.goto('https://www.haxball.com/headless', {
>     waitUntil: 'networkidle0',
>     timeout: 20000,
>   });
> 
>   await waitForHaxballApiInit(page);
>   await applyGameBot(page, token);
> 
>   console.log(await getRoomLink(page));
> } catch (e) {
>   await browser.close();
>   console.error(e);
> }
> ```
> 
> #### bot.js
> ```js
> HBInit({ roomName: "My room", maxPlayers: 16, token: window.botConfig.token });
> ```

the problem is this, when i use haxball.js we cant play in my room because of lag, if i open my room on chrome without discord and haxball.js integration it doesnt lag. Idk, maybe haxball.js doesnt cause this, maybe its problem of my terminal. I'm not sure its because haxball.js but im trying to find a way to open my discord integrated room with no lag .
