### ISSUE TITLE
How to load edited headless min js file for puppeteer method

### ISSUE THREAD

**Issue by kadavrahaxball** [haxball/haxball-issues#2002]
Everything is okay. But i cant find the way to use my edited headless min js file.
<img width="506" alt="Ekran Resmi 2023-06-18 22 31 39" src="https://github.com/haxball/haxball-issues/assets/128331759/83bf5293-074c-4fc6-b6ef-8ac46258b695">

**Comment by kadavrahaxball** [comment]
yesss i found the way

**Comment by kadavrahaxball** [comment]
yessss i found the way.

**Comment by punisherhaxball** [comment]
Share solution for future issues then…
