### ISSUE TITLE
afk status based on the map's coordinates

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#2004]
Hello, I have a general knowledge quiz bot. When the question is asked by the bot, I want the bot to automatically take the players to the spectator if they don't move for 4 seconds, to prevent the players from copying from google. 

 The problem is that I only want it to do this at certain coordinates of the map.
When the contestant goes to any of the answers, it doesn't matter whether he moves or not. I want this to only affect players who haven't answered the question yet. 

Is it possible to write such code?

I couldn't do it despite trying for days. To be honest, I'm a bit of a novice. Anyone want to contact me to help me with this?

**Comment by ghost** [comment]
Anyone want to help? :/ I'm still trying and I couldn't.

**Comment by SLNMX** [comment]
Well you can try the next approach

https://github.com/thenorthstar/HaxBall-Example-Scripts/blob/main/Beginner/ZoneCheck.js


This is from TheNorthstar examples scripts. My logic would be to create a big marked zone where they are afk therefore the other zones if would be ok.

Some measurement would be needed. Now, I am not sure that you can create zones that are not a four-corner figure...
