### ISSUE TITLE
cool avatar

### ISSUE THREAD

**Issue by peppewarrior1** [haxball/haxball-issues#2007]
Greetings. A few days ago I saw a player who had a very cool character as an avatar. I looked for it together with a friend of mine and I found it (⨳)only that compared to him it is very small. Do you know if there is the real character or if it is possible to enlarge the avatar?
![Immagine WhatsApp 2023-06-22 ore 01 53 52](https://github.com/haxball/haxball-issues/assets/68575316/3bf0c8dd-a2ed-4ae3-a46e-b39c023a35cd)

**Comment by peppewarrior1** [comment]
![Immagine WhatsApp 2023-06-26 ore 17 49 39](https://github.com/haxball/haxball-issues/assets/68575316/9cf853de-4c28-416e-9c27-c0215eb66e6b)
:(

**Comment by Warrior3093** [comment]
> Greetings. A few days ago I saw a player who had a very cool character as an avatar. I looked for it together with a friend of mine and I found it (⨳)only that compared to him it is very small. Do you know if there is the real character or if it is possible to enlarge the avatar? ![Immagine WhatsApp 2023-06-22 ore 01 53 52](https://user-images.githubusercontent.com/68575316/248832254-3bf0c8dd-a2ed-4ae3-a46e-b39c023a35cd.jpg)

I found some cool avatars at https://www.reddit.com/r/haxball/comments/ht4x2k/some_haxball_avatars_if_anyone_cares/

**Comment by peppewarrior1** [comment]
> > Greetings. A few days ago I saw a player who had a very cool character as an avatar. I looked for it together with a friend of mine and I found it (⨳)only that compared to him it is very small. Do you know if there is the real character or if it is possible to enlarge the avatar? ![Immagine WhatsApp 2023-06-22 ore 01 53 52](https://user-images.githubusercontent.com/68575316/248832254-3bf0c8dd-a2ed-4ae3-a46e-b39c023a35cd.jpg)
> 
> I found some cool avatars at https://www.reddit.com/r/haxball/comments/ht4x2k/some_haxball_avatars_if_anyone_cares/

I'm looking for these two avatars though

**Comment by peppewarrior1** [comment]
> ![Immagine WhatsApp 2023-06-26 ore 17 49 39](https://user-images.githubusercontent.com/68575316/248864271-9cf853de-4c28-416e-9c27-c0215eb66e6b.jpg) :(

𒐫

**Comment by peppewarrior1** [comment]
> Greetings. A few days ago I saw a player who had a very cool character as an avatar. I looked for it together with a friend of mine and I found it (⨳)only that compared to him it is very small. Do you know if there is the real character or if it is possible to enlarge the avatar? ![Immagine WhatsApp 2023-06-22 ore 01 53 52](https://user-images.githubusercontent.com/68575316/248832254-3bf0c8dd-a2ed-4ae3-a46e-b39c023a35cd.jpg)

𒐦
