### ISSUE TITLE
afk players code /  where am i doing wrong?

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#2008]
```js
var room = HBInit({
    roomName: "TEST",
    maxPlayers: 30,
    noPlayer: true,
    public: false,
  });

var AFK_TIMEOUT = 4000; // Hareketsizlik zaman aşımı (4 saniye)
var afkTimers = {}; // Hareketsizlik zamanlayıcıları

room.onPlayerJoin = function(player) {
  afkTimers[player.id] = setTimeout(function() {
    room.setPlayerTeam(player.id, 0); // Oyuncuyu spectator kısmına al
  }, AFK_TIMEOUT);
};

room.onGameStart = function(player) {
  afkTimers[player.id] = setTimeout(function() {
    room.setPlayerTeam(player.id, 0); // Oyuncuyu spectator kısmına al
  }, AFK_TIMEOUT);
};

room.onGamePause = function(player) {
clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını sıfırla
};

room.onPlayerActivity = function(player) {
  clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını sıfırla

  afkTimers[player.id] = setTimeout(function() {
    room.setPlayerTeam(player.id, 0); // Oyuncuyu spectator kısmına al
  }, AFK_TIMEOUT);
};

room.onPlayerLeave = function(player) {
  clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını temizle
};                                                                                    
``` 

This code only works correctly for the first person ( admin ) to enter the room. When the game is started, afk players in the room are not taken to the spectator. The code only works if they become afk after making the first move. 

How do I make afk timer work for all players as soon as the game starts?

**Comment by basro** [comment]
The argument to onGameStart is only the player who did the game start action. You are resetting that player's afk timer but not anyone elses. You should reset the timer for all players.

**Comment by Anilcanbrsn** [comment]
`var room = HBInit({
    roomName: "TEST",
    maxPlayers: 30,
    noPlayer: true,
    public: false,
  });

var AFK_TIMEOUT = 4000; // Hareketsizlik zaman aşımı (4 saniye)
var afkTimers = {}; // Hareketsizlik zamanlayıcıları

room.onPlayerJoin = function(player) {
  afkTimers[player.id] = setTimeout(function() {
    room.setPlayerTeam(player.id, 0); // Oyuncuyu spectator kısmına al
  }, AFK_TIMEOUT);
};

room.onGamePause = function(player) {
clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını sıfırla
};

room.onPlayerActivity = function(player) {
  clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını sıfırla

  afkTimers[player.id] = setTimeout(function() {
    room.setPlayerTeam(player.id, 0); // Oyuncuyu spectator kısmına al
  }, AFK_TIMEOUT);
};

room.onPlayerLeave = function(player) {
  clearTimeout(afkTimers[player.id]); // Oyuncunun zamanlayıcısını temizle
};
`
