### ISSUE TITLE
Ball going through the wall

### ISSUE THREAD

**Issue by MoisesAsafi** [haxball/haxball-issues#2010]
When I shoot well in that corner, the ball goes through the wall 100% of the time. I've already tried to make an invisible wall back there but it still goes through... Does anyone know what I edit so the ball doesn't go through?

![image](https://github.com/haxball/haxball-issues/assets/68512914/93abc431-4c7d-443f-99a1-e8c721373fbe)

**Comment by basro** [comment]
Have you tried using the [bias](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#bias--float) property?

**Comment by MoisesAsafi** [comment]
Sorry! It worked by bias
