### ISSUE TITLE
room.onPlayerPositionChange feature request

### ISSUE THREAD

**Issue by ghost** [haxball/haxball-issues#2011]
The coordinates of the players on the map can only be printed on the console when they use their own keyboard. However, if a player in the game pushes the other player or if any ground or object in the game pushes the player, that is, changes its position, the last coordinate of the player cannot be printed on the console.
The player is counted as not moving. 

A new function is needed to detect this.

@basro

english is not my first language sorry for mistakes

**Comment by basro** [comment]
You can do this by remembering what the previous position was and comparing it in onGameTick.
