### ISSUE TITLE
New way to run code

### ISSUE THREAD

**Issue by Khoi13** [haxball/haxball-issues#2015]
Instead of run code through the console, why don’t the upload a folder, with an index.js file in it. That means js module is support so we can split the code into small files, easier to maintain

**Comment by uzayyli** [comment]
Not sure if it helps but most browsers support drag-and-drop on console. Just drag your .js file in your console and it will act like copy-pasting the code in it.

**Comment by mertushka** [comment]
There is a native Haxball Headless API implemantation for Node.JS: [haxball.js](https://github.com/mertushka/haxball.js) 😀

**Comment by Khoi13** [comment]
> There is a native Haxball Headless API implemantation for Node.JS: [haxball.js](https://github.com/mertushka/haxball.js) 😀

Its gud
