### ISSUE TITLE
Joining Errors delay

### ISSUE THREAD

**Issue by enes05** [haxball/haxball-issues#202]
joining the rooms is very hardly it's kee pwaiting me very much it says trying reverse connection because this game has vpn blocking when i work to enter with vpn im getting master connection error plz remove vpn protection also i don't use vpn even im entering the rooms hardly (sry bad english)

**Comment by basro** [comment]
I have no idea what you are asking.

**Comment by enes05** [comment]
@basro fix it
![screenshot 3](https://user-images.githubusercontent.com/19493347/34518448-88c1c9e0-f090-11e7-8f36-71ce1166ba5b.png)
![screenshot 2](https://user-images.githubusercontent.com/19493347/34518451-8b570d32-f090-11e7-8ff5-1e3b9b4f7860.png)

**Comment by enes05** [comment]
@basro fix it plz i dont asking im telling the problem but my england is bad there is connection problem

**Comment by basro** [comment]
@enes05, this is most likely a problem with your router, and not something I can fix...
For example try connecting to a friend using this other webrtc application: http://cdn.peerjs.com/demo/chat.html

**Comment by enes05** [comment]
i restarted modem router still same
