### ISSUE TITLE
Issue with the room.onroomlink or Idk what it is

### ISSUE THREAD

**Issue by SLNMX** [haxball/haxball-issues#2031]
Hello.

Once again I come up with a question... I am currently the manager of some rooms across LATAM, but I've got some questions in order to enhance both what is shown to the people and what I am trying to achieve.

<img width="587" alt="Screen Shot 2023-07-25 at 21 42 47" src="https://github.com/haxball/haxball-issues/assets/123231321/526ce89e-0eb7-468b-9642-a33ac5bd20bf">

I don't know why it sends the link a lot of times... Is it possible to make it send just once?

**Comment by ghost** [comment]
You're sending it when you receive a RoomLink event, right? I believe it is dispatched every time the room connects to the game's backend, which can happen many times if the connection drops. (@basro please correct me if I'm wrong)

To achieve what you want, you can create a variable (flag) with a falsy value and check in the RoomLink handler if its value is not truthy. If it is not, you set it to a truthy one and send the Discord webhook. This way, the code block will only run once.

**Comment by SLNMX** [comment]
Oh that's a nice trick. I'll do it that way :) thanks.
