### ISSUE TITLE
Problem with giving a player admin (headless host)

### ISSUE THREAD

**Issue by Fluffyboiiiiii** [haxball/haxball-issues#2032]
Hello everyone! i've been trying to code something so only 1 person can host the room at a time by typing "!admin"
I've seen lots of servers do this and i just can't do it. 
Thanks in advance!!

**Comment by gokdenizuzunoglu** [comment]
When a player types "!admin", give this player admin if room has no admin player.
```js
room.onPlayerChat = (player, message) => {
    var players = room.getPlayerList();
    if (message === "!admin") {
        if (!players.some(p => p.admin)) { // check if room has no admin
            room.setPlayerAdmin(player.id, true);
        }
    }
}
```
