### ISSUE TITLE
A Question About room.onGameTick()

### ISSUE THREAD

**Issue by thenorthstar** [haxball/haxball-issues#2042]
Hello everyone. I have a question about the famous event handler named **room.onGameTick**. So, as an attachment I will share a video link to make you saw what happens and then reply: https://haxball-replay-analyzer.github.io/?replayId=43194

OK, firstly my problem isn't advertising myself or asking for other ways like using **Date.now()** or **performance.now()** to get a timespan; just gonna ask how to get the current game time as a floating number ending with 2, 4, 7 or 9 with only using this game tick. For example in this video you see a floating number ending with **33** but it may not end with 33, may end with 34, 35 or something else but the current API doesn't allow us to see numbers between some tick points. For more detail, you can just see the following numbers as the last 2 digits of any floating number:
**.00**
**.17**
**.33**
**.50**
**.67**
**.83**

This means exactly 94 different numbers are lost in this scope. I will appreciate any reasonable comments or ideas, thanks from right now.

**Comment by basro** [comment]
game ticks are 1/60 seconds long, you'll only see multiples of that fraction

**Comment by thenorthstar** [comment]
> game ticks are 1/60 seconds long, you'll only see multiples of that fraction

@basro I know why it happens, just asking for a solution. Apparently another issue will be closed without any solution, OK.
