### ISSUE TITLE
Question about network ip

### ISSUE THREAD

**Issue by cnkelvin** [haxball/haxball-issues#2043]
I have a brother and in some rooms automated by bots they get the network ip instead of the computer. Is there already a functionality that gets only the computer's ip?

**Comment by iSebek** [comment]
Hi, there are multiple approaches available for achieving this task, such as editing the 'headless-min' file and more. However, I believe the most straightforward method involves converting the 'conn' you obtain from the 'onPlayerJoin' event.

`const ipConverter = (conn) => {
  const connString = conn.toString();
  let ip = '';

  for (let i = 0; i < connString.length; i += 2) {
    const connStringByte = connString.slice(i, i + 2);
    const ipByte = String.fromCharCode(parseInt(connStringByte, 16));
    ip += ipByte;
  }

  return ip;
};`
