### ISSUE TITLE
Cant Start haxball

### ISSUE THREAD

**Issue by Gollok** [haxball/haxball-issues#205]
Hello,
I am German People so dont be afraid of my English.
I go at haxball.com and than comes you need to install Adobe Flash Player 10 , i have it install and still seeing this message. It is in Javascript enabled. Please Help ;(

**Comment by drivfe** [comment]
go to http://html5.haxball.com

**Comment by Gollok** [comment]
And the FLASH Rooms?

**Comment by basro** [comment]
@Gollok, what browser are you using?
In some browsers you might need to click the "install flash player" button so that the browser will ask you if you want to activate flash player on haxball.com.

**Comment by Gollok** [comment]
Chrome

**Comment by Gollok** [comment]
Or Opera

**Comment by basro** [comment]
In chrome click on the get adobe flash player button, that will make a popup appear that asks if you want to enable flash player in haxball.com, click yes and then it will work.

**Comment by Gollok** [comment]
Thank you very much!
