### ISSUE TITLE
browser error?

### ISSUE THREAD

**Issue by Gimenez20** [haxball/haxball-issues#2070]
![image](https://github.com/haxball/haxball-issues/assets/55249793/f3b75798-86ff-4004-b1ac-5aa8ce746f16)
I have this error always that i create the rooms.

Is not a code problem because i used the same code yesterday and it works.

Maybe the browsers cant detect the player.id for some reason that i dont know.

I have tested with brave, chrome, opera, yandex, vivaldi and it has the same error.

I dont know that is haxball headless error or browsers error.

I used the latest version for all browsers.

**Comment by basro** [comment]
It should be fixed now.

**Comment by Gimenez20** [comment]
what problem was? @basro for ask if happens in the future

**Comment by basro** [comment]
I had accidentally changed the default for the noPlayer option in the HBInit function to false.

It shouldn't happen again.
