### ISSUE TITLE
Stuck on the green screen, I can't enter the game.

### ISSUE THREAD

**Issue by teslavargas** [haxball/haxball-issues#2085]
![image](https://github.com/haxball/haxball-issues/assets/72205075/9a81f479-40fd-4dc3-baff-fce98ae061e7)

I am using Google Chrome. From incognito it works normally.

**Comment by ghost** [comment]
When did this start to happen?
Does it happen when you load the website or when you try to join a room?
Do you have any extension enabled on your browser?
Are all first-party requests succeeding? (e.g. javascript files)
Is some meaningful error or warning being written to the console?

This may sound silly but maybe for some weird reason your cached files aren't updated to the latest version. Try clearing the website's data to see if it loads normally.

**Comment by teslavargas** [comment]
I disabled the cache and it worked again. Thank you!
