### ISSUE TITLE
Feature Request - onPlayerConnect Event and Return Reason

### ISSUE THREAD

**Issue by hisham-tareqz** [haxball/haxball-issues#2096]
### Description

I would like to propose the addition of a new feature, specifically the inclusion of an onPlayerConnect event. This event would serve a distinct purpose from the existing onPlayerJoin event by triggering before it.

### Details

- **Event Name:** `onPlayerConnect`
- **Purpose:** To execute custom code or handle actions before a player officially joins the room.
- **Parameters:**
  - player: PlayerObject
  
### Example Usage

```javascript
room.onPlayerConnect = function (player) {
    return "Connection not allowed due to a custom reason.";
}
```
### Motivation
The onPlayerConnect event is proposed to precede the onPlayerJoin event, providing developers with the ability to control the connection process before it is finalized. This is crucial for scenarios where a return reason needs to be provided to the player, preventing the completion of the join process.

### Return Reason

If the onPlayerConnect event returns a reason (e.g., "Connection not allowed due to custom reason."), the player will not proceed to join the room. Instead, the specified reason will be displayed to the player. This helps maintain a clean chat box.

### Comparison with onPlayerJoin:

While the onPlayerJoin event lacks a return mechanism, the proposed event fills this gap by allowing developers to control whether a player can join based on specific conditions.

###### Thank you for considering this feature request.

**Comment by Anooxy** [comment]
lol, u can make your own function or return false, theere's no reason to update it//

**Comment by hisham-tareqz** [comment]
Give me an example, I don't know what's funny!
