### ISSUE TITLE
What is the name of the player's outside line?

### ISSUE THREAD

**Issue by genjutsus** [haxball/haxball-issues#2115]
![image](https://github.com/haxball/haxball-issues/assets/154602378/4782a4eb-714f-4a04-bacf-d89b1cf14557)

Is there a class for this transparent circular line? Or a way to target it?

**Comment by basro** [comment]
There is not, it is hardcoded in the renderer

**Comment by genjutsus** [comment]
But I already saw a code (in Greasemonkey repository iirc) that removed that line. How is this possible?

**Comment by basro** [comment]
Greasemonkey has the ability of replacing the game code (the hardcoded render being a part of it) with something else. I do not recommend or approve of such modifications.

**Comment by genjutsus** [comment]
> Greasemonkey has the ability of replacing the game code (the hardcoded render being a part of it) with something else. I do not recommend or approve of such modifications.

This line doesn't serve any purpose and worsen the gameplay. Some modifications to the game are malicious, but removing this line is not. What is it's name inside the hardcoded render?
