### ISSUE TITLE
Hide host events

### ISSUE THREAD

**Issue by fedMiranda** [haxball/haxball-issues#2130]
I'd like to hide messages from the host like :

"Game started"

"x was moved to Spectators"

"y was moved to Spectators"

Is there an option?

**Comment by hisham-tareqz** [comment]
No, you can't do that. These modifications are only possible on the client-side ([`game-min.js`](https://www.haxball.com/wzwh85f6/__cache_static__/g/game-min.js)) and will reflect only on the client and not everyone.
