### ISSUE TITLE
What will happen to haxball in the future?

### ISSUE THREAD

**Issue by abisrc** [haxball/haxball-issues#2150]
Hello, you probably know the game HaxBall, a 2D multiplayer soccer game that is characterized by being simple and entertaining.

I (owner of this project) have been playing HaxBall for about 3-4 years and it has become one of my favorite games due to its entertaining gameplay and community.

However, unfortunately, during my time playing, I have noticed that HaxBall does not receive constant updates, although Basro has always been aware of the community by making small updates and helping when haxball has a bug. This disappointed me a lot, the game has a lot of potential and could easily be an esports game. Although the creator (@basro) refuses to update the game, it is not his fault, haxball has been alive for more than 14 years and completely free, although updating the game is very important so that it does not lose visibility.

For these things, I have decided to open my project for a 2D multiplayer soccer game, with air-hockey style physics, although this is not all.
My idea is to create a project for the community, with ideas from the community and for now I have some ideas in mind such as:

- More compatibility:
Although haxball is compatible with PC and Mobile, this is not completely official. The web version is the only official version of these, the clients and the cell phone version are not official and may have some other errors, either optimization or vulnerability (in addition, they are not official from Haxball and are not approved by Basro).

- Different mechanics:
I plan to make the game more customizable than haxball already is, making maps, t-shirts, rooms (I understand that I will also use WebRTC to establish the connections) and more.

And more things for the community such as account systems, security (currently in haxball they can easily get your IP through a room) and other things, I need ideas from the community and things they would like to implement.

If you are interested in following the project, you can[ join the discord server](https://discord.gg/ZVXRKQ9U6M) either to stay up to date on the project or to contribute ideas.

Thank you so much! <3

**Comment by basro** [comment]
Don't use the issue tracker to promote your competing project.
