### ISSUE TITLE
Missing TraitsObject Documentation

### ISSUE THREAD

**Issue by RicardoPinto26** [haxball/haxball-issues#2187]
As per the [Stadium Documentation](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#traits--traitsobject), there should be some documentation on TraitsObject, but I am unable to find it.

I am currently updating @types/haxball-headless-browser to include the stadium definition, but without this documentation, I am unable to complete it.

Seems like this has been an issue since 2019 #833, so the documentation might not exist.

**Comment by basro** [comment]
Thanks for pointing it out, I've written documentation for it now.
