### ISSUE TITLE
Bad host, but perfect ping

### ISSUE THREAD

**Issue by cofimaslisa** [haxball/haxball-issues#219]
My ping in any other room since html5 is good, BUT when i host a room, when there are above 5 players, it starts to spike and lag for my players, NOT FOR ME. What to do to fix this? My internet speed is the same, i never had a problem with only 6 persons in room, only 12 and above, and now i cant even host normally 2v2 with more than 5 players

**Comment by olegmisar** [comment]
The same problem

**Comment by basro** [comment]
This means your internet connection is unable to handle the bandwidth requirements.
There's not much that can be done on my end.
