### ISSUE TITLE
Every player kicked due to "bad actor"

### ISSUE THREAD

**Issue by saviola777** [haxball/haxball-issues#22]
In a room with ~10 players, every single player was automatically kicked (reason: bad actor) by the host. Everyone could re-join afterwards and we played for ~10 minutes before and after that, it happened only once.

For one player it said he was kicked, for me the sound stopped (ball was kicked but no sound), shortly afterwards the game was paused, then nothing happened. I was not kicked but I could not write or unpause the game, I had to rejoin.

**Comment by basro** [comment]
This is clearly a bug, unfortunately I'm not sure why it happens.

The game will kick players with bad actor message when it detects that they are doing something "malicious". (either flooding or sending broken messages) This system is in place to prevent room DoS.

Obviously something went wrong with it. If someone can find a way to reproduce this reliably it would be very helpful.

**Comment by basro** [comment]
I've released an update which should fix this issue but I'm unsure since it's hard to reproduce.
Please report if it continues to happen in rooms created from now on.

**Comment by saviola777** [comment]
Sorry, haven't been able to play a lot since then and the problem didn't occur again. Since there don't seem to be other reports of similar behavior, it may be fixed. Feel free to close this issue or keep it open a while longer.
