### ISSUE TITLE
Can't join rooms when there is only 1 slot available

### ISSUE THREAD

**Issue by kalqsko** [haxball/haxball-issues#221]
Hey so I can never join rooms when there is only one free slot because it says the room is full, but it's not. Other players can join and if there are 2 or more slots I can join as well. It's only happening on the html hax and it only seems to be happening to me.

**Comment by basro** [comment]
I think I have a good idea about why this would happen.
I believe enabling this the reverse connection setting [>here<]{http://html5.haxball.com/reverse_setting.html} would allow you to bypass this problem.

I'll be fixing this in the future.

**Comment by basro** [comment]
This bug should now be fixed.
