### ISSUE TITLE
Ability to set semi-transparent discs or joints? (Stadium editor)

### ISSUE THREAD

**Issue by studiorafa** [haxball/haxball-issues#2216]
I need to make a semi transparent joint that is a line on the map, however, it seems that there are only transparent joints.

I know that if you set the color to "transparent" it's no longer visible. Not only that, but I've tried setting it to -1, or -0.5, and it doesn't work, which I've seen in some places that -1 means transparent.

Setting the value into the file directly also doesn't work.
![image](https://github.com/user-attachments/assets/774cd3f4-c8e3-4444-abcf-f6099b27d2c2)

**Comment by ChasmSolacer** [comment]
There is no semi-transparency here.
If you set [color](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#color) to a negative number, the game translates to 0, which is #000000 (black). If you set it to "transparent", the game transtales it to -1, which tells the game that disc is transparent. The `-1` is not meant to be inserted in the .hbs file, it is used to dynamically change the [disc color](https://github.com/haxball/haxball-issues/wiki/Headless-Host#color--int) in the Headless Host console

**Comment by damian18zb** [comment]
I envy you that you have such problems, in Europe we are fighting with cloned rooms and bot attacks 🫤

**Comment by sefinek** [comment]
@damian18zb, i think this might be a good moment to take a break and optionally touch some grass <3 🐗🐗🐗

**Comment by damian18zb** [comment]
@sefinek you don't know me so please stop responding to all my comments in such a negative manner.

**Comment by sefinek** [comment]
@damian18zb You probably don't know what a negative manner means. btw, there's something called freedom of speech. You won't limit me

**Comment by studiorafa** [comment]
> I envy you that you have such problems, in Europe we are fighting with cloned rooms and bot attacks 🫤

I had an idea some days ago of a google extension that makes a log in system in haxball with recaptcha and other security measures. It should be able to communicate with the server it's trying to join so that we can actually have a secure system as well as banning

**Comment by studiorafa** [comment]
> There is no semi-transparency here. If you set [color](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#color) to a negative number, the game translates to 0, which is #000000 (black). If you set it to "transparent", the game transtales it to -1, which tells the game that disc is transparent. The `-1` is not meant to be inserted in the .hbs file, it is used to dynamically change the [disc color](https://github.com/haxball/haxball-issues/wiki/Headless-Host#color--int) in the Headless Host console

Thank you, i thought that there was a way to set it to a number
