### ISSUE TITLE
haxrec.com - can't upload hbr2 files.

### ISSUE THREAD

**Issue by ArshileG** [haxball/haxball-issues#224]
We need haxrec like system to have match preview links.

**Comment by haxballer** [comment]
On my forum we made this type of player, so far you can use this as a guest.

`http://thehax.pl/forum/powtorki.php`

**Comment by ArshileG** [comment]
Can you give script to use on our site?(with credits probably)

**Comment by haxballer** [comment]
It's not possible. My friend worked hard to get this effect, it is to help in the promotion of our forum, which exists for over 3 years. We don't provide the script, certainly not for free, because we spent a lot of time on it.

Have fun using our work. (:

**Comment by haxballer** [comment]
@ArshileG, it's not possible. My friend worked hard to get this effect, it is to help in the promotion of our forum, which exists for over 3 years.

Have fun using our work.

**Comment by ArshileG** [comment]
Don't you know about site, that was counting passes shots and other things?!

**Comment by haxballer** [comment]
I don't know such a site. It's possible that in the future we will develop our player and will be able to do so. I can't tell you more.
