### ISSUE TITLE
Changing the goal line rule

### ISSUE THREAD

**Issue by cofimaslisa** [haxball/haxball-issues#225]
many of players are wondering and willing for this to happen, since in every sport, ball must cross the line fully to recognise the goal, the feature in this game would be awesome and fair to all teams, not to pass over 50%.

**Comment by usmth** [comment]
...
#185

**Comment by r2308145** [comment]
yeah, this was already suggested but @basro said he won't be changing the goal line rule for the default maps

**Comment by rwiebe-va** [comment]
![slow short](https://user-images.githubusercontent.com/15327741/37854402-6532ccb4-2eb0-11e8-9544-34c715ca95fe.gif)

**Comment by cofimaslisa** [comment]
If you ask me, in every sport ball must pass the whole line, so this rule is very very unfair

**Comment by Leo-MapCreator** [comment]
@cofimaslisa About your 1st comment, i dont think this is unfair, both teams are set to the same rules, its not a rule for the Red and a rule for the Blue, both of them have the same 'problem'
