### ISSUE TITLE
Master connection error.

### ISSUE THREAD

**Issue by petric971** [haxball/haxball-issues#229]
Hello. I have a problem with connecting to server HTML5 in haxball. When i click a room hmtl5 I get an error: "Master connection error" How fixed it?

**Comment by basro** [comment]
I just released a new version which might fix this issue for you, please tell me if you still can't connect.

**Comment by petric971** [comment]
Problem solved. Thanks for released a new wersion. Everything works.

**Comment by basro** [comment]
Terrific

**Comment by iscoman** [comment]
me either, "master connection error"
also when i open my own host, it says "waiting for link" when i try to copy the url.

**Comment by basro** [comment]
What browser and OS are you using?

Does this site work for you? https://websocket.org/echo.html
Try connecting and then sending a message.

You should see this text:
```
CONNECTED
SENT: Rock it with HTML5 WebSocket
RECEIVED: Rock it with HTML5 WebSocket
```

**Comment by Avelium** [comment]
Same "Master connection error" here. Windows 8.1, both Chrome and Opera. However, using VPN clearly removes this problem. 

Also please note that I'm from Russia and this connection issue appeard right after couple of days when our local "Service for Supervision of Communications" named Roskomnadzor start to block millions of IP-s somehow "related" to Telegram messenger. The "funniest" part is that this action did not affect Telegram itself but broke access to many different sites and applications for russian users.

Of course it could be just a coincident but... who knows?

**Comment by basro** [comment]
@softwarereality, @iscoman are you also from Russia?

**Comment by basro** [comment]
@Avelium: does https://websocket.org/echo.html work for you?

**Comment by Avelium** [comment]
@basro, yes, it works fine.
https://imgur.com/rtEMVtv

**Comment by basro** [comment]
@Avelium: http://p2p.haxball.com/test does this page load and print OK?

**Comment by basro** [comment]
Yeah, not much I can do if you can't even communicate with my server.
You should contact your ISP about it.

**Comment by Avelium** [comment]
@basro, roger that. Thank you for your time! :)

**Comment by iscoman** [comment]
basro for some reason a few hours after i wrote that message the html5 haxball got fixed..
i had this error for a few days, didn't do anything but it works now! thanks

**Comment by softwarereality** [comment]
I fucking love this game, but the errors do not allow me to go into any room ...

**Comment by basro** [comment]
@softwarereality, do you get a response if you visit this link? http://p2p.haxball.com/test

**Comment by softwarereality** [comment]
barso, Nope!

**Comment by softwarereality** [comment]
barso, yes

**Comment by basro** [comment]
I've now read a bit more and informed myself about the situations that @Avelium mentioned, it is indeed as he said, the Russian goverment has started blocking huge amount of ips in order and the haxball server has been hit by those ip blocks.

@softwarereality, if you are in Russia this is the most likely cause of your problem.

**Comment by iscoman** [comment]
hi basro, after a month without any errors i got this "master connections error" again.
im not from russia, using win 7 and chrome.
i got this again right after i've been playing a few haxball flash games, that could be maybe the cause for this error?
i can play html5 from firefox but its not as good as chrome for me. thanks^^

**Comment by loreberto2011** [comment]
same problem baby
