### ISSUE TITLE
Flash or HTML5. Have to decide.

### ISSUE THREAD

**Issue by Minion22** [haxball/haxball-issues#230]
HTML5 is already 90% **perfect**. We still have some dreams for sure, but nothing too necessary.
No **fatal** bugs.

Now we (HTML5) are **60%** (and getting more) of HaxBall;

HTML5 has a **perfectly** sync with Google Chrome (Most popular Browser in Desktop/Smartphone something close to 60%);

**Google Chrome's relationship with Flash Player is already over.** The majority of games in the MOST popular browser it is now unplayable.

All those players who search HaxBall in Google are going to the poor Flash Player. **New players** don't have to get in this 1999 stuff anymore (thanks to Basro <3).

HTML5 is called by ALPHA but we HTML5's players know that is not true **anymore**. Most of ALPHA game is a terror to play because all the bugs and stuff.

After all this;
The real question:
Why is not HTML5 the main in www.haxball.com ?
This perfect thing that you have created Basro, need to grow up and realize that he is not ALPHA.

_“Sometimes we have to move on. Even if we got something tying us to the past.”_

**Comment by basro** [comment]
I still plan to have www point to the html5 version eventually, but since the plan is to not take down the flash version it has become a lot more tedious to do so it will take time.
