### ISSUE TITLE
MAC OSX Chrome Html5 connection problem

### ISSUE THREAD

**Issue by Wasteman42** [haxball/haxball-issues#232]
Hi, for about a week now I have not been able to connect to HTML5 rooms. It's fine with flash but HTML5 I can't connect. My internet download speed is 47.5 mbps download 13 mbps upload so my internet is fine but I keep getting the message to failed to connect

**Comment by basro** [comment]
I just released a new version which might fix this issue for you, please tell me if you still can't connect.

**Comment by Wasteman42** [comment]
Fixed. Thanks !

**Comment by basro** [comment]
Great!
