### ISSUE TITLE
Spammer destroying public rooms

### ISSUE THREAD

**Issue by haxballer** [haxball/haxball-issues#234]
Hey, on haxball html5 there is a person who destroys fun. He goes into every room and starts spamming, he does it very quickly, then he runs away. His actions make people don't normal play, could you do something about it?

It's possible that similar posts have already appeared, but the matter is very serious, because it is impossible to play in public rooms, mainly polish.

PS. Later i give ss, help...

**Comment by basro** [comment]
What kind of spam? Does it cause lag?
Would being able to ban players that have already left the room solve this problem for you?

**Comment by haxballer** [comment]
It looks like the room is joined by a guest who begins to automatically paste a string of strange symbols, then quickly leaves, even if you manage to ban him, he will come back. Spam is huge, only the password results, but then random players will not come to us.

Does it cause a delay? I honestly admit that yesterday, the game immediately began to crash horribly after his actions, and the fps were stable, I don't know if it has anything in common.

After all, this man is abnormal, you can't play, because this spam is really huge.

**Comment by basro** [comment]
It would be helpful if you can capture it happening in a replay recording.

**Comment by haxballer** [comment]
Well, in the evening I will try to initiate the action and send the recording.

**Comment by haxballer** [comment]
Well, in the evening I will try to initiate the action and send the recording.

**Update:** @basro, my friend managed to record it, it looks like this:
[http://thehax.pl/forum/powtorki.php?nagranie=1522783595](url)

**Comment by basro** [comment]
Ok, I'll see try to do something about it

**Comment by haxballer** [comment]
Thanks a lot! This is really very important, because this man doesn't give people to play. I hope you can deal with ubiquitous spam, because it's terrible.

Greetings!

**Comment by basro** [comment]
For now I've implemented some rate limits on room joining, this will prevent the attacker from rejoining at such a high rate.
In the future I'll probably implement some way for the host to ban players that have already left the room.

**Comment by haxballer** [comment]
Hi. Apparently, spammers are still on the attack, i got the information. I think it's same person who once had "ddos" rooms on the flash Haxball. I hope you can handle this problem fully, because it really irritates. Thanks for everything.

**Comment by haxballer** [comment]
Apparently, spammers are still on the attack, i got the information. I think it's same person who once had "ddos" rooms on the flash Haxball. I hope you can handle this problem fully, because it really irritates. Thanks for everything.

**Comment by Kibrisli153** [comment]
I have a haxball bot code and it has anti spam code. We cant even chat in game . It kicks us . Can you delete it I cant find it
