### ISSUE TITLE
Reset bans

### ISSUE THREAD

**Issue by humpyy** [haxball/haxball-issues#235]
Would we be able to get a host command to clear bans without having to reset the room?

**Comment by basro** [comment]
Yes, although it would be a host-only command, like the set/clear password

**Comment by humpyy** [comment]
Ya that'd be perfect.  I could use that right away when its implemented :D

**Comment by basro** [comment]
This is now implemented and released.
The command is /clear_bans and only the host can use it.

**Comment by TejasPrakash** [comment]
.
