### ISSUE TITLE
Asking about future

### ISSUE THREAD

**Issue by Whunpp2** [haxball/haxball-issues#239]
Now that you have created the HTML5 (which is pretty cool) do you have any thoughts in your mind about share Haxball in Steam? This would help to bring us new players.
Because our fake (Ball*D) has something there.
Maybe we all can chip in to do this work.
Also I was looking and the (BallsomethingD) has a statistics thing pretty cool tho.
http://prntscr.com/j1u1ax
Maybe can you copy your copy? LOL
For you folks that don't know the Haxball's Copy do not even want to try it. The gameplay is pure garbage compared to Haxball.
_If you haven't played Haxball in your life, maybe you can have some fun tho._

Sorry yo if is not here to do this topic.

**Comment by basro** [comment]
I don't plan to put HaxBall in steam right now. It doesn't mean I'm opposed to the idea.
