### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by wrozbita** [haxball/haxball-issues#244]
I play on Maxhton5. I've never had any problems with playing on html5 version but today I got this error: 

Unexpected Error

An error ocurred while attempting to join the room.

This might be caused by a browser extension, try disabling all extensions and refreshing the site.

The error has been printed to the inspector console.

**Comment by basro** [comment]
After that error appears, right click on the webpage and click inspect. Look for a console tab and copy the contents of the console here so that I can figure out what went wrong.

**Comment by saviola777** [comment]
Without seeing the error I can't be sure that it's the same, but I saw [a screenshot](https://gyazo.com/99e3e5b6f75f93a0d34396828c9d39ba) of someone reporting the exact same problem, only on Maxthon (5.1.3.2000). It started happening on 24.04, he was still able to play the evening before.

**Comment by wrozbita** [comment]
2html5.haxball.com/:37 A Parser-blocking, cross-origin script, https://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=376200, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ ?c=UzjEywtknV4:37
https://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=376200 Failed to load resource
VM58:1 start parse
VM58:1 -------createCandidate() tag: DIV  className/id: container flexCol/
VM58:1 getContentScore: 30.01265976500359
VM58:1 classWeight:1
VM58:1 -------createCandidate() tag: DIV  className/id: flexRow flexGrow/
VM58:1 getContentScore: 0
VM58:1 classWeight:1
VM58:1 -------createCandidate() tag: DIV  className/id: flexGrow/
VM58:1 getContentScore: 0
VM58:1 classWeight:1
VM58:1 getCandidateList 3
VM58:1 candidate tag: DIV  score:30.01265976500359  className/id: container flexCol/
VM58:1 candidate tag: DIV  score:0  className/id: flexRow flexGrow/
VM58:1 candidate tag: DIV  score:0  className/id: flexGrow/
VM58:1 results length:0
game-min.js:132 ReferenceError: RTCPeerConnection is not defined
    at Ta [as f] (game-min.js:47)
    at pb [as f] (game-min.js:48)
    at d (game-min.js:43)
    at Fa [as f] (game-min.js:44)
    at Function.w.Te (game-min.js:130)
    at w.Pn (game-min.js:124)
    at ib.b.rj (game-min.js:123)
    at HTMLButtonElement.b (game-min.js:24)

**Comment by basro** [comment]
Looks like this is a bug caused by some code refactoring I did on the 24/04. I accidentally removed some webrtc api normalization code during the refactoring process.

It should now be fixed, please confirm @wrozbita
