### ISSUE TITLE
INTERESANT UPDATES FOR HAXBALL

### ISSUE THREAD

**Issue by Kozlov98** [haxball/haxball-issues#25]
Hi Basro, I leave you some of the updates that would be needed on Haxball according to order of importance

For some of the official competitions, I think it would be good to implement some record on who make the goals and assists in the matches or that appear when they get the goal.

Secondly, a / mute command to silence annoying or spammers

Last but not least, in some maps like Big / Huge / Big Easy the ball scores goal without it has entered all, that is something that always annoying to the players since 2011 xD

Greetings from the Haxball Argentina Community

**Comment by basro** [comment]
@Kozlov98, there issues should focus on a single thing. I'm closing this, feel free to make an issue about each individual item.
