### ISSUE TITLE
GPU acceleration trouble

### ISSUE THREAD

**Issue by Skunky32** [haxball/haxball-issues#250]
So, I was playing futsal in HTML5 Haxball with my friends and we were also typing a bit while playing. When I was running from left side to right side (playing WASD and Space), my fingers slept off and I pressed some weird combination of keys, which led me to disabling GPU acceleration, like in Flash Haxball, making the game look edgy. As I do not have any problems with HTML5 Haxball game, I don't need it and I can't turn it back on. 

P.S.
Refreshing and clearing cache did not help :(

**Comment by basro** [comment]
What browser are you using? If chrome go to this page: chrome://gpu/ and paste the results here.

I don't know of any combination of keys that would disable gpu acceleration though.

You say the game looks edgy, could you upload a screenshot of it?

**Comment by Phantom831** [comment]
Basro, I left a topic to share with you but I think, you didnt want to see it somehow? I have a godlike pc and im somehow lagging, Idk what it is, I tried different browsers and anything its just fps dropping somehow.

**Comment by Phantom831** [comment]
CheckerImaging: Disabled for example if this is the problem just tell me

**Comment by basro** [comment]
@Phantom831, don't spam unrelated issues.

**Comment by Skunky32** [comment]
@basro Yes, you were correct, I somehow zoomed out the game :)
Sorry for me being that naive, and thanks for your attention!
