### ISSUE TITLE
Administrator privileges

### ISSUE THREAD

**Issue by malybobo** [haxball/haxball-issues#262]
Hey,
Is it possible to add room administrator rights after entering the password in the chat window by the user, off course, the password is generated by the host
let's put it through the command "/adminpass"
It would be very useful when setting up a room for VPS.
Thanks

**Comment by basro** [comment]
You could do it with headless host, except there's no way to send private messages that only reach the host, so maybe that feature is what is needed.

**Comment by malybobo** [comment]
Thanks Basro!
The solution is really great.

However, I was expecting you  do a command with a password to use administrator privileges.
There are a lot of young people on haxball who are not good at managing the room.
Generating a password to administer the room would be for a group of people who know the administration.

**Comment by saviola777** [comment]
Maybe custom commands could be used for that? Like `/authenticate <PW>`, anything starting with `/` will not be printed to chat but can be caught on the headless host using a special event?

**Comment by Wrathen** [comment]
It's very doable with the current Headless API. No need for private messaging. You can do "!auth <password>" that only you know and changes every time you host. So Its a random password. Its easy to do. And After You use the password It changes again then you console.log the new password etc...

**Comment by saviola777** [comment]
Yeah, but that's very cumbersome, it's a workaround more than anything else. You'd need to login to your VPS each time the PW changes.

**Comment by Wrathen** [comment]
`var currentPassword;`
`function MakeNewPassword(){currentPassword=RandomPasswordGenerator();console.log(currentPassword);}`

onPlayerChat --> You check if the message == your currentPassword then you give admin privileges to the player and you MakeNewPassword(); so the old password won't be available for usage.

**Comment by basro** [comment]
The onPlayerChat event now lets you stop the propagation of the chat message to other players. You could use this to hide the room password.
