### ISSUE TITLE
Auto - Rand?

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#268]
What is the difference between Auto and Rand? I've tested and it seems the same.
Sorry to post this here but I couldnt find it anywhere nor any place like a forum to post this.

**Comment by Raamyy** [comment]
I think auto always selects the top player, While rand selects random one.

**Comment by Leo-MapCreator** [comment]
No it doesnt i tested it, it seems the same, maybe the difference is on the random mode, idk

**Comment by Leo-MapCreator** [comment]
Thx
