### ISSUE TITLE
[_______] was unbanned

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#270]
Please create the option to unban someone, sometimes a stupid admin bans everyone to troll the room, it would be good if you could create an option to see who was banned and decide to unban or not

**Comment by Whunpp2** [comment]
There already a command: /clear_bans
I dont think that we need a redundancy command.

**Comment by Leo-MapCreator** [comment]
I didnt know about that, is it a HTML5 thing? Im sure it didnt work on Flash nor was published anywhere in update news

**Comment by Whunpp2** [comment]
basro Is not posting all the updates in News, which is pretty bad. Majority of updates is only posted here (also without a single topic, all of it only in answers.)

**Comment by basro** [comment]
As Whunpp2 mentioned there's no a /clear_bans command that was added recently.

Indeed I didn't make a news post about it or about many other small changes that happened recently because... ¯\_(ツ)_/¯

**Comment by cr0ndor** [comment]
Can any admin call /clear_bans or only host?

**Comment by Leo-MapCreator** [comment]
only host, but you can set the host to clear bans if the admin say a determined message
