### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by Whunpp2** [haxball/haxball-issues#273]
The link posted in News is giving us the wrong way to Flash version. Because it is catching the comma. I dont know if here is the right place but thats it. 

![image](https://user-images.githubusercontent.com/38140405/40091337-6a921cda-588d-11e8-9c6a-fadb35dc8780.png)

**Comment by Leo-MapCreator** [comment]
Why www.haxball.com/flash link doesnt work but www.haxball.com/flash/ works?

**Comment by Whunpp2** [comment]
Two wrong links @basro

**Comment by basro** [comment]
I've fixed the link, thanks for pointing it out @Whunpp2

www.haxball.com/flash is not exactly broken since it wasn't meant to direct to anything, although I guess I can add a redirect to /flash/
