### ISSUE TITLE
Headless Flash

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#274]
Can you provide a headless host version for the flash game ?

I know it is dying, But there is much of people who likes playing in the flash version of **HaxBall**.

So if you have the ability to provide Headless host for the flash version, Please do it :smile:

**Comment by Wrathen** [comment]
We need to encourage people to play on HTML5 not on Flash version. So I dont think its a good idea. Flash will eventually die so no more investment should be made on that any more. Thats how I think tbh...

**Comment by basro** [comment]
While I'll be keeping the flash version up (until 2020 at most), I won't work on new features for it. So this isn't going to happen.
