### ISSUE TITLE
Headless Controls Team Colours

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#275]
_Sorry for these bulk of issues and ideas but i hope that they are helpful :sweat_smile:_

**Comment by Wrathen** [comment]
instead of resetting maybe getting them would be more logical.
Also some guy had an idea about Logging Goals and who shot them. We need more power from API. Give us the ultimate power!! Argh :D

**Comment by Raamyy** [comment]
This is what we need :point_down: 

![17a8wbe](https://user-images.githubusercontent.com/29176293/40133434-0e6102e2-5940-11e8-90a0-a22280909a02.gif)

**Comment by Wrathen** [comment]
Exactly LOL!

**Comment by basro** [comment]
No need to apologize for making suggestions, they are always welcome.

I'll be adding a bunch of extra stuff to the headless api soon-ish.

**Comment by Wrathen** [comment]
Define "soon-ish" :^)
I'm refreshing the API page every now on then. Make it "soon-er-ish" :c

**Comment by basro** [comment]
This is now implemented.
