### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by dedel12** [haxball/haxball-issues#277]
Can someone give me headless room codes? I really have no knowledge and I want to try.

**Comment by Raamyy** [comment]
What exactly you don't understand ?
you don't where to type the code or what is the exact problem with you ?

**Comment by dedel12** [comment]
@Raamyy Actually, I want headless codes from you. I do not know how to write java code and could you give me the written codes.

**Comment by Raamyy** [comment]
First of all let me clarify to you that the language used is **JavaScript** not Java.

Here are some sample codes:
```javascript
room.onPlayerChat=function(player,message){
	if(message=="Hello"){
            //Do something
         }
}
```	
In the top example if a player sent a chat message which text is **Hello**  the code you implement should be executed.

Other example:
```javascript
room.sendChat("Hello World");
```
This makes the bot send Hello World text to the chat.

The same way of syntax will be used with the rest of provided functions.

I can't promise that i can give you my code, But if you are stuck in any problem just ask me and I will answer :smile:

**Comment by Wrathen** [comment]
Good ol' "Hello World" :'(

**Comment by saviola777** [comment]
Here is a simple [host.js](http://quickswans.de/headless/host.js) to get you started, you have to source this file on the headless host page, for example using one of the ways described [here](https://github.com/haxball/haxball-issues/issues/267#issuecomment-389425944).

**Comment by Leo-MapCreator** [comment]
@Raamyy can you teach me the basics of using javascript API?

**Comment by Raamyy** [comment]
Okay I will try to make a simple video that helps you starting your room. :D

**Comment by Raamyy** [comment]
@Leo-MapCreator  Hey Leo.. Check #300 Please
