### ISSUE TITLE
Handicap

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#280]
I can set handicap from 0 to 300ms but it doesnt show anywhere how much handicap i have like in the flash that had a green number to indicate it

**Comment by basro** [comment]
I'm not going to bring this feature back, it isn't that important to show the handicap and almost nobody uses the feature anyway.

**Comment by basro** [comment]
I might show the handicap to the client only next to the ping.

**Comment by Leo-MapCreator** [comment]
@basro sorry, i didnt know i could post here, yeah, it doenst need to show to everyone in the room, you just need to know that you have it on and how many ms
