### ISSUE TITLE
Haxball Headless API

### ISSUE THREAD

**Issue by Manderigon** [haxball/haxball-issues#284]
Hello.
Function getPlayerList() should have an option to choose a team to select from.
Function setPlayerTeam() should have an option to move all players from team to spec.
Greetings, Manderigon.

**Comment by Raamyy** [comment]
You can filter them using ```filter()```  function

**Comment by Raamyy** [comment]
Feel free making your own functions using existing ones.
As an example you can make function that is called **```resetPlayers()```** which loops on all of the players and sets their teams into **_0_** **(Spectator teamId)**.

**Comment by Wrathen** [comment]
function GetRedTeam(){return room.getPlayerList().filter((player) => player.team == 1);};
function GetBlueTeam(){return room.getPlayerList().filter((player) => player.team == 2);};
function GetSpecTeam(){return room.getPlayerList().filter((player) => player.team == 0);};

or
function GetTeam(id){return room.getPlayerList().filter((player) => player.team == id);};

**Comment by basro** [comment]
I wont be adding these methods since they are easily doable from the already existing api.
