### ISSUE TITLE
Func. of Headless 

### ISSUE THREAD

**Issue by malybobo** [haxball/haxball-issues#285]
Hi, 
How can I write such a function:

> room.onPlayerChat = function(player, message) {
> (url)if (message == 'givemeadmin') {
>   room.setPlayerAdmin(players, true);     //<--- Give admin to player who wrote givemeadmin
> }
> 
> }`
Thank in advance for your help.

**Comment by Raamyy** [comment]
```javascript
room.onPlayerChat = function(player, message) {
   if (message == 'givemeadmin') {
   room.setPlayerAdmin(player.id, true);
   }
}

**Comment by malybobo** [comment]
It seems to me that I have already tried my mind.
Check again.
Thank you so much for such a quick response.

**Comment by Raamyy** [comment]
You are welcomed :smile: 

I just added player.id instead of players, and made double quotations not single.

Good Luck :D.

**Comment by malybobo** [comment]
Great! 
It works perfectly.
Question part II :)
Can I enter a function in Headless that will upload a map other than from the list?
For example, Power MAP
