### ISSUE TITLE
Related to Headless API Improvements

### ISSUE THREAD

**Issue by Wrathen** [haxball/haxball-issues#287]
When will the API get improvements? It's been 3 days since the last update.  I am trying to push you to improve it :D And maybe an API version string in the https://html5.haxball.com/headless would be great. So I can know when to check the documentation

**Comment by saviola777** [comment]
It's done when it's done. Try to be a bit more patient… And this is an issue tracker, not a "nag the developer" forum. :P

**Comment by basro** [comment]
What saviola said.

Also when it's done I'll post in the HaxBall news blog, so you can spam F5 there if you want.
