### ISSUE TITLE
Checksum

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#288]
Every map have an unique checksum, right?
Now let's suppose we have a map stored but we don't have the file, is it possible to have the map file only having the map checksum? Something like 'reverse engineering'
If so, can you create this 'feature'?

**Comment by saviola777** [comment]
I don't think this is possible – hash/checksum functions are usually one-way, it's impossible to go back to the original map unless you have some sort of database with checksums and maps where you can perform a lookup for the checksum.

**Comment by basro** [comment]
The checksum is useless for that purpose, but the hbs file could be generated from the in memory representation of the stadium, I might do it at some point.

**Comment by Leo-MapCreator** [comment]
Why this thread was closed?

**Comment by saviola777** [comment]
Because what you asked for is not possible, I guess.

**Comment by Leo-MapCreator** [comment]
The thread is not about the way to do this, but the feature
