### ISSUE TITLE
clearChat();

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#301]
Please create a function to clear the chat, this way selected people that know the password can use the password to be admin, while the host will clear the chat, hidding and preserving the password from everyone

**Comment by Leo-MapCreator** [comment]
I clear the chat by sending 24 blank messages, but it is too loud and sometimes scares the people that are not ready for it hahaha

**Comment by basro** [comment]
I wont be implementing this, it doesn't make sense for the host to be able to clear the client's chat log and it would be a really bad idea to try to hide a password this way.
