### ISSUE TITLE
Directed messages

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#302]
It should be a thing to send private messages from the host to the player, because of this:
_function welcome() {
 room.sendChat("Welcome to the S3DB room, for more information type !help");
}_
When the person says !help, the host says a lot of commands available + group info and many other things, and sometimes it pollutes the chat for the people that didn't ask for it, please make it possible to send the message only to that specific person, maybe  **sendPrivateChat(playerID: int, message: string)**

**Comment by basro** [comment]
I want to implement this in the future, unfortunately it requires some backwards incompatible changes to the netcode so it'll have to wait a bit.

**Comment by Leo-MapCreator** [comment]
This is already done
