### ISSUE TITLE
setTeamColors

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#311]
I read the argument of this function by I still have no clue how to use it, I've tried different ways but it doesnt work, could you please give an example using that function for this color code: /colors red 60 FF6B6B A13235 852D2D?

**Comment by basro** [comment]
`room.setTeamColors(1, 60, 0xFF6B6B, [0xA13235, 0x852D2D])`

**Comment by Leo-MapCreator** [comment]
What about it in RGB? how to write that in RGB?
