### ISSUE TITLE
Headless event request: onPlayerBallTouch()

### ISSUE THREAD

**Issue by yerooleopard** [haxball/haxball-issues#314]
Hello, 

onPlayerBallKick() event is great, but require player reaction to trigger. **onPlayerBallTouch()** would help for some modes like "6Man strong", when very often we don't know who touched ball last and should win or lose.

**Comment by basro** [comment]
You could do this by measuring the distance between the ball and the players, consider them touching the ball if the distance is less or equal than the sum of their radius plus a small epsilon say 0.01.

**Comment by Leo-MapCreator** [comment]
@basro I dont know if its that simple, because the ball has if im not mistaken 1 pixel of radius where you do not touch the ball but you are able to kick it, idk if this 1 pixel is radius+1 or if this 1 pixel is equal radius, or if its playerRadius + 1 or playerRadius, better check that

**Comment by basro** [comment]
Here's an example of how to do it: https://github.com/haxball/haxball-issues/blob/master/headless/examples/ballTouchExample.js

**Comment by VukBakic** [comment]
@bassro
Sometimes when player kicks ball it doesn't record that he touched it. Is there way to fix this?
Maybe increasing 0.01?

**Comment by basro** [comment]
@VukBakic, yes, by listening to the onPlayerBallKick event.
