### ISSUE TITLE
onBallReplaced();

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#315]
Well, you do have onTeamGoal, but how do i do onBallReplaced(); that its when the ball is replaced on center? Because i have a macro detector, that detects kicks/seconds and if its higher than the limit it kicks the player out of the room, but after the goal you are able to kick the ball but the time isnt running, so that means if you kick the ball after it entered your goal, and then you kick the ball to start the game, it will detect as a macro user, because the time of kick1 and kick2 will be the same, so that means 2 kicks/(00000000000.1) seconds, that is higher than the limit, how to fix that? PS: i already clear the timer after a goal is scored, but i cant clear the timer if the kick happens after the goal while the time is stopped

**Comment by basro** [comment]
When reset the ball will be placed at {x: 0, y: 0}, so you could check for that.

**Comment by Leo-MapCreator** [comment]
but what if the ball passes trough 0,0 troughout the game?

**Comment by basro** [comment]
Only check for it after a goal happens. The odds of the ball returning to position 0, 0 are practically 0 anyway.

**Comment by Leo-MapCreator** [comment]
No chance to create onBallReplaced()?

**Comment by basro** [comment]
Yes there is, but in the meantime this is what you can do to work around it.

**Comment by Leo-MapCreator** [comment]
How long is going to be this meantime? Because if its short ill wait for it, otherwise ill work around

**Comment by basro** [comment]
I'm currently hunting a hard to figure out bug and I wont be expanding the api until that is done. Don't know how long it will take.

**Comment by basro** [comment]
This is now implemented, the event name is onPositionsReset.
