### ISSUE TITLE
Player unique id

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#320]
Can we get id that doesn't change when player rejoins room?
I have players ranks and people started joining with other people names and it kinda ruins the point.
Can we get like unique id that corresponds to players ip address? 
I think this could be done since bans are probably handled that way and this would also make #317 doable.

**Comment by tohey** [comment]
This is definitely an urgent need. However, giving out IP addresses can harm privacy. How about hashing the IP address? For extra privacy, add a random salt that changes after a long enough period of time.

**Comment by Wrathen** [comment]
> This is definitely an urgent need. However, giving out IP addresses can harm privacy. How about hashing the IP address? For extra privacy, add a random salt that changes after a long enough period of time.

This was implemented in flash version. But in the current version when you are banning people it uses the IP adress. He can't give other people's IP adress thats for sure but making an ID based on IP and maybe some other factors is something he can do.

**Comment by olegmisar** [comment]
You can look at players' IPs if you are host. Just track webrtc connections with your browser. So, I think hashing IP addresses is not necessary.

**Comment by basro** [comment]
This feature is implemented (player auth) now so I'm closing this issue.
