### ISSUE TITLE
Auto / Rand

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#321]
Create onAutoPressed(byPlayer: id) and onRandPressed(byPlayer: id) 
And clickAuto() and clickRand()

**Comment by VukBakic** [comment]
You can implement clickAuto and clickRand...
for clickRand() just get list of players with filter team id == 0 and add random to the team.

**Comment by Leo-MapCreator** [comment]
How to random?

**Comment by Wrathen** [comment]
`function TakimlariEsitle(redMaksimumOyuncuSayisi, blueMaksimumOyuncuSayisi)
{
	var red = room.getPlayerList().filter((player) => player.id != 0 && player.team == 1);
	var blue = room.getPlayerList().filter((player) => player.id != 0 && player.team == 2);
	var spec = room.getPlayerList().filter((player) => player.id != 0 && player.team == 0);
	var red_ = red.length;
	var blue_ = blue.length;
	var spec_ = spec.length;
	for(var i = 0; i < spec_; i++) // Distribute Spec
	{
		if(red_ < redMaksimumOyuncuSayisi && red_ <= blue_) // Priority: Filling teams with lesser players
		{
			room.setPlayerTeam(spec[i].id,1);
			red_++;
		}
		else if(blue_ < blueMaksimumOyuncuSayisi && blue_ <= red_)
		{
			room.setPlayerTeam(spec[i].id,2);
			blue_++;
		}
		else if(red_ < redMaksimumOyuncuSayisi)
		{
			room.setPlayerTeam(spec[i].id,1);
			red_++;
		}
		else if(blue_ < blueMaksimumOyuncuSayisi)
		{
			room.setPlayerTeam(spec[i].id,2);
			blue_++;
		}
	}
	if(red_ > blue_ + 1 && blue_ < blueMaksimumOyuncuSayisi)
	{
		for (var i = 1; i < red_ - blue_; i++)
		{
			if(!(blue < blueMaksimumOyuncuSayisi)) return;
			room.setPlayerTeam(red[red_ - i].id,2);
			blue_++;
		}
	}
	else if (blue_ > red_ + 1 && red_ < redMaksimumOyuncuSayisi)
	{
		for (var i = 1; i < blue_ - red_; i++)
		{
			if(!(red < redMaksimumOyuncuSayisi)) return;
			room.setPlayerTeam(blue[blue_ - i].id,1);
			red_++;
		}
	}
}`
call it by TakimlariEsitle(redMaxPlayers, blueMaxPlayers);

**Comment by basro** [comment]
I will not implement any of these.

Also, the behaviour of Auto and Rand is easily implementable with the current api.
