### ISSUE TITLE
onPlayerKicked : bool

### ISSUE THREAD

**Issue by FrescoPL** [haxball/haxball-issues#323]
Just like onPlayerChat

**Comment by Raamyy** [comment]
It alerady exists check the wiki again.

**Comment by FrescoPL** [comment]
onPlayerChat has an option to mute players, I want the onPlayerKicked function to work the same way, for example to make someone unkickable in my room

**Comment by dixtel** [comment]
Just remove admin mode for this player...

**Comment by basro** [comment]
Even though it's useful, being able to filter the chat messages is a big of an ugly hack in the code. It's simpler for chat messages since they have no real effect on the game's state but not so much for any other action.

I wont be adding filtering functionality to the other events for now.
