### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#324]
https://gyazo.com/e27c1581db37b3d10a13c3d0bb6e9344

**Comment by Wrathen** [comment]
Disable browser extensions

**Comment by Leo-MapCreator** [comment]
Let me check

**Comment by basro** [comment]
No idea what that error is, it doesn't look like it comes from HaxBall.

**Comment by basro** [comment]
I'm closing this, if you find that it still happens after disabling extensions and think it's something wrong in haxball let me know here and I'll reopen the issue.
