### ISSUE TITLE
Handicap ..

### ISSUE THREAD

**Issue by qLaur98** [haxball/haxball-issues#326]
He was handicapped the way he was before, so plz it's so bad/delay keyboard..

**Comment by Wrathen** [comment]
Yes I like pizza too.

**Comment by qLaur98** [comment]
Update handicap ? plz

**Comment by basro** [comment]
I have no idea what you are trying to say qLaur98

**Comment by qLaur98** [comment]
Why it does not work anymore handicap? ...

**Comment by qLaur98** [comment]
Why I'm seeing handicap the opponent me,but it does not work on me

**Comment by basro** [comment]
I still don't exactly know what you are trying to say.

I guess that you were using the handicap feature while it was buggy and caused you to warp, that was a bug and it was fixed in the last update. The way it works now is how it was always meant to work, and how the flash version worked.
