### ISSUE TITLE
Get game state

### ISSUE THREAD

**Issue by tohey** [haxball/haxball-issues#327]
Is there a way to get the game state (i.e. started / stopped / paused)? If not, please implement it :)

**Edit**: In addition to `onGameStart()` and `onGameStop()`, an `onGamePaused()` is enough to solve this.

**Comment by Raamyy** [comment]
you can achieve this by 3 boolean variables each one for every state.

**Comment by basro** [comment]
There's currently no way to keep track of the game pause state, I'll add api for that later on.

**Comment by Leo-MapCreator** [comment]
onGameStart = {
beingPlayed = 1
}
onGameStop = {
beingPlayed = 0
}

**Comment by basro** [comment]
There's now onGamePause and onGameUnpause which allow for keeping track of the pause state.
