### ISSUE TITLE
onTeamVictory difference in time

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#331]
If onTeamVictory is called by scorelimit, it takes something like 3 seconds before executing the commands, but if onTeamVictory is called by timelimite it execute instantly, and that's kinda bad because one of the commands I have is to stop the game, and when the timer hits the timelimit it instatly stop the game and you don't even know why the game stopped

**Comment by Leo-MapCreator** [comment]
I can record it if you want

**Comment by basro** [comment]
That's how it works at the moment.
I recommend waiting for the gameStop event instead of stopping the game yourself since the game will be stopped automatically after a team victory.
