### ISSUE TITLE
im loose.

### ISSUE THREAD

**Issue by malybobo** [haxball/haxball-issues#334]
As the topic.
How can I hide the administrator's password in the command:
room.onPlayerChat = function(player, message) {
   if (message == "admpswrd") {
   room.setPlayerAdmin(player.id, true);
   }
}

**Comment by Raamyy** [comment]
```c++
room.onPlayerChat = function(player, message) {
if (message == "admpswrd") {
  room.setPlayerAdmin(player.id, true);
  return false;
  }
}
```

**Comment by malybobo** [comment]
raamyy give me your mail or fb:)

**Comment by Raamyy** [comment]
[Facebook](www.facebook.com/mimoo.ismaily)
ramyeg26@gmail.com
