### ISSUE TITLE
My host have too ping.

### ISSUE THREAD

**Issue by SebiPeppins** [haxball/haxball-issues#339]
My problem is that when I create bot room this have too ping. I tested with my normal host and have good ping, I have 10 mb of internet, Telecentro Argentina S.A
Script:

`var room = HBInit({ roomName: "Memz Bot 3v3", maxPlayers: 20,public : true,playerName : "✘✘MemZ Bot✘✘"  });
room.setDefaultStadium("Big");
room.setScoreLimit(3);
room.setTimeLimit(3);
// If there are no admins left in the room give admin to one of the remaining players.
function updateAdmins() { 
  // Get all players except the room.onPlayerJoin = function(player) { (id = 0 is always the host)
  var players = room.getPlayerList().filter((player) => player.id != 0 );
  if ( players.length == 0 ) return; // No players left, do nothing.
  if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
  room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
}

room.onPlayerJoin = function(player) {
  room.sendChat( "Bienvenido "+player.name+"! Disfruta tu instancia en el host ✘D");
  updateAdmins();
}

room.onPlayerLeave = function(player) {
  room.sendChat( "Adiós "+player.name+" ✘D");
  updateAdmins();
}
room.setPlayerAdmin = function(player) {
room.sendChat( "Ahora eres un administrador.");
}
room.stopGame = function(player) {
room.sendChat( "Se termino el partido! Rojo "+score.red+" - "+score.blue+"");
}`

**Comment by Raamyy** [comment]
I'm not seeing any operations that can cause any problems.
Try looking at the console window it can tell you if there is any errors in the code.

**Comment by SebiPeppins** [comment]
The console says:↓↓↓

**Comment by SebiPeppins** [comment]
var room = HBInit({ roomName: "Memz Bot 3v3", maxPlayers: 20,public : true,playerName : "✘✘MemZ Bot✘✘"  });
room.setDefaultStadium("Big");
room.setScoreLimit(3);
room.setTimeLimit(3);
// If there are no admins left in the room give admin to one of the remaining players.
function updateAdmins() { 
  // Get all players except the room.onPlayerJoin = function(player) { (id = 0 is always the host)
  var players = room.getPlayerList().filter((player) => player.id != 0 );
  if ( players.length == 0 ) return; // No players left, do nothing.
  if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
  room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
}

room.onPlayerJoin = function(player) {
  room.sendChat( "Bienvenido "+player.name+"! Disfruta tu instancia en el host ✘D");
  updateAdmins();
}

room.onPlayerLeave = function(player) {
  room.sendChat( "Adiós "+player.name+" ✘D");
  updateAdmins();
}
room.setPlayerAdmin = function(player) {
room.sendChat( "Ahora eres un administrador.");
}
room.stopGame = function(player) {
room.sendChat( "Se termino el partido! Rojo "+score.red+" - "+score.blue+"");
}
ƒ (player) {
room.sendChat( "Se termino el partido! Rojo "+score.red+" - "+score.blue+"");
}

**Comment by SebiPeppins** [comment]
Not errors :(

**Comment by SebiPeppins** [comment]
The console only says:
ƒ (player) {
room.sendChat( "Se termino el partido! Rojo "+score.red+" - "+score.blue+"");
}
After put the script.

**Comment by SebiPeppins** [comment]
In the host:
Ping: 19816.5

Max Ping: 20813

Fps: 60

**Comment by SebiPeppins** [comment]
In my normal (human) host: 
Ping: 68.5

Max Ping: 146.7

Fps: 126

**Comment by Raamyy** [comment]
> In the host:
Ping: 19816.5
Max Ping: 20813

Is this the ping of **you** when you enter the room of your host !?
or the ping of players who enter the room?

**Comment by SebiPeppins** [comment]
These ping (first) is of the Bot host

**Comment by SebiPeppins** [comment]
In the BOT host:
Ping: 19816.5
Max Ping: 20813
In my HUMAN host:
Ping: 68.5

Max Ping: 146.7

Fps: 126

**Comment by SebiPeppins** [comment]
> Is this the ping of you when you enter the room of your host !?
or the ping of players who enter the room?
Its my ping to enter to my bot host

**Comment by SebiPeppins** [comment]
↑ Its my ping to enter to my bot host

**Comment by SebiPeppins** [comment]
sry im from argentina my english is crap

**Comment by Raamyy** [comment]
my ping in my host is about 3 !
so check this code from another internet connection or another machine and see if the problem presits.

**Comment by SebiPeppins** [comment]
I tested in my desktop pc and i have 2 ping under

**Comment by SebiPeppins** [comment]
var room = HBInit({ roomName: "MemZ Bot 3v3", maxPlayers: 20,public : true,playerName : "✘✘MemZ Bot✘✘"  });
room.setDefaultStadium("Big");
room.setScoreLimit(3);
room.setTimeLimit(3);
// If there are no admins left in the room give admin to one of the remaining players.
function updateAdmins() { 
  // Get all players except the room.onPlayerJoin = function(player) { (id = 0 is always the host)
  var players = room.getPlayerList().filter((player) => player.id != 0 );
  if ( players.length == 0 ) return; // No players left, do nothing.
  if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
  room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
}

room.onPlayerJoin = function(player) {
  room.sendChat( "Bienvenido "+player.name+"! Disfrutá tu instancia en el host ✘D Tu id es: "+player.id+"");
  updateAdmins();
}
room.onPlayerLeave = function(player) {
  room.sendChat( "Adiós "+player.name+" ✘D");
  updateAdmins();
}
room.onGameStop(byPlayer : PlayerObject) : void
room.sendChat( "Se terminó el partido!");
}
room.onTeamVictory(scores : ScoresObject) : void
room.sendChat( "Ganó el "+team.id+"");
}

**Comment by SebiPeppins** [comment]
/* SETTINGS */

/* ROOM */

var roomName = "MemZ Bot 3v3";
var maxPlayers = 20;
var roomPublic = true;

/* STADIUM */

var stadiumWidth = 1150;
var stadiumHeight = 600;
var radiusBall = 9.8;

/* SETTINGS */

var lastScores = 0;
var lastTeamTouched = 0;
var triggerDistance = radiusBall + 15 + 0.01;
stadiumWidth += (radiusBall / 2) + 6;
stadiumHeight += (radiusBall / 2) + 6;
var Team = {
    SPECTATORS: 0,
    RED: 1,
    BLUE: 2
};
var room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: "✘✘MemZ Bot✘✘" });
room.setScoreLimit(0);
room.setTimeLimit(0);

room.onTeamGoal = function(team) {
    setTimeout(function() {
        lastScores = room.getScores().red + room.getScores().blue;
    }, 1000);
}
room.onGameStart = function(player) {
    lastScores = room.getScores().red + room.getScores().blue;
}
room.onPlayerBallKick = function(player) {
    lastTeamTouched = player.team;
}
room.onGameTick = function() {
    getLastTouchTheBall();
    checkBallPosition();
}

room.onPlayerJoin = function(player) {
    if(player.id == 1) {
room.sendChat( "Bienvenido "+player.name+"! Disfrutá tu instancia en el host ✘D Tu id es: "+player.id+"");
        room.setPlayerAdmin(player.id, true);
    }
}

function isOutsideStadium(ballPosition) {
    return ballPosition.x > stadiumWidth || ballPosition.x < -stadiumWidth || ballPosition.y > stadiumHeight || ballPosition.y < -stadiumHeight;
}

var isBallOutsideStadium = false;

function checkBallPosition() {
    var ballPosition = room.getBallPosition();
    if(isOutsideStadium(ballPosition)) {
        if(!isBallOutsideStadium) {
            isBallOutsideStadium = true;
            var totalScores = room.getScores().red + room.getScores().blue;
            if(lastScores != totalScores) {
                lastScores = totalScores;
                return false;
            }
            if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.RED || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.BLUE) {
                room.sendChat("GK");
            }
            else if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.BLUE || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.RED) {
                room.sendChat("CK");
            }
            else {
                room.sendChat(lastTeamTouched == Team.RED ? "B" : "R");
            }
        }
    }
    else {
        isBallOutsideStadium = false;
    }
    return true;
}

function getLastTouchTheBall() {
    var ballPosition = room.getBallPosition();
    var players = room.getPlayerList();
    for(var i = 0; i < players.length; i++) {
        if(players[i].position != null) {
            var distanceToBall = pointDistance(players[i].position, ballPosition);
            if(distanceToBall < triggerDistance) {
                lastTeamTouched = players[i].team;
            }
        }
    }
}

function pointDistance(p1, p2) {
    var d1 = p1.x - p2.x;
    var d2 = p1.y - p2.y;
    return Math.sqrt(d1 * d1 + d2 * d2);
}

**Comment by SebiPeppins** [comment]
This script not have lag lol

**Comment by SebiPeppins** [comment]
/* SETTINGS */

/* ROOM */

var roomName = "MemZ Bot 3v3";
var maxPlayers = 255;
var roomPublic = true;

/* STADIUM */

var stadiumWidth = 1150;
var stadiumHeight = 600;
var radiusBall = 9.8;

/* SETTINGS */

var lastScores = 0;
var lastTeamTouched = 0;
var triggerDistance = radiusBall + 15 + 0.01;
stadiumWidth += (radiusBall / 2) + 6;
stadiumHeight += (radiusBall / 2) + 6;
var Team = {
    SPECTATORS: 0,
    RED: 1,
    BLUE: 2
};
var room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: "✘✘MemZ Bot✘✘" });
room.setScoreLimit(0);
room.setTimeLimit(0);

room.onTeamGoal = function(team) {
    setTimeout(function() {
        lastScores = room.getScores().red + room.getScores().blue;
    }, 1000);
}
room.onGameStart = function(player) {
    lastScores = room.getScores().red + room.getScores().blue;
}
room.onPlayerBallKick = function(player) {
    lastTeamTouched = player.team;
}
room.onGameTick = function() {
    getLastTouchTheBall();
    checkBallPosition();
}

room.onPlayerJoin = function(player) {
room.sendChat( "Bienvenido "+player.name+"! Disfrutá tu instancia en el host ✘D Tu id es: "+player.id+"");
        room.setPlayerAdmin(player.id, true);
    }
}
room.onsetPlayerAdmin(player.id, true);
room.sendChat( "Ahora eres un administrador.");
}
room.onTeamGoal = function(team) {
room.sendChat( "GOLAAAZOOO!!!! Lo hizo "+player.name+" para el "+team+"");
}
function isOutsideStadium(ballPosition) {
    return ballPosition.x > stadiumWidth || ballPosition.x < -stadiumWidth || ballPosition.y > stadiumHeight || ballPosition.y < -stadiumHeight;
}

var isBallOutsideStadium = false;

function checkBallPosition() {
    var ballPosition = room.getBallPosition();
    if(isOutsideStadium(ballPosition)) {
        if(!isBallOutsideStadium) {
            isBallOutsideStadium = true;
            var totalScores = room.getScores().red + room.getScores().blue;
            if(lastScores != totalScores) {
                lastScores = totalScores;
                return false;
            }
            if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.RED || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.BLUE) {
                room.sendChat("GK");
            }
            else if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.BLUE || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.RED) {
                room.sendChat("CK");
            }
            else {
                room.sendChat(lastTeamTouched == Team.RED ? "B" : "R");
            }
        }
    }
    else {
        isBallOutsideStadium = false;
    }
    return true;
}

function getLastTouchTheBall() {
    var ballPosition = room.getBallPosition();
    var players = room.getPlayerList();
    for(var i = 0; i < players.length; i++) {
        if(players[i].position != null) {
            var distanceToBall = pointDistance(players[i].position, ballPosition);
            if(distanceToBall < triggerDistance) {
                lastTeamTouched = players[i].team;
            }
        }
    }
}

function pointDistance(p1, p2) {
    var d1 = p1.x - p2.x;
    var d2 = p1.y - p2.y;
    return Math.sqrt(d1 * d1 + d2 * d2);
}

**Comment by SebiPeppins** [comment]
I repaired my PC wifi, now the host its okay, Tkx for help
