### ISSUE TITLE
Uncaught Syntax Error: Unexpected token Identifier

### ISSUE THREAD

**Issue by SebiPeppins** [haxball/haxball-issues#341]
Hi, When i put the JS script in the command prompt of chrome i recieve this error.
**"Uncaught Syntax Error: Unexpected token Identifier"**

My script is:

/* SETTINGS */

/* ROOM */

var roomName = "MemZ Bot XvX";
var maxPlayers = 255;
var roomPublic = true;

/* STADIUM */

var stadiumWidth = 1150;
var stadiumHeight = 600;
var radiusBall = 9.8;

/* SETTINGS */

var lastScores = 0;
var lastTeamTouched = 0;
var triggerDistance = radiusBall + 15 + 0.01;
stadiumWidth += (radiusBall / 2) + 6;
stadiumHeight += (radiusBall / 2) + 6;
var Team = {
    SPECTATORS: 0
    RED: 1
    BLUE: 2
};
var room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: "✘✘MemZ Bot✘✘" });
room.setScoreLimit(0);
room.setTimeLimit(0);

room.onTeamGoal = function(team) {
    setTimeout(function() {
        lastScores = room.getScores().red + room.getScores().blue;, 1000);
}
room.onGameStart = function(player) {
    lastScores = room.getScores().red + room.getScores().blue;
}
room.onPlayerBallKick = function(player) {
    lastTeamTouched = player.team;
}
room.onGameTick = function() {
    getLastTouchTheBall();
    checkBallPosition();
}

room.onPlayerJoin = function(player) {
room.sendChat( "Bienvenido "+player.name+"! Disfrutá tu instancia en el host ✘D Tu id es: "+player.id+"");
        room.setPlayerAdmin(player.id, true);
}
room.onPlayerChat(player : PlayerObject "!comandos" : String) : bool
room.sendChat( "Comandos: !autor, !big, !huge, !1v1, !hockey, !hockeybig... MAS COMANDOS PROXIMAMENTE!");
}
room.onPlayerChat(player : PlayerObject "!big" : String) : bool
room.setDefaultStadium(Big : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject "!1v1" : String) : bool
room.setDefaultStadium(Classic : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject "!hockey" : String) : bool
room.setDefaultStadium(Hockey : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject "!hockeybig" : String) : bool
room.setDefaultStadium(Big Hockey : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject "!big" : String) : bool
room.sendChat( "Autor: Sebi Peppins (o MemZ) Discord: Sebi Peppins#8556");
}
function isOutsideStadium(ballPosition) {
    return ballPosition.x > stadiumWidth || ballPosition.x < -stadiumWidth || ballPosition.y > stadiumHeight || ballPosition.y < -stadiumHeight;
}

var isBallOutsideStadium = false;

function checkBallPosition() {
    var ballPosition = room.getBallPosition();
    if(isOutsideStadium(ballPosition)) {
        if(!isBallOutsideStadium) {
            isBallOutsideStadium = true;
            var totalScores = room.getScores().red + room.getScores().blue;
            if(lastScores != totalScores) {
                lastScores = totalScores;
                return false;
            }
            if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.RED || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.BLUE) {
                room.sendChat("GK");
            }
            else if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.BLUE || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.RED) {
                room.sendChat("CK");
            }
            else {
                room.sendChat(lastTeamTouched == Team.RED ? "B" : "R");
            }
        }
    }
    else {
        isBallOutsideStadium = false;
    }
    return true;
}

function getLastTouchTheBall() {
    var ballPosition = room.getBallPosition();
    var players = room.getPlayerList();
    for(var i = 0; i < players.length; i++) {
        if(players[i].position != null) {
            var distanceToBall = pointDistance(players[i].position, ballPosition);
            if(distanceToBall < triggerDistance) {
                lastTeamTouched = players[i].team;
            }
        }
    }
}

function pointDistance(p1, p2) {
    var d1 = p1.x - p2.x;
    var d2 = p1.y - p2.y;
    return Math.sqrt(d1 * d1 + d2 * d2);
}
/* SETTINGS */

/* ROOM */

var roomName = "MemZ Bot XvX";
var maxPlayers = 255;
var roomPublic = true;

/* STADIUM */

var stadiumWidth = 1150;
var stadiumHeight = 600;
var radiusBall = 9.8;

/* SETTINGS */

var lastScores = 0;
var lastTeamTouched = 0;
var triggerDistance = radiusBall + 15 + 0.01;
stadiumWidth += (radiusBall / 2) + 6;
stadiumHeight += (radiusBall / 2) + 6;
var Team = {
    SPECTATORS: 0,
    RED: 1,
    BLUE: 2
};
var room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: "✘✘MemZ Bot✘✘" });
room.setScoreLimit(0);
room.setTimeLimit(0);

room.onTeamGoal = function(team) {
    setTimeout(function() {
        lastScores = room.getScores().red + room.getScores().blue;
    }, 1000);
}
room.onGameStart = function(player) {
    lastScores = room.getScores().red + room.getScores().blue;
}
room.onPlayerBallKick = function(player) {
    lastTeamTouched = player.team;
}
room.onGameTick = function() {
    getLastTouchTheBall();
    checkBallPosition();
}

room.onPlayerJoin = function(player) {
room.sendChat( "Bienvenido "+player.name+"! Disfrutá tu instancia en el host ✘D Tu id es: "+player.id+"");
        room.setPlayerAdmin(player.id, true);
}
room.onPlayerChat(player : PlayerObject, "!comandos" : String) : bool
room.sendChat( "Comandos: !autor, !big, !huge, !1v1, !hockey, !hockeybig... MAS COMANDOS PROXIMAMENTE!");
}
room.onPlayerChat(player : PlayerObject, "!big" : String) : bool
room.setDefaultStadium(Big : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject, "!1v1" : String) : bool
room.setDefaultStadium(Classic : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject, "!hockey" : String) : bool
room.setDefaultStadium(Hockey : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject, "!hockeybig" : String) : bool
room.setDefaultStadium(Big Hockey : string) : void
setScoreLimit(3 : int) : void
setTimeLimit(3 : int) : 
}
room.onPlayerChat(player : PlayerObject, "!big" : String) : bool
room.sendChat( "Autor: Sebi Peppins (o MemZ) Discord: Sebi Peppins#8556");
}
function isOutsideStadium(ballPosition) {
    return ballPosition.x > stadiumWidth || ballPosition.x < -stadiumWidth || ballPosition.y > stadiumHeight || ballPosition.y < -stadiumHeight;
}

var isBallOutsideStadium = false;

function checkBallPosition() {
    var ballPosition = room.getBallPosition();
    if(isOutsideStadium(ballPosition)) {
        if(!isBallOutsideStadium) {
            isBallOutsideStadium = true;
            var totalScores = room.getScores().red + room.getScores().blue;
            if(lastScores != totalScores) {
                lastScores = totalScores;
                return false;
            }
            if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.RED || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.BLUE) {
                room.sendChat("GK");
            }
            else if(ballPosition.x > stadiumWidth && lastTeamTouched == Team.BLUE || ballPosition.x < -stadiumWidth && lastTeamTouched == Team.RED) {
                room.sendChat("CK");
            }
            else {
                room.sendChat(lastTeamTouched == Team.RED ? "B" : "R");
            }
        }
    }
    else {
        isBallOutsideStadium = false;
    }
    return true;
}

function getLastTouchTheBall() {
    var ballPosition = room.getBallPosition();
    var players = room.getPlayerList();
    for(var i = 0; i < players.length; i++) {
        if(players[i].position != null) {
            var distanceToBall = pointDistance(players[i].position, ballPosition);
            if(distanceToBall < triggerDistance) {
                lastTeamTouched = players[i].team;

**Comment by dixtel** [comment]
Error: Line 51: Unexpected token ,
Use js syntax checker to find errors e.g. http://esprima.org/demo/validate.html

**Comment by Raamyy** [comment]
Yes, Because your syntax is wrong..

Functions are defined like this :point_down: 
![image](https://user-images.githubusercontent.com/29176293/40683652-75891ffa-638f-11e8-87e3-20a53baf891f.png)
there is no **: bool** in the end and **:** after every parameter, this is written in the documentation to clarify the type of objects that will be passed to the function, But not written in the actual code.

**Comment by SebiPeppins** [comment]
Segun el corrector el java script esta bien, pero ahora me dice al colocar el script: Uncaught SyntaxError: missing ) after argument list
