### ISSUE TITLE
Update sendChat() function

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#342]
I think that sendChat() function should updated to be :

### `sendChat(message : string , playerID : int)`

where playerID has a default parameter, as if it is not provided in the function call the messaged is displayed to the whole room.

But if there is a specific player id it is only shown to that player.

**Comment by basro** [comment]
Yes, this is the plan.

**Comment by SebiPeppins** [comment]
Good feature

**Comment by olegmisar** [comment]
@basro, when are you going to make this improvement? Rooms which are based on headless host are full of spam. Everyone wants to know what are commands available, what's the current streak etc. This feature is really needed. About how much time it will take to make this feature?
