### ISSUE TITLE
More Zoom Options 2x 3x 4x?

### ISSUE THREAD

**Issue by haxplayer** [haxball/haxball-issues#344]
I play on a 4k monitor and while the max zoom(1.5x) is better than original flash zoom, it is still considerably small on my 4k resolution.

Any chance you could add more zoom levels?

Before anyone mentions to use zoom controls on browser, this causes bad pixelation and makes the game look terrible.

**Comment by Wrathen** [comment]
Open the Developer Tools and It will make your game screen smaller. And also you can zoom in ingame to adjust the view. It might be a temporary solution for you.

**Comment by Leo-MapCreator** [comment]
2x is more far or more close?

**Comment by haxplayer** [comment]
@Wrathen I'm requesting for higher zoom levels eg. make the game screen larger. I'm aware of the in game zoom levels(I use 3).

**Comment by basro** [comment]
There's now more zoom levels available through the zoom option in the video settings tab.

**Comment by meteus** [comment]
@Wrathen dayı discorddan eklesene beni nick: 187#3248 seninle konuşmam gereken bir şey var
