### ISSUE TITLE
Support more than 2 teams

### ISSUE THREAD

**Issue by pmanacas** [haxball/haxball-issues#345]
It would be nice if we could create custom stadiums for more than 2 teams and custom win rules.
for example to be able to replicate three sided football
https://en.wikipedia.org/wiki/Three_sided_football

i.e.
3 teams
3 goals
lowest goals conceded wins

**Comment by Leo-MapCreator** [comment]
I think you can do that with the API

**Comment by pmanacas** [comment]
@Leo-MapCreator 
Do you mean using the headless host API? (https://github.com/haxball/haxball-issues/wiki/Headless-Host)
As far as I saw in the documentation it seems to have only Red and Blue teams hardcoded as well as win condition being the first to reach a max points limit.

**Comment by Leo-MapCreator** [comment]
Imagine 4 players in red and blue. You can set that the 2 first from red are Red, the 2 last from red are Purple, the 2 first from blue are Blue and the 2 last from blue are Cyan

**Comment by basro** [comment]
I wont be adding support for 3 teams, but as Leo-MapCreator suggests with some creative hacking it'd be possible to do with the headless host api.
