### ISSUE TITLE
Personal team custom colors

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#346]
I don't know if that makes sense, but create an option to display the team colors that you want after you disable the team custom colors from the room, you would be able to enable your personal custom colors instead of it displaying the basic color

**Comment by iamrenan** [comment]
Adding to that feature request, a custom name for the teams would be nice too. Instead of red and white, we could change it to orange and purple, or even "Barcelona" and "Real Madrid". These names would be displayed in the victory message, the game menu, and the chat.

**Comment by basro** [comment]
Sorry but I don't think I'll implement this feature.
