### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by Skarmunds** [haxball/haxball-issues#354]
Hi! The headless host code works on my laptop and it worked before on server PC through remote connection (I'm just an admin for haxball cummunity and have access). Now it shows just this error in console after solving captcha. 
`headless-min.js:17 WebSocket connection to 'wss://p2p.haxball.com/host?token=thr1.AAAAAFsRdMTRwv9WM2W5dQ.ozh7ozzoYIY' failed: Error during WebSocket handshake: Unexpected response code: 502`
Is it just relevant to their server config?

**Comment by basro** [comment]
You are probably reaching the limit of connections per ip.

**Comment by Skarmunds** [comment]
I think it is. Keep asking captcha when opening a normal room.
