### ISSUE TITLE
onPlayerBallTouch()

### ISSUE THREAD

**Issue by tohey** [haxball/haxball-issues#357]
I know you implemented an example using `onGameTick()`. However, checking all the players 60 times per second seems computationally demanding. I wonder if it's possible to define an event that is fired when a player touches the ball.

Thanks!

**Comment by basro** [comment]
I won't be implementing this.

The computational cost is fine, trust me.

**Comment by Leo-MapCreator** [comment]
@tohey Dude, trust him xDDDD
