### ISSUE TITLE
Has Haxball sped up?

### ISSUE THREAD

**Issue by mrhaxball** [haxball/haxball-issues#359]
I noticed haxball feels quicker, and that balls i kick past people don't get tackled anymore because they just don't reach it like they used to. is this because of this?

Netplay

The netplay works very similarly to the flash version but uses WebRTC instead of RTMFP.

If you have issues connecting to room hosts but were able to do it in the flash version you should report it here.

You will notice ping will be a bit lower than usual, this is mainly because in flash network events were handled 60 frames per second while in html5 the events are handled immediately and independent of the screen refresh rate. This meant that flash could add about 32msec of latency depending on how close to the frame updates the network packets would arrive.

 Feels like a great improvement from the slower flash, keep up the good work !

**Comment by basro** [comment]
Game physics and speed have remained unchanged.

The html5 version has smoother prediction and lower latency so maybe that's what you are feeling.
