### ISSUE TITLE
Stuck On Loading...

### ISSUE THREAD

**Issue by Quantellig** [haxball/haxball-issues#36]
![2017-10-25_19-17-28](https://user-images.githubusercontent.com/33106441/32027848-5dac3d02-b9b9-11e7-92db-0b4908d1e2dc.png)
Tried opera, firefox and chrome but I'm stuck on the loading page
Please help me basro i rly wanna test the new gameplay

**Comment by basro** [comment]
@Quantellig please follow this instructions and report back:
1) Press right click -> Inspect anywhere on the site.
2) Refresh the site while the inspector window is open.
3) Go to the console tab and if there's anything printed there copy it and paste here.
4) Go to the network tab, scroll to the bottom and take a screenshot, upload the screenshot here.

**Comment by Quantellig** [comment]
A parser-blocking, cross site (i.e. different eTLD+1) script, http://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=278378, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ (index):37
(index):37 GET http://server.cpmstar.com/view.aspx?poolid=26640&script=1&rnd=278378 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ (index):37
pako-jszip.min.js:50 Uncaught (in promise) Error: Corrupted zip : can't find end of central directory
    at e.readEndOfCentral (pako-jszip.min.js:50)
    at e.load (pako-jszip.min.js:52)
    at new e (pako-jszip.min.js:45)
    at e.k.exports [as load] (pako-jszip.min.js:16)
    at new e (pako-jszip.min.js:15)
    at game-min.js:95
    at <anonymous>
readEndOfCentral @ pako-jszip.min.js:50
load @ pako-jszip.min.js:52
e @ pako-jszip.min.js:45
k.exports @ pako-jszip.min.js:16
e @ pako-jszip.min.js:15
(anonymous) @ game-min.js:95
Promise rejected (async)
(anonymous) @ game-min.js:96
l.Gj @ game-min.js:97
l.pk @ game-min.js:95
(anonymous) @ game-min.js:201
(anonymous) @ game-min.js:201


![chrome_2017-10-27_17-44-45](https://user-images.githubusercontent.com/33106441/32126433-b6374fe4-bb3e-11e7-82dc-653ddac6ae39.png)
![chrome_2017-10-27_17-44-59](https://user-images.githubusercontent.com/33106441/32126434-b64365fe-bb3e-11e7-9fe9-97f2904a6639.png)

**Comment by Quantellig** [comment]
Tried disabling adblock, didn't work

**Comment by basro** [comment]
res.zip is corrupted for some reason, your browser says it's 122 bytes but it should be several kilobytes
Try downloading this: http://html5.haxball.com/g/8p8ZBIFi/res.zip
Is it a valid zip file?

**Comment by Quantellig** [comment]
I downloaded it with IDM and yes it's a valid zip file but I don't know which folder i should put it in

**Comment by Quantellig** [comment]
It worked, I had to uninstall Internet Download Manager though.

**Comment by basro** [comment]
Do you mean that haxball is working now or the zip file is valid?
