### ISSUE TITLE
[Headless] Help With Stats Bot (goal/assist/games/...)

### ISSUE THREAD

**Issue by wohSi** [haxball/haxball-issues#360]
I dont know how to do it. Can anyone help me?!
How can i do with this code for example? https://www.hastebin.com/esemewibey.php

**Comment by Raamyy** [comment]
What do you mean by 

> How can i do with this code for example?

**Comment by wohSi** [comment]
What I mean is to use this "code" to put the stats bot. @Raamyy

**Comment by VukBakic** [comment]
What do you do to execute code with php? Do you still have to evaluate it in console?

**Comment by wohSi** [comment]
Same thing with others codes, yes

**Comment by tohey** [comment]
Very related: https://github.com/haxball/haxball-issues/issues/348#issuecomment-393608952

**Comment by SebiPeppins** [comment]
You are Ryu? Portugal? Im sebi bro!

**Comment by wohSi** [comment]
Who?

**Comment by SebiPeppins** [comment]
You are not Azis friend?

**Comment by SebiPeppins** [comment]
We were flash hackers you had a page but it closed

**Comment by SebiPeppins** [comment]
I are friend of messi deis

**Comment by SebiPeppins** [comment]
You are Ishow?

**Comment by SebiPeppins** [comment]
http://densk.7m.pl
