### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#362]
Create an page with all the commands available for haxball in-game for people to have knowledge of it, for example i didn't know the existance of extrapolation and clear_bans, some usefull comands are not used because players don't know the existance of them, in brazil a lot of them know how to use set_password, but after that they gotta recreate a room to clear the password because they don't know that clear_password exists, i bet 90% of players don't know how to clear teams uniform, it serves kind of a tutorial for new players too

**Comment by Leo-MapCreator** [comment]
@basro Where is /clear_bans in _News_ ?

**Comment by basro** [comment]
https://github.com/haxball/haxball-issues/wiki/Chat-Commands
