### ISSUE TITLE
resetTeams

### ISSUE THREAD

**Issue by SebiPeppins** [haxball/haxball-issues#366]
Something great would be to add a function of resetTeams for the API.
Example:

room.onGameStop = function(b) {
    if (b == null) {
room.resetTeams();
        setTimeout(function() { room.startGame(); }, 5000);

**Comment by Leo-MapCreator** [comment]
You can even create a function called resetTeams

**Comment by SebiPeppins** [comment]
After finished the game in 5 seconds start new game
