### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#368]
Is it possible to make a queue for a full room? Something like this:
http://www.habboxwiki.com/wiki/images/f/fc/Room_queue.png

**Comment by Leo-MapCreator** [comment]
No need to create the spectator part though

**Comment by Wenomka** [comment]
spectator mode - good idea

**Comment by Leo-MapCreator** [comment]
I also dont agree with Spectator, it would add unnecessary lag to the room, plus it would be harder to do

**Comment by basro** [comment]
Sorry but this is not going to be implemented.

**Comment by Leo-MapCreator** [comment]
Why its not going to be implemented? Its a good idea if you want to join a determined room but it is full

**Comment by cr0ndor** [comment]
No explanation??
