### ISSUE TITLE
Player and Ball shape

### ISSUE THREAD

**Issue by B4D4SS** [haxball/haxball-issues#37]
The new update has changed the shape of the player circle and the ball. They're both less squared on the north-south and east-west sides, so shaped more like a circle and less like a hectagon: https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Regular_octagon.svg/500px-Regular_octagon.svg.png

I hope this goes back to how it was with the same exact shape, since the feel on the ball is too different, and some skill has been taken out of the game imo. There's less blocking between players since now they slip off each other too easily, and on the ball you can't have a nice grip on it while turning like the original Haxball has, which reduces the amount of skills and tricks possible, so the skill ceiling of the game is lowered which isn't wanted or needed.

**Comment by B4D4SS** [comment]
Also the thickness of the black line around the Player and Ball have changed a lot too, I'm not sure exactly how this affects the gameplay or if it just affect the looks, but maybe it should be the same as it was too, even if the physics aren't affected by it, for the same feel that we had in the original Haxball.

**Comment by basro** [comment]
The physics are unchanged. The ball might have been less round before but that would be a visual bug, it was perfectly round in the physics.

I wont be making the balls look less round.
