### ISSUE TITLE
Game frozen but ping continues to update

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#373]
I couldn't send chat, well, i could, but it didnt show on the chat, what other people said wouldn't appear on the chat also, it was like i'd lost connection, but ping graph was working, 40, i wasnt lagging, it happened after i entered the room, almost the exact moment i joined the red team had won and the host/admin stopped the game, after that chat was useless but ping was working, i reentered the room, they said i was sending messages to them, but nothing appear to me, the game was stopped on menu for me, but when i rejoined the game was actually being played, kind of the grapich/sound have freezed

**Comment by Leo-MapCreator** [comment]
Extra: It wasnt an API room

**Comment by basro** [comment]
The good news is I know what you are talking about, the bad news is don't really know why it would have happened.

Please report if it happens again so that I get an idea of the rarity of this event.

I'll edit the name of your issue to be more descriptive so that others can find it.

**Comment by basro** [comment]
I've found that an old version of chrome has a bug which causes this.
I've implemented a workaround that fixes it for that version of chrome, I think this is what happened to you.

@Leo-MapCreator: is there any chance that you can tell me which version of chrome you and the host were using?

**Comment by Leo-MapCreator** [comment]
Mine isnt that old, probably the most updated or close to that, idk about the host though, i dont remember his name

**Comment by basro** [comment]
Ok well, I'm going to consider it fixed and close this. But please report if you ever see that happen again.

**Comment by Leo-MapCreator** [comment]
I think it was something with the update rather than my client, it happened the same day

**Comment by basro** [comment]
It might have been a coincidence that you joined a room hosted by someone using an old version of chrome the same day.
