### ISSUE TITLE
Divulgation

### ISSUE THREAD

**Issue by gandinaldinho** [haxball/haxball-issues#374]
This is a question I've always had, does the game have some kind of disclosure somewhere? I've known the game through friends from other games, and everyone I know is the same case. Taking advantage of this great update, would not it be a good time to try and bring in new players? Are there any plans for disclosure?

**Comment by basro** [comment]
I've never done any active advertising for haxball, it's always been spread by organic word of mouth.

**Comment by Leo-MapCreator** [comment]
@basro You can invest part of the money you make with advertising to advertise haxball on game sites to atract new players
