### ISSUE TITLE
The balls are jagged

### ISSUE THREAD

**Issue by FrescoPL** [haxball/haxball-issues#377]
Basro my friend has a problem. At 1920x1080 resolution, the balls are jagged, while on the resolution of 1280x720 everything looks normal and the balls are smooth. I tested various internet browsers and change in settings zoom (last update). Could you help him somehow? I'm sending screenshots about what's going on.

https://cdn.discordapp.com/attachments/360944817213014018/454285453848215553/unknown.png
https://cdn.discordapp.com/attachments/360944817213014018/454285753896140830/unknown.png

**Comment by basro** [comment]
This kind of thing happens when you apply zoom on the browser. Make sure the browser's zoom level is set at 100%.

In chrome there's a global zoom setting:
![image](https://user-images.githubusercontent.com/1387293/41106276-1a06ba1c-6a46-11e8-891b-8fcd76c2f5bd.png)

**Comment by FrescoPL** [comment]
Thanks :D

**Comment by basro** [comment]
Did you confirm with your friend that this fixed the problem?

**Comment by FrescoPL** [comment]
Kinda, on 100% zoom it still looks like this. The balls are ok on 80% browser zoom, but because of this he needs to increase his in-Haxball zoom

**Comment by basro** [comment]
I've investigated a bit further and it looks like it's possible to fix this so that there's no jaggies regardless of the zoom level or screen DPI.

I'll be fixing this soon.

**Comment by basro** [comment]
This should now be fixed regardless of DPI or browser zoom level.
