### ISSUE TITLE
Cookies Problem

### ISSUE THREAD

**Issue by Whunpp2** [haxball/haxball-issues#380]
Haxball is not telling us players that needs Cookies activated to get access of everything. 
Before the "Update: Configurable Keys" just browsers with enabled Cookies could change the uniforms and others settings in Settings. 
But now Settings just not opening, and Haxball don't specific us why this is happening. So I think now Haxball HAVE to tell US that we need Cookies enable to get a perfect Client.

**Comment by basro** [comment]
HaxBall doesn't require or use cookies in any way so I don't know what you are talking about.

**Comment by Leo-MapCreator** [comment]
LULULULULULULUL

**Comment by Whunpp2** [comment]
What? It does.
Do this in your Chrome:
![image](https://user-images.githubusercontent.com/38140405/41132401-682beb12-6a97-11e8-89e0-f41f2574c8b6.png)
The first difference will be the unnamed to undefined:
![image](https://user-images.githubusercontent.com/38140405/41132447-b0bd0758-6a97-11e8-9d00-e4f2c58d50c3.png)
Then now try to open Settings.

**Comment by Whunpp2** [comment]
What? It does.
Do this in your Chrome:
![image](https://user-images.githubusercontent.com/38140405/41132580-50793db6-6a98-11e8-9a3a-6cf0edd46a3d.png)
The first difference will be the unnamed to undefined:
![image](https://user-images.githubusercontent.com/38140405/41132585-5593b3b2-6a98-11e8-9d27-94db41190cb5.png)

Then now try to open Settings.

@basro

**Comment by basro** [comment]
Ok, it seems this is a bug introduced in the last update.

**Comment by basro** [comment]
This should be fixed now.
