### ISSUE TITLE
Page Closing Warning

### ISSUE THREAD

**Issue by Raamyy** [haxball/haxball-issues#381]
Add a warning when closing the **Headless** page to prevent accident closes.
like this :point_down: 
![image](https://user-images.githubusercontent.com/29176293/41158492-7256192c-6b29-11e8-825d-392d66b21073.png)

**Comment by pilaf** [comment]
You can implement this yourself by using `window.onbeforeunload`:

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by tohey** [comment]
+1. Also please add `target="_blank"` attribute to the room link so that left click opens it in a new tab. I accidentally closed the bot many times just forgetting to hold Ctrl while I click.

**Comment by basro** [comment]
I wont be adding this since as pilaf said, it can be implemented by the user already.
