### ISSUE TITLE
Bot with goal scorer

### ISSUE THREAD

**Issue by pirocra** [haxball/haxball-issues#385]
Hello could you tell me how does my bot count og goals and in the room have the goal rank

**Comment by Leo-MapCreator** [comment]
array with the name of the players that scored, check if the player that scores is already in array, if yes, +1 goal, if not, save his name and add 1 goal

**Comment by pirocra** [comment]
I would like the code because I'm not good at programming

**Comment by Leo-MapCreator** [comment]
Nah, its kinda complicated, im not doing this

**Comment by pirocra** [comment]
:)
