### ISSUE TITLE
Cant Shoot with Numpad 0

### ISSUE THREAD

**Issue by Allenaq** [haxball/haxball-issues#389]
Lan aminagoyim, i cant shoot with Numpad 0 it dosont Work. Please fix this because i play only with Numpad 0. hadi fast fix pls thank you.

**Comment by basro** [comment]
You can edit the keys from the settings now:
![image](https://user-images.githubusercontent.com/1387293/41251164-79bed38a-6d8f-11e8-90a2-463025d4817e.png)

**Comment by Leo-MapCreator** [comment]
I think he is talking about Numpad0 being removed from default kick input
