### ISSUE TITLE
Saving data

### ISSUE THREAD

**Issue by Basirius007** [haxball/haxball-issues#392]
Hello, I have a question if anybody figured out, how to save data, so when i set up new room there are already player names and their goals, assists and so on that the had in previous room?

**Comment by olegmisar** [comment]
You can use localStorage. But localStorage have limitation of ~5mb(depends on browser). If you want to make big storage to store a lot of data, you should look at (https://developer.mozilla.org/ru/docs/IndexedDB)[IndexedDB] or make backend server. But I think the simplest way to store a big amount of data is (https://localforage.github.io/localForage/)[localforage library].

**Comment by Wolf72** [comment]
@olegmisar Don't you need to have installed localforge library on server? And by server I mean where haxball.com/headless is hosted. The problem is cross domain policy. I tried setting cors server locally but couldn't connect to haxball using xmlhttprequest....

**Comment by olegmisar** [comment]
How have u tried to connect to haxball? Code, please.

**Comment by Wolf72** [comment]
```
function createCORSRequest(method, url) {
  var xhr = new XMLHttpRequest();
  if ("withCredentials" in xhr) {

    // Check if the XMLHttpRequest object has a "withCredentials" property.
    // "withCredentials" only exists on XMLHTTPRequest2 objects.
    xhr.open(method, url, true);

  } else if (typeof XDomainRequest != "undefined") {

    // Otherwise, check if XDomainRequest.
    // XDomainRequest only exists in IE, and is IE's way of making CORS requests.
    xhr = new XDomainRequest();
    xhr.open(method, url);

  } else {

    // Otherwise, CORS is not supported by the browser.
    xhr = null;

  }
  return xhr;
}



var request = createCORSRequest( "GET", "http://localhost:8123/scoreboard.JSON" );
if ( request ){
  // Define a callback function
  request.onload = function(){
	  scoreBoard=JSON.parse(request.responseText);
  };
  // Send request
  request.send();
}
```

**Comment by olegmisar** [comment]
What browser do u use?

**Comment by Wolf72** [comment]
chrome

**Comment by olegmisar** [comment]
You have to allow mixed content. [Here](https://pearsonnacommunity.force.com/support/s/article/How-to-display-mixed-content-with-Google-Chrome-Internet-Explorer-or-Firefox-1408394589290) are solutions for different browsers.

**Comment by Wolf72** [comment]
@olegmisar That actually worked :D Problem is now that anyone can access my files at 8123 port xD
Still I would need to update my whole scoreboard.json everytime some event happens (player scores goal, team wins etc.). I am not so familiar with php to make backend script on my server.
What do you personally use for storing info olegmisar?

**Comment by olegmisar** [comment]
Maybe I will use IndexedDB. Or localforage library, which is a wrapper for IndexedDB. Localforage is simple to use and doesn't require backend, it saves all the data in browser. But you should read about limitations. I believe that IndexedDB doesn't have limits but I am not sure.

**Comment by Wolf72** [comment]
@olegmisar Is there way to update indexeddb store without fetching whole player object , updating it and then using put request to update it?

**Comment by meteus** [comment]
@Wolf72 Do you have discord? I want to ask you something.

**Comment by Wolf72** [comment]
@meteus Wolf72x#6765

**Comment by meteus** [comment]
@Wolf72 Hey, added you. My name is 187#3248
