### ISSUE TITLE
ICE failed, add a TURN server and see about

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#393]
Hello, i'm trying to improve my headless but i just realized some players couldn't join it (and i can't join their) with this issue: ICE failed, add a TURN server and see about:webrtc for more details

**Comment by olegmisar** [comment]
The same problem when I use headless host on my computer. Firefox 57.0b7

**Comment by AnddyAnddy** [comment]
Firefox Version 60.0.2 (64 bits) for me

**Comment by basro** [comment]
This message appears when a player is unable to join your room, either your router or his router firewall prevented the connection.

It is safe to ignore.
