### ISSUE TITLE
[Question label] Physics

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#394]
Is it possible for you to define what are the physics in haxball, for map creator?
For example: what is a [1,0] speed? I know its from the x axis to the right, with speed of 1, but what is a speed of 1? Through tests i discovered that a speed of 1 is 60 distances in 1 seconds, and giving that haxball works with 60Hz, its a distance of 1 every tick, but what is a damping of 0.99, of 1.21, what is a bCoef of 2? I suppose it returns twice the speed before contact, but i can be wrong, what is for example an acceleration of 0.81?

**Comment by Leo-MapCreator** [comment]
Please define them, it would help to create more fancy smart maps and more diversificated, because i can control better the physics, it wont be trial and error untill you succed

**Comment by basro** [comment]
Speed is in units per game tick, and yes it's 60 ticks per second.

Damping is a value that multiplies the speed every game tick, it works exponentially. Basically every frame `newSpeed = oldSpeed * damping`
Values lower than 1 will cause the ball to slow down over time, while higher than 1 will cause it to speed up.

bCoef stands for bouncing coefficient and represents how much of the initial speed is preserved when a collision happens.
bCoef of 0.5 means half of the speed is lost, bCoef of 1 means it bounces perfectly and no speed is lost. bCoef of 2 means the resulting speed is twice as much as the initial speed (this could never happen in real life)

For a ball to go through a line it's speed has to be higher than it's radius.

I'll probably write some documentation in the wiki page later on.

**Comment by Leo-MapCreator** [comment]
Thx for the info basro, one last thing that i forgot to ask, how do you define speed after a kick? For example i have a kicking coefficient of 5, kickStrengh*invMass = 5, how much is that in speed after the kick? And if the ball speed is higher than it radius, will it always go trough, or depends on the distance?

**Comment by Leo-MapCreator** [comment]
If you want help with physics formulas such calculating the distance the ball will stop with a given initial speed and a damping, or the time it will take to stop, i can help you, plus by _**newSpeed = oldSpeed * damping**_ the ball will never stop in fact?

**Comment by Leo-MapCreator** [comment]
@basro, how do you define the speed after the kick with a given kickCoefficient?

**Comment by basro** [comment]
There's no kickCoefficient, there's kickStrength and that value is multiplied by the invMass of the ball and added to it's speed.
`
finalSpeed = initalSpeed + kickVector * kickStrength / ballMass`

**Comment by Leo-MapCreator** [comment]
I defined kickCoefficient up there, it was a simpler way to say
