### ISSUE TITLE
Petition to change "Auto" to "Top"

### ISSUE THREAD

**Issue by cr0ndor** [haxball/haxball-issues#396]
Players still say auto when they really want to pick a random team. I have never heard a player say "Auto" to mean they want the players at the top of the specs. Everyone just says "Top". It's a minor thing, but I don't understand why Auto was ever changed in the first place.

**Comment by Leo-MapCreator** [comment]
Vote what you want here
https://www.strawpoll.me/15892784

**Comment by Leo-MapCreator** [comment]
@basro Any words about this thread?

**Comment by basro** [comment]
I won't change the name on the button.

**Comment by Leo-MapCreator** [comment]
Why not? It is to prevent the confusion

**Comment by cr0ndor** [comment]
Is it a coding/API issue? Are there too many instances where the term "Auto" is already used, which would have to be changed? Auto equated to random for nearly 6 years. Over 90% of the community is in favor of the change. This seems more like a "wontfix" than a closed discussion.

**Comment by Leo-MapCreator** [comment]
I also think the name Auto is better, but the inconvenience is that Auto had a different meaning for everyone, it happens with me when i create a map and i have to fix something, i wouldnt like to change the name, but i have to do this so people can identify the correct one, you can't simply change the meaning of a thing without changing its name

**Comment by Leo-MapCreator** [comment]
I think this should be taken into account, this is what a lot of players think about the 'Auto':
_'HiddenName'_: cara não inteligente **(very unsmart guy)** [He is talking about you]
_'HiddenName'_: mantem o nome e muda a funçao **(keeps the name but changes the function)** [He is talking about auto]

A lot of players are unsatisfied with that, and in my opinion this is what matters in the end, what the users think
