### ISSUE TITLE
Why spaces are removing from text

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#397]
When in text is two or more spaces then they are merged to one space. I want to more readable my statistic that why I used two spaces beetwen text.

**Comment by olegmisar** [comment]
Player chat is based on html. In html all space characters (tabs, newlines etc) are merged to one space. To prevent this behavior you have to wrap your text with "pre" tag. But I am not sure it's is possible because all html tags are escaped before showing in chat.
