### ISSUE TITLE
Add setPassword removePassword

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#398]
Hello, please add this functions to api.

**Comment by iamrenan** [comment]
Alternatively, you can enter your own room and type `/set_password <password>` and `/clear_password`.
I don't know if it works but I think using `room.sendChat("/set_password <password>")` might work too, so you don't have to open a new tab.

**Comment by olegmisar** [comment]
No, you cannot enter headless room and set password because only host(in this case headless host) can set password.

**Comment by iamrenan** [comment]
That's right, I forgot to note that and assumed op could give himself admin with the `room.setPlayerAdmin` API function.

**Comment by olegmisar** [comment]
Admins can't set password too

**Comment by basro** [comment]
I'll be adding this api soon.

**Comment by haxplayer** [comment]
Also would like this feature.

**Comment by basro** [comment]
This is now implemented. [Docs here.](https://github.com/haxball/haxball-issues/wiki/Headless-Host#setpasswordpass--string--void)
