### ISSUE TITLE
Custom link

### ISSUE THREAD

**Issue by FrescoPL** [haxball/haxball-issues#399]
Hey, what do you think about adding an option to create a room with a custom link, for example https://html5.haxball.com/play?c=thehax1

**Comment by Leo-MapCreator** [comment]
Why?

**Comment by FrescoPL** [comment]
It would help me create my forum-tagged rooms, hotlinked on the forum, without a need to change a link in the system every time I reset the server

**Comment by Leo-MapCreator** [comment]
But how would you associate the custom link with the real link in haxball? Redirecting?
Honestly, I dont think basro would do that, but i can be wrong

**Comment by basro** [comment]
I wont be implementing this feature.
