### ISSUE TITLE
fps options

### ISSUE THREAD

**Issue by voyayeah** [haxball/haxball-issues#40]
Having an option to change FPS settings like in flash haxball would be very useful. I've only used 30fps in flash haxball and now that we only get to play with 60fps, I can't get used to it.

**Comment by helppe** [comment]
what is the advantage of 30fps?

**Comment by julysfx** [comment]
Playing with 60fps is too slippery for me and some of my friends prefer playing with 30fps too

**Comment by slavel** [comment]
I feel the ball only at 30 fps

**Comment by basro** [comment]
30 FPS option is now implemented and released.
