### ISSUE TITLE
 Giving admin a player with a specific nickname

### ISSUE THREAD

**Issue by taboret1234** [haxball/haxball-issues#400]
Hi, How can I make such a command to a host to give admin the player with a specific name? Thank you in advance for your help!

**Comment by AnddyAnddy** [comment]
you can try:
room.onPlayerJoin = function(player){
if (player.name == specificName) room.setPlayerAdmin(player.id, true) ; 
}
where specificName is a string 
you could also allow several names by using an array where will be set different nicks

**Comment by taboret1234** [comment]
The first way did not work. Unfortunately, I do not know about coding, could you show how to create such an array?

**Comment by olegmisar** [comment]
You should learn basics of JavaScript before coding something. Here is code:
```javascript
const names = ['olegmisar', 'taboret', 'anddy']
room.onPlayerJoin = player => {
    if (names.includes(player.name)) 
        room.setPlayerAdmin(player.id, true)
}
```

**Comment by Leo-MapCreator** [comment]
The 1st way didnt work because you probably used if (player.name == specificName) like it is here, unless specificName is a variable, you gotta do if (player.name == "specificName")
