### ISSUE TITLE
Headless and Captcha

### ISSUE THREAD

**Issue by laichzeit** [haxball/haxball-issues#401]
Hi,
I don't have any experience with JS so that i try my code many times. While while working on in, after awhile solving captha for each code-test gets annoying.  Is there a easier way? Because over time captcha gets harder and it is discouraging. 

Thank you.

**Comment by pilaf** [comment]
You could write a dummy version of the headless API and test your code against it. You wouldn't be able to join the room and test manually, but it would help you debug faster and even write unit tests.

**Comment by laichzeit** [comment]
Could you explain what is dummy version of headless API to a dummy? I utilize console.log() to see output of API function and then try to do something.

**Comment by pilaf** [comment]
Dummy version means that you just replicate the methods/events of the API but without the actual game. Then your bot code can interact with that dummy API instead of the real game and you can create scenarios for testing.

**Comment by Leo-MapCreator** [comment]
You dont need to reboot the server, just copy-paste all of your code on the same console, it will update automatically and you dont need to reset it

**Comment by Leo-MapCreator** [comment]
For example, i wrote 
room.onPlayerTeamChange = function(changedPlayer){
 if(changedPlayer.id == 0){
 room.setPlayerTeam(changedPlayer.id,0)
 }
}

but now i want 
room.onPlayerTeamChange = function(changedPlayer){
 if(changedPlayer.id == 0){
 room.setPlayerTeam(changedPlayer.id,0)
 room.sendChat("The host can't be moved")
 }
}

just copy paste this single part and it will update the onPlayerChange function
