### ISSUE TITLE
Ping haxball bug.

### ISSUE THREAD

**Issue by qLaur98** [haxball/haxball-issues#402]
Why ping  jumping from 30-40 ping to 200- 300. (Why appearred line from ping .. )
https://imgur.com/a/1w1OlQ4

**Comment by Leo-MapCreator** [comment]
???

**Comment by Leo-MapCreator** [comment]
Red means you lost a pack

**Comment by basro** [comment]
This is not a bug, the red lines signify that a ping message was sent but the reply never came back. This means your connection to the host has some amount of packet loss which is never good.
