### ISSUE TITLE
goal by player.id asist by player.id 

### ISSUE THREAD

**Issue by ekmekyiyen** [haxball/haxball-issues#406]
I tried it but it doesnt work.
// If Player Goals
{
		room.sendChat("Goal from"(player.id);
If Player Asists
{room.sendChat("Asist from"(player.id);

I also make it combine. Looks like it:
Bot: Goal by xxx, asist yyy

**Comment by AnddyAnddy** [comment]
it's more like:
room.sendChat("Assist from" + player.name );

**Comment by Leo-MapCreator** [comment]
onPlayerKickBall {
lastkicker2 = lastkicker
lastkicker = player.id
}

onTeamScore {
room.sendChat("Goal from " + lastkicker + ", Assist from " + lastkicker2)
}

**Comment by Leo-MapCreator** [comment]
You can do it more complex considering the teams to see if it was own goal or not, and if the assist was from the same team or not, but that's another thing

**Comment by AnddyAnddy** [comment]
Be careful if a player scores without kicking the ball, it can lead to an error !

**Comment by Leo-MapCreator** [comment]
Yeah, but that is more complex, still doable though
