### ISSUE TITLE
Change team name

### ISSUE THREAD

**Issue by olegmisar** [haxball/haxball-issues#408]
We can change team colors: `/colors red 0 FFFFFF CE2485`. But we cannot set team names. It is strange to see in chat that _Red team won the match_, but actual team color is magenta. Changing team name is only cosmetic but will be more logically correct. Team name should be changed in menu, in chat, on scoreboard.

Command: `/team_name team name`  
`/team_name red orange` will change "red" team name to "orange" and `/team_name red red` will cancel changes.

Headless API: `room.setTeamName(team: int, name: string)`.  
`room.setTeamName(2, 'purple')` will change blue team name to "purple".

**Comment by ekmekyiyen** [comment]
nice idea

**Comment by ekmekyiyen** [comment]
good idea

**Comment by Leo-MapCreator** [comment]
From other older threads, it seems that basro doesnt like this idea

**Comment by olegmisar** [comment]
@Leo-MapCreator please, links to these threads. Any this is only COSMETIC change. It is almost no changes in code, just adding a couple of functions.

**Comment by Leo-MapCreator** [comment]
Check comment 2 in #346, and in #251 
Im not saying that he doesnt want to implement, im saying it seems that he doesnt want to implement

**Comment by olegmisar** [comment]
@Leo-MapCreator if you are not sure then don't say anything. Use facts, not guesses.

**Comment by Leo-MapCreator** [comment]
Im not confusing anyone

**Comment by basro** [comment]
I will not implement team name changing.
