### ISSUE TITLE
Team color bug

### ISSUE THREAD

**Issue by olegmisar** [haxball/haxball-issues#409]
When you set team color, arrows' colors, which show players those are offscreen, don't change. [screenshot](https://prnt.sc/jxbv2o).

**Comment by dixtel** [comment]
Arrows didn't change colors

**Comment by Leo-MapCreator** [comment]
It never changed

**Comment by olegmisar** [comment]
@Leo-MapCreator these arrows should be the same colors as actual team colors. I have a room where players pick colors. When _BLUE team_ color is a shade of red but arrow is still blue it confuses players. So they don't focus on game because they try to compare their real color and arrow color.

**Comment by Leo-MapCreator** [comment]
Im not saying this is right or this is wrong, im saying it wasnt meant to change the arrow color, just the uniform color, thus not a bug

**Comment by olegmisar** [comment]
@Leo-MapCreator anyway it shouldn't distract players. I think it's have to be fixed/implemented.

**Comment by basro** [comment]
This is not a bug.
