### ISSUE TITLE
extrapolation command (slow movement)

### ISSUE THREAD

**Issue by iscoman** [haxball/haxball-issues#412]
Hi basro, Me and a few of my friends noticed that like a week ago something has changed in the resolution/graphic of the game (correct me if I'm wrong), also there is a new command called "extrapolation".
idk if its only in our heads but we all feel like the movement isn't the same since then, we feel like its very hard to turn around and do simple things that we used to do easily before that update.
even though its a small change, it's very important for us since we play leagues and we cant perform our best.
for me personally, when i use the extrapolation command the movement feels good but its annoying cause the screen lags alot.  
i hope it's not only in my head ^_^, I wouldn't bother u if it was only me, but since i heard other ppl complaining about that I've decided to post here.
thank you for your time, hope you know what im talking about. xD

**Comment by Leo-MapCreator** [comment]
Does it feels laggy without extrapolation?
How much extrapolation do you use?

**Comment by penetrated** [comment]
I'm also experiencing this too (Windows 10, 64Bit, Build 17692.) Extrapolation doesn't help at all for me.

Gameplay is very smooth with no delays on Linux (Ubuntu) when I play on my Linux machine.

**Comment by basro** [comment]
The resolution/graphic change you mention could be a bugfix I did a bit after the last update. In the past HaxBall ignored your DPI or browser zoom level which cause the canvas resolution to be wrong if DPI was 1 or zoom was not 100%.

This should not affect input lag though, so it is likely that you just noticed input delay now despite it always being there.

**Comment by iscoman** [comment]
leo - 
it doesnt feel laggy without extrapolation, but as basro said its probably a delay that i didnt notice before the bugfix, so i must use extrapolation to be able to turnaround without being a truck ^^
and im using 25 extrapolation, tried everything already, changed so many browsers and numbers, thats the only way i can play (but ofc there are screen laggs cause of extrapolation).

penetrated - i know how u feel man, unfortunately, win 10 isn't good for haxball.

basro thanks for answering, i wanted to ask one more thing : does the quality of ur monitor change anything of haxball gameplay? i mean, i know some ppl that plays with 144 fps, it means that they won't notice the delay same as i notice it?

**Comment by Leo-MapCreator** [comment]
I also use extrapolation do anulate a lil bit of input delay i have, but i only use 15, i think higher values tend to ''lag'', maybe its that
How many Hz is your monitor? 30?

**Comment by iscoman** [comment]
i know that, but i still feel like a truck when i play with 15 :(
my monitor is 60 hz

**Comment by Leo-MapCreator** [comment]
60 Hz shouldnt interfere in anything

**Comment by penetrated** [comment]
@iscoman This might be placebo but have you tried using Waterfox browser? (Not Firefox but really similiar) I don't notice any delay on it.

**Comment by Leo-MapCreator** [comment]
Maybe internet connection that is slow?

**Comment by basro** [comment]
@iscoman, yes higher framerate monitor like 144hz could possibly reduce the windows 10 delay if it is a fixed number of frames.
