### ISSUE TITLE
Default maps as .hbs

### ISSUE THREAD

**Issue by tohey** [haxball/haxball-issues#417]
Hello,
Can you please provide the default maps in .hbs format?
Links [here](http://blog.haxball.com/post/13925587901/default-stadiums-in-hbs-format) don't work anymore.
Thanks

**Comment by Leo-MapCreator** [comment]
[haxball_default_stadiums.zip](https://github.com/haxball/haxball-issues/files/2130333/haxball_default_stadiums.zip)

**Comment by tohey** [comment]
Thank you very much!

**Comment by basro** [comment]
I've now added them here as well:
https://github.com/haxball/haxball-issues/tree/master/stadiums
