### ISSUE TITLE
"Blue" team font is not blue

### ISSUE THREAD

**Issue by butt-farmer** [haxball/haxball-issues#42]
Another low priority but the OCD will kill me. hex #b7b7ff is not a good representation of blue.

**Comment by barnaba** [comment]
burso pls fix literally unplayable
+1

**Comment by s-m-k** [comment]
#b7b7ff is objectively a shade of blue.

**Comment by basro** [comment]
![light blue](https://user-images.githubusercontent.com/1387293/32051399-cecb98d6-ba2a-11e7-8852-c28c143c47de.png)

Look at the hue bar, dead center in the blue spectrum in my opinion.

**Comment by butt-farmer** [comment]
:(

**Comment by Leo-MapCreator** [comment]
:(
Could be a little bit darker
OCD is real
