### ISSUE TITLE
Begginer Problem

### ISSUE THREAD

**Issue by MBR17** [haxball/haxball-issues#420]
My room doesn't show to other players, what should I do?

public : true
var room = HBInit({ roomName: "Anythingl", playerName: "BotMBR", maxPlayers: 16 });
room.setDefaultStadium("Big");
room.setScoreLimit(5);
room.setTimeLimit(0);

// If there are no admins left in the room give admin to one of the remaining players.
function updateAdmins() { 
  // Get all players except the host (id = 0 is always the host)
  var players = room.getPlayerList().filter((player) => player.id != 0 );
  if ( players.length == 0 ) return; // No players left, do nothing.
  if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
  room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
}

room.onPlayerJoin = function(player) {
  updateAdmins();
}

room.onPlayerLeave = function(player) {
  updateAdmins();
}

**Comment by Leo-MapCreator** [comment]
var room = HBInit({ roomName: "Anythingl", playerName: "BotMBR", maxPlayers: 16, public: true });

**Comment by MBR17** [comment]
Thanks
