### ISSUE TITLE
API Host commands

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#421]
Is it possible to make haxball recognize commands from the API Host?
For example: /handicap, /avatar, /set_password, and so on..

**Comment by basro** [comment]
I don't understand what you are asking.

**Comment by Leo-MapCreator** [comment]
room.sendChat('/avatar') to be recognized

**Comment by basro** [comment]
No, that wont happen.

**Comment by Leo-MapCreator** [comment]
Why not?

**Comment by basro** [comment]
Because it makes no sense.

**Comment by Leo-MapCreator** [comment]
Why not, i prefer to clear red/blue uniform using this than that complicated function
