### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#424]
Sorry! Your browser doesn't yet implement some features which are required for HaxBall to work.

The missing features are: datachannel, peerconnection
Recommended browsers:
Firefox
Chrome
Opera

How do i work around this?

**Comment by olegmisar** [comment]
Download Chrome, Firefox or Opera

**Comment by Leo-MapCreator** [comment]
WOW, OMG, I DIDNT THINK ABOUT THAT, YOU ARE VERY VERY SMART

**Comment by olegmisar** [comment]
If you don't want to download one of this browsers and want to solve problem than provide more details about problem(ur browser, version, where do u run browser, which OS etc)

**Comment by basro** [comment]
The message means required webrtc features were detected as missing. What browser are you using?

**Comment by Leo-MapCreator** [comment]
Tor

**Comment by basro** [comment]
It doesn't have support for webrtc, so it wont work.

**Comment by Leo-MapCreator** [comment]
:(

**Comment by Leo-MapCreator** [comment]
Do you any browser that has this support and works like Tor (proxy easy to change)?
