### ISSUE TITLE
win streak

### ISSUE THREAD

**Issue by ekmekyiyen** [haxball/haxball-issues#427]
exp: blue team wins x times in a row.

i tried some bad codes and not work :( How can i do it?

**Comment by Leo-MapCreator** [comment]
onTeamVictory {
if(winnerteam == 'team.id') {
wins = wins +1
}else{
wins = 1
}
winnerteam = 'team.id'
}

**Comment by basro** [comment]
@Leo-MapCreator that is not even valid javascript...

Regardless, this is not the place to make this kind of questions so I'm closing this.

**Comment by Leo-MapCreator** [comment]
I forgot to say that this was just the idea, that he had to code correctly
