### ISSUE TITLE
Change two players from lost team

### ISSUE THREAD

**Issue by MBR17** [haxball/haxball-issues#428]
What should I add, if I want give two players for lost team to spec?

`function banTeam(teamID)
{
  var team = room.getPlayerList().filter((player) => player.team == teamID);
  for(var i = 0; i < team.length; i++){
    room.setPlayerTeam(team[i].id, 0);
    room.kickPlayer(team[i].id, "test", true);
  }
}

room.onTeamVictory = function(score)
{
  var nextPlayer = room.getPlayerList().filter((p) => p.team == 0)[1];

  if(nextPlayer == null){
    room.stopGame();

    setTimeout(function(){
      room.startGame();
    }, 300);
    return;
  }

  if(score.red > score.blue)
  {
    var deadPlayer = room.getPlayerList().filter((p) => p.team == 2)[0];
    if(deadPlayer != null)
    {
      room.setPlayerTeam(deadPlayer.id, 0);
    }
    room.setPlayerTeam(nextPlayer.id, 2);
  }

  if(score.blue > score.red)
  {
    var deadPlayer = room.getPlayerList().filter((p) => p.team == 1)[0];
    var winPlayer = room.getPlayerList().filter((p) => p.team == 2)[0];
    if(deadPlayer != null)
    {
      room.setPlayerTeam(deadPlayer.id, 0);
    }
    room.setPlayerTeam(nextPlayer.id, 2);

    if(winPlayer != null)
    {
      room.setPlayerTeam(winPlayer.id, 1);
    }
  }

  room.stopGame();

  setTimeout(function(){
    room.startGame();
  }, 300);
}

function vacancy()
{
  if(room.getPlayerList().filter((p) => p.team == 1).length == 0){
    return 1;
  }
  else return 2;
}`

**Comment by Leo-MapCreator** [comment]
I didnt read what you wrote, just do this:

**room.onTeamVictory = function(score) {**
var losers = room.getPlayerList().filter((player) => player.team = _**'loserteamID'**_);
for(var i = 0; i < losers.length; i++) {
 _room.setPlayerTeam(losers[i].id, 0);_
 }
**}**
