### ISSUE TITLE
kick option

### ISSUE THREAD

**Issue by MBR17** [haxball/haxball-issues#429]
How can I give 
commands on my ingame server?
Iike: 
!kick (nickname)

**Comment by dixtel** [comment]
`room.onPlayerChat(player, message) {
	
	var splited = message.split();

	if (splited.length > 1) {

		if (splited[0] == "!kick") {

			message = message.replace("!kick ");

			var player_id = player_manager.SerachPlayerIdByName(message);

			if (player_id == null)
				return false;

			room.kickPlayer(player_id, "", false);

			return false;
		}
	}
}`

**Comment by MBR17** [comment]
Doesn't work

**Comment by dixtel** [comment]
Because you must thinking

```
function SerachPlayerIdByName(name) {

	var players = room.getPlayerList();

	for (var i = 0; i < players.length; i++) {
		
		if(players[i].name == name)
			return players[i].id;
	}

	return null;
}

room.onPlayerChat(player, message) {
	
	var splited = message.split();

	if (splited.length > 1) {

		if (splited[0] == "!kick") {

			message = message.replace("!kick ");

			var player_id = SerachPlayerIdByName(message);

			if (player_id == null)
				return false;

			room.kickPlayer(player_id, "", false);

			return false;
		}
	}
}
```
