### ISSUE TITLE
Gamepad cruciform directional input is detected as 4 kick buttons

### ISSUE THREAD

**Issue by tito76webs** [haxball/haxball-issues#43]
Gamepad cruciform directional input is detected as 4 kick buttons.

Hey, what about to make a real analog movement for he left stick?

**Comment by saviola777** [comment]
Related to #11.

**Comment by helppe** [comment]
analog movement is not possible since with keyboard you cant do it.

**Comment by basro** [comment]
I've disabled gamepad support for now. Might be enabled in the future if I implement key mappings as a setting.

Real analog movment is not impossible. I might implement it someday.
