### ISSUE TITLE
onTeamScore

### ISSUE THREAD

**Issue by coadra** [haxball/haxball-issues#431]
please, i need help!
     i want the server automatically send message like 
          room.sendChat (player_id + "Just scored a goal!")
    but idk how to implement onTeamScore command 
anyone can give me an example?

my english is bad iknow

**Comment by Raamyy** [comment]
U need to track the last player who touched/kicked the ball, so when the goal is scored you can see who was the last player who touched/kicked it. And this player will be the Goal scorer.

**Comment by coadra** [comment]
@Raamyy Yes! i know that, i Just want to know how to use this roomObject:"onTeamScore" and i cant find any example :(

**Comment by AnddyAnddy** [comment]
Trivial example of using this event: 

`room.onTeamGoal = function(team){
room.sendChat("A goal has been taken by " + team ) 
}

`
