### ISSUE TITLE
Remove captcha. I can't solve it.

### ISSUE THREAD

**Issue by olegmisar** [haxball/haxball-issues#432]
I am solving google's recaptcha 2 days. 2 DAYS! I can't start my room. Basro, please, do something with it. 

UPD: I am talking about headless host.
UPD2: After some more tries i got this message: <https://prnt.sc/jzumn0>

**Comment by basro** [comment]
The captcha will not be removed but as I said before I'll implement a way to solve the captcha on a different computer than the headless host.

I'm sorry that this is happening to you, please have patience until that feature is implemented.

**Comment by olegmisar** [comment]
@basro i have 2 rooms where 100-200 players play everyday. I don't want to stop providing players with good rooms. I invested a lot of time in my bot and it's sad to stop it. Hopping for faster token implementation.

**Comment by evi1a** [comment]
I got to agree with olegmisar. I can tell through my experience that reCaptcha is nothing for a headless host.

I like the fact that you are trying to improve things for us, but I would prefer if we could communicate a bit more with you and share thoughts so you don't waste your time doing things people aren't going to need.

I really value your work and everything, but I got to admit even if it would soon be possible to solve a reCaptcha from another computer without using some remote tool, it still wouldn't really solve the problem. For the headless api there should be a better option than only reCaptcha.

Issuing tokens could be one option, like olegmisar already mentioned. It's a one time confirmation process, and when you see the token gets abused, you can just revoke it. And if people using that token want to host more rooms for example, they maybe can extend their token if their behavior was normal for enough time. Like this I could restart my room without any obstacles and fully headless.

This is only a suggestion, and you decide what you are going to implement. But I would really appreciate it if we could find some solution together.

**Comment by zikolo** [comment]
I'm facing issue to resolve recaptcha on headless chromium. Every time the captcha is solved, the link to the room doesn't come up. Instead, recaptcha button is rendered again.

**Comment by olegmisar** [comment]
I had the same problem.

Why your can't solve captcha? It's because browser doesn't really see how you move mouse, browser registers only mouse clicks. And it looks like your mouse pointer teleports. Google (recaptcha inventor) thinks that mouse teleporting is strange and doesn't believe that you are human.

Solution: install GUI to allow browser register `mousemove` event and all will work great.

**Comment by basro** [comment]
Last update included headless token, which solves this issue. [Docs here.](https://github.com/haxball/haxball-issues/wiki/Headless-Host#token--string)
