### ISSUE TITLE
Newbie Problem with Team Swap

### ISSUE THREAD

**Issue by Marcin000** [haxball/haxball-issues#434]
Hi, I wanted to make the team that loses to spectators and make the person that will choose. Can you help me?
That's my code:
`//Moving loser team to specs and top spec to loser
function updateTeams(winner){
	if (winner == "red") {
		var blues = getBlueTeam();
		blues.reverse(); //reverse order of putting 
		for (let i = 0; i < blues.length; i++) //loop on blue team and spec them
		{
			room.setPlayerTeam(blues[i].id, 0);
		}
		var specs = getSpectators();
		if (specs.length != 0)
			room.setPlayerTeam(specs[0].id, 2); //moving top spec to blue team
	} 
     else if (winner == "blue") {
		var reds = getRedTeam();
		reds.reverse(); //reverse order of putting specs
		for (let i = 0; i < reds.length; i++) //loop on red team and spec them
		{
			room.setPlayerTeam(reds[i].id, 0);
		}
		var specs = getSpectators();
		if (specs.length != 0)
			room.setPlayerTeam(specs[0].id, 1); //moving top spec to red team
	}
}

function updateAdmins() { 
  // Get all players except the host (id = 0 is always the host)
  var players = room.getPlayerList().filter((player) => player.id != 0 );
  if ( players.length == 0 ) return; // No players left, do nothing.
  if ( players.find((player) => player.admin) != null ) return; // There's an admin left so do nothing.
  room.setPlayerAdmin(players[0].id, true); // Give admin to the first non admin player in the list
}

room.onPlayerJoin = function(player) {
  room.sendChat( "Welcome"+player.name+" on our room!");
  updateAdmins();
}

room.onPlayerLeave = function(player) {
  room.sendChat ( "Player "+player.name+" left us!");
  updateAdmins();
}

room.onTeamVictory = function(scores) {
  updateTeams(winner);
  }`
This code was made by Raamyy.
When I start it I am receiving this:
Uncaught ReferenceError: winner is not defined

Please help me

**Comment by olegmisar** [comment]
```js
room.onTeamVictory = function (scores) {
  var teamName = scores.red > scores.blue ? 'red' : 'blue'
  updateTeams(team name)
}
```

**Comment by Marcin000** [comment]
I still have problems. Now console says
`Uncaught ReferenceError: getBlueTeam is not defined`

**Comment by olegmisar** [comment]
Do you know how to write code? Do you know JavaScript? If not, you have no need to make headless host. First learn basics of JavaScript and then try to write something.
