### ISSUE TITLE
Map Limits

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#435]
Is there limits for map parametrs/size? e.g vertexes limit or segements?
I see that vertexes cannot be bigger than 255. Can you increase this limit? Maybe to 400? I want to draw text on map that why i need more vertexes.

**Comment by Leo-MapCreator** [comment]
well, if you used haxpuck you can put big distances or it will not display the map anymore, it will be a black screen, but they work in haxball, you just can't see the map in haxpuck

**Comment by basro** [comment]
Yes, there's a limit of 255 to every one of the lists (vertexes, segments, planes and discs).
For now this limit will not be increased.

**Comment by Leo-MapCreator** [comment]
Funny that it has 256 limit for vertexes and 256 for segments, but usually a segment uses 2 vertexes

**Comment by basro** [comment]
Segments can share vertexes, if you make a chain you can end up with 255 vertexes and 254 segments.

**Comment by olegmisar** [comment]
255 vertexes and 255 segments are also possible

**Comment by Leo-MapCreator** [comment]
Yeah of course, but that's not what usually happens, you dont make a 'closed' line with that many segments

**Comment by Leo-MapCreator** [comment]
Isnt it 256 rather than 255? It starts at 0

**Comment by bugramurat** [comment]
I need more discs than 255, please can someone help me?
