### ISSUE TITLE
minViewWidth

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#436]
Create this please, some maps like hide and seek get destroyed because of the zoom, when i seek i just need to put my zoom on max and it will give away peoples position because the arrow points towards the hiders
With 1.25x zoom: https://gyazo.com/9dadf5b7d1e7fe38c2fa8023723d24c5
With 2.5x zoom: https://gyazo.com/c3541eea5aa59da9e00add8e14fe47b6

**Comment by haxplayer** [comment]
You know they can do that even at 1x zoom by resizing their window really small.

**Comment by Leo-MapCreator** [comment]
But that prevents people that doesnt know that

**Comment by basro** [comment]
#618 is a better way to solve this. I'm closing this one.

**Comment by Leo-MapCreator** [comment]
About this one, it is still useful in other situations, when a map is big and you want the players to have a low zoom, but whatever, not a necessity
