### ISSUE TITLE
No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#437]
This error is showed more and more frequently on my rooms 
`Failed to load https://www.haxball.com/rs/api/host: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://html5.haxball.com' is therefore not allowed access. The response had HTTP status code 522.
2www.haxball.com/rs/api/host:1 Failed to load resource: the server responded with a status of 522 ()`

**Comment by basro** [comment]
There was a network issue today that caused the server to go down multiple times, these errors were probably caused by it.

The issues have been resolved so it should work fine now.
