### ISSUE TITLE
onOvertime() feature

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#441]
Hey, i'm making a cleensheet handler and i'd like to not charge the onGameTick, my problem appears in only one case:
The game reached it's limit but it's a 0-0, so both gk gets a cleensheet, so the game will stop and the gk won't get their stats.
So i'd like you to add a room.onOvertime() to avoid to do something like:
room.onGameTick(){
if (room.getScores().time > timeLimit) players.cleensheet += 1;
}

I don't want to have bad conscience with 60*timeLimit operations :p

**Comment by pilaf** [comment]
Your machine can likely perform millions of operations within a second (even with JS), it will barely feel those 60 operations/second you're afraid of.

And if you're still uneasy you could use `setInterval(fn, 1000)` (1 second interval checks) instead of `room.onGameTick()`.

**Comment by olegmisar** [comment]
You can also use this:
```js
if (room.getScores().time > timeLimit)
  players.cleensheet += 1 / 60
}
```

**Comment by Prozac77** [comment]
hey andy. u scprit good but room.onTeamGoal usually wrong. especially og goal

this room.onTeamGoal perfect. pls use this room.onTeamGoal

https://hastebin.com/avekisifuw.php

**Comment by Prozac77** [comment]
andy pls change. usually gk players ''og'' goal. this is wrong.

**Comment by Prozac77** [comment]
@AnddyAnddy andy pls change. usually gk players ''og'' goal. this is wrong.

**Comment by AnddyAnddy** [comment]
Hey, could you explain what you mean ? be more precise maybe ? i don't have any problem with owngoal with my script but maybe you figured out a bug! Give me a rec if it's the case and come to the feed me teamspeak, i'll be here.

**Comment by Prozac77** [comment]
@AnddyAnddy 

U script room;

http://thehax.pl/forum/powtorki.php?nagranie=0560de92984a42909b6d7dc3bd5d1db1
this goal og.  this not true. should be Aaaaaaa goal.

other script room;

http://thehax.pl/forum/powtorki.php?nagranie=ab5a9f45bf9eca83b7dd2dbcbd6e969b
this is true.  goal : Aaaaaaa

**Comment by AnddyAnddy** [comment]
Hey, i'm sorry to tell you that you script doesnt work good too
http://thehax.pl/forum/powtorki.php?nagranie=727a26c310109eb366614b34d9453bcb

this should be an own goal since the shot was not on target. Therefore we have 2 differents vision, both are wrong: You're allowing goals when it's an own goal and i'm putting owngoal when it's a goal.

The good idea would be to check on each tick the direction the ball is taking, since in haxball the ball only goes straight, it wouldn't be hard to see if the shot is on target. 
But i'll stop with my script soon, just waiting for basro to add pm and i'll be done with this

**Comment by Prozac77** [comment]
@AnddyAnddy

u script disadvantage for goalkeeper. Frequently GK is own goal. this not good.

Therefore we have 2 differents vision, both are wrong. yes but u script frequently own goal  this not good. but other scrip normal scores. this better.

I think you should change.

thx for answer

**Comment by AnddyAnddy** [comment]
Your script gives an advantage for the scorer, i won't change my wrong script for another wrong script. I don't fix a bug with another known bug. If you don't like it, don't use it, but i keep telling you our 2 scripts are wrong on this point, neither of both are better than the other one.
The only argument if you want that I change my script is to give me the algorithm of the true version, not another bugged one, sorry.

**Comment by Prozac77** [comment]
i use your script for 3 hours. Frequently GK is own goal. therefore i want change :D
you can try to open a poll about it.

if you do not want to change. it will be unusable. :(



even so thanks for working

**Comment by Prozac77** [comment]
@AnddyAnddy 
i use your script for 3 hours. Frequently GK is own goal. therefore i want change :D
you can try to open a poll about it.

if you do not want to change. it will be unusable. :(

even so thanks for working

**Comment by AnddyAnddy** [comment]
http://thehax.pl/forum/powtorki.php?nagranie=5cae0a5ed4ba013e6bf1abc0a6b699f1

I guess this is worse than own goals, the assist in this case should not be given, sorry but i will definitely not change my script to yours since none is better than the other.

**Comment by Prozac77** [comment]
@AnddyAnddy 

I do not agree.

my criterion;  which fault becomes more frequent ?

i use other script for 4-5 day. this asist fault is rare in 4vs4 match. also ''assist'' positive stats. y ?

but ''og goal'' negative stats and that fault it will be more frequent.

for this reason rare '' asist fault '' ignore. i thing.

don't you agree with that ?

**Comment by AnddyAnddy** [comment]
Maybe you should read rules of all communities.

**Comment by Prozac77** [comment]
if it is not difficult to change

can you do it for me and my communities. ?

i would be grateful to you

**Comment by Prozac77** [comment]
@AnddyAnddy 

if it is not difficult to change

can you do it for me and my communities. ?

i would be grateful to you

**Comment by Prozac77** [comment]
@AnddyAnddy 

We're just talking. talk=cry for you ?

I will not write to you if i have coding ability

Can you change it for me and my communities.?

I would be grateful to you

**Comment by cr0ndor** [comment]
I really dislike the idea of OG's in general for stat keeping with regards to haxball. Anecdotally, a good 90% of the "own goals" that occur in games (even when the player must x the ball into their own goal for it to count) are simply the last player back who is trying to make a desperate save at an obvious goal. 

Not only does it take away the goal from the attacker, but it credits an OG to the defender, which is a stat that really has no interpretation. I've never based a player on their OG's, and I've never felt a player was undeserved of a goal that they didn't directly score, but caromed off a defender.

**Comment by AnddyAnddy** [comment]
I can't disagree with that but it is simply haxball, football or even handball convention, in order to track informations as much as possible, we need to know it.
