### ISSUE TITLE
[new feature] enter a room as spectator only

### ISSUE THREAD

**Issue by helppe** [haxball/haxball-issues#45]
what about the possibility to enter a room to only watchthe matches (no speaking possibilities) without using a slot of the room.

**example**: a room is created for 4 people.
so 4 people can enter to talk and play, and other people that find the room full can enter as "spectator" mode to only watch the matches without talking or playing.

**Comment by helppe** [comment]
nope, you don't read my topic carefully.
i don't talk about mute or annoying people...

i talk about someone who want/choose to enter a room without taking any slot of the room... so he is invisible for other players and he can't react with them.

**Comment by basro** [comment]
The player limit is there because the host has limited resources/bandwidth. The spectator only mode which you suggest would use just as much bandwidth as a player who is in the game.

I wont be implementing this.
