### ISSUE TITLE
Flag Problem

### ISSUE THREAD

**Issue by TheTurkishHaxballer** [haxball/haxball-issues#451]
You can change the flag in game. But it does not work in headless. For example I live in the Netherlands. but I want host game for Turkish players and next to the turkish rooms on the rooms list.

. Is this possible?

**Comment by olegmisar** [comment]
Yes, it is possible. But read [documentation](https://github.com/haxball/haxball-issues/wiki/Headless-Host) before asking something here.
```js
const room = HBInit({
  code: 'tr',
  lon: turkLongtitude,
  lat: turkLatitude
})
```
[All country codes](https://www.worldatlas.com/aatlas/ctycodes.htm). Look for Turkey longtitude and latitude in Google.

**Comment by tohey** [comment]
Do this:

```
var room = HBInit({ roomName: "room name", playerName: "bot name", public:true, maxPlayers: 20, geo : {
code: 'af',
lon: 69.160652,
lat: 34.543896
} });
```
