### ISSUE TITLE
onPositionsReset

### ISSUE THREAD

**Issue by subxqns** [haxball/haxball-issues#456]
How can I use onPositionsReset? And can I use it to change a team's color in that event? I've managed to change a team's color when they score using onTeamGoal, but I want to get back to the initial colors once the "goal celebration" has finished, thx

Also, how do I make the game stop at the time limit even when it's a draw using ~a timer~ the scores time?

**Comment by coadra** [comment]
room.onPositionsReset = function(){

room.setTeamColors(1, 60, 0xFFFFFF, [0xE56E56, 0xE56E56]);

room.setTeamColors(2, 60, 0xFFFFFF, [0x5689E5, 0x5689E5]);

}

**Comment by Leo-MapCreator** [comment]
onGameTick{
getScores()
if(time > time.limit){ stopGame()
}
}

This is just the idea, do the right coding

**Comment by subxqns** [comment]
Thx
