### ISSUE TITLE
VPS server terminal

### ISSUE THREAD

**Issue by meisterrr** [haxball/haxball-issues#463]
How to host room on vps with terminal only? Is That posibble?

**Comment by olegmisar** [comment]
Detail explanation how to connect to VPS using terminal and chrome browser: #340

**Comment by meisterrr** [comment]
help please

**Comment by olegmisar** [comment]
Look for videos on YouTube how to install GUI on vps(Amazon web services, Google cloud platform etc).

**Comment by meisterrr** [comment]
I know how but when i installed GUI in my ubuntu and connecterd to remote desktop its laggy, and my room laggy also :/ That's why i'm asking how to do it through terminal.

**Comment by olegmisar** [comment]
Use screen lower resolution, use the simplest GUI available for ur OS. And to run GUI on machine you need at least 2 GB of RAM. 1 GB isn't enough to host even 1 room.

**Comment by meisterrr** [comment]
I got on my vps 
CPU: 4x2.4 GHz
RAM: 8 GB
SSD: 160 GB
and my room really laggy, speed test is very good, max ping sometimes is 1500/2000 so i dont know what im doing wrong

**Comment by meisterrr** [comment]
help please

**Comment by olegmisar** [comment]
https://youtu.be/9BAoJ7JZHr0

**Comment by meisterrr** [comment]
my vps isn't on aws

**Comment by olegmisar** [comment]
No matter, if u just use Ubuntu(Ubuntu-like) OS this should work
