### ISSUE TITLE
Bad actor issue

### ISSUE THREAD

**Issue by bratzdenko** [haxball/haxball-issues#465]
Hello, upon trying to use admin commands in my room I get kicked out by a bot, with a message saying "Bad actor". I've seen this bug several times, and only way I was able to solve it is by completely changing part of the code which was triggering that event.
Here is the code:
```
// Big stadium command
    if (player.admin == true && message == "!big") {
        room.setCustomStadium(big);
        big = true;
    }
```
```
// Small stadium command
    if (player.admin == true && message == "!small") {
        room.setCustomStadium(small);
        big = false;
}
```
It works with "!small" command, but not with "!big".
I believe the "Bad actor" thing is for Dos attack prevention, but this is piece of code is far from that.
Please fix it.

**Comment by basro** [comment]
If your code throws an exception it will also cause a bad actor kick of the player, make sure that no exceptions are being thrown.

**Comment by zikolo** [comment]
It is because you are trying to use variable names instead of string values for a stadium name. You may want to change it to something like this: `room.setCustomStadium("Big")` or `room.setCustomStadium("Small")`.

**Comment by bratzdenko** [comment]
I've found what was causing the issue, it was just a spelling mistake. @zikolo I am using custom stadiums, big and small are just my variable names, but thanks for comment.
