### ISSUE TITLE
maps with "damping" parameter are obsolete (don't load)

### ISSUE THREAD

**Issue by helppe** [haxball/haxball-issues#47]
i noticed that some maps don't load.
i checked the code and found that maps using the "damping" parameter (for discs properties) are not loadable.
in the the code we use to write: **"damping":"1.2"** for example
in html5 version this is not valid and map doesn't load
but if i replace with: **"damping":1.2** (so without the " around the number) it works and the map loads.

many maps use this parameter so maybe something has to be done?

**Comment by basro** [comment]
Damping should be a number, not a string. The flash version converts the strings to floats, but that was in fact a bug.

It is the maps that need to be fixed. I also I need to implement better stadium load error reporting so that users know why their maps aren't loading.
