### ISSUE TITLE
Question about getPlayerList(); function

### ISSUE THREAD

**Issue by bratzdenko** [haxball/haxball-issues#471]
I wanted to make a code that sets bot position to 0 in spectators if he is changed by admin, but I can't get to work it because from what I see, getPlayerList(); doesn't return the list in a pattern. Does player's position in getPlayerList(); array depends on anything?

**Comment by Raamyy** [comment]
you can use on player position change function, if the changed player id was 0 then it is the bot .. so get it back to the spectators.

**Comment by zikolo** [comment]
There is a workaround for it
```javascript
function setPlayerOnTop(playerID) {
	let players = room.getPlayerList();
	
	for (let p of players) {
		if (p.id == playerID || p.team !=0) continue;
		room.setPlayerTeam(p.id, 1);
		room.setPlayerTeam(p.id, 0);
	}
}
```
But i'm not 100% sure if this works as expected, because all these API operations are executed asynchronously and your chat will be spammed with notifications.

**Comment by Leo-MapCreator** [comment]
Yes there is a pattern on player id, and the bot id is always 0

**Comment by bratzdenko** [comment]
@zikolo I've tried something similiar to that, but I want to keep players position the same as it was before the admin was change. Than there will be no misunderstandings about who plays next.

**Comment by olegmisar** [comment]
> because from what I see, `getPlayerList()` doesn't return the list in a pattern.
That's not true. Check out this code:
```js
const players = room.getPlayerList()
const spects = players.filter(p => p.team === 0)
const red = players.filter(p => p.team === 1)
const blue = players.filter(p => p.team === 2)
```
This code will always return properly sorted player lists. 0 index = highest position in team.
You can wrap that code in function:
```js
function getPlayerListByTeam() {
  const players = room.getPlayerList()
  const spects = players.filter(p => p.team === 0)
  const red = players.filter(p => p.team === 1)
  const blue = players.filter(p => p.team === 2)
  return [spects, red, blue]
```
Usage:
```js
const [specs, red, blue] = getPlayerListByTeam()
```
Notice, that above snippet is a compact way of this:
```js
const teams = getPlayerListByTeam()
const spects = teams[0]
const red = teams[1]
const blue = teams[2]
```

**Comment by Leo-MapCreator** [comment]
@bratzdenko The thing is, if the bot is at the last position then nothing will change, everyone will maintain the same position at the queue

**Comment by Wazarr94** [comment]
Thanks to olegmisar, I understand getPlayerList() works.
On every player movement, the player gets pushed to the end of the list. That's it.
For instance, imagine BOT, a, b, c, 4 players who come in this order. The players list would be [BOT, a, b, c]. If a goes to the red/blue team, the new list would be [BOT, b, c, a]. Then BOT to red/blue team : [b, c, a, BOT] and so on.
You can check by yourself on a headless host. It's the reason why the function olegmisar posted work.

What you're asking is manipulating players' position so the bot stays top of the spec list ? If so, basro said he was working on it for a future update. The only way to make it work now is something like what zikolo posted, but the notifications coming from this maneuver would be too annoying.

**Comment by bratzdenko** [comment]
Thanks for the help guys I understand now. Algorithm works because each player is moved and taken back per iteration. My function was moving all players to team id 1 and then to spectators.

**Comment by bratzdenko** [comment]
Thanks for the help guys I understand now. Algorithm works because each player is moved and taken back per iteration. My function was moving all players to team id 1 and then to spectators.
