### ISSUE TITLE
[new feature] default zoom level for maps creators

### ISSUE THREAD

**Issue by helppe** [haxball/haxball-issues#48]
what about a "default zoom level" to set in the code of the maps?

people can anyway change by pressing 1, 2 or 3 but if the autor of a map could choose by default a "correct" zoom level and when the map is loaded it is loaded with the zoom chosen by the autor.

**Comment by basro** [comment]
I'll be doing something similar to this, I explained it here: https://github.com/haxball/haxball-issues/issues/51#issuecomment-340081003

**Comment by basro** [comment]
The maxViewWidth feature is now implemented.
