### ISSUE TITLE
Default physics

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#480]
Hi, 
I've been looking for the default settings for the players and the ball, but I didn't find anything online.
I tried calculating them by hand, but it's not very precise :  for instance, for the ball damping, from what basro said in a previous issue (newSpeed = damping * oldSpeed each frame), I find around 0.99933, but I'd like to know what's the real ball damping is
For player, I'm looking for bounce, mass, acceleration, damping, kicking attributes and for ball : radius, bounce, damping, mass, collision mask and collision group.
Thanks. 

Extra question : are angles kept when the ball bounce of a wall/post ? It seems like it is, but I could be wrong.

**Comment by Leo-MapCreator** [comment]
"playerPhysics" : {
		"bCoef" : 0.5,
		"invMass" : 0.5,
		"damping" : 0.96,
		"acceleration" : 0.1,
		"kickingAcceleration" : 0.07,
		"kickingDamping" : 0.96,
		"kickStrength" : 5

	},

	"ballPhysics" : {
		"radius" : 10,
		"bCoef" : 0.5,
		"invMass" : 1,
		"damping" : 0.99,
		"color" : "FFFFFF",
		"cMask" : [ "all"
		],
		"cGroup" : [ "ball"
		]

	}

**Comment by Leo-MapCreator** [comment]
Angles are kept if the bCoef of the wall is 1

**Comment by Wazarr94** [comment]
Thank you very much
