### ISSUE TITLE
Spam Attackers

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#485]
How protect room when attackers spam? Ban dosent work. Its enoying when all day attacker join to my room and spam every 10 seconds...

**Comment by Leo-MapCreator** [comment]
You can do a spam detector with ban

**Comment by dixtel** [comment]
@Leo-MapCreator Yes.. I have this but ban dosent work. Attacker every join  have different ip or something else that he can join all time

**Comment by Leo-MapCreator** [comment]
The only one that can help you is basro

**Comment by r00t-ux** [comment]
Can you add me? r00tux#2260 @Leo-MapCreator

**Comment by thenorthstar** [comment]
> @Leo-MapCreator Yes.. I have this but ban dosent work. Attacker every join have different ip or something else that he can join all time

@dixtel So, did you try to ban him through **auth** then? Because most probably he doesn't change his auth if back to the room very fast. (Or maybe he can try this on multiple tabs with different auths.)

**Comment by dixtel** [comment]
@thenorthstar its old topic and I not have room anymore but i can answer. The auth property can be easily change (remove cookie) and this change nothing. For the future readers i can say that the best option is to make own backend for authentication user and not allow to chat, play or be admin without being authenticate. Or wait for to general registration system in haxball (hehe ;) )
