### ISSUE TITLE
I can't join on a HTML5 room

### ISSUE THREAD

**Issue by xRobert07** [haxball/haxball-issues#49]
Please solve !

**Comment by Kubsulec** [comment]
Yea, some of my friends can't join any room too. It's still a big problem, unfortunately.

**Comment by helppe** [comment]
you should try with firefox

**Comment by Kubsulec** [comment]
No, you shouldn't. No difference at all.

**Comment by helppe** [comment]
> No, you shouldn't. No difference at all.

what's the matter in trying...?
