### ISSUE TITLE
PLEASE ADD REGISTRATION, IDTIOT PLAYERS DESTROY MY ROOM

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#493]
OMG bastro please add registration. My room dies because idiot players have admins and banning every one in room or spammed my room 24/h. PLEASE bastro....

**Comment by Leo-MapCreator** [comment]
@basro

**Comment by coadra** [comment]
If you are talking about your headless room u  shoud add ¨reset bans¨ function, something to dont allow admins to ban or will be banned and a blacklist with nicknames who get banned by headless code to dont allow them to get admin again.
On the other hand, if you are talking about your normal room, u shoud be more careful at the time you are giving admin

**Comment by dixtel** [comment]
@coadra Man, i have all these functions but still banned players can join to my room.

**Comment by zikolo** [comment]
Why don't you just implement registration on your side. That way, you could have way more control over it.

**Comment by tohey** [comment]
I wish GitHub implemented some way to detect that this topic has already been discussed a gazillion times..
