### ISSUE TITLE
Game freezing, but NOT kicking out

### ISSUE THREAD

**Issue by Kubsulec** [haxball/haxball-issues#50]
Hey, I think nobody wrote about that, so I'll be first. Apart from problems with entering a lot of rooms, game freezes on me after a few minutes of playing, IF I get in the room. I haven't got this problem on old Haxball, but I was dealing with different ones many times, so it might be related to my Internet.
Hope it won't be ignored, thanks in advance. New version look fantastic and I can't wait to play it normally.

**Comment by basro** [comment]
I've just released an update that might also have fixed this problem of yours.
Please report if you continue to experience this issue.

**Comment by Kubsulec** [comment]
sorry, forgot to answer. Yes, now game is 100% working for me. Not sure if your update or my changes in router settings fixed it, but effect is great.
