### ISSUE TITLE
Easy to find the host's ip and crush his internet .

### ISSUE THREAD

**Issue by Fuse1** [haxball/haxball-issues#529]
If I open a host anyone can find my IP and crush my internet.
Please fix it.
Thank you.

**Comment by penetrated** [comment]
Can you please provide proof? an example? (with censoring the ips ofc)

**Comment by Fuse1** [comment]
the name of the program is wireshark i'll send u a picture

**Comment by Fuse1** [comment]
![screenshot_1](https://user-images.githubusercontent.com/43438772/45817828-9bf8ab80-bce8-11e8-9020-8bbb6f413a25.png)
