### ISSUE TITLE
Joining rooms on mobile data

### ISSUE THREAD

**Issue by Germaniac** [haxball/haxball-issues#531]
Apparently people can't join rooms using their mobile data. Any fixes?

**Comment by Germaniac** [comment]
What I mean by mobile data is connection like 3G or 4G, here are two other people who can't join any room with their mobile data connection

https://www.reddit.com/r/haxball/comments/8yt48m/unable_to_join_rooms_using_4g/

Please let me know that you're reading this, basro. Cheers.

**Comment by basro** [comment]
There's no fixes for this that I'm aware of, mobile networks often use very restrictive NAT and firewalls that prevent p2p connections like these.

For the record though, I've been able to connect to some rooms using 4G networks in the past, so it's not all networks.
