### ISSUE TITLE
Ball going through walls, but not planes

### ISSUE THREAD

**Issue by teisseire117** [haxball/haxball-issues#534]
walls = segments for me;

Hey,

On this map : http://haxmaps.com/map/2874 ball often goes through the walls near goals. I do not know why. I've tried to put many many walls to avoid it but still goes through.

I found a solution, putting a 'plane' wall. It works fine and the ball doesn't go through anymore. But the problem is that this wall is 'infinite', you cannot set its size, so the ball doesn't go in the goals.
It still counts as a goal tho, but players in my room don't like it, it's not like before. Even tho they're happy the bug is fixed about the ball going through wall, they don't like that the ball can't fully go in the goal.

Is there a way to be able to set a size for this 'plane' wall ? Because it's the only one that fully prevent the ball from going through.

Thank you.

**Comment by basro** [comment]
Planes are infinite, there's no way to limit their size.

There's a trick you can use to reinforce walls by placing more walls with a certain offset, have a look at the example here: https://github.com/haxball/haxball-issues/issues/67
