### ISSUE TITLE
Saved maps with /store in old version

### ISSUE THREAD

**Issue by BrazilHax** [haxball/haxball-issues#54]
Will only the saved maps with the store in Flash Haxball disappear?
Will it have some type compatibility so that we can use the maps that we have saved only with store?

**Comment by basro** [comment]
This is actually fairly hard to do, so probably not. You'll have to get the .hbs files again.

**Comment by basro** [comment]
You can export any maps trapped inside the flash version using this tool: http://html5-local.haxball.com/flash/stadium-exporter.html
