### ISSUE TITLE
Get Player IP, ping etc...

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#540]
`getPlayerIpObject: function(id) {return r.Ab.get(id);},`
Add this after  getPlayerList function inside headless-min.js. (Debug it and save it before calling HBINIT)
it gives object about rtcp connection including IP address, ping and some other info xD

**Comment by teisseire117** [comment]
@Wolf72 Delete it before he sees it and remove it please :(

**Comment by basro** [comment]
This kind of thing will break by itself every time I make any change to the game since anything that is not part of the headless host api is not stable.
