### ISSUE TITLE
Fps limit is a lie.. the options are only 30 fps and v-sync

### ISSUE THREAD

**Issue by MrKarpuz** [haxball/haxball-issues#542]
![1](https://user-images.githubusercontent.com/41875825/46250667-535b9380-c448-11e8-9044-e1b23a22f627.png)
![2](https://user-images.githubusercontent.com/41875825/46250668-548cc080-c448-11e8-91fe-a29f5b7bf5c8.png)

This game has so much potential ! a lot of players are waiting for years for some real updates like standalone client.

I never remember a moment when I play haxball without a problem (in flash and html5 as well)

I dont think Basro plays this game. I just want a smooth gameplay on a 2d browser game, and Im ready to pay a lot of money to see this game is really ok

30 fps is playable, ball control is not that good but ok, but the other option is not unlimited fps. its v-sync. 
Im playing this game for 7 years. I started when I go high school, Im now graduated from university..

Is it too hard Basro ? to make a fair, playable game after these years ?

Do not mention about extrapolation command it works like shit.

**Comment by MrKarpuz** [comment]
amınakoyim millet pubg ye falan sövüyor düzeltin şu oyunu diye, 2d tarayıcı oyunu hala oynanmıyor yıl 2019 olacak bu basro denen adam harbi bilmiyor bu işi ya. olm ben şu oyundan aldıgım keyifi hiçbir oyundan alamıyorum 2d tarayıcı oyunu lan bu yuvarlak adamları yönetiyoruz 5 tane komut var oyunda harbi merak ediyorum çok mu zor oynanabilir seviyeye getirmek...

**Comment by Mirac35** [comment]
Herifle kendi chat kanalında sohbet ederken sordum aynılarını dedi ki oyun öyle bildiğimiz 2d oyunlardan farklı WebSocket vsvs bişeyler söyledi valla konulara uzak olduğum için anlamadım ama özet olarak modifiye edilmesi zormuş, yaklaşık 2.5 senesini almış html5’e port etmesi. Hoş flashte kalsa yine useroptions vs düzenleme yapabiliyorduk 500 fps vs gibi tweakler ama işte html5e geçince flash eskide kaldı neyse ya boşa konuşuyoruz burda…  

Windows 10 için Posta ile gönderildi

Kimden: MrKarpuz
Gönderilme: 6 Ekim 2018 Cumartesi 22:46
Kime: haxball/haxball-issues
Bilgi: Mirac35; Comment
Konu: Re: [haxball/haxball-issues] Fps limit is a lie.. the options areonly 30 fps and v-sync (#542)

amınakoyim millet pubg ye falan sövüyor düzeltin şu oyunu diye, 2d tarayıcı oyunu hala oynanmıyor yıl 2019 olacak bu basro denen adam harbi bilmiyor bu işi ya. olm ben şu oyundan aldıgım keyifi hiçbir oyundan alamıyorum 2d tarayıcı oyunu lan bu yuvarlak adamları yönetiyoruz 5 tane komut var oyunda harbi merak ediyorum çok mu zor oynanabilir seviyeye getirmek...

**Comment by MrKarpuz** [comment]
144hz monitor olunca fps 144'temi kilitleniyor kardeş ? eğer öyleyse saçmalık bu. şu oyunun clientini yapacak adam koyacak steame parası neyse oynayan herkes verir amk. sanki tır dönderiyorum öyle geç algılıyor ki tuşları oyun cidden v-sync yani bu herkes bu koşullarda oynuyor sanıyordum ben ekranı iyi alınca akıcı oluyormu

**Comment by Mirac35** [comment]
Evet kitleniyor. Ayrıca monitörünün kalitesine göre de yenileme sıklığını değiştirebildiğin için (288hz kadar destekliyor benimki) ekranda yırtılma vs meydana gelmiyor. Sanki borderless fullscreen oynarmış gibi de görüntü alıyorsun. Clientinin gelmemesini de buna bağlıyordu basro. 

Windows 10 için Posta ile gönderildi

Kimden: MrKarpuz
Gönderilme: 6 Ekim 2018 Cumartesi 22:59
Kime: haxball/haxball-issues
Bilgi: Mirac35; Comment
Konu: Re: [haxball/haxball-issues] Fps limit is a lie.. the options areonly 30 fps and v-sync (#542)

144hz monitor olunca fps 144'temi kilitleniyor kardeş ? eğer öyleyse saçmalık bu. şu oyunun clientini yapacak adam koyacak steame parası neyse oynayan herkes verir amk. sanki tır dönderiyorum öyle geç algılıyor ki tuşları oyun cidden v-sync yani bu herkes bu koşullarda oynuyor sanıyordum ben ekranı iyi alınca akıcı oluyormu

**Comment by MrKarpuz** [comment]
yav madem oyun 60 üstü fps verebiliyor versin amk en azından şu input lagdan kurtulurum 60hz monitor yetiyor bana zaten laptop kullanıyorum. chrome'da falan ayarı yokmu bunun kandıramıyormuyuz daha üst hz kullandığıma dair. 150 200 fps versin bana ekranım gene 60 göstersin skıntı yok yani benim sorunum şu input lag :( bu kurla şuan ekranı geç oyun bile alamıyorum kendime haxballa daha girmeyecem ozaman tek çözüm bu

**Comment by Mirac35** [comment]
İnput delay sorununu ancak 72hz üzeri monitörlerle %50’ye (belli bi yere kadar) çözebilirsin. Asıl çözüm 144hz monitör almak. Şimdi, 1000 fps alabileceğini varsayalım. 1000 FPS su olsun, monitör de huni. Huni olmazsa su şişeye istediğimiz gibi akıcı bir şekilde dolamaz değil mi ?  Sen monitör ile aslında suyun şişeye dolma kalitesini de geliştirmiş oluyorsun. Çok çektirmişti bana 60fpste oynamak zamanında. 30a alıp yine gecikme yaşamadan oynuyordum. Yine bir neyse ile bitirmek yerine sana bir tavsiye. Mümkünse 144 yenileme sıklığına sahip bir monitör alıp oyuna girdiğinde ayarlardan fpsi 30a çekince (half-cut) oyun sana 72 fpste input delay olmadan 2010 Aralıkta nasıl oynuyorsan öyle bir oyun deneyimi sunuyor. Ha yok monitörler araba parası almam bir oyun için dersen de ekran kartının ayarlarından mevcut laptopunun monitörünün yenileme sıklığını (izin veriyorsa/müsaitse) 72ye scale edip oyun ayarlarından 60 fpsi seçebilirsin. Bu şekilde oyunu tongaya getirerek 50% less input lag ile eski aradığın oyun deneyimine ulaşabilirsin. Eyyorlamam bugadar.
Windows 10 için Posta ile gönderildi

Kimden: MrKarpuz
Gönderilme: 6 Ekim 2018 Cumartesi 23:06
Kime: haxball/haxball-issues
Bilgi: Mirac35; Comment
Konu: Re: [haxball/haxball-issues] Fps limit is a lie.. the options areonly 30 fps and v-sync (#542)

yav madem oyun 60 üstü fps verebiliyor versin amk en azından şu input lagdan kurtulurum 60hz monitor yetiyor bana zaten laptop kullanıyorum. chrome'da falan ayarı yokmu bunun kandıramıyormuyuz daha üst hz kullandığıma dair. 150 200 fps versin bana ekranım gene 60 göstersin skıntı yok yani benim sorunum şu input lag :( bu kurla şuan ekranı geç oyun bile alamıyorum kendime haxballa daha girmeyecem ozaman tek çözüm bu

**Comment by Mirac35** [comment]
Ya aslında biraz öyle ama dediğim gibi donanımın destekliyorsa 50% less input lag büyük bir nimet. 72 Hz li özel bir çözünürlük ayarlamana izin veriyorsa elindeki makine o kadar para bayılmaya gerek yok. Sikeyim basroyu bu arada dediğin gibi bir steam client yapması bu kadar mı zor amk.

**Comment by MrKarpuz** [comment]
yok ya nvidia ayarlarında 60hz var bende sadece 30 fps oynayarakta kör edemem kendimi genç yaşımda hax defterini kapattım bundan sonra

**Comment by MrKarpuz** [comment]
@Mirac35 işe yarar herhangi bir şey bulabildin mi dostum ? 30 fps 20 extrapolation ile oynuyorum şuan hlcb ligindeyim kanser ediyor artık bu durum beni, ekranın hz sini programlarla artırmaya çalışıp ekranı kararttım başka bir monitore bağlayarak düzelttim pcyi kafayı yiyecem yani şu gecikme olayını düzeltebilecek bir şey bulabilirsen lütfen bana da haber ver çünkü ısrarla söylememize rağmen hala gecikme yok diyor devler.
