### ISSUE TITLE
Improved Player API (+ missing attributes like avatar, flag…)

### ISSUE THREAD

**Issue by evi1a** [haxball/haxball-issues#543]
Since the **Player object** of the current version of the Headless API lacks information (avatar, flag…) and some features (auto-refreshing attributes, a direct way to change values + methods) I modified the script to add some of the things I personally miss, and wanted to share it with you.

I'll share the way how to reproduce this script alone, what I changed and how exactly it improves the API.

I'll start with some examples of what you will be able to do:
```js
let players = room.getPlayerList();
let evi1a = players[1];
console.log(evi1a.admin);
-> false
evi1a.admin = true;
console.log(evi1a.admin);
-> true
evi1a.team = 2;
console.log(evi1a.avatar);
-> 22
console.log(evi1a.flag);
-> uk
evi1a.ban("spam");
```

So, to accomplish this I downloaded the [headless script](https://html5.haxball.com/GWdlxPQ6/__cache_static__/g/headless-min.js) and beautified/maximized it. I mainly changed a function called  `e(a)` that `getPlayerList()` and `onPlayer...(player)` use to get Player objects. I added the mssing stuff I mentioned above and now it looks like this…
  
```js
function e(a) {
      if (null == a) return null;
      var b = null,
        c = a.L;
      null != c && (b = {
        x: c.a.x,
        y: c.a.y
      });
      return {
        get name() {
          return a.ha;
        },
        get team() {
          return a.fa.Y;
        },
        set team(team) {
          B.setPlayerTeam(a.pa, team);
        },
        get id() {
          return a.pa;
        },
        get ip() {
          return 'this is your homework :)';
        },
        get avatar() {
          return a.gb;
        },
        get flag() {
          return a.wd;
        },
        get admin() {
          return a.oa;
        },
        set admin(bool) {
          B.setPlayerAdmin(a.pa, bool);
        },
        get position() {
          return b;
        },
        kick: (reason, ban) => B.kickPlayer(a.pa, reason, ban),
        ban: (reason) => B.kickPlayer(a.pa, reason, true)
      }
    }
```

You can download the [full modified script](https://gist.github.com/evi1a/48bf5aaae82a3122e2e741bd46fd3d4b) and replace it with the original one.

**Comment by Raamyy** [comment]
Good Job @evi1a 
I hope that the game turns to be open source and open for more community collaboration in the future.

**Comment by evi1a** [comment]
That would be awesome, but tbh I doubt that would happen...

**Comment by p2haxball** [comment]
awesome how can i replace with the original

**Comment by evi1a** [comment]
```js
let iframe = document.querySelector('iframe').contentWindow.document;
iframe.querySelector('script[src="headless-min.js"]').remove();
let script = document.createElement('script');
script.src = 'https://rawgit.com/evi1a/48bf5aaae82a3122e2e741bd46fd3d4b/raw/1f2adb48190f5152194fb9ed4aa8e29590d21f56/headless_modified.js';
iframe.querySelector('body').appendChild(script);
```

```js
let room = HBInit({});
```

**Comment by evi1a** [comment]
Now I've also added an own method called **`getPlayers()`** which returns an object you get once but can always use to either get a **player by his id**, get a **specific team** or just get **all players** like with `getPlayerList()`.

A quick example on how to use this Players API:
```js
const Room = HBInit({});
const Players = Room.getPlayers(); // get Players API only once

const Host = Players.get(0); // get Host player by id
let evi1a = Players.get(1); // get normal player by id

console.log(Players.all); // log all players
-> Array[{…}, {…}]
console.log(Players.red); // get team using attribute
-> Array[{...}]
console.log(Players.getTeam(2)); // get team using index
-> Array[]
evi1a.team = 2; // move to blue
Host.team = 2; // move to blue
console.log(Players.blue);
-> Array[{...}, {...}]
console.log(Players.specs); // get specs
-> Array[]
```

To load the new script you need to enter following code into the dev console:
```js
let iframe = document.querySelector('iframe').contentWindow.document;
iframe.querySelector('script[src="headless-min.js"]').remove();
let script = document.createElement('script');
script.src = 'https://rawgit.com/evi1a/48bf5aaae82a3122e2e741bd46fd3d4b/raw/93f077639e173cdc0669ae0adbc98fa0ad107659/headless_modified.js';
iframe.querySelector('body').appendChild(script);
```

**Comment by basro** [comment]
I'm sorry but I'll have to ask you to stop spreading this kind of thing. It will become a problem when an update is released if there are people running code that don't depend on the public stable parts of the api.
