### ISSUE TITLE
How to view > 6Mb .hbr2 file

### ISSUE THREAD

**Issue by teisseire117** [haxball/haxball-issues#544]
Hi,

First of all about haxrec it only allows to view .hbr files.

I've found http://thehax.pl/forum/powtorki.php but it only allows < 3Mb files.

My file is 6,x Mb and I do not know how to cut it in 3 or how to view it without the help of this website or found another website.

help please :3 
Thanks !

**Comment by basro** [comment]
You can view them in haxball, by using the Replays button:

![image](https://user-images.githubusercontent.com/1387293/46371479-dfdf9f00-c65e-11e8-93a7-63f4c8d4c88c.png)
