### ISSUE TITLE
Question about the new update incoming

### ISSUE THREAD

**Issue by teisseire117** [haxball/haxball-issues#549]
Hey,

I spent weeks on my actual room bot script, and if any room. commands had to change it'd be really exhausting to update all of my code.
I was wondering if when the update come we would need to change our script to make it compatible ?

Thanks

**Comment by basro** [comment]
The headless host API is expanded but every function that was there still works, there's now going to be more functions that's all.

The netcode however has changed and so rooms will need to be reloaded, old scripts will work in the new version.
