### ISSUE TITLE
10 Suggestions for the new HaxBall HTML5

### ISSUE THREAD

**Issue by haxballer** [haxball/haxball-issues#55]
At the start I will say that I don't know if it is a good place, but I will try. (Basro - don't beat)

**1.** User accounts. Why? My suggestion is to be able to register account and nickname, in order to eliminate the fake players. For that you could add a friend list and ignore the option and private chat with a particular player and set up a game.

**2.** Turning off the chat window during gameplay: It's about minimizing the chat window so you can focus on the gameplay.

**3.** The possibility of private chat on the room with the player by clicking on nickname.

**4.** Possibility to ignore people in the chat - In haxball there are a lot of trolls that offend people and just to enter the game, I would like to have such people ignore.

**5.** Fps limit, just like traditional haxball, the ability to set fps limit yourself.

**6.** The ability to turn off sounds from the game during the game, is that sometimes we want to listen to music on the pc, the new haxball isn't possible because the background noise is disturbing.

**7.** Quick change of sides, in the league matches you have to manually move the players one by one, my suggestion is to make the ability to quickly swap players on both sides without having to manually change them, which will be much faster and more enjoyable.

**8.** Optimization - Optimize and improve liquidity for older pc, if possible, because many pro gamers complain about slow balls, which prevents them from playing.

**9.** Improving fonts for avatar and nickname players, in old haxball they were nicer.

**10.** More emphasis on game promotions!

That's all my suggestions. Haxball is a really awesome game that has enormous potential for eSports, so I hope it's still going to fire. Yours and success. Cya :)

**Comment by curromc93** [comment]
I agree with you, that would be great!

**Comment by basro** [comment]
Issues should be about a single thing, many of these suggestions are already posted here.
Make sure not to create duplicates.
