### ISSUE TITLE
Unbannable admins

### ISSUE THREAD

**Issue by meteus** [haxball/haxball-issues#550]
Hey @basro ! Is it possible to make unbannable users? Like I am the owner of room (not host because of headless bot is host) in this situation if I give admin perm to someone, they are able to ban me. Is it possible to make unbannable users? Something like you type command with id. And that id cannot get banned anymore.

**Comment by basro** [comment]
The upcoming update has a clearBan(id) method which you could use to immediately clear the ban on specific players. You wont be able to prevent kicking of players though.
