### ISSUE TITLE
SyntaxError when changing map background color

### ISSUE THREAD

**Issue by teisseire117** [haxball/haxball-issues#553]
Hey,

I'm trying to change the background color : 
	"bg" : { "type" : "hockey", "width" : 0, "height" : 0, 	"color" : b3f6fd, "kickOffRadius" : 80, "cornerRadius" : 0 },

but it returns a Syntaxerror, am I doing something wrong ?

**Comment by Wolf72** [comment]
"b3f6fd"

**Comment by teisseire117** [comment]
Alright thank you :)
