### ISSUE TITLE
Having our own stats through time

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#555]
Hey, you finally made an update and it's a good one, i'm known in europe for having shared my own code to feed me. And i managed rooms  room with stats (i.e. goals, assists, wins, loses, cleensheets, goals taken, ELO) but as you will guess, it's only revelant to the rooms related to my script.

I'm sure we all would enjoy a window on haxball where we can see all our stats forever made, I mean, not using a script with your headless but it could be saved in cookies if you still don't want to make accounts.

It could have the format of this thread https://github.com/haxball/haxball-issues/issues/469 but i believe you see what i mean.

Thanks to the headless we (coders) are able to get almost every information we need to maintain stats to our own scripts but since it's made in OUR vps/... it's impossible to let every player know their own stats for the time they played.

Well i think you got the main idea ^^

Thanks for the update, keep going you do great job!

**Comment by basro** [comment]
The problem with this is persistent local storage is not a simple thing in HTML5.
I use local storage to store settings and the auth key, but it's fine if settings are lost since it's just a minor inconvinience and the auth key is supposed to be backed up somewhere if the player cares about it enough.
Local storage data can be lost at any moment, it's not a very persistent thing. Capacity is also very limited.

For this reason I wont be implementing such a feature anytime soon. Sorry.

**Comment by AnddyAnddy** [comment]
Isn't it possible to simply add events like whoScored, whoAssisted etc (which are already coded in most of headlesses) to the haxball.com/play instead of the headless? I know it's not as easy as i let understand.


So we would be able to make an extension for every users, by simply getting these info, the user would store like an array/map in his cookies/localstorage/SSD.

Also it would be fine if our stats are lost, it would be like when we cleared cookies in flash, all our stored map were gone, it was tidious but not dramatic, We could also centralize the data somewhere but it would be our problem, not yours anymore, we just ask for a way to get room events in haxball.com/play console.

**Comment by evi1a** [comment]
Creating a community-based project to centralize the stats could work.
