### ISSUE TITLE
Two acoounts

### ISSUE THREAD

**Issue by Fiflaczek324** [haxball/haxball-issues#556]
How do I detect if a player has 2 accounts per room, and if he has to dig one of them?

Help.PLS

**Comment by andriyleu** [comment]
Create an array, store the players .conn attribute and check this attributes (current_connections.includes(player.conn).

Take into account that you must also update this list at onPlayerLeave.

**Comment by Fiflaczek324** [comment]
Could you explain me more?

**Comment by AnddyAnddy** [comment]
example
let current_connections = [];
room.onPlayerJoin = function(player){
if (current_connections.includes(player.conn) room.sendChat("2 accounts have been detected from " + player.name);
else current_connections.push(player.conn);
}

**Comment by Fiflaczek324** [comment]
and how to make one-player kicks?

**Comment by Fiflaczek324** [comment]
How do I update the list when the player leaves?
