### ISSUE TITLE
Indicator - turn-off option

### ISSUE THREAD

**Issue by kojo953** [haxball/haxball-issues#557]
Can u add turn-on/off option of indicator that shows when a player is typing in the chat, like it is with custom colors, or crowd sound? It distracts attention while playing.

**Comment by andriyleu** [comment]
+1

**Comment by iamrenan** [comment]
Hijacking this to also request a feature - Could we create one of those ourselves? As in, after a room event happens, we could get a player and display an emoji on his top, just like the indicator, for just a second. Could be used for displaying a 💤 if player is inactive for too long, or displaying a ⚽ just on the player that scored a goal.

**Comment by basro** [comment]
An option to disable it is very reasonable, I'll implement it soon.

Sorry @iamrenan but I wont be implementing that suggestion for the time being.

**Comment by basro** [comment]
This is now implemented.
