### ISSUE TITLE
new feature - "radius of the ball"

### ISSUE THREAD

**Issue by Wenomka** [haxball/haxball-issues#56]
Could you add feature under options "time limit" and "score limit"?

**Comment by basro** [comment]
You can configure the ball radius by using custom stadiums.

**Comment by Wenomka** [comment]
@basro would be nice if it will be like standart option. But like i said before - need for fix left and right board, cuz "segment" could be crash by ball with radius <5

**Comment by Wenomka** [comment]
@basro  Ball can still go through boards
