### ISSUE TITLE
Displaying player's id somewhere

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#560]
(next to ping for exammple) 

Again me, since we can now unban from id, pm from id, do everything with id..

I think in order to easily write commands like "!pm id message" or "!unban id" from admins in rooms or even from players, that's we should easily access to other players' ids
As you want

**Comment by meteus** [comment]
5 mins ago I see same example in a headless room what you said. 

The owner created pm system.

First you use !id command to get ids.
In chat, bot sends everyone's id.
Then you use !pm id message
And bot send the message.

I think owner made this with room.onGameChat();

Any ideas about how he made it?

**Comment by AnddyAnddy** [comment]
Yes i know it's possible and pretty not hard to do, but you have to do 2 commands, one in order to get the id, the other to use the feature
The point i wanted to show is that's easy to make for coders but it's boring to do as a simple player in rooms, it would be better if the id was directly shown by haxball and not by us

**Comment by evi1a** [comment]
Yeah, it would be better if basro could display it for example after the name like username like **Username#id**.
So you see it at first glance and don't need any extra commands.
I think it's really needed since headless got released, it would also make it possible to distinguish between two user with a different name for example. So people can't troll around like that any longer.

**Comment by olegmisar** [comment]
You can use players' nicknames to send PMs

**Comment by evi1a** [comment]
sure but ids are generally shorter and unique

**Comment by olegmisar** [comment]
Yeah, it's a problem that haxball doesn't have registration. But there aren't a lot of players with similar nicknames and it is more convenient to use nicknames to send PMs.

**Comment by evi1a** [comment]
Yeah, I got something like a hybrid where u can combine both but still it would enhance the experience if the ids would be visible at first glance for the case you need them

**Comment by iamrenan** [comment]
Here's my script for getting a player by it's name or ID, it may prove useful in situations like this. Note that it requires ES6.

```javascript
function getPlayer(nameOrID) {
    const isID = Number.isInteger(Number.parseInt(nameOrID))
        if (isID)
            return room.getPlayer(nameOrID)
        return room.getPlayerList().find(p => {
            if (p.name.normalize('NFKD').toLowerCase().includes(nameOrID.normalize('NFKD').toLowerCase()))
                return p
        })
}
```
The `normalize('NFKD')` bit is helpful for player that have custom nicknames such as 𝐢𝐚𝐦𝐫𝐞𝐧𝐚𝐧, 𝓲𝓪𝓶𝓻𝓮𝓷𝓪𝓷, ｉａｍｒｅｎａｎ and so on - It converts them to a readable version (iamrenan in this case).

Now you don't need ids to do actions! An example of how I would use this in my room, using the new targetId feature:

```javascript
room.onPlayerChat = function (player, message) {
    const words = message.split(' ')
    // words must have at least 3 items: "!pm", the player partial name or id as the second item, and the last items become the message.
    if (message.startsWith("!pm") && words.length >= 3) {
        // we must check whether the user typed a valid name/id, or he'll be kicked out of the room
        if (getPlayer(words[1]) !== undefined || getPlayer(words[1]) !== null)
            return false
        let msg;
        words.forEach(w => { msg += `${w} ` });
        room.sendChat(`📨 from ${player.name}: ${msg}`, getPlayer(words[1]).id)
        room.sendChat(`Your message to ${getPlayer(words[1]).name} was sent!`, player.id)
    }
}
```

I didn't tested it but the premise to make it work is there ;p

**Comment by evi1a** [comment]
This is good, but there is also a problem when someone has his name written in a foreign script like cyrillic or arabic... :(

**Comment by evi1a** [comment]
do you maybe know a way to solve that issue too?

**Comment by basro** [comment]
I agree with this feature being useful, so I'll probably implement something like this in the future.

I think it would be best if it was displayed in some kind of nickname auto-completion system, press @ while chatting and a drop down menu with the player names and id's would appear.

**Comment by basro** [comment]
Logically I mean it'd be both things in one shot, player name auto-completion/mentioning and also make it so that it's unambiguous for scripts. After selecting a name from the dropdown the format would probably be something like @23:iamrenan (where 23 is the id number).

**Comment by basro** [comment]
The auto-completion feature is now implemented.

Instead of mixing the id and the name in a single autocompletion format I decided to use @ for names and # for IDs. So I recommend using the # mode for headless room commands.
