### ISSUE TITLE
html5 link

### ISSUE THREAD

**Issue by Wolf72** [haxball/haxball-issues#568]
https://html5.haxball.com/playerauth
https://haxball.com/playerauth

2 different keys. it's really annoying

**Comment by basro** [comment]
Well, just don't use the html5 subdomain :P
I guess I'll have to make the html5 subdomain redirect to www

**Comment by Wolf72** [comment]
ah i thought html5 is official xD
Anyway my auth kept changing and it took me a while to figure i was using different domains xD
