### ISSUE TITLE
setPassword() feature request

### ISSUE THREAD

**Issue by kamild706** [haxball/haxball-issues#569]
I know it has already been requested (#382 or #398) but I want to remind you about this feature as it would be surprisingly useful. Changing password dynamically could prevent spammers, trolls, and other kids from interrupting the game as they couldn't join the room when the password is set after gathering required number of players.

Having said that, I hope you implement this soon.

**Comment by basro** [comment]
You don't need to open a new issue, just commenting on the already existing ones would have been sufficient.

Removing because it's a duplicate.
