### ISSUE TITLE
HELP WITH CODE FOR HEADLESS

### ISSUE THREAD

**Issue by PheuxHWN** [haxball/haxball-issues#580]
@Raamyy @basro @Wrathen

Hello, I need your help. I would like you to help me edit this code.
It's almost finished, it's for "Real Soccer".
The bot says the corners, sides, bow kicks, etc.
I just need to say ball possession, statistics (assists and goals), that remove the AFK and that you can vote administrator.

HERE IS THE RS CODE

I HAVE THIS OTHER

But the bot does not say: laterals, corners, arc serves.
Please add it. And if it's not too much trouble, the administrator vote too.

**I'm trying to learn about this, but for now I need your help. I'm a newbie.
Would be a great help. Thank you.**

**Comment by Kozlov98** [comment]
Phuex, porfavor deja de spamear con tu liga de fantasia """""GLH""""", no ayudas en nada a la comunidad argentina que esta en constante crecimiento, la gente entra y se piensa que GLH es una liga verdadera, porfavor. Gracias.

Pheux, please stop spamming with your fantasy league GLH, you don't help to argentina community, That is constantly growing, the people enter to yours host and think that GLH is a real league, please, thank you.

**Comment by PheuxHWN** [comment]
Disculpa pero en primer lugar no es "mi liga". Y segundo, tampoco es "fantasía". Y en tercer lugar, pero no menos importante, no se a que comunidad te refieres, la que está en "constante crecimiento". Pero la única liga que realmente está creciendo, empíricamente hablando, es GLH.
La gente utiliza sus mapas, cada vez hay más gente inscrita, así que ten un poco de respeto.
