### ISSUE TITLE
Players didnt spawn on map

### ISSUE THREAD

**Issue by Gonah** [haxball/haxball-issues#59]
Only saw this happen once, but after setting teams (4v4), I hit start game and the map showed but the player balls weren't there. The names of the players still showed in the normal start locations. No one could move. It corrected itself after stopping and starting the game.

Probably pretty low priority since it recovers. Only saw it happen once out of maybe 50 games.

**Comment by basro** [comment]
This is related to #63

**Comment by basro** [comment]
This is now fixed.
