### ISSUE TITLE
Issue connecting to room hosts

### ISSUE THREAD

**Issue by Hoperly** [haxball/haxball-issues#6]
Can't enter any room in the HTML version. 
It says me ["Master connection error"](https://gyazo.com/a5d7fd0202d7977355ff0e70d8779838)
But when I'm using VPN I can enter rooms.

**Comment by basro** [comment]
Hoperly, please have a look at the conversation in this issue: https://github.com/haxball/haxball-issues/issues/95

Follow the steps that I told user daklaj to follow and report your results.

**Comment by basro** [comment]
I apologize for the long wait, I've now released an SSL enabled version of haxball that probably fixes this issue.
