### ISSUE TITLE
Implement kits

### ISSUE THREAD

**Issue by jenrisito** [haxball/haxball-issues#60]
Kits aren't implemented in HTML5 version.

Besides that, I think that HTML5 offers more options to customize your own kit. I think it would be a good idea to be able to load our own kits on the same way we can load our maps. For example, if we want to create the Croatia kit with the squares or current Barcelona kit with thiner stripes, we need some new features for kit implementation that Flash doesn't have.

Thank you for reading and for your work!

**Comment by basro** [comment]
Custom team colors are now implemented as they were in the flash version.
