### ISSUE TITLE
Broken extrapolation

### ISSUE THREAD

**Issue by asap11** [haxball/haxball-issues#603]
Why can't i play on extrapolation higher than 10? I've heard that a lot of players play on 40+ and the game is smooth, but when i set it to 15 the screen shakes so much that it's almost impossible to play. Both PC and internet are really good so i guess that's not the reason.  What's the problem?

**Comment by Leo-MapCreator** [comment]
Maybe the host connection
40 is a lot of extrapolation though
15 should be without this shaking, but its probably the connection with the host that is bad

**Comment by asap11** [comment]
I don't think it's internec connection because i'm having this issue even on the rooms in 20 km range.

**Comment by basro** [comment]
Extrapolation will cause the game to become jittery like you describe, 40+ is a fairly high value for it.
