### ISSUE TITLE
basro

### ISSUE THREAD

**Issue by fakeuser117** [haxball/haxball-issues#607]
Sorry, won't happen again.
you probably know what I'm talking about.

Just, sorry. You don't need to accept my apology or something, let's just forget about it.
If you don't know what I'm talking about it's embarrassing(scaleway 163/172). Anyway, again, sorry, and have a good continuation.

EDIT: I see it's still going on, it's not me. just restart.

**Comment by basro** [comment]
If you are sincerely sorry please send an email to haxball@gmail.com, I'd like to have a private conversation with you.
