### ISSUE TITLE
Room is dead after +/- Day, errors in console

### ISSUE THREAD

**Issue by dixtel** [haxball/haxball-issues#608]
Hello @basro 
Several times when i host my bot with token my room is dead next day.
This is screenshot from console
![screenshot_2018-11-02_19-12-05](https://user-images.githubusercontent.com/10550755/47933456-eae35480-ded4-11e8-989c-b9fe0b0784d4.png)

**Comment by fakeuser117** [comment]
At what date + time were these error message

**Comment by basro** [comment]
There has been downtime of the haxball master server which is most likely what caused those errors.
