### ISSUE TITLE
Re-add goals to replay!

### ISSUE THREAD

**Issue by nmygui** [haxball/haxball-issues#610]
Why were the goals removed from the replay?!

Could you add it again?

**Comment by basro** [comment]
Are you talking about the goal markers? They haven't been removed, and they seem to work for me.
Could you share a replay file were they don't work? It might be a bug.

**Comment by nmygui** [comment]
is not the goal markers, it would be the "view goals" that shows who made the goals and assists.

sorry if I was not very explanatory on 1 topic

**Comment by Skarmunds** [comment]
@nmygui TheHax updated their replay tool last week and it's working like before. You could close the issue.
