### ISSUE TITLE
anti afks

### ISSUE THREAD

**Issue by rafivglepi** [haxball/haxball-issues#625]
I need help creating an anti-afk. A command that a player types, example "!afk" for when he is moved to a team. it be moved to spectators

**Comment by AnddyAnddy** [comment]
https://github.com/haxball/haxball-issues/issues?utf8=%E2%9C%93&q=is%3Aissue++afk+

**Comment by RafaN3rd** [comment]
i dont understand.

**Comment by olegmisar** [comment]
He provided you with page of related issues. You should first search for issues before creating a new one. Btw, you should not ask "how to" questions here.
```js
room.onPlayerChat = (p, m) => {
  if (m === 'afk') {
    room.setPlayerTeam(p.id, 0)
  }
}
```

**Comment by RafaN3rd** [comment]
> Ele forneceu a você uma página de questões relacionadas. Você deve primeiro procurar por problemas antes de criar um novo. Btw, você não deve perguntar "como fazer" perguntas aqui.
> 
> ```js
> quarto . onPlayerChat  = ( p , m ) => {
>    se (m ===  ' afk ' ) {
>      espaço . setPlayerTeam ( p . id , 0 )
>   }
> }
> ```


I already researched. but nobody explained well. I was not understanding anything. I'm new to haxball headless. especially my room and the anddy script. I just modified his open source. and the code you gave. it just makes the player go to viewers and not always while it does not type again.

**Comment by RafaN3rd** [comment]
> He provided you with page of related issues. You should first search for issues before creating a new one. Btw, you should not ask "how to" questions here.
> 
> ```js
> room.onPlayerChat = (p, m) => {
>   if (m === 'afk') {
>     room.setPlayerTeam(p.id, 0)
>   }
> }
> ```

I already researched. but nobody explained well. I was not understanding anything. I'm new to haxball headless. especially my room and the anddy script. I just modified his open source. and the code you gave. it just makes the player go to spectators and not always while it does not type again.

**Comment by raviglepi** [comment]
oh wow i was a dumb kid
