### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by Zorark** [haxball/haxball-issues#63]
This already happened three time, when I start a new game all the players become invisible then only restarting the match to play normally

**Comment by basro** [comment]
Can you give me more info?
Were you playing a custom stadium? If so, which?
Was this bug observed by everyone in the room or just you?

I've not seen this bug myself yet, if you can figure out a way to reproduce consistently it it would be very helpful.

**Comment by loveuhaxball** [comment]
y this problem really

**Comment by Zorark** [comment]
@basro
Yes, playing SpaceBounce 4 vs 4 
Everyone in the room saw the same thing

Exactly as #59 report to you
In these 4 days maybe happened 3 or 4 times

**Comment by Zorark** [comment]
@basro Now the bug happened 2 times in a row I also notes then is more easy when the room have two or three admins. Maybe, just maybe is because the two of admins started simultaneously.

I have a screen to how  it looks:
http://prntscr.com/h4ktw1

**Comment by basro** [comment]
@Zorark, that is exactly the reason!
Thanks for your help, I'll be fixing this in the next release.

**Comment by basro** [comment]
The fix is now released.
