### ISSUE TITLE
Room goes off the room list

### ISSUE THREAD

**Issue by NiExTy** [haxball/haxball-issues#633]
I noticed sometimes room disappears from the room list (2 days?), it is still working but eventually dies out because no new players can join. When players try to join trough direct link it says:

> **Disconnected**
> Connection closed (4001)

No console errors. Worst thing is that you can't tell when your room disappears from the room list, because all in-game functions work fine.

Can we get something like:
> room.getRoomList();

Or other function to notify host?

**Comment by Leo-MapCreator** [comment]
If is says Connection closed, the room is not online anymore

**Comment by NiExTy** [comment]
It is online, and we can still play in it until we leave. I see other Futsal room under my room going off the list about at the same time.

**Comment by Leo-MapCreator** [comment]
Do this test:
Put the room1 up, then after 12 hours, put the room2 up, if they disappear at the same time, its something with your connection, if they disappear 12 hours apart, its something with the time the room has been up

**Comment by basro** [comment]
This issue has probably been fixed now.
