### ISSUE TITLE
Handler in onGameTick with id

### ISSUE THREAD

**Issue by LGosh** [haxball/haxball-issues#634]
I'm trying to handle the players that have not moved for a while. What I've done so far does not work, it does not send a chat message, neither logs any errors in console. Any ideas? Thanks

```
const activities = {};
let id;
room.onGameTick = function () {
    activities[room.getPlayer(id)] = Date.now();


    let now = Date.now();
    for (let id in activities) {
        if (now - activities[id] > 5000) {
          room.sendChat(room.getPlayer(id) + 'has not moved for a while');
        } else if (now - activities[id] > 8000) {
          room.sendChat(room.getPlayer(id) + 'has not moved for even longer');
        }
    }

**Comment by kamild706** [comment]
The `onGameTick` is invoked 60 times per second, and since probably you are testing this script using one account then your last activity time is updated constantly is 4<sup>th</sup> line. Secondly, you set properties of `activities` using `PlayerObject` - this is what `getPlayer(id)` returns. And in `for in` loop you invoke `room.getPlayer(id)` where the id in this case is `PlayerObject`. So it doesn't make sense to make such call. You should also add an `else` block to your loop for debugging purposes.

**Comment by LGosh** [comment]
Thanks for the quick reply. This is what I've tried according to your suggestions, but it just sends "not afk" message in the console even if I join with 2 accounts (with new tab, does this count?). Don't be surprised if you'll see something very stupid in this code, as I am still a novice to this. Thanks

```const activities = {};
let id;
room.onGameTick = function () {
  let players = room.getPlayerList();

  for (let player of players) {
    activities[player.id] = Date.now();

    let now = Date.now();
    for (let id in activities) {
        if (now - activities[id] > 5000) {
          room.sendChat(player.id + 'არის AFK');
        } else if (now - activities[id] > 8000) {
          room.sendChat(player.id + 'გაიკიკა');
        } else {
          console.log(player.id + 'not afk');
    }
  }
}

**Comment by kamild706** [comment]
I thought you showed us only a part of your code related to detecting inactive players, but it seems that I was mistaken.

You need to use `onPlayerActivity(player)` callback to save time of player's last activity. In `onGameTick` you then compare actual time to the stored time of player's activity and if time difference is bigger than given threshold then you know that the player is inactive.

Your actual code doesn't make sense, because you set players' last activity time constantly 60 times per second. You should detect player's activity in `onPlayerActivity(player)` not `onGameTick`.

**Comment by LGosh** [comment]
I decided to set players' last activity in `onGameTick` because if a player "spawns" inactive, the `onPlayerActivity(player)` wouldn't handle that situation. And regarding the last code I posted, do you see some major/minor errors in there? Because I think it's close to be completed, just naming conventions error or something, I don't know. Thanks

**Comment by kamild706** [comment]
The problem is that you don't update players' last activity time when the activity occurs. You update this time non-stop in `onGameTick`.

**Comment by LGosh** [comment]
Woah, I am getting more and more confused, sorry. Could you please, for the love of god 🤣, if you have time of course, write a code for me that does what I am trying to do, including the "spawning" inactive fix. I'll be very glad.

**Comment by Wazarr94** [comment]
In any case, you can only detect players' activity via `onPlayerActivity`
You'll need to handle the case where players "spawn" (does it mean getting switched to a team ?) inactive using other events, probably `onTeamChange`

**Comment by LGosh** [comment]
> I believe the code should look like this:
> 
> ```js
> let lastActivityTime = {};
> 
> room.onPlayerActivity = player => {
>     lastActivityTime[player.id] = Date.now();
> };
> 
> room.onGameTick = () => {
>     let now = Date.now();
>     for (let playerId in lastActivityTime) {
>         if (now - lastActivityTime[playerId] > 5000) {
>             room.sendChat(`${room.getPlayer(playerId).name} is inactive`);
>         }
>     }
> };
> 
> room.onPlayerTeamChange = changedPlayer => {
>     if (changedPlayer.team !== 0) {
>         lastActivityTime[changedPlayer.id] = Date.now();
>     }
> };
> ```
> 
> I didn't tested it but looks fine and rather works. Of course this is very simple solution that needs to be corrected.

Thanks, it definitely works, I appreciate your assistance and time!

**Comment by LGosh** [comment]
I've been trying to "correct" your solution, but guess what 😞. I couldn't. The given solution prints out "**TestPlayer is inactive**" endlessly, and once the "**TestPlayer**" leaves the host, the console gets spammed with `"room.getPlayer(...) is null"`.

**Comment by olegmisar** [comment]
`room.getPlayer(id)` returns `null` if there isn't any player with that `id`. Probably that player has left.
You should remove player's last activity time when player leaves the room.
```js
room.onPlayerLeave = player => {
  delete lastActivityTime[player.id]
}
```

**Comment by LGosh** [comment]
> `room.getPlayer(id)` returns `null` if there isn't any player with that `id`. Probably that player has left.
> You should remove player's last activity time when he leaves the room.
> 
> ```js
> room.onPlayerLeave = player => {
>     delete lastActivityTime[player.id]
> }
> ```

Great, it works, thank you, I appreciate it. However, the last issue is still there, the one where the message "**TestPlayer is inactive**" is being sent endlessly, 60 times per second or so.

**Comment by olegmisar** [comment]
It's not an issue. Look at the code. In `room.onGameTick` you send that message again and again, 60 times per second for each player.

**Comment by LGosh** [comment]
Sorry I must have not explained myself clearly. I know it is not an issue, but I called it an issue because I tried to correct it but couldn't. I know what's happening in `room.onGameTick`, and I know a solution in theory, and I tried lots of different things, but none of them worked.

**Comment by olegmisar** [comment]
Just remove `room.sendChat` from `onGameTick`

**Comment by LGosh** [comment]
The thing is that I want to send the message just once.

**Comment by olegmisar** [comment]
How many times exactly? The simplest solution will be to use `setInterval` instead of room.onGameTick`. Look for `setInterval`  in Google.

**Comment by LGosh** [comment]
Only 1 time. Ok I'll look it up.

**Comment by LGosh** [comment]
Ok I did the following with the `setInterval` but all it does is send a "**TestPlayer is inactive**" message once in every 1 second. **I know why it's happening in theory, but I can't fix it in practice**. Can anyone help please? Thanks

```function updateAfksMessage() {
  let now = Date.now();

  for (let playerId in lastActivityTime) {
      if (now - lastActivityTime[playerId] > 4000 && room.getPlayer(playerId).team !== 0) {
      room.sendChat(`${room.getPlayer(playerId).name} is inactive`);
      } else if (now - lastActivityTime[playerId] > 8000 && room.getPlayer(playerId).team !== 0) {
        room.kickPlayer(room.getPlayer(playerId).id, 'kicked for long inactivity', false);
  }
}
};

let updateAfksMessageInverval = setInterval(updateAfksMessage, 1000);

**Comment by olegmisar** [comment]
Please post all code and I will be able to replicate your problem

**Comment by kamild706** [comment]
```javascript
let afkNotificationShowed = [];

room.onPlayerActivity = player => {
  lastActivityTime[player.id] = Date.now();

  let id = afkNotificationShowed.indexOf(player.id);
  if (id !== -1) afkNotificationShowed.splice(id, 1);
};

function updateAfksMessage() {
    let now = Date.now();

    for (let playerId in lastActivityTime) {
        if (room.getPlayer(playerId).team !== 0) {
            if (now - lastActivityTime[playerId] > 4000 && !afkNotificationShowed.includes(playerId)) {
                room.sendChat(`${room.getPlayer(playerId).name} is inactive`);
                afkNotificationShowed.push(playerId);
            } else if (now - lastActivityTime[playerId] > 8000) {
                room.kickPlayer(playerId, 'kicked for long inactivity', false);
            }
        }
    }
}
```

Notice that this code should work only when game is in progress. Otherwise you will kick red and blue players during teams choosing.

**Comment by LGosh** [comment]
Thanks a lot, it sends a message just once, as it was intended. However, if a player gets a message, and then moves until getting kicked, and then goes inactive again, the message is not getting displayed again, only getting kicked in 8 secs. I guess the `splice` does not work as intended?
