### ISSUE TITLE
Issue with onPlayerActivity

### ISSUE THREAD

**Issue by lashagosh** [haxball/haxball-issues#637]
I'm handling inactive players by listening to `onPlayerActivity`. 90% of the time it works as intended, however, when I change map to i.e. Huge, where if a player stands in Red's goal, and presses only D (or right arrow), to get to Blue's goal, it will take him about 7 seconds to get there. The `onPlayerActivity` is not updated if a player moves for a while with holding down only one button. Is there a better alternative to find out whether a player is moving or not?

I know I can probably find out players' positions by `player.position`, but I can't apply this theory to the practice, as I don't know how. Thanks

**Comment by LGosh** [comment]
Solved
