### ISSUE TITLE
Getting position from players list returns Object

### ISSUE THREAD

**Issue by LGosh** [haxball/haxball-issues#638]
I'm trying to detect if a player is moving or not, by creating a function and setting an interval to call it. What I implemented logs "`[object Object] position]`". Any ideas why it does not return an actual position?

```  
  let players = room.getPlayerList().filter(player => player.id !== 0);
  players = players.filter(player => player.team !== 0);

  for (let playerId in lastActivityTime) {
    for (i = 0; i < players.length; i++) {
        console.log(players[i].id + " id");
        console.log(players[i].position + "  position");
          var currentPosition = players[i].position;
          var previousPosition = currentPosition;
          if (previousPosition != currentPosition) {
            playerMoving = true;
          } else if (previousPosition == currentPosition) {
            playerMoving = false;
          }
   }

**Comment by LGosh** [comment]
Solved

**Comment by olegmisar** [comment]
If you still want to know why it is logging `[object Object] position]`, continue reading.

`position` is an object: `{ x: 0, y: 0 }`. `x` and `y` can be any number, not only `0`. So, you log `players[i].position + ' position'`. `+` operator concatenates `players[i].position` __object__ and `' position'` __string__. So, it converts that object to the string. JavaScript doesn't convert objects to the human readable string. It converts it to the `'[object Object]'` string. Look at the following example:
```js
let obj = {
  a: 'a',
  b: 2 
}
obj.toString() // [object Object]
'' + obj // [object Object]
obj.a + ' ' + obj.b // "a 2"
```

**Comment by LGosh** [comment]
Got it, thanks.
