### ISSUE TITLE
I can't join in rooms

### ISSUE THREAD

**Issue by smthg** [haxball/haxball-issues#64]
I can't join in 95% rooms. Is this problem with ports or what ?
Can u fix this ?

**Comment by basro** [comment]
Have you tried the things listed here?: https://github.com/haxball/haxball-issues/wiki/Connection-Issues

**Comment by smthg** [comment]
I did it now and nothing. Do u have something else ?

**Comment by basro** [comment]
smthg, if you join irc channel #haxball in here https://webchat.freenode.net/ I'll try to figure out with why you can't connect.

**Comment by smthg** [comment]
I'm in, so what now ?
