### ISSUE TITLE
Ping Command

### ISSUE THREAD

**Issue by fnacs** [haxball/haxball-issues#643]
It'd be great a command that returns the player's ping

e.g.:
```
Bot: Player1 scored a goal - 00:38

Player2: i'm lag, it's fair play

Player1: !ping Player2

Bot: Ping: 23 | Max Ping: 76

Player1: you're lying! No fair play
```

**Comment by Leo-MapCreator** [comment]
@basro What you can do is put ping as player object, and if the bot identifies you want to know the ping of someone, get the instant ping and send the message, of course it will not change over time, just everytime the playerObject is requested
