### ISSUE TITLE
How can I implement the localstorage?

### ISSUE THREAD

**Issue by Gorillaz2-D** [haxball/haxball-issues#645]
I used this code:

![image](https://i.imgur.com/7rKYAY8.png)

But I came across this error that I can not solve. What is missing? 
Thank you!

![image](https://i.imgur.com/xsh1UKK.png)

**Comment by Gorillaz2-D** [comment]
I just identified and solved the problem.

**Comment by meteus** [comment]
Hey do you have discord? I want to ask you a question. Please tell me ur discord username, or skype, or any social thing we can communicate instantly. @Gorillaz2-D
