### ISSUE TITLE
Game state timeout

### ISSUE THREAD

**Issue by coIev** [haxball/haxball-issues#650]
I joined a game earlier and upon joining I got "Game state timeout"

Running W10 Insider 18290

Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)

![4887e443785bf8a29b807a8a13dfc152](https://user-images.githubusercontent.com/44411392/50037177-83d0b980-ffc3-11e8-8db8-025cd61ede0a.png)

**Comment by basro** [comment]
This is normal behavior unless you see it happen often, it just means that you connected to the host but then the host never sent the game data. It could happen if the room is closed just as you are joining it and for a plethora of other reasons too.

**Comment by Robfera** [comment]
I have this problem only on one server. Any ideas how someone might fix it?
