### ISSUE TITLE
Little bug in replay

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#673]
In a replay, administration changes are shown even though we are skipping the moment it happened.

For example, take a replay that's 30 minutes long and someone gets admin at 01:00. If I am at 00:00 and I click to go at 23:00, the chat gives the admin notification, even though it happened while fast forwarding.

**Comment by basro** [comment]
Well spotted, thanks

**Comment by basro** [comment]
This bug should now be fixed.
