### ISSUE TITLE
Flash storage

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#675]
Before shutting down the Flash version of haxball, can you implement #288 there (Getting the .hbs file)? This way we can save maps that does not have the .hbs file but are stored in the memory, and assure that old good maps will be not lost forever

**Comment by Wolf72** [comment]
I made function for html5 version which gets the stadium. It was hella lot of work since code is obfuscated. I don't think it works anymore since update...Should not be hard to do same in flash

**Comment by basro** [comment]
I am currently working on this.

**Comment by Leo-MapCreator** [comment]
I don't know if it has something to do with the map name, but maps that contains | in the name do not work

**Comment by basro** [comment]
They don't work in what way? does it not output a file or does the output file fail to load afterwards?

**Comment by Leo-MapCreator** [comment]
Doesnt output, it doesnt even appear the window to save the map name

**Comment by basro** [comment]
Yes, it seems to be the characters of the name that are the problem, I'll fix it.

**Comment by Leo-MapCreator** [comment]
I think that its because you can't save file with those characters

**Comment by basro** [comment]
It should be fixed now.

**Comment by Leo-MapCreator** [comment]
Working fine. Thank you basro

**Comment by basro** [comment]
@Wolf72 there you go.

**Comment by Leo-MapCreator** [comment]
FUCKING YEAH
