### ISSUE TITLE
Room list unconsistent ?

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#685]
https://i.gyazo.com/8f151ba47f1b3fb850ff85425a90adfe.png

Rooms disappear and reappear for no reason ? (Several headless rooms are not showing in this image)

The room list in reality something like that (maybe other rooms are not showing) : https://i.gyazo.com/bc98e94f81c89f4fb65ec3656b01733c.png

**Comment by basro** [comment]
This is a bug, I'll be fixing it today. Thanks for reporting it.

**Comment by basro** [comment]
The issue should be fixed now although you need to refresh the site for the fix to take effect.

**Comment by AnddyAnddy** [comment]
Still bugging sometimes (I don't have a screen, i'll try to get it today if it happens)
