### ISSUE TITLE
Haxball 16 or 33msec latency effects on gameplay (email sent 7th February)

### ISSUE THREAD

**Issue by HaxAddict** [haxball/haxball-issues#699]
Look you don’t have to agree with me or anything, but please have a quick read through it. It took me a very long time because I didn’t just have to write it, I also had to find a lot of evidence/gifs showing what I meant, and added many quotes of other players describing their thoughts about the same issues as well, and included a big poll that was done.

Each topic is titled in bold and capitals above their paragraph, so you can skip through parts of the email that you think don’t apply to the central point, and read through the email much quicker if time is an issue. It would be greatly appreciated, thanks.

**Comment by HaxAddict** [comment]
Sent to:

haxball@gmail.com

**Comment by basro** [comment]
Believe it or not your email was marked as spam by gmail so I never got to see it.
It's quite the wall of text and I'm currently reading it, I'll close this issue and reply to your email.
