### ISSUE TITLE
Mute spectators

### ISSUE THREAD

**Issue by SalgadoDoce** [haxball/haxball-issues#702]
i want to mute spectators with !spec_off

**Comment by iamrenan** [comment]
room.onPlayerChat = (player, message) => {
    if (player.team === 0)
        return false;
}

As simple as that. With this code, no message sent by spectators will be
seen by anyone.

Em sáb, 9 de mar de 2019 17:26, SalgadoDoce <notifications@github.com>
escreveu:

**Comment by iamrenan** [comment]
Oh, you want to !spec_off:

let spec_off = false;

room.onPlayerChat = (player, message) => {
    if (player.admin && message.startsWith("!spec_off").toLowerCase()) {
         spec_off = !spec_off;
}
    if (player.team === 0 && spec_off) {
        return false;
   }

If an admin types "!spec_off", spectators won't be able to send any
messages.
I sent this from my phone so pardon any misspelling or errors!

Em sáb, 9 de mar de 2019 17:32, Renan Aguiar <renan.aguiar17@gmail.com>
escreveu:

**Comment by SalgadoDoce** [comment]
thankyou =)

**Comment by SalgadoDoce** [comment]
your code did not work, I had to make some changes

room.onPlayerChat = (player, message) => {
    if (player.admin && message == '!spec_off') {
         spec_off = !spec_off;
         return false;
	}
    if (player.team === 0 && spec_off) {
        return false;
    }
}

**Comment by SalgadoDoce** [comment]
`room.onPlayerChat = (player, message) => {
    if (player.admin && message == '!spec_off') {
         spec_off = !spec_off;
         return false;
	}
    if (player.team === 0 && spec_off) {
        return false;
    }
}`
