### ISSUE TITLE
Headless bug

### ISSUE THREAD

**Issue by subxqns** [haxball/haxball-issues#706]
Last night I experienced a weird bug, I was hosting a headless room and there was an admin who wasn't me, I was just watching how it all worked. At some point, during a game, the admin got inactive but I waited until he'd come back which he didn't so I kicked him from the console and some other player would take the admin rights automatically.
What I couldn't notice was that I was given the rights, because the game froze and didn't even show me the admin controls, and I couldn't see the game being paused/stopped/started either. While this was happening in the game, the console.log was showing everything fine, how the players didn't understand what was happening and how they were able to talk to each other (meaning I was the only one unable to read the chat).

I left the room hoping some other player would take the admin rights but, for what I could see, he was going through the same problems I had had, he was unable to read the chat and was trying some commands in there.
When I joined again and gave myself admin rights using a command I went through the same again so I guess it was an admin bug. 

Any ideas what it could have been?

**Comment by olegmisar** [comment]
Error in any call back can disconnect player. Are you sure there aren't any errors in the function where you give admin rights to someone? Send the code where you do this.

**Comment by subxqns** [comment]
Players weren't disconnected when given admin rights, they'd just got their game frozen (menu, chat, game view, and admin controls wouldn't show), besides I could see them writing in the chat from the console. The code for giving admin is the same as the example code here in github (look for any admins left and if there are none give admin to the first player in playersList, and do this onPlayerJoin and onPlayerLeave)

**Comment by olegmisar** [comment]
This also can be a result of an infinite loop. Does this problem appear if you give someone admin rights directly (right click on player -> give admin rights)

**Comment by subxqns** [comment]
There's not a single problem when I test the room on my own, giving admin automatically or manually, it just happened that one time with the room public. I'll have to host again and see if the same thing occurs
