### ISSUE TITLE
Multi tab detection

### ISSUE THREAD

**Issue by UyuzWeb** [haxball/haxball-issues#707]
Hello everyone, 
I want to detect a user who has opened multiple tabs and they will kick. 
For ex. In my room there are 2 different nickname but they are same person. I want to kick both of them.
How can I do that? Could you give an example codes?

**Comment by olegmisar** [comment]
You can use `auth`: https://github.com/haxball/haxball-issues/wiki/Headless-Host#auth--string

**Comment by UyuzWeb** [comment]
> You can use `auth`: https://github.com/haxball/haxball-issues/wiki/Headless-Host#auth--string

I know this code, but I couldnt. Could you help me ?

**Comment by olegmisar** [comment]
IDK if this code works but this is general idea

```js
const authLookup = {}
room.onPlayerJoin = player => {
  if (authLookup[player.auth] !== undefined) {
    // Player with the same auth has joined
  } else {
    authLookup[player.auth] = player.id
  }
}

room.onPlayerLeave = player => {
  for (const [auth, id] of Object.entries(authLookup)) {
    if (authLookup[auth] === player.id) {
      delete authLookup[auth]
    }
  }
}
```

**Comment by UyuzWeb** [comment]
> IDK if this code works but this is general idea
> 
> ```js
> const authLookup = {}
> room.onPlayerJoin = player => {
>   if (authLookup[player.auth] !== undefined) {
>     // Player with the same auth has joined
>   } else {
>     authLookup[player.auth] = player.id
>   }
> }
> 
> room.onPlayerLeave = player => {
>   for (const auth of Object.keys(authLookup)) {
>     if (authLookup[auth] === player.id) {
>       delete authLookup[auth]
>     }
>   }
> }
> ```

The room freezes when I tried it. I do not know why. Could I send my all codes your e-mail?

**Comment by olegmisar** [comment]
Yes, olegmisar@gmail.com

**Comment by UyuzWeb** [comment]
My problem continues..

**Comment by subxqns** [comment]
How can you improve this method? I thought of this before but I noticed that if you open a tab on html5.haxball.com/play, or haxball.com/play, or those same pages but on incognito or another browser, you get a different auth value for each. Then I thought of using the conn property but there may be more than one person playing so now i'm clueless
