### ISSUE TITLE
room.onRoomClose

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#718]
Hey, is there a way to catch when the room closes or i believe harder, when the browser leaves the headless window ? 
Otherwise, would it be possible to add this feature ?

**Comment by iamrenan** [comment]
I'm not sure whether it's exactly what you want, but you can use
window.onbeforeunload (see more info here:
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#Syntax).
When the headless tab is closed, this event is fired before that happens.

Em qui, 28 de mar de 2019 16:15, AnddyAnddy <notifications@github.com>
escreveu:

**Comment by AnddyAnddy** [comment]
Thanks, it's what i needed

**Comment by olegmisar** [comment]
I believe `unload` event is more relevant because it fires when window is about to be closed and, unlike `beforeunload` cannot prevent window closing.
