### ISSUE TITLE
Loading local file

### ISSUE THREAD

**Issue by LGosh** [haxball/haxball-issues#724]
Hi, I've been trying to backup stats, everything works perfect except for the restoring part. So, stats are being populated, then I have a command, for example, !download, which stringifies the data and downloads it (either in .txt, or .json, or whatever is needed). And now comes the part I've been stuck on for a while. I created a command !restore, and I couldn't make it to load the local file. I've tried a lot of stuff, such as XMLHttpRequest and what not. Could anyone help please? Thanks I appreciate it

**Comment by olegmisar** [comment]
Why doesn't XMLHttpRequest work?

**Comment by LGosh** [comment]
Gives me an 404 error, because instead of locating the file locally, it tries to locate it on haxball.com/data.txt 
I just saw somewhere that I might need to add file:/// in the path, so that might fix it right? I’ll give it a try in a little.

**Comment by LGosh** [comment]
But do you think that XML request is the best approach to this issue? Thanks

**Comment by olegmisar** [comment]
No, you should use `fetch` because it is easier to use. But if you don't know what is `Promise`, use XHR instead.

And yeah, you have to specify the full path to the file. E.g., `file:///C:/Users/User/stats.txt` or `~/stats.txt`.

**Comment by LGosh** [comment]
I know what a `Promise` is, and I tried to use `fetch`, but now I'm getting the following error on Chrome: `URL scheme "file" is not supported.` and on Firefox: `TypeError: "NetworkError when attempting to fetch resource."`. After some research on web, it says that `fetch` does not accept `file://` and `ftp://` schemes. Is this true? Is there a workaround for this?

**Comment by olegmisar** [comment]
IDK because I don't use `file` protocol in my code. You can run a simple server if you have installed either node.js or python.

For node.js
1. Install `http-server` globally:
```
npm i http-server -g
```
2. Run it in any directory:
```
http-server
```

For python 3:
```
python3 -m http.server
```

After running a server, all files in the directory will be available under `localhost:8080` URL. E.g., if you start a server in the `C:/bot` directory and it contains `stats.txt` file, you can access `stats.txt` using this URL: `localhost:8080/stats.txt`

Also, try to use `XHR`, maybe it allows `file` protocol.

**Comment by LGosh** [comment]
I installed `http-server`, and tried to access it the way you said, but now I'm getting the following:

On Firefox: `Blocked loading mixed active content “http://localhost:8080/server_stats.txt”`
On Chrome: `Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:8080/server_stats.txt with MIME type text/plain.`

I think I'm cursed for my life with this CORS thing.

Any ideas? Thanks

**Comment by LGosh** [comment]
Ok I managed to suppress all the errors and warnings, but now I'm getting an `opaque response` (empty response) when I'm trying to do `fetch` because I suppressed the `CORS` warning. Guys what could be an alternative of loading a `.txt` or `.json` file? Thanks

**Comment by saviola777** [comment]
If you just want to save the stats and later restore them, you could use local storage, for example using [localForage](https://github.com/localForage/localForage).

Shameless plug: Or you could use your plugin with the [HHM](https://github.com/saviola777/haxball-headless-manager) which gives you two handlers `onPersist()` and `onRestore(data)`, where you just return the data you want to store in `onPersist` and you get the stored data when the room is loaded the next time in `onRestore`.

**Comment by LGosh** [comment]
Thanks, I am using local storage right now, but as it's not as consistent as actually exporting and backing up, I thought to try the latter one. And didn't realize it would be so much pain for me to restore the local file. 
And thanks, I'll try out the HHM as well.

**Comment by Wolf72** [comment]
Try IndexedDB it more powerful than local storage for me

**Comment by LGosh** [comment]
@Wolf72 Would you mind showing a basic example of `IndexedDB`? Thanks

**Comment by Wolf72** [comment]
Sure, let say you want to create HaxBall database with Object Store "ScoreBoard" where you will add players and their stats by key "name" which is obviously their username. 
```
var request = window.indexedDB.open("HaxBall");
var db;

request.onupgradeneeded = function(event) {
    db = event.target.result;

    var objectStore1 = db.createObjectStore("ScoreBoard", {
        keyPath: "name"
    });
    var index1 = objectStore1.createIndex("goals", "goals", {
        unique: false
    });

};
request.onerror = function(event) {
    console.error("Error opening database");
};
request.onsuccess = function(event) {
    console.log("Loaded indexeDB.");
    db = request.result;
    db.onerror = function(event) {
        console.error("Database error: " + event.target.errorCode);
    };
}
```

So when player joins you should add him to database:
```
function addPlayer(player){
    var tx = db.transaction(["ScoreBoard"], "readwrite");
    var store = tx.objectStore("ScoreBoard");
    var playerObject={name:player, goals:0};
    store.put(temp);
}
```
let's say you want to show him his stats when he types !stats
function playerStats(player){
    var tx = db.transaction(["ScoreBoard"], "readonly");
    var store = tx.objectStore("ScoreBoard");

    var getRequest = store.get(player.name);
    getRequest.onsuccess = function() {
       if (getRequest.result != null){
           room.sendChat(`${player.name}` you scored ${getRequest.result.goals} goals.`,player.id);
       }
   }
}

**Comment by LGosh** [comment]
Oh my god, thanks mate! I appreciate your help and devoted time. Will definitely try it out as soon as I get home. Thank you again.

**Comment by meteus** [comment]
@LGosh Can you send me the !download code, I need that one too.

**Comment by LGosh** [comment]
@meteus Yes sure, sorry I just saw this. Here you go.

> function download(data, filename, type) {
>   var file = new Blob([data], { type: type });
>   var a = document.createElement("a"),
>     url = URL.createObjectURL(file);
>   a.href = url;
>   a.download = filename;
>   document.body.appendChild(a);
>   a.click();
>   setTimeout(function () {
>     document.body.removeChild(a);
>     window.URL.revokeObjectURL(url);
>   }, 0);
> }
> 
> function backupServerData() {
>   let data = {};
>   data.stats = stats;
>   // data.bans = bans;
> 
>   let jsonData = JSON.stringify(data);
>   download(jsonData, "server_stats.json", "application/json");
> }
> 

And whenever you call `backupServerData()` the `server_stats.json` file will be downloaded automatically.

**Comment by meteus** [comment]
@LGosh Can I get your discord name please? I want to have a private conversation with you if you don't mind. Btw, thanks for the code! :)

**Comment by LGosh** [comment]
@meteus Yeah sure. LGosh#3756
