### ISSUE TITLE
Recapcha not showing up.

### ISSUE THREAD

**Issue by FullTimeBellend** [haxball/haxball-issues#733]
A friend and I were trying to make a room but neither he or I could get the recapcha to do so. Refreshing didn't fix it neither did rebooting our browsers. I live in Bosnia and he lives in Serbia if that has anything to do with it.

**Comment by FrcAndroid** [comment]
Same here, I live in EU West and I've replicated the issue on Google Chrome and Mozilla Firefox.

Refreshed the browser several times, tested with and without adblock, deleted cookies and temporary files.

**Comment by basro** [comment]
Thanks for reporting, I'll attempt to fix it.

**Comment by basro** [comment]
Should be fixed now.
