### ISSUE TITLE
Disconnected Players take 5 minutes before they actually leave the room

### ISSUE THREAD

**Issue by haxplayer** [haxball/haxball-issues#76]
When someone disconnects(internet drops out or whatever), their player lingers in the room for 5 minutes before they finally leave.

It would be good if they instantly leave the room if they DC. Or have a shorter timeout time (30 seconds) because they are preventing another player from joining for 5 minutes and the host doesn't know they have disconnected to kick them(they might think they are AFK).

**Comment by basro** [comment]
I'll definitely improve this in the future.

**Comment by basro** [comment]
I've implemented an inactive connection timeout of 30 seconds now.
