### ISSUE TITLE
Removing the Host Player

### ISSUE THREAD

**Issue by cikolata28** [haxball/haxball-issues#765]
Hi Basro, i have an idea that can help  players to play haxball nowadays.You know, since released  the HTML5 many players could not join  rooms that has a Host Player. And i think  it can be better if all  rooms has a Headless Bot. For example when  player wants to open a room he will type the room name, set the room size after than  he can be  admin with the Bot. I think if this going to be happen more player will play Haxball.

**Comment by basro** [comment]
I wish it was this simple.

The headless host is not special, what is special is that the rooms are often hosted in VPS that don't use NAT and don't have restrictive firewalls as home routers do.
