### ISSUE TITLE
Option for default avatars

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#766]
Hello, 

We should have an option to show default avatars. Some players dislike emojis and some people are using a tool that changes their avatar multiple times a second, which is extremely annoying.
thanks.

(also we still need return false on kick/bans please ! would really change auto rooms for the best)

**Comment by subxqns** [comment]
what do you mean with 'return false kick/bans'?

**Comment by Wazarr94** [comment]
Basically, the possibility of cancelling a ban. Even though it looks like basro needs to change things for it, it would be extremely worth it since auto rooms are the future of this game. #323

**Comment by 4tires** [comment]
> Basically, the possibility of cancelling a ban. Even though it looks like basro needs to change things for it, it would be extremely worth it since auto rooms are the future of this game. #323

You already have that [possibility](https://github.com/haxball/haxball-issues/wiki/Headless-Host#clearbanplayerid--int--void).

**Comment by Wazarr94** [comment]
Not removing a ban, cancelling a ban. This way, the player doesn't go out of the room.

**Comment by subxqns** [comment]
To prevent an admin from banning a player? I guess that'd be good

**Comment by coadra** [comment]
U dont really need that, if the room is "auto room" why´re u going to give someone admin?
Make an auto room that doesnt need human interaction and that´s the solution, you have the resources to do it

**Comment by subxqns** [comment]
Some people use headless hosts only to improve it's reach due to trouble with connections on normal hosting, not everyone wants to automatise the whole thing

**Comment by coadra** [comment]
what a bolardo

**Comment by Wazarr94** [comment]
Fixed in new update
