### ISSUE TITLE
[HELP Javascript] Prevent multiple accounts in bot

### ISSUE THREAD

**Issue by lootenant** [haxball/haxball-issues#767]
Hello,

We have a "tournament bot". Every time a player joins it creates an account based on his name.
We would like to prevent people creating more than 1 account on this particular room because of security reasons for our tournament.

It should probably be something based on the player.conn and player.auth.
For example if my first and original account is X, and then 3 days later I join with Y.
The bot kicks me.

I would be greatful if someone can code this part for us or lead us because we have almost no experience.

**Comment by 4tires** [comment]
I don't think it's possible to do something like that since I assume player.conn only detects a connection in the moment, for example when you open 2 tabs and join the same room.

And player.auth relies on the public IP, which for most people it's their communication operator that provides the public IP.

I think this problem could only be solved by a login system.

**Comment by basro** [comment]
conn relies on the public IP, auth doesn't. None of those will help with what lootenant wants.

A login system wouldn't help with this either since players would be able to make multiple accounts anyway.

I don't think lootentant's problem has any solution.

**Comment by lootenant** [comment]
Thanks for the answers, I understand.
The idea is to force the player to use the name he used at the first place and not allow him to change.

Before closing this subjetct, I would like to have your opinion again for a last time.

When a player joins, Wouldn't it be possible to link the conn to his name and store it ?
And if this conn joins with another name than the original one,, the bot kicks.

And the only way the conn is accepted by the bot is to come back with the original name ?

**Comment by basro** [comment]
conn is directly tied to the user's ip so that's not going to be very effective. Most people have dynamic ip addresses that will change over time.

**Comment by 4tires** [comment]
> conn relies on the public IP, auth doesn't. None of those will help with what lootenant wants.
> 
> A login system wouldn't help with this either since players would be able to make multiple accounts anyway.
> 
> I don't think lootentant's problem has any solution.

May I suggest then modifying the wiki for the headless host "auth" function to clarify the public ID.

**Comment by lootenant** [comment]
I totally understands the reasons why it would not be very effective since people can have different ip and clear cache.
But yet I think restricting 1 name per auth or 1 name per conn would be helpful and better than the actual situation where we have nothing.

I would be really so thankful if someone who is reading this can code us that function. If not, thank you all very much for your time.

**Comment by basro** [comment]
@4tires I've added some explanation.

@lootenant then what you want is possible, I wont be the one making the implementation for you, I wish you luck.

**Comment by lootenant** [comment]
Happy to learn it's possible. Thank you again for your explanations, I'll be waiting here with the hope someone can help us about this restriction.

**Comment by saviola777** [comment]
Guess something like [this](https://github.com/saviola777/hhm-plugins/blob/development/src/sav/force-same-name.js) (untested). The important part is in the `onPlayerJoinHandler` function. If you run this with haxroomie it will also store player auths and conns between room restarts.

**Comment by lootenant** [comment]
@saviola777 Thank you very much for your contribution to this issue and to Haxball in general. I'll try this asap and adapt it to our situation.

**Comment by lootenant** [comment]
@saviola777 If would like to run this code with a condition. In our case when a player gets muted we push in stats, Stats[player.name].mute = true.

When I apply this to the code I have an error saying : Cannot read property of undefined

I would like to apply your code to muted players to prevent mute evading by changing names.
Could be please help me about that condition ?

**Comment by saviola777** [comment]
I don't mind helping you, but let's continue this discussion via discord, you can find me on the [haxroomie discord](https://discord.gg/TeJAEWu).
