### ISSUE TITLE
Extrapolation is a forced crutch

### ISSUE THREAD

**Issue by Jacob-1998** [haxball/haxball-issues#768]
Extrapolation is a big problem, heres why:

It gives a massive advantage to players who use it. The best players often use around 100 extrapolation. The reason for this is simple, extrapolation does make micro-movements harder to read (shaky), but its worth the price, because you see longer/heavier movements of players MUCH earlier, which is the information that is really most valuable if your playing at any decent level.

This allows you to press while always seeing the 'worst case scenario' (the heavy/longer movement the opponent could use to kick the ball past you), which makes it very easy to press and always go as close as possible WHILE never moving too close that you won't reach 'the worst case scenario' if you opponent uses that, because you are always seeing the heavy/longer movements much earlier.

The same applies to passing, when you are reading your teammates movement, you see him turn to you heavy/longer, and you see this before it happens (and with experience you know exactly what situations they will do it), so you give yourself more time to adjust your positioning so that you give the perfect pass back or the perfect angle to shoot. Most passes come from heavy/longer movements of your teammate when they turn to you, its just the nature of the game at a reasonable level.

The problem is that its not fun playing with a shaky game. It makes you a better player over people not using extrapolation, pretty much by synthetic cheating, but at the cost of having a fun and smooth gameplay.

Haxball shouldn't be like this, it should be a level-playing field for everybody. Extrapolation was introduced to help the players with input delay, but the amount of players who have that problem is a small minority. By adding extrapolation you have added a big issue that affects ALL players. We have to use annoying extrapolation or play with a huge disadvantage.

So trying to fix a small problem, has caused a new bigger problem. So the right thing to do would be to reverse the failed solution that is extrapolation, and find another way to fix input delay for the minority of players who have it.. And if you can't find a new fix, removing extrapolation is still the right thing to do because it affects everybody and it not the real true Haxball gameplay we are playing anymore. Qualities like anticipation and reading the game are not an advantage when people can use extrapolation to get perfect anticipation and reading, using no /thinking/game sense of their own.

Over 75% of competitive players are using extrapolation to gain its advantages despite the shaky gameplay it provides, as you can see here:
https://i.ibb.co/PCm3qp6/448ef7c93a19fdcaa19bd8f532dfdca2.png

It is something we have to use to keep up, but don't like using because its shaky gameplay. It is also not real Haxball anymore, its pretty much playing Haxball with synthetic cheats against other cheats.

Playing without extrapolation vs players with extrapolation, is like walking with a broken leg without crutches. Your forcing people to use crutches to be even, instead of allowing us all to walk normally like we used to before extrapolation (don't have to deal with shakiness or disadvantage, your making us pick our poison right now).

**Comment by basro** [comment]
No need to post the same thing twice, you coulld have added on your previous issue. #755
