### ISSUE TITLE
Fast help

### ISSUE THREAD

**Issue by pog666** [haxball/haxball-issues#769]
Can somebody give me or tell me how to know all the settings of this map if this is possible please?
http://haxmaps.com/map/3306

**Comment by subxqns** [comment]
what do you mean? if you open the file in a text editor you can see everything there is

**Comment by pog666** [comment]
Forget that, now i have another problem. When i put this script on headless, there is an error message: SyntaxError: Unexpected 'o' at line 1 column 3 of the JSON5 data. Still to read: "object Object]"

How to fix that with this script ? (i'm bad at coding)

`/* VARIABLES */

/* ROOM */

const roomName = "🏐 VOLLEYBALL 2D [24/7]";
const botName = "VolleyBot";
const maxPlayers = 9;
const roomPublic = true;
const geo = [{"code": "HT", "lat": 51.9, "lon": 19.1}];

const room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: botName, geo: geo[0] });

const scoreLimit = 8;
const timeLimit = 0;
room.setScoreLimit(scoreLimit);
room.setTimeLimit(timeLimit);
room.setTeamsLock(true);

var volleyMap = {"name":"volleyball from HaxMaps","width":420,"height":200,"spawnDistance":299,"bg":{"type":"hockey","width":0,"height":0,"kickOffRadius":0,"cornerRadius":0},"vertexes":[{"x":-5,"y":20,"trait":"net"},{"x":5,"y":20,"trait":"net"},{"x":-3,"y":120,"trait":"net"},{"x":100,"y":200,"trait":"kickOffBarrier"},{"x":100,"y":-200,"trait":"kickOffBarrier"},{"x":-100,"y":200,"trait":"kickOffBarrier"},{"x":-100,"y":-200,"trait":"kickOffBarrier"},{"x":-385,"y":100,"trait":"line"},{"x":-400,"y":125,"trait":"line"},{"x":400,"y":125,"trait":"line"},{"x":385,"y":100,"trait":"line"},{"x":-70,"y":-50,"trait":"line"},{"x":70,"y":-50,"trait":"line"},{"x":3,"y":120,"trait":"net"},{"x":-385,"y":103,"trait":"line","color":"CFB795"},{"x":385,"y":103,"trait":"line","color":"CFB795"},{"x":-387,"y":106,"trait":"line","color":"CFB795"},{"x":387,"y":106,"trait":"line","color":"CFB795"},{"x":-388,"y":109,"trait":"line","color":"CFB795"},{"x":388,"y":109,"trait":"line","color":"CFB795"},{"x":-391,"y":112,"trait":"line","color":"CFB795"},{"x":391,"y":112,"trait":"line","color":"CFB795"},{"x":-394,"y":115,"trait":"line","color":"CFB795"},{"x":394,"y":115,"trait":"line","color":"CFB795"},{"x":-396,"y":118,"trait":"line","color":"CFB795"},{"x":396,"y":118,"trait":"line","color":"CFB795"},{"x":-396,"y":121,"trait":"line","color":"CFB795"},{"x":396,"y":121,"trait":"line","color":"CFB795"},{"x":-396,"y":122,"trait":"line","color":"CFB795"},{"x":396,"y":122,"trait":"line","color":"CFB795"},{"x":3,"y":20,"trait":"net"},{"x":0,"y":23,"trait":"net","color":"FFFFFF"},{"trait":"line","x":100,"y":101},{"trait":"line","x":106,"y":124},{"trait":"line","x":-100,"y":101},{"trait":"line","x":-106,"y":124},{"x":-3,"y":20,"trait":"net"}],"segments":[{"v0":0,"v1":1,"trait":"net"},{"v0":3,"v1":4,"trait":"kickOffBarrier","cGroup":["redKO"]},{"v0":5,"v1":6,"trait":"kickOffBarrier","cGroup":["blueKO"]},{"v0":0,"v1":11,"trait":"kickOffBarrier","cGroup":["redKO"]},{"v0":1,"v1":12,"trait":"kickOffBarrier","cGroup":["blueKO"]},{"v0":8,"v1":9,"trait":"line"},{"v0":10,"v1":7,"trait":"line"},{"v0":15,"v1":14,"trait":"line","y":103,"color":"CFB795"},{"v0":17,"v1":16,"trait":"line","y":106,"color":"CFB795"},{"v0":19,"v1":18,"trait":"line","y":109,"color":"CFB795"},{"v0":21,"v1":20,"trait":"line","y":112,"color":"CFB795"},{"v0":23,"v1":22,"trait":"line","y":115,"color":"CFB795"},{"v0":25,"v1":24,"trait":"line","y":118,"color":"CFB795"},{"v0":27,"v1":26,"trait":"line","y":121,"color":"CFB795"},{"v0":29,"v1":28,"trait":"line","y":122,"color":"CFB795"},{"vis":true,"color":"FFFFFF","trait":"line","v0":8,"v1":7},{"vis":true,"color":"FFFFFF","trait":"line","v0":10,"v1":9},{"vis":true,"color":"FFFFFF","trait":"line","v0":32,"v1":33},{"vis":true,"color":"FFFFFF","trait":"line","v0":34,"v1":35}],"goals":[{"p0":[0,114],"p1":[420,114],"team":"blue"},{"p0":[0,114],"p1":[-420,114],"team":"red"}],"discs":[{"pos":[0,25],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,35],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,45],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,55],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,65],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,75],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,85],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,95],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,105],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,115],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,-100000],"trait":"ballPush"}],"planes":[{"normal":[0,-1],"dist":-210,"cGroup":["ball"],"bCoef":0},{"normal":[0,1],"dist":-50,"cMask":["red"],"bCoef":-1},{"normal":[0,1],"dist":-50,"cMask":["blue"],"bCoef":-1},{"normal":[0,-1],"dist":-125,"cMask":["red","blue","ball"],"bCoef":0},{"normal":[1,0],"dist":0,"cMask":["blue"],"bCoef":0.1},{"normal":[-1,0],"dist":0,"cMask":["red"],"bCoef":0.1},{"normal":[1,0],"dist":-420,"cMask":["ball","red","blue"],"bCoef":0.6},{"normal":[-1,0],"dist":-420,"cMask":["ball","red","blue"],"bCoef":0.6},{"normal":[0,1],"dist":-199790,"cGroup":["ball"],"bCoef":0},{"normal":[-1,0],"dist":-100000,"cGroup":["ball"],"bCoef":0},{"normal":[1,0],"dist":-100000,"cGroup":["ball"],"bCoef":0}],"playerPhysics":{"bCoef":0.5,"invMass":0.5,"damping":0.85,"acceleration":0.5,"kickingAcceleration":0.07,"kickingDamping":0.96,"kickStrength":20},"ballPhysics":{"radius":10,"bCoef":1,"invMass":0.9,"damping":0.98,"color":"FFFFFF","cMask":["wall"],"cGroup":["ball"]},"traits":{"net":{"vis":true,"bCoef":0,"invMass":0,"cMask":["ball"]},"line":{"vis":true,"cMask":[""],"color":"FFFFFF"},"redline":{"vis":true,"cMask":[""],"color":"FF4A4A"},"blueline":{"vis":true,"cMask":[""],"color":"6782FE"},"kickOffBarrier":{"vis":false,"bCoef":0.1,"cGroup":["redKO","blueKO"],"cMask":["red","blue"]},"ballPush":{"radius":100000,"invMass":60,"cMask":["ball"],"bCoef":0,"color":"FFFFFFFF"}}};
room.setCustomStadium(volleyMap);

room.onStadiumChange = function (newStadiumName, byPlayer) {
  if (newStadiumName != "volleyball from HaxMaps") {
    room.setCustomStadium(volleyMap);
  }
}

var adminPassword = 100 + getRandomInt(900);
console.log("adminPassword : " + adminPassword);

/* OPTIONS */

var drawTimeLimit = Infinity;

/* PLAYERS */

const Team = { SPECTATORS: 0, RED: 1, BLUE: 2 };
var players;
var teamR;
var teamB;
var teamS;

/* GAME */

var lastPlayersTouched;
var point = [{"x": 0, "y": 0}, {"x": 0, "y": 0}];
var ballSpeed;
var goldenGoal = false;

/* AUXILIARY */

var checkTimeVariable = false;

/* FUNCTIONS */

/* AUXILIARY FUNCTIONS */

function getRandomInt(max) { // return random number from 0 to max-1
    return Math.floor(Math.random() * Math.floor(max)); 
}

function arrayMin(arr) {
    var len = arr.length;
    var min = Infinity;
    while (len--) {
        if (arr[len] < min) {
            min = arr[len];
        }
    }
    return min;
}

function getTime(scores) {
    return "[" + Math.floor(Math.floor(scores.time/60)/10).toString() + Math.floor(Math.floor(scores.time/60)%10).toString() + ":" + Math.floor(Math.floor(scores.time - (Math.floor(scores.time/60) * 60))/10).toString() + Math.floor(Math.floor(scores.time - (Math.floor(scores.time/60) * 60))%10).toString() + "]"
}

function pointDistance(p1, p2) {
    var d1 = p1.x - p2.x;
    var d2 = p1.y - p2.y;
    return Math.sqrt(d1 * d1 + d2 * d2);
}

/* GAME FUNCTIONS */

function checkTime() {
    const scores = room.getScores();
    if (Math.abs(scores.time - scores.timeLimit) <= 0.01 && scores.timeLimit != 0) {
        if (scores.red != scores.blue) {
            if (checkTimeVariable == false) {
                checkTimeVariable = true;
                setTimeout(() => { checkTimeVariable = false; }, 3000);
                scores.red > scores.blue ? endGame(Team.RED) : endGame(Team.BLUE);
                setTimeout(() => { room.stopGame(); }, 2000);
            }
            return;
        }
        goldenGoal = true;
        room.sendChat("⚽ First goal wins! ⚽");
    }
    if (Math.abs(drawTimeLimit * 60 - scores.time - 60) <= 0.01 && players.length > 2) {
        if (checkTimeVariable == false) {
            checkTimeVariable = true;
            setTimeout(() => { checkTimeVariable = false; }, 10);
            room.sendChat("⌛ 60 seconds left until draw! ⌛");
        }
    }
    if (Math.abs(scores.time - drawTimeLimit * 60) <= 0.01 && players.length > 2) {
        if (checkTimeVariable == false) {
            checkTimeVariable = true;
            setTimeout(() => { checkTimeVariable = false; }, 10);
            endGame(Team.SPECTATORS);
            room.stopGame();
            goldenGoal = false;
        }
    }
}

function endGame(winner) { // no stopGame() function in it
    const scores = room.getScores();
    if (winner == Team.RED) {
        room.sendChat("🔴 Red Team won " + scores.red + "-" + scores.blue + "!");
    }
    else if (winner == Team.BLUE) {
        room.sendChat("🔵 Blue Team won " + scores.blue + "-" + scores.red + "!");
    }
    else {
        room.sendChat("💤 Draw limit reached! 💤");
    }
}

/* PLAYER FUNCTIONS */

function updateTeams() {
    players = room.getPlayerList().filter((player) => player.id != 0);
    teamR = players.filter(p => p.team === Team.RED);
    teamB = players.filter(p => p.team === Team.BLUE);
    teamS = players.filter(p => p.team === Team.SPECTATORS);
}

function updateAdmins() {
    if (players.length == 0 || players.find((player) => player.admin) != null) {
        return;
    }
    var copie = []; 
    players.forEach(function(element) { copie.push(element.id); });
    room.setPlayerAdmin(arrayMin(copie), true); // Give admin to the player who's played the longest on the room
}

/* STATS FUNCTIONS */

function getStats() {
    const ballPosition = room.getBallPosition();
    point[1] = point[0];
    point[0] = ballPosition;
    ballSpeed = (pointDistance(point[0], point[1]) * 60 * 60 * 60)/15000;
}

/* EVENTS */

/* PLAYER MOVEMENT */

room.onPlayerJoin = function(player) {
    room.sendChat("[PM] 👋 Welcome " + player.name + " ! This 24/7 host is for a community. Discord: https://discord.gg/6V5prAK ! [RULES: 1 TOUCH PER PLAYER, 4 PASSES MAXIMUM]", player.id);
    updateTeams();
    updateAdmins();
}

room.onPlayerTeamChange = function(changedPlayer, byPlayer) {
    if (changedPlayer.id == 0) {
        room.setPlayerTeam(0, Team.SPECTATORS);
        return;
    }
    updateTeams();
}

room.onPlayerLeave = function(player) {
    updateTeams();
    updateAdmins();
}

room.onPlayerKicked = function(kickedPlayer, reason, ban, byPlayer) {
}

/* PLAYER ACTIVITY */

room.onPlayerChat = function(player, message) {
    message = message.split(" ");
    if (["!claim"].includes(message[0].toLowerCase())) {
        if (message[1] == adminPassword) {
            room.setPlayerAdmin(player.id, true);
            adminPassword = 100 + getRandomInt(900);
            console.log("adminPassword : " + adminPassword);
        }
    }
    if (message[0][0] == "!") {
        return false;
    }
}

room.onPlayerActivity = function(player) {
}

room.onPlayerBallKick = function(player) {
    if (lastPlayersTouched[0] == null || player.id != lastPlayersTouched[0].id) {
        lastPlayersTouched[1] = lastPlayersTouched[0];
        lastPlayersTouched[0] = player;
    }
}

/* GAME MANAGEMENT */

room.onGameStart = function(byPlayer) {
    goldenGoal = false;
    lastPlayersTouched = [null, null];
}

room.onGameStop = function(byPlayer) {
}

room.onGamePause = function(byPlayer) {
}

room.onGameUnpause = function(byPlayer) {
}

room.onTeamGoal = function(team) {
    const scores = room.getScores();
    if (lastPlayersTouched[0] != null && lastPlayersTouched[0].team == team) {
        if (lastPlayersTouched[1] != null && lastPlayersTouched[1].team == team) {
            room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
        }
        else {
            room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
                } 
    }
    else {
        room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
    }
    if (scores.red == scores.scoreLimit || scores.blue == scores.scoreLimit || goldenGoal == true) {
        endGame(team);
        goldenGoal = false;
        setTimeout(() => { room.stopGame(); }, 1000);
    }
}

room.onPositionsReset = function() {
    lastPlayersTouched = [null, null];
}

/* MISCELLANEOUS */

room.onRoomLink = function(url) {
}

room.onPlayerAdminChange = function(changedPlayer, byPlayer) {
}

room.onStadiumChange = function(newStadiumName, byPlayer) {
}

room.onGameTick = function() {
    checkTime();
    getStats();
}`

**Comment by TurboFalafel** [comment]
Map text should be between ``, ie:

var map = `{"name":"volleyball from HaxMaps"}`;

**Comment by Wazarr94** [comment]
You need to put your map code between `` (Altgr + 7). The map variable needs to be a string.

Also, in the code, use the existing events, you don't need to create one (you have 2 onStadiumChange event which might be troublesome).

```
/* VARIABLES */

/* ROOM */

const roomName = "🏐 VOLLEYBALL 2D [24/7]";
const botName = "VolleyBot";
const maxPlayers = 9;
const roomPublic = true;
const geo = [{"code": "HT", "lat": 51.9, "lon": 19.1}];

const room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: botName, geo: geo[0] });

const scoreLimit = 8;
const timeLimit = 0;
room.setScoreLimit(scoreLimit);
room.setTimeLimit(timeLimit);
room.setTeamsLock(true);

var volleyMap = `{"name":"volleyball from HaxMaps","width":420,"height":200,"spawnDistance":299,"bg":{"type":"hockey","width":0,"height":0,"kickOffRadius":0,"cornerRadius":0},"vertexes":[{"x":-5,"y":20,"trait":"net"},{"x":5,"y":20,"trait":"net"},{"x":-3,"y":120,"trait":"net"},{"x":100,"y":200,"trait":"kickOffBarrier"},{"x":100,"y":-200,"trait":"kickOffBarrier"},{"x":-100,"y":200,"trait":"kickOffBarrier"},{"x":-100,"y":-200,"trait":"kickOffBarrier"},{"x":-385,"y":100,"trait":"line"},{"x":-400,"y":125,"trait":"line"},{"x":400,"y":125,"trait":"line"},{"x":385,"y":100,"trait":"line"},{"x":-70,"y":-50,"trait":"line"},{"x":70,"y":-50,"trait":"line"},{"x":3,"y":120,"trait":"net"},{"x":-385,"y":103,"trait":"line","color":"CFB795"},{"x":385,"y":103,"trait":"line","color":"CFB795"},{"x":-387,"y":106,"trait":"line","color":"CFB795"},{"x":387,"y":106,"trait":"line","color":"CFB795"},{"x":-388,"y":109,"trait":"line","color":"CFB795"},{"x":388,"y":109,"trait":"line","color":"CFB795"},{"x":-391,"y":112,"trait":"line","color":"CFB795"},{"x":391,"y":112,"trait":"line","color":"CFB795"},{"x":-394,"y":115,"trait":"line","color":"CFB795"},{"x":394,"y":115,"trait":"line","color":"CFB795"},{"x":-396,"y":118,"trait":"line","color":"CFB795"},{"x":396,"y":118,"trait":"line","color":"CFB795"},{"x":-396,"y":121,"trait":"line","color":"CFB795"},{"x":396,"y":121,"trait":"line","color":"CFB795"},{"x":-396,"y":122,"trait":"line","color":"CFB795"},{"x":396,"y":122,"trait":"line","color":"CFB795"},{"x":3,"y":20,"trait":"net"},{"x":0,"y":23,"trait":"net","color":"FFFFFF"},{"trait":"line","x":100,"y":101},{"trait":"line","x":106,"y":124},{"trait":"line","x":-100,"y":101},{"trait":"line","x":-106,"y":124},{"x":-3,"y":20,"trait":"net"}],"segments":[{"v0":0,"v1":1,"trait":"net"},{"v0":3,"v1":4,"trait":"kickOffBarrier","cGroup":["redKO"]},{"v0":5,"v1":6,"trait":"kickOffBarrier","cGroup":["blueKO"]},{"v0":0,"v1":11,"trait":"kickOffBarrier","cGroup":["redKO"]},{"v0":1,"v1":12,"trait":"kickOffBarrier","cGroup":["blueKO"]},{"v0":8,"v1":9,"trait":"line"},{"v0":10,"v1":7,"trait":"line"},{"v0":15,"v1":14,"trait":"line","y":103,"color":"CFB795"},{"v0":17,"v1":16,"trait":"line","y":106,"color":"CFB795"},{"v0":19,"v1":18,"trait":"line","y":109,"color":"CFB795"},{"v0":21,"v1":20,"trait":"line","y":112,"color":"CFB795"},{"v0":23,"v1":22,"trait":"line","y":115,"color":"CFB795"},{"v0":25,"v1":24,"trait":"line","y":118,"color":"CFB795"},{"v0":27,"v1":26,"trait":"line","y":121,"color":"CFB795"},{"v0":29,"v1":28,"trait":"line","y":122,"color":"CFB795"},{"vis":true,"color":"FFFFFF","trait":"line","v0":8,"v1":7},{"vis":true,"color":"FFFFFF","trait":"line","v0":10,"v1":9},{"vis":true,"color":"FFFFFF","trait":"line","v0":32,"v1":33},{"vis":true,"color":"FFFFFF","trait":"line","v0":34,"v1":35}],"goals":[{"p0":[0,114],"p1":[420,114],"team":"blue"},{"p0":[0,114],"p1":[-420,114],"team":"red"}],"discs":[{"pos":[0,25],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,35],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,45],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,55],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,65],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,75],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,85],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,95],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,105],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,115],"trait":"net","radius":4,"color":"6D6C6B"},{"pos":[0,-100000],"trait":"ballPush"}],"planes":[{"normal":[0,-1],"dist":-210,"cGroup":["ball"],"bCoef":0},{"normal":[0,1],"dist":-50,"cMask":["red"],"bCoef":-1},{"normal":[0,1],"dist":-50,"cMask":["blue"],"bCoef":-1},{"normal":[0,-1],"dist":-125,"cMask":["red","blue","ball"],"bCoef":0},{"normal":[1,0],"dist":0,"cMask":["blue"],"bCoef":0.1},{"normal":[-1,0],"dist":0,"cMask":["red"],"bCoef":0.1},{"normal":[1,0],"dist":-420,"cMask":["ball","red","blue"],"bCoef":0.6},{"normal":[-1,0],"dist":-420,"cMask":["ball","red","blue"],"bCoef":0.6},{"normal":[0,1],"dist":-199790,"cGroup":["ball"],"bCoef":0},{"normal":[-1,0],"dist":-100000,"cGroup":["ball"],"bCoef":0},{"normal":[1,0],"dist":-100000,"cGroup":["ball"],"bCoef":0}],"playerPhysics":{"bCoef":0.5,"invMass":0.5,"damping":0.85,"acceleration":0.5,"kickingAcceleration":0.07,"kickingDamping":0.96,"kickStrength":20},"ballPhysics":{"radius":10,"bCoef":1,"invMass":0.9,"damping":0.98,"color":"FFFFFF","cMask":["wall"],"cGroup":["ball"]},"traits":{"net":{"vis":true,"bCoef":0,"invMass":0,"cMask":["ball"]},"line":{"vis":true,"cMask":[""],"color":"FFFFFF"},"redline":{"vis":true,"cMask":[""],"color":"FF4A4A"},"blueline":{"vis":true,"cMask":[""],"color":"6782FE"},"kickOffBarrier":{"vis":false,"bCoef":0.1,"cGroup":["redKO","blueKO"],"cMask":["red","blue"]},"ballPush":{"radius":100000,"invMass":60,"cMask":["ball"],"bCoef":0,"color":"FFFFFFFF"}}}`;
room.setCustomStadium(volleyMap);

var adminPassword = 100 + getRandomInt(900);
console.log("adminPassword : " + adminPassword);

/* OPTIONS */

var drawTimeLimit = Infinity;

/* PLAYERS */

const Team = { SPECTATORS: 0, RED: 1, BLUE: 2 };
var players;
var teamR;
var teamB;
var teamS;

/* GAME */

var lastPlayersTouched;
var point = [{"x": 0, "y": 0}, {"x": 0, "y": 0}];
var ballSpeed;
var goldenGoal = false;

/* AUXILIARY */

var checkTimeVariable = false;

/* FUNCTIONS */

/* AUXILIARY FUNCTIONS */

function getRandomInt(max) { // return random number from 0 to max-1
return Math.floor(Math.random() * Math.floor(max));
}

function arrayMin(arr) {
var len = arr.length;
var min = Infinity;
while (len--) {
if (arr[len] < min) {
min = arr[len];
}
}
return min;
}

function getTime(scores) {
return "[" + Math.floor(Math.floor(scores.time/60)/10).toString() + Math.floor(Math.floor(scores.time/60)%10).toString() + ":" + Math.floor(Math.floor(scores.time - (Math.floor(scores.time/60) * 60))/10).toString() + Math.floor(Math.floor(scores.time - (Math.floor(scores.time/60) * 60))%10).toString() + "]"
}

function pointDistance(p1, p2) {
var d1 = p1.x - p2.x;
var d2 = p1.y - p2.y;
return Math.sqrt(d1 * d1 + d2 * d2);
}

/* GAME FUNCTIONS */

function checkTime() {
const scores = room.getScores();
if (Math.abs(scores.time - scores.timeLimit) <= 0.01 && scores.timeLimit != 0) {
if (scores.red != scores.blue) {
if (checkTimeVariable == false) {
checkTimeVariable = true;
setTimeout(() => { checkTimeVariable = false; }, 3000);
scores.red > scores.blue ? endGame(Team.RED) : endGame(Team.BLUE);
setTimeout(() => { room.stopGame(); }, 2000);
}
return;
}
goldenGoal = true;
room.sendChat("⚽ First goal wins! ⚽");
}
if (Math.abs(drawTimeLimit * 60 - scores.time - 60) <= 0.01 && players.length > 2) {
if (checkTimeVariable == false) {
checkTimeVariable = true;
setTimeout(() => { checkTimeVariable = false; }, 10);
room.sendChat("⌛ 60 seconds left until draw! ⌛");
}
}
if (Math.abs(scores.time - drawTimeLimit * 60) <= 0.01 && players.length > 2) {
if (checkTimeVariable == false) {
checkTimeVariable = true;
setTimeout(() => { checkTimeVariable = false; }, 10);
endGame(Team.SPECTATORS);
room.stopGame();
goldenGoal = false;
}
}
}

function endGame(winner) { // no stopGame() function in it
const scores = room.getScores();
if (winner == Team.RED) {
room.sendChat("🔴 Red Team won " + scores.red + "-" + scores.blue + "!");
}
else if (winner == Team.BLUE) {
room.sendChat("🔵 Blue Team won " + scores.blue + "-" + scores.red + "!");
}
else {
room.sendChat("💤 Draw limit reached! 💤");
}
}

/* PLAYER FUNCTIONS */

function updateTeams() {
players = room.getPlayerList().filter((player) => player.id != 0);
teamR = players.filter(p => p.team === Team.RED);
teamB = players.filter(p => p.team === Team.BLUE);
teamS = players.filter(p => p.team === Team.SPECTATORS);
}

function updateAdmins() {
if (players.length == 0 || players.find((player) => player.admin) != null) {
return;
}
var copie = [];
players.forEach(function(element) { copie.push(element.id); });
room.setPlayerAdmin(arrayMin(copie), true); // Give admin to the player who's played the longest on the room
}

/* STATS FUNCTIONS */

function getStats() {
const ballPosition = room.getBallPosition();
point[1] = point[0];
point[0] = ballPosition;
ballSpeed = (pointDistance(point[0], point[1]) * 60 * 60 * 60)/15000;
}

/* EVENTS */

/* PLAYER MOVEMENT */

room.onPlayerJoin = function(player) {
room.sendChat("[PM] 👋 Welcome " + player.name + " ! This 24/7 host is for a community. Discord: https://discord.gg/6V5prAK ! [RULES: 1 TOUCH PER PLAYER, 4 PASSES MAXIMUM]", player.id);
updateTeams();
updateAdmins();
}

room.onPlayerTeamChange = function(changedPlayer, byPlayer) {
if (changedPlayer.id == 0) {
room.setPlayerTeam(0, Team.SPECTATORS);
return;
}
updateTeams();
}

room.onPlayerLeave = function(player) {
updateTeams();
updateAdmins();
}

room.onPlayerKicked = function(kickedPlayer, reason, ban, byPlayer) {
}

/* PLAYER ACTIVITY */

room.onPlayerChat = function(player, message) {
message = message.split(" ");
if (["!claim"].includes(message[0].toLowerCase())) {
if (message[1] == adminPassword) {
room.setPlayerAdmin(player.id, true);
adminPassword = 100 + getRandomInt(900);
console.log("adminPassword : " + adminPassword);
}
}
if (message[0][0] == "!") {
return false;
}
}

room.onPlayerActivity = function(player) {
}

room.onPlayerBallKick = function(player) {
if (lastPlayersTouched[0] == null || player.id != lastPlayersTouched[0].id) {
lastPlayersTouched[1] = lastPlayersTouched[0];
lastPlayersTouched[0] = player;
}
}

/* GAME MANAGEMENT */

room.onGameStart = function(byPlayer) {
goldenGoal = false;
lastPlayersTouched = [null, null];
}

room.onGameStop = function(byPlayer) {
}

room.onGamePause = function(byPlayer) {
}

room.onGameUnpause = function(byPlayer) {
}

room.onTeamGoal = function(team) {
const scores = room.getScores();
if (lastPlayersTouched[0] != null && lastPlayersTouched[0].team == team) {
if (lastPlayersTouched[1] != null && lastPlayersTouched[1].team == team) {
room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
}
else {
room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
}
}
else {
room.sendChat("🏐 " + getTime(scores) + " Point for " + (team == Team.RED ? "🔴" : "🔵"));
}
if (scores.red == scores.scoreLimit || scores.blue == scores.scoreLimit || goldenGoal == true) {
endGame(team);
goldenGoal = false;
setTimeout(() => { room.stopGame(); }, 1000);
}
}

room.onPositionsReset = function() {
lastPlayersTouched = [null, null];
}

/* MISCELLANEOUS */

room.onRoomLink = function(url) {
}

room.onPlayerAdminChange = function(changedPlayer, byPlayer) {
}

room.onStadiumChange = function (newStadiumName, byPlayer) {
if (newStadiumName != "volleyball from HaxMaps") {
room.setCustomStadium(volleyMap);
}
}

room.onGameTick = function() {
checkTime();
getStats();
}
```

**Comment by pog666** [comment]
Thanks!

**Comment by Ansu1Fati** [comment]
hi i have red lines while my ping is good i wish there was something i could do i even reseted my laptop
