### ISSUE TITLE
when i open in new update

### ISSUE THREAD

**Issue by Ahmedessam1bas** [haxball/haxball-issues#77]
![image](https://user-images.githubusercontent.com/33099725/32134595-67876494-bbf0-11e7-88a4-fbf2fb60f523.png) what this problem ?

**Comment by basro** [comment]
By the looks of it you have internet download manager installed, some other user had problems with it. Try disabling it.
Have a look at: #36

**Comment by Ahmedessam1bas** [comment]
ok i will try disabling it and say to you done or no ♥ thx

**Comment by Ahmedessam1bas** [comment]
Worked
