### ISSUE TITLE
(BOT) typing number to choose spec

### ISSUE THREAD

**Issue by Faggioni50** [haxball/haxball-issues#772]
hello, I am trying to make it easy in room for the guy who is choosing and this is why i need a function like this one : the guy who is first in his team, who should choose, when he types 3 for example, the bot puts automatically the player who is in the 3rd place (whithout counting the host), in his team, and of course only when the first guy types the bot makes move not when others type.
I have seen things similar.

If someone who has experience in coding could share this function I will be thankful.

**Comment by AnddyAnddy** [comment]
The room.getPlayerList().filter ((p) => p.id != 0 && p.team == 0) ; will give you the spectators in the good order in an array (iterable element), that means the top spec will be the 0th element of the array, the third spec will be the 2nd element... Till the length of the array.

**Comment by 4tires** [comment]
With @AnddyAnddy's snippet I've done the full one:

`var roomName = "AUTO";
var maxPlayers = 12;
var roomPublic = true;
var playerName = "Host";
 
/* SETTINGS */
 
var Team = {
    SPECTATORS: 0,
    RED: 1,
    BLUE: 2
};

var room = HBInit({ roomName: roomName, maxPlayers: maxPlayers, public: roomPublic, playerName: playerName});
    room.setScoreLimit(3);
    room.setTimeLimit(3);

room.onPlayerChat = function (player, message) {
	if (message[0] === "!") {
		var playersInSpectators = room.getPlayerList().filter ((p) => p.id != 0 && p.team == 0);
		var playerOrder = message[1]-1;
		room.setPlayerTeam(playersInSpectators[playerOrder].id, player.team);
	}
}`

Be aware that it can give you errors

**Comment by Faggioni50** [comment]
thank you fellas for sharing

**Comment by Wazarr94** [comment]
The bot using this system is mine and u can grab it :
https://github.com/Wazarr94/haxball_bot/blob/master/Level_4/HaxBot_v4.js
