### ISSUE TITLE
Broken nickname autocompletion

### ISSUE THREAD

**Issue by olegmisar** [haxball/haxball-issues#777]
The nickname autocompletion (when pressing "@") has been broken since it was released. It autocompletes the right nicknames but the order is strange, it is not relevant.

For example, there are two players in the room: Oso, and Hostinho. When I type "@os" it shows "Hostinho" first, and then "Oso". This is not the desired behaviour.

I propose to use something known as **fuzzy search**. There are plenty of javascript libraries which implement fuzzy search. The simplest I found is [this](https://github.com/wouter2203/fuzzy-search) one. 

## Browser version
You can just copy paste the `FuzzySearch.js` file from `dist/` to your project, add `script` tag in `index.html`, and use it like this:
```js
// `names` is of type `string[]` and query is of type `string`
function searchPlayerNames(names, query) {
  return new FuzzySearch(names, { caseSensitive: false, sort: true }).search(query)
}
```

## Npm version
If you use npm, you can visit [this page](https://www.npmjs.com/package/fuzzy-search). Then do the same as in "Browser version" section (above).

**Comment by olegmisar** [comment]
Hey, @basro. When is this going to be fixed? I think it is a fairly simple problem to fix.

**Comment by basro** [comment]
I don't have a schedule.

**Comment by basro** [comment]
Nicknames now are sorted by match size and how early they appear in the string. Smaller and leftmost matches are first.
