### ISSUE TITLE
Imput problem

### ISSUE THREAD

**Issue by Hangoy** [haxball/haxball-issues#783]
I play with the arrows and i can't do three imputs at the same time, for example i can't go in diagonal and shot simultaneously. With the wasd control there is no problem.

**Comment by saviola777** [comment]
This is related to key rollover and [key jamming/ghosting](https://en.wikipedia.org/wiki/Rollover_(key)#Key_jamming_and_ghosting), to solve this you need a keyboard which supports three key rollover for all keys, which most gaming keyboards do, I believe.

**Comment by Hangoy** [comment]
Thanks, it works with x.
