### ISSUE TITLE
Issues with parser blocking and cross site

### ISSUE THREAD

**Issue by wwiifanatic** [haxball/haxball-issues#784]
![Screenshot (103)](https://user-images.githubusercontent.com/52607770/60759564-2c447a80-9ff5-11e9-9339-108028104320.png)

This comes up every time I try to join and the connection immediately closes. I'm new to this so please help me.

**Comment by basro** [comment]
The text in the console is a warning that you can ignore, it doesn't affect the game and is unrelated to your connection problem.

**Comment by wwiifanatic** [comment]
So the issue with the connection immediately closing is my own poor connection?

**Comment by basro** [comment]
Could you give more details of what you are experiencing?

**Comment by wwiifanatic** [comment]
Whenever I click on the Haxball link and press to join it says the connection is closed error (4001).

**Comment by basro** [comment]
4001 means that the room you are trying to join no longer exists.
What you are clicking is a link to a specific room, those links expire when the room is closed, you can tell them apart because of the ?c=roomcode at the end of the link.

**Comment by basro** [comment]
I should in the future show a text message explaining that, instead of just displaying 4001
