### ISSUE TITLE
Chat Filter

### ISSUE THREAD

**Issue by vulonviing** [haxball/haxball-issues#785]
I need chat filter commands. When someone write bad thing like "fu*k" "idi*t" "m*therf*cker" end etc. bot must hide this message. I repeat; but must hide, not ban.

**Comment by CupBonk** [comment]
room.onPlayerChat = function(player, message) {
if(message=="fuck"){
return false;
}
}

**Comment by vulonviing** [comment]
yes it works but i need more.

i mean, this command just affect "fuck"
when someone write "fuck you", "clouds so beauty, fuck it." or "fuck bla bla bla" bot must detain and hide msg.

and ofc, admins must not affect from that.

**Comment by alebcj** [comment]
Hi, you could use an Array with certain word, and then check if message from player contains any of these words in array, and set the return false, as Cup did.
I`ve worked on sth similar with chinese characters and it is working.

**Comment by vulonviing** [comment]
Can you give me a example button please?

**Comment by raoglu** [comment]
function x (player, message){

var filter = [/fuck/i, /cock/i, /chuck/i, /etc/i];

for (i=0;i<filter.length;i++){
  var result=message.search(filter[i]); //if it doesnt find it returns -1
   if (result!=-1)
     return false;
}
}

**Comment by alebcj** [comment]
thanks raoglu

**Comment by vulonviing** [comment]
yes its great! tahnx
