### ISSUE TITLE
chat slow mode

### ISSUE THREAD

**Issue by vulonviing** [haxball/haxball-issues#788]
I have spam filter inside my bot but its not affective because bot always kick innocent players. So, clear fix is slow mode. Wıth a command, like "!slowmode", chat must switch to slow mode and no one souldnt send msg within 2 sc. 

And ofc admins shouldnt affect from that and when I want I should close that.

Is it possible?

**Comment by coadra** [comment]
Yes it is

**Comment by emret2** [comment]
mjk
