### ISSUE TITLE
Haxball not working on firefox | Connection closed (1000)

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#791]
For a lot of rooms and a lot of players we get this message:
Connection closed (1000)

https://gyazo.com/10ea78e8785eebf1e3df84ba30728a72

**Comment by basro** [comment]
I've not been able to reproduce this.
If the problem is still happening to you, could you try disabling all extensions to see if that fixes it?

**Comment by AlucarD2211** [comment]
I tried disabling all extensions and it's same..Help pls :v
Working on chrome but not on firefox..

**Comment by basro** [comment]
Do you know of other rooms that have this problem other than the one you mentioned @AlucarD2211 ?

**Comment by AlucarD2211** [comment]
Every german's room,and some of other countries,but idc about other countries xd,want to play in luck's one :v

**Comment by basro** [comment]
Update: I think I've been able to track the bug, I believe it's caused by a change in the latest version of firefox which was released on July 9, 2019.

I'm currently working to work around it, I'll release a fix soon.

**Comment by basro** [comment]
I've uploaded the fix, refresh the site and it should now be working on Firefox again.

**Comment by AlucarD2211** [comment]
Thanks basro alot :)
It workings now,and yep when latest version of firefox released it stopped working,thanks again :)
