### ISSUE TITLE
HAXBALL AIM HACK / AVATAR HACK VIDEO (BASRO LOOK)

### ISSUE THREAD

**Issue by meteus** [haxball/haxball-issues#795]
Hey basro I got the avatar bot and aim assist for Haxball.

If you want to know how I do that shit, e-mail me: devsaiderr@gmail.com

And you said "changing javascript code doesn't give you any advantage in game" in past, see i got the advantage.

I'll give the files, and every info if you give me a one thing, I'll say that in e-mail when I receive an e-mail from you.

HERE IS THE SHOWCASE VIDEO OF THE STUFF I'VE MENTIONED ABOVE:

https://www.youtube.com/watch?v=8IBlQwZaE8c&feature=youtu.be

**SKIP TO THE 0:46** STUFF HAPPENS THERE. STUPID VIDEO PROGRAM ONLY RECORDED THE CHROME SCREEN SORRY FOR THAT.

**Comment by basro** [comment]
I don't need the files, I know exactly how such things would be done.

There's nothing I can do to stop these kinds of hacks, though I've tried making my own aim-asist in the past and concluded it's more annoying than helpful. Maybe after getting used to it it would end up being advantageous but I doubt it's very impactful overall.

There's nothing a player can do to give himself physical advantage by changing his client (for example go faster than other players is impossible), that is probably what I meant whenever I said what you read.

People making these kinds of things can give themselves a pat on their backs knowing they make the game a little worse for everyone, good job!
