### ISSUE TITLE
A headless script that logs room chat into console

### ISSUE THREAD

**Issue by bartakabstina** [haxball/haxball-issues#801]
I want that when someone writes "Cech" in the room, my console will say "playername : Cech".

I know that this is possible to make because I saw it in those Turkish sniper scripts.
Does anyone here know how to make that logging?

**Comment by saviola777** [comment]
I think what you're looking for is [`console.log`](https://developer.mozilla.org/en-US/docs/Web/API/Console/log). Simply use a `room.onPlayerChat` handler and pass the message and player to `console.log`.

**Comment by bartakabstina** [comment]
Thank you very much!

пет, 26. јул 2019. 17:12 saviola777 <notifications@github.com> је
написао/ла:
