### ISSUE TITLE
auth verification

### ISSUE THREAD

**Issue by vulonviing** [haxball/haxball-issues#802]
I just want create an auth verif system. sometimes fake people takes my friend's nickname and they join the room. I dont want that.

I want build a auth verif system. if nickname's auth is true, bot do not anything but if auth is false bot must ban fake guy.

for examp, talk about friend xxx.

```
`room.onPlayerJoin = function(player) {
  if (player.name === "xxx") {
if(player.auth === "xxx's special auth"){
;}
else
    {room.kickPlayer(player.id, "Fake.", true);
  }
}
}`
```

I build this. but it didn't work. when I use this code and someone join the room, room get crashed.

what can I do? whats the mistake?

**Comment by saviola777** [comment]
Do you get an error on the console on the headless host? Think you could simplify this to

```javascript
room.onPlayerJoin = function(player) {
    if(player.name === "xxx" && player.auth !== "xxx's special auth") {
        room.kickPlayer(player.id, "Fake.", true);}
    }
}
```

**Comment by vulonviing** [comment]
I use your variant.
```

`function fakers(){
if(player.name === "xxx" && player.auth !== "xxx's special auth") {
        room.kickPlayer(player.id, "Fake.", true);
    }
	}

room.onPlayerJoin = function(player) {
fakers();
}`
```

But still room gives crash when someone join room. 
```

ReferenceError: player is not defined   headless-min.js:48 
    at fakers (<anonymous>:5793:1)
    at room.onPlayerJoin (<anonymous>:5458:1)
    at u.Gg (headless-min.js:60)
    at L.apply (headless-min.js:99)
    at xa.Ge (headless-min.js:43)
    at xa.Pb (headless-min.js:44)
    at z.Ag (headless-min.js:59)
    at Function.wa.wa (headless-min.js:51)
    at headless-min.js:47
```

I dont understand why. What can I do?

**Comment by saviola777** [comment]
You put your code into a separate function but don't pass the player object to that function, so it can't find it.

Use `fakers(player)` instead.

**Comment by vulonviing** [comment]
Yes it works! Thanks
