### ISSUE TITLE
On tomorrows update, a huge slap in the face

### ISSUE THREAD

**Issue by mago-di-oz** [haxball/haxball-issues#805]
I might as well be open about this now as tomorrow it's all part of history

`<rant>`
öz here, creator of haxbot. Despite nobody ever having approached me to have a bot dev chat and not being part of the bot dev community you have going on here, I know you know of my existence since my bot has clearly been an inspiration for all those bots out there and for most of the questions of "how do I add X" on here.

I'm pissed that you've succumbed to those feature requests for things that could have been done without the update. Pretty much everything that sets my bot apart from the rest, you've decided to make available through the API. It had:

Collision detection through parsing popular stadiums
Macro detection by setting a kick rate limit
Avatar parsing through live parsing the hbr replay
not spammy UX thanks to Announcements, simulated by hijacking the chat, routing everything through the bot player and utilizing the ability to send chats to a specified recipient
Colored those announcements through a clientside script
That same clientside script removes the bot player
Player management through keeping ordered players, reorderPlayers is part of it

Yup, everything that's in tomorrow's update, was perfectly possible without it. I'm pissed to be met with a update that throws away a year's work on a 1 day notice. It's a huge slap in the face.

Now, I'm going to assume there is close collaboration with bot devs, because adding a function like setPlayerAvatar has to have sprung from collaboration with devs doing 6man/rambo rooms. What other use does it have? Surely players should have total control over their own avatar. Like 90% of the requests on here to date, feature requests will continue to be 90% bad ideas. Don't succumb to them. Consider whether something is perfectly possible already and in doing so stay considerate of those bot devs who are trying to keep an edge over the competition
`</rant>`

I'm happy my work has inspired bot devs and contributed to the haxball landscape today. Keep up the good work. As for me, I'm taking a break.

For more future inspiration, here's a screenshot of what's in the next pending release.

![haxmod2](https://user-images.githubusercontent.com/53398333/62006611-23058400-b143-11e9-99d2-1790781f6af3.jpg)
![haxmod](https://user-images.githubusercontent.com/53398333/62006612-23058400-b143-11e9-9960-3620ffe53802.jpg)

Here's some feature requests that make sense to me
Ability to configure more than 2 teams
Ability to set team's names (ie. "Destroyers" or "AC Milan". "Red" and "Blue" make no sense if you change colors)
Ability to end games in a draw (competitive haxball knows 2 game halves that need to be able to end)

**Comment by basro** [comment]
The stuff you made was only possible because you worked outside of what is the public API.

HaxBall is not an open source project, reverse engineering the code and doing what you did goes against my wishes. It'd be nice if people respected the wishes of the author of the game they like so much. What you did feels like a slap in the face to me.

Another important reason not to work outside of the public API (even if you don't give a shit about what my wishes are) is that things will break every time I release an update. If things like what you do become popular they becomes a counter-incentive for me to release more updates because I obviously don't like breaking the game.

**Comment by mago-di-oz** [comment]
```
The stuff you made was only possible because you worked outside of what is the public API.

HaxBall is not an open source project, reverse engineering the code and doing what you did goes against my wishes. It'd be nice if people respected the wishes of the author of the game they like so much. What you did feels like a slap in the face to me.
```

I think you misinterpret the screenshots. Maybe it comes at a surprise to you that this is all possible, but I haven't reverse engineered anything and everything is within the scope of your public API.

> Another important reason not to work outside of the public API (even if you don't give a shit about what my wishes are) is that things will break every time I release an update.

I'm just saying if you collaborate with _some_ bot devs, it would surely be constructive and fair if those discussions were public. So nobody is met with surprises on a one day notice. Not that I expect anything to break

Don't be mad, lol

**Comment by basro** [comment]
I apologize, I did misinterpret how you achieved what you did. The HBR format is not public api though, so parsing it will also break.

In any case, I did not work with anyone other than looking at the issues that were open here.

**Comment by mago-di-oz** [comment]
> I apologize, I did misinterpret how you achieved what you did. The HBR format is not public api though, so parsing it will also break.

No worries

It's something I had laying around since pre-html5 days. If along with a avatar setter, you could add a getter or a Player.avatar property, I'll ditch it immediately. Don't forget a onPlayerAvatarChange event in this case

On topic, would you be open to more collaboration or at least insights into your dev goals? 
> things will break every time I release an update.
For the simple reason that we are all devs, and since the birth of the API we have all taken it into completely different directions. Which is the beauty of it. But nobody wants to see their work be set back by months. 

We're already on the perfect platform for it

**Comment by Wolf72** [comment]
> 
 I know you know of my existence since my bot has clearly been an inspiration for all those bots out there and for most of the questions of "how do I add X" on here.

> 
Who are you? :d

**Comment by mago-di-oz** [comment]
> > I know you know of my existence since my bot has clearly been an inspiration for all those bots out there and for most of the questions of "how do I add X" on here.
> 
> Who are you? :d

> </rant>

 😇

**Comment by Wolf72** [comment]
Everything on that screenshot is made from api?
Ok so you are telling me if I join your room without downloading any extra software or without injecting any other script into haxball I would see everything exactly as on screenshot?
Room link? :D

**Comment by mago-di-oz** [comment]
> Everything on that screenshot is made from api?
Yes

> Ok so you are telling me if I join your room without downloading any extra software or without injecting any other script into haxball I would see everything exactly as on screenshot?
No

> Room link? :D
https://www.haxball.com/play?c=GcUfeM33AlY

**Comment by basro** [comment]
> On topic, would you be open to more collaboration or at least insights into your dev goals?

Sorry, but no. Collaborating and communicating takes a lot of energy in a one to **many** situation like this one.

My goals are to continue to do sporadic updates like I've been doing for 9 years.

Bug fixes are the highest priority for me, whenever something breaks I usually stop what I'm doing to fix HaxBall. Otherwise I'll work on new features which are often times influenced by the issues posted in here. But this is not a full-time gig, I have other projects and things I want to do with my life.

**Comment by Wolf72** [comment]
> > Everything on that screenshot is made from api?
> 
> Yes
> 
> > Ok so you are telling me if I join your room without downloading any extra software or without injecting any other script into haxball I would see everything exactly as on screenshot?
> 
> No
> 
> > Room link? :D
> 
> https://www.haxball.com/play?c=GcUfeM33AlY

Nothing innovative here, I could use my macro, standard bot like in other rooms idk why ur whining here xD

**Comment by mago-di-oz** [comment]
> > On topic, would you be open to more collaboration or at least insights into your dev goals?
> 
> Sorry, but no. Collaborating and communicating takes a lot of energy in a one to **many** situation like this one.
> 
> My goals are to continue to do sporadic updates like I've been doing for 9 years.
> 
> Bug fixes are the highest priority for me, whenever something breaks I usually stop what I'm doing to fix HaxBall. Otherwise I'll work on new features which are often times influenced by the issues posted in here. But this is not a full-time gig, I have other projects and things I want to do with my life.

It is what it is then

> Nothing innovative here, I could use my macro, standard bot like in other rooms idk why ur whining here xD

very cute. thanks for your input. had a bad night sleep?
![cute](https://user-images.githubusercontent.com/53398333/62007392-2271eb00-b14d-11e9-9efe-1e4be04ae626.jpg)
