### ISSUE TITLE
room.setPlayerDiscProperties - color

### ISSUE THREAD

**Issue by TurboFalafel** [haxball/haxball-issues#812]
![hxb1](https://user-images.githubusercontent.com/40662510/62027329-b2f80c00-b1dd-11e9-9ab9-64b965b025ff.PNG)

Am I doing something wrong, or is it impossible to change player disc color?

**Comment by Wolf72** [comment]
I think this has something to do with /colors overriding it maybe?

**Comment by basro** [comment]
It is impossible to change the color of a player because indeed the team colors take precedence.
