### ISSUE TITLE
Hey basro

### ISSUE THREAD

**Issue by Dr121** [haxball/haxball-issues#814]
Hi, I just wanted to congratulate you on the new haxball update. I think it's almost perfect, I would say it's not perfect because since you limited the extrapolation to 50 it is no longer possible to play because my character has become so unstable. that I can't control it if I could verify this that I commented or go back after the extrapolation update would be of great help since several players are stopping playing for this same reason

**Comment by basro** [comment]
Extrapolation change has been reverted.
