### ISSUE TITLE
thanks basro, you fucked up the game

### ISSUE THREAD

**Issue by meteus** [haxball/haxball-issues#815]
first, u created the extrapolation command and people played with it.

for me i played with 200 extrapolation cuz thats the only setting i can play without input lags. i became pro in 1v1 and 3v3, destroyed other pros because thats how supposed to be, no one fucking wants a smooth game, we want 0 input delay game is it hard to understand??? 

couple of lifeless noob faggot cried here in github issues then u decide to limit exp to 50, 
now everyone playing like noobs

good job fucking pro scene, good job forcing players to play with input lag

good job orospu çocuğu

**Comment by Wolf72** [comment]
ay lmao all those "pro" players bitching here

**Comment by meteus** [comment]
look, i played with extrapolation 200, and I'm used to playing like this. now changing it to 50 is destroying my game experience. physics are changed like hell to me. idk how can i explain that, but basro decided to win noob players with that decision, not pros.

**Comment by 4tires** [comment]
And what's the problem with noobs players, they don't deserve to play? I don't understand where you "pro" players got the feeling you're superior to the rest of the people.

**Comment by meteus** [comment]
are you kidding with me? does extrapolation 200 command only available to pro players? everyone can use that? you are talking like we are the only one can use extrapolation and act superior to other players. look even i got disadvantage cuz it shaky as fuck. but i am used to play like that, now forcing it to 50 is a horrible decision. maybe i have huge input lag and now i am forced to play with exp 50, can't be that happen? yeah if u are addicted to power, slowball or any autistic stuff like that yeah u hate extrapolation, but if u ever played in any league u would agree with me. forcing extrapolation to 50 is killing all pro players now. when we move to html5 90 percent of pro players left the game. now with that extrapolation 50 decision remaining 10 percent of pros left too. 

good job "creating" community with bunch of retarded basro. u lose all of the players who is here since beginning when classic, big is MAIN GOAL of this game. not some fucking dumbass power, speed or slow ball communities.

**Comment by Appur23** [comment]
I don't know why you're all in such a state of dramatics, extrapolation can be brought back, I already did it myself, I'm sure if you're motivated enough you can too. It wasn't removed, it was simply blocked off from people who don't know how to change a couple numbers around.

**Comment by basro** [comment]
This change has been reverted.

**Comment by vulonviing** [comment]
200 extra nedir amk? zaten yaptığınız turnuvalar almanya merkezli olmuyor mu? max pinginizi 70 civarı olması lazım. tamam değişiklik geri alınmışta, en sağlıklısı max 50'de sınırlanmasıydı. zorla anasını sikerek oynuyorsunuz oyunu

**Comment by meteus** [comment]
ya sana ne amına koyayım ben 150 de bile karakterimin 500 kg olduğunu hissediyorum. sana ne isteyen isteediği gibi oynar. ki zaten düşük expde oyuncular daha seri oynuyor. exp zaten komple dezavantaj fakat ben karakterimin yavaş olduğunu hissetmek istemediğim için 200de oynuyorum.

**Comment by vulonviing** [comment]
akelaa, bana discordunu ver kanka. seninle özel olarak tanışmak ve bu konu hakkında sohbet etmek isterim
