### ISSUE TITLE
YOU DID AN AMAZING UPDATE AND NOW YOU CANCELLED IT...

### ISSUE THREAD

**Issue by TheMaskedMan99** [haxball/haxball-issues#818]
I'M DONE OF HAXBALL FOR REAL. FINALLY WHEN I TOUGHT WE WOULD BE FREE OF ALL THE CANCEROUS GAMEPLAY EXTRAPOLATION BRINGS AND KNOWN ADVANTAGES TO THE PEOPLE THAT ABUSE OF THE FEATURE... with the great update you made.... now you reverted it.

Fuck this game for real. I'm done.

**Comment by basro** [comment]
The morale of this story is that the road to hell is paved with good intentions.
