### ISSUE TITLE
Haxball for map creators

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#82]
Hi Barso, my name is Leo and I create maps for haxball, the HTML5 HaxB have something differente from the Flash HaxB, a lot of maps were made knowing that 'discs' would always cover lines and players, like hide and seek, a part of Cops and Robbers by MC, where the player hid inside the disc, with the new HTML5 version, now discs cant cover players anymore, that means that maps that were made using that knowledge will no longer be useful, is it too hard to put that 'feature' back to work?

Thx. in advance
Leo ß

**Comment by basro** [comment]
Yes, this is a bug, I plan to fix it in the future.

**Comment by basro** [comment]
This should be fixed now.
