### ISSUE TITLE
About the gravity

### ISSUE THREAD

**Issue by rzBOSS** [haxball/haxball-issues#826]
When will it reach us players, the GRAVITY UPDATE to insert in our maps? And a complement: You will create the alternative to HaxPuck?

Sorry for my ignorance of the English language. I do not write very well. ¡Saludos!

**Comment by PheuxHWN** [comment]
Visit [GLH](https://grandesligashaxball.wixsite.com/grandesligashaxball)

There we will be uploading **updates**.

**Comment by basro** [comment]
Gravity and joints are already released. You'll have to edit maps with a text editor to use that though.
