### ISSUE TITLE
Headless host wiki typo

### ISSUE THREAD

**Issue by roknr** [haxball/haxball-issues#833]
There's a minor typo in the headless host wiki for the [getPlayerDiscProperties](https://github.com/haxball/haxball-issues/wiki/Headless-Host#getplayerdiscproperties). The parameter should probably be named "playerId" instead of "discIndex". Of course this doesn't impact the code, it just might confuse someone.

**Comment by basro** [comment]
Fixed it, thanks for reporting.

**Comment by roknr** [comment]
To avoid creating a new issue - another possible typo in the wiki [here](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#cgroup--float)? Shouldn't the type of the cGroup property be `string[]`?

**Comment by basro** [comment]
You are correct, thanks!

**Comment by roknr** [comment]
One more thing - either I can't find them or the [TraitsObject](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#traits--traitsobject) docs are missing?

**Comment by basro** [comment]
You are right, I also forgot about that. I'll write it later.
Thanks again
