### ISSUE TITLE
cGroup ["score"] problem

### ISSUE THREAD

**Issue by subxqns** [haxball/haxball-issues#835]
I'm trying to add some kickable discs which should also score goals. All of these discs have cGroup ["kick", "score"] but the latter is not working.

Also, it would be nice to have the default ball & player's physics for the original stadiums

**Comment by basro** [comment]
Show me the .hbs file you have created, if you don't want to show it publicly send it to haxball@gmail.com

**Comment by subxqns** [comment]
I was just testing so I didn't save it but I'll try to reproduce the error.

Anyway, after I tried addind those discs and failing to make them scorable I created another map in which I added one "extra ball" (cGroup["kick","score","ball" ] and cMask["red","blue","wall" ]) and at first it didn't score goals though it was kickable but then when I made a joint with that disc and the actual ball I could score goals with both.
It was weird beacause I didn't touch anything else on the code but that.
