### ISSUE TITLE
Player radius reset after each game event

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#836]
Since I can't upload a rec at the moment i'll explain
After putting a new player radius, when you score a goal/stop the match, the radius get back to the original.
No idea if it's the way you wanted to put it so I don't know if it's a bug but I still wanted to warm you

Oh and also, when you put a negative radius for someone, the ball just disappear.

**Comment by basro** [comment]
The reset is intended the player gets fully reinitialized on kickoff. There's also a new property in .hbs `StadiumObject.kickoffReset` that lets you set it up so that all discs get reset on kickoff instead of just the players and the ball.
