### ISSUE TITLE
players cant move/ are invisible after starting a game

### ISSUE THREAD

**Issue by kawawe** [haxball/haxball-issues#84]
After I just started a game in my room players couldn't move and were invisible:
[https://imgur.com/a/QPlkm](url)
[https://imgur.com/a/1J6lQ](url)

**Comment by Antiseptic** [comment]
It's a very rare behaviour but I saw it once too.
![invisible-players](https://user-images.githubusercontent.com/9195780/32143098-347551fc-bcad-11e7-83f1-e6625e34c0f0.png)

**Comment by basro** [comment]
This is now fixed.
