### ISSUE TITLE
Camera not following the ball on the intro menu

### ISSUE THREAD

**Issue by AnddyAnddy** [haxball/haxball-issues#845]
Well, that's the dumbest issue i ever reported
on the intro (haxball.com) I was watching the game in the background and I saw that the camera didn't follow well the ball when it went down
https://gyazo.com/4fddca3fde83ebcb10f4fda5e8c6ad15

This absolutely doesn't matter and nobody surely ever watched the intro till the end but still :D

**Comment by Leo-MapCreator** [comment]
Oh no, hax is broken

**Comment by pilaf** [comment]
The game in the homepage is a YouTube video stretched to fit the screen, so some parts of it may get chopped off if you're not on full-HD/full-screen resolution.

**Comment by basro** [comment]
As pilaf said, this ain't a bug that can be fixed.
