### ISSUE TITLE
SHUTDOWN HOST! ¿DDOS? After the update! Help! From Argentina.

### ISSUE THREAD

**Issue by tianewton27** [haxball/haxball-issues#848]
### Hello everyone ### 
**and mainly to the support of Haxball** 
I write this because I can't find a way to stop what was happening these days after the update...

People of Haxball Chile, found a way through a web page to be able to send you some kind of "ddos" to the computer and close the host, in addition to cutting off the internet connection for 3 or 5 minutes.
This not only affected the Chilean haxball community, but it did not spread to Argentina and they are closing host every day in the afternoon and evening.
PS: I tried to change the VPN of my internet and it worked for a while but then they did it again.
Posdata2: People of Chile are disclosing the IP and the page with which they execute this cut but nothing was confirmed yet.

I hope you find some solution to this problem since it is tedious to play knowing that the server will come to turn you off.

From already thank you very much.
 
> Tía Newton
from Argentina.
CONTACT:
[https://www.facebook.com/garippo2k19](url)

**Comment by basro** [comment]
Unfortunately I don't have a solution to this problem.

I'll be deleting this issue because it might incite others to do this. Feel free to contact me through email (haxball@gmail.com) to talk about it.
