### ISSUE TITLE
Not able to load stored stadium with changed background color.

### ISSUE THREAD

**Issue by awareofdistractions** [haxball/haxball-issues#850]
After using "/store" command, stadium is correctly saved.
It is showing on "Pick a stadium" list, but it is not possible to load it.
Neither double click nor "Pick" button works.
Other players confirmed this bug as well.
Developer console is showing that message:
> Uncaught (in promise) Bad color

The only value that seems to work is default:
`"color" : "718C5A"`

Loading .hbs file from disc works correctly.
I am attaching a problematic stadium saved as .txt (github requirement):
[gravity.hbs.txt](https://github.com/haxball/haxball-issues/files/3469324/gravity.hbs.txt)

**Comment by basro** [comment]
Definitely a bug, thanks for reporting.

I'll try to fix it soon.

**Comment by basro** [comment]
The bug should now be fixed.
