### ISSUE TITLE
Support for AI

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#853]
After looking at the RLBot community, a community that helps people build an AI for the game Rocket League, which is pretty much HaxBall in 3D with cars for those who do not know, and its rising popularity which brings many people in (their Discord has 1.3k), among them, many developers who can add many things to the game, I suggest HaxBall could use a similar system, which could help drastically the game in many ways.

It could bring many new people eager to develop an AI and their surroundings. Since those people know how to develop an AI, if they're interested in the game, they could then help out with the development of headless bots, but also other tools like haxpuck 2.0 or such. Headless bots could be so much better, having developed a bot myself, I know many more features could be done (and even more now with the new update!)

Furthermore, HaxBall looks like the perfect game for someone who wants to play with AI, since the mechanics are pretty simple, compared to other games, like Starcraft or Dota, but not too linear (otherwise players would have moved away pretty quickly).

So far, HaxBall is pretty closed, which is not helping. As an example, Psyonix, the company owning Rocket League has been helping the RLBot community since it could only help them.

Thanks for reading this long post.
Also, could we have the formulas used for the physics of the game ? Back then, you told you would publish it pretty soon, but it must have been something like 8 months ago or so. With the new map system, many people will try to do maps myself included, and having all the information could only help.

**Comment by AnddyAnddy** [comment]
Pm me on discord Anddy#2086

**Comment by gandeladri** [comment]
I created a similar issue a long time ago:
https://github.com/haxball/haxball-issues/issues/522

I'd love to play HaxBall against AI

**Comment by Wazarr94** [comment]
made my own project to support AI
