### ISSUE TITLE
[bug] conn doesn't works when onPlayerKicked

### ISSUE THREAD

**Issue by dapucita** [haxball/haxball-issues#857]
```
// PlayerObject conn : String
room.onPlayerKicked = function(kickedPlayer : PlayerObject, reason : string, ban : bool, byPlayer : PlayerObject) {
  console.log(kickedPlayer.conn);
}
```

> \> _undefined_

I found a problem that PlayerObject.conn hadn't been made when onPlayerKicked event called.
It will be more useful if PlayerObject.conn could be conveyed.

**Comment by basro** [comment]
This is not a bug.

The [conn](https://github.com/haxball/haxball-issues/wiki/Headless-Host#conn--string) property is only defined in the RoomObject.onPlayerJoin event.

**Comment by dapucita** [comment]
> This is not a bug.
> 
> The [conn](https://github.com/haxball/haxball-issues/wiki/Headless-Host#conn--string) property is only defined in the RoomObject.onPlayerJoin event.

Oh.. okay :)
