### ISSUE TITLE
Is it possible to run obfuscated scripts?

### ISSUE THREAD

**Issue by akelaa** [haxball/haxball-issues#860]
Hey Basaringaron, I want to give my headless script to some people but I don't trust them 100 percent. So I don't want to see my code at everywhere on the internet. So is it possible to run obfuscated  scripts in headless?

**Comment by dixtel** [comment]
yes, its impossible

**Comment by akelaa** [comment]
@dixtel Yeah got it. Thanks! 

I'm closing the issue.
