### ISSUE TITLE
HELP! my room becomes laggy after few hours

### ISSUE THREAD

**Issue by gamingmastar** [haxball/haxball-issues#861]
i made a stats count which save on hosted mysql database, when someone goal assist etc.. it sends request to php via xmlhttprequest() but
after sending 30, 40 request
my room start lagging
is there a solution?
function saveStats(player, goals, assists, wins, loses, og)
{

    var playerName = player;
    if(!checkConfirmPlayer.includes(playerName))
    {
        return false;
    }

      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
          return false;
        }
      };

      xhttp.open("POST", "https://examplewebsite/statsdata.php", true);
      xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
      xhttp.send("player="+playerName+"&goal="+goals+"&assist="+assists+"&win="+wins+"&lose="+loses+"&og="+og);
}
is there a fix ?

**Comment by akelaa** [comment]
Add me on Discord. 

akelaa#5231

**Comment by gamingmastar** [comment]
i fixed my problem, the problem came from room.ongametick i fixed it.

**Comment by akelaa** [comment]
That's nice. But still, add me. I am doing exact thing like you and I have couple questions on some stuff.

**Comment by akelaa** [comment]
@gamingmastar

**Comment by gamingmastar** [comment]
OK BRO

**Comment by gamingmastar** [comment]
i sent you a request, if you haven't received add me KDB#2519
