### ISSUE TITLE
info about admins actions

### ISSUE THREAD

**Issue by Wenomka** [haxball/haxball-issues#87]
If we have now info which user stopped match with pause, we need knows who unpaused game. 

+ will be nice knows who stopped game and started game aswell.

**Comment by Leo-MapCreator** [comment]
It is missing 'Player1' was moved to Red/Blue Team / Spectator, by 'Player2'

**Comment by Wenomka** [comment]
its not so important

**Comment by Leo-MapCreator** [comment]
Its a feature Flash had, and basro is going to put that back to work, it is important, im just writing it here so he remembers it

**Comment by basro** [comment]
This has been implemented for a long time now, forgot to close it.
