### ISSUE TITLE
sendAnnouncement HELP!

### ISSUE THREAD

**Issue by Mateusz-code** [haxball/haxball-issues#877]
Hi,
i have a little problem with room.sendAnnouncoucement function. How can i add style like a

> "normal","bold","italic", "small", "small-bold", "small-italic"

`        room.sendAnnouncement('Example text', player.id, 0xF4D03F);
`

for this code? Can someone give me a ready code, please :smile:

**Comment by saviola777** [comment]
It is perfectly documented [here](https://github.com/haxball/haxball-issues/wiki/Headless-Host#sendannouncement), just add one of the strings after the color.
