### ISSUE TITLE
Gamepad user

### ISSUE THREAD

**Issue by Teraquista** [haxball/haxball-issues#89]
Hi, i have an issue playing Haxball in HTML5 using my gamepad. When moving around the pitch, sometimes i will press the stick down (unavoidable) activating the button beneath it, this puts my avatar in permanent kick mode, slowing me down or kicking the ball at the wrong time. Is there anyway i can disable the stick button? Thanks Teraquista

**Comment by saviola777** [comment]
Gamepad support should be disabled with the recent update (see #11), is that not the case?

**Comment by Teraquista** [comment]
Thanks Sav, must have missed #11, just tested and my problem is a problem no more. Thanks all
