### ISSUE TITLE
Modifying properties of wall

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#890]
Hello, 

Today I tried out the new functions for modifying the properties of all discs, and it was really fun, I found many and many things to be done.

However, I've come to the point where I had ideas that would involve modifying wall properties, for many utilizations, like in a race, in competitive games, etc.
Will we ever have the possibility of editing the properties of walls ?

Right now, to have a line blocking people, I have to insert multiple discs when I could be using simply a line.

Thanks for that update, and the documentation has been great, after watching what was bitwise operation, it was a piece of cake to understand (also I think we should have getDiscList, because anyone manipulating discs will require that).

**Comment by Wazarr94** [comment]
To block people, it actually doesn't require modifying wall properties.

But it would still be nice to have the possibility of editing the cGroup, cMask, bias, position of extremity 1, position of extremity 2 !

**Comment by basro** [comment]
You can modify the cGroup of players, make a wall with cMask "c0" and then add or remove "c0" from the player's cGroup to toggle the wall collision for them.

At the moment everything other than the discs is immutable, there are performance costs that would need to be paid to make it mutable/modifiable in game.

**Comment by Wazarr94** [comment]
OK, thanks for the answer, that's what I figured. I'm going to make a thread for a weird interaction that i noticed. I'm trying to find the source of the problem I'm currently experiencing with planes.
