### ISSUE TITLE
Blocking planes

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#891]
Hello, after using a line to block c0 players, I tried using a plane to block players.

Working great, but it doesn't act as if it were a simple line. Let me explain in which way.

When I add c0 to the player cGroup, what happens is you get teleported on one side, depending whether you're in one half or another.
Reading the documentation, I don't think it's the intended behavior.

Screenshots of classic map with plane added with following properties :
`{ "bCoef" : 0, "cMask" : ["c0" ], "dist" : -230, "normal" : [1,0 ] }`

Before the command `room.setPlayerDiscProperties(1, {cGroup: playerDiscProps.cGroup | room.CollisionFlags.c0});` :

https://i.gyazo.com/ef322b51f49c9ecf29995de6fb7d313c.png

After the command :

https://i.gyazo.com/65eb2ff9afd1d7086857c5b4664a69af.png

Since I'm on the left side, I get TP'd to the right of the plane. If I'm on the right, I get TP'd to the left of the plane. And I cannot teleport myself to the left of the plane using the command `room.setPlayerDiscProperties(1, {x: -400});`

Is it a bug or a feature ?

**Comment by basro** [comment]
> If I'm on the right, I get TP'd to the left of the plane.

This shouldn't happen, are you sure this is what happens? Could you describe that part better?

**Comment by Wazarr94** [comment]
Yes, absolutely certain, I've tested it 4 times on a custom map and then on the classic map, which I include below.

To reproduce : Get in a headless room, load the map and put yourself, go the most left and then use the command `room.setPlayerDiscProperties(1, {cGroup: playerDiscProps.cGroup | room.CollisionFlags.c0});`, then observe where your player is.

You can try the command `room.setPlayerDiscProperties(1, {x: -400});`, and nothing should happen.

[classic-modified.txt](https://github.com/haxball/haxball-issues/files/3591431/classic-modified.txt)

**Comment by basro** [comment]
> go the most left and then use the command

What I mean that should not happen is moving from the right to the left. Being moved from the left to the right would be expected and correct.

**Comment by Wazarr94** [comment]
OK, then it's working as expected. 

I thought it should act exactly as a line.

For a line, players on the left side on the wall do not get teleported.

**Comment by basro** [comment]
If you negate both the dist and normal it will flip the plane.
`{ "bCoef" : 0, "cMask" : ["c0" ], "dist" : 230, "normal" : [-1,0 ] }`

**Comment by Wazarr94** [comment]
Very nice, working very nicely, useful to know for maps, thanks
