### ISSUE TITLE
Real Soccer Haxball Bot

### ISSUE THREAD

**Issue by Gimenez20** [haxball/haxball-issues#894]
Hello, I am a Spanish player who try to create automatic bots, and I need help to create a real soccer bot.
If anyone can create it, it would do me a great favor.
Here I have a template of a futsal bot, and I would like it to have that configuration but adding that the game will run in 4v4 in Real Soccer.

Template: https://pastebin.com/mbTWndjA

**Comment by xRoos3velt** [comment]
@Gimenez20 can u add me on Discord plz
I need ask something to you.
xRoos3velt#3441
