### ISSUE TITLE
Ping Value

### ISSUE THREAD

**Issue by Leo-MapCreator** [haxball/haxball-issues#90]
I was playing in a room at the ping graph had almost every bar over the limit, which i think its 999, if im not mistaken 17/20 bars where over it, but the ping was only around 500, even though the max ping was much higher than 999, the math doesnt seem right, how is the ping calculated in HTML5?

**Comment by Leo-MapCreator** [comment]
Assuming 17 bars were at 999, and the others 3 were 0, the math indicates that the ping needs to be AT LEAST 849,15

**Comment by basro** [comment]
The graph shows the range between 0 and 400ms, bars higher than 400ms high are clipped.
