### ISSUE TITLE
Performance issues on Chrome on certain maps (+ Chromium-based browsers) ?

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#903]
Hello, 

Wanted to play some futsal in public, the popular map of today, but I was stunned to see my framerate going to 30 (I have a good PC) and my ping rising up.
I use Brave, and do not experience this on other browsers (I tested Opera and Mozilla).

When I'm alone on a public futsal room, I don't experience anything, only when another person comes.
I keep mentionning Futsal, because for a reason that leaves me clueless, it only happens on this map (the map is characterized a small and fast ball).

Also, another player also had this issue on Chrome.

If you need any detail on this, I'm here.

**Comment by mob-hash** [comment]
Oh yes thats happening me too. If map is custom and big size im having FPS drop and lag. But same room, they open any default map lag is gone and also fps is fixed too.

**Comment by Wazarr94** [comment]
Bump, I'm seeing more players having this issue.

Any update on this ?

**Comment by Raamyy** [comment]
I also have this problem with LongBounce maps.

I have to reduce the resolution to 50% to maintain the 60 fps.

**Comment by basro** [comment]
It seems like a change in chrome has cause a performance regression in HaxBall.

I'm investigating.

**Comment by basro** [comment]
I've deployed a fix/workaround, please refresh the site and see if the situation improved for you.

**Comment by Wazarr94** [comment]
Fine for me, I'll close this after I get more feedback from people who experienced the issue

**Comment by Wazarr94** [comment]
It's fixed, but I've heard of another issue.

One player is used to play with 75 fps, after the update he is stuck with 60. Anything on that ?
Thanks for the fix, appreciate it 👍
