### ISSUE TITLE
Auth with salt

### ISSUE THREAD

**Issue by nxta** [haxball/haxball-issues#921]
Many rooms use PlayerObject.auth for authentication, including mine. This however is really unsafe. I have a large collection of players' auth keys and I should be able use them to log in to other rooms. You could certainly do it in mine... 😛

I added a check for PlayerObject.conn for the time being, but now my laptop playing peoples who play at school can't authenticate when they are home.

Please add a optional RoomConfigObject.salt property in order to make PlayerObject.auth one that we can't abuse across rooms.

**Comment by saviola777** [comment]
I do not think that's how the auth property works, at least I hope it isn't. If you try to use someone else's auth, the ID validation should fail.

**Comment by nxta** [comment]
You're right I can't set my own auth by changing the localStorage value. Ofcourse I didnt try until AFTER I posted haha

Regardless it's a property that should be salted

**Comment by Wazarr94** [comment]
The auth you have in headless is the public auth.
You can impersonate people if you have their private auth.

See https://www.haxball.com/playerauth

**Comment by sublime801** [comment]
wtf 

> I have a large collection of players' auth keys and I should be able use them to log in to other rooms.
