### ISSUE TITLE
problems with replays on custom maps

### ISSUE THREAD

**Issue by Wenamka** [haxball/haxball-issues#926]
[HBReplay-2019-10-12-03h09m.zip](https://github.com/haxball/haxball-issues/files/3721770/HBReplay-2019-10-12-03h09m.zip)

Probably only im see that issue, but after some time in the replay i see like all of players move without ball and ball stopped in random place and no one touching it.

**Comment by Wenamka** [comment]
[HBReplay-2019-10-12-04h07m.zip](https://github.com/haxball/haxball-issues/files/3721777/HBReplay-2019-10-12-04h07m.zip)
more

**Comment by basro** [comment]
It does look like a bug.

Could you give me the stadium file that is being played in the replay?

**Comment by Wenamka** [comment]
[haxmaps_144522153775 (1).zip](https://github.com/haxball/haxball-issues/files/3722138/haxmaps_144522153775.1.zip)
i guess this map, im not sure cuz admin of public could modificate it

**Comment by basro** [comment]
This bug has now been fixed.
The source of the problem was the setDiscProperties headless room method. Luckily the problem was on the client side so there's no need to restart the rooms for the fix to work.
