### ISSUE TITLE
Option to disable [ /store ] command in headless rooms

### ISSUE THREAD

**Issue by totallylucky** [haxball/haxball-issues#933]
**Why should there be this option?**
Main reason is for rooms to have **original** maps that would increase originality for **specific type of headless rooms**  and potentially decrease number of copycat rooms who just "/store" map then export it and make very minimal modifications such as change it's name and maaaybe color changes..

This change can cause competition for originality between headless rooms which can result in improvement in better rooms and community in general.

**Comment by basro** [comment]
The feature already exists: [Docs](https://github.com/haxball/haxball-issues/wiki/Stadium-(.hbs)-File#canbestored--boolean).
