### ISSUE TITLE
Repeat Chat [Title | Name | Message]

### ISSUE THREAD

**Issue by kauanmity** [haxball/haxball-issues#947]
I wanted to know this kind of witchcraft in BOT, that it writes your title, name and the message you wrote, could anyone help me? I'm desperate for that.

Witchcraft:
![image](https://user-images.githubusercontent.com/56240913/68092091-75eb8780-fe66-11e9-9f88-a4f45cf981d4.png)

**Comment by saviola777** [comment]
Similar answer as the other issue:

Use `onPlayerChat`, then call `room.sendAnnouncement` with the player nick and message and the color you want and return `false` from `onPlayerChat`.

**Comment by kauanmity** [comment]
Could you give me a base? I'm kind of new to these moves, I want to take a course, but I don't know if it's going to do anything
@saviola777

**Comment by kauanmity** [comment]
> Similar answer as the other issue:
> 
> Use `onPlayerChat`, then call `room.sendAnnouncement` with the player nick and message and the color you want and return `false` from `onPlayerChat`.

![image](https://user-images.githubusercontent.com/56240913/68093159-81907b80-fe71-11e9-9338-ec7642a42345.png)

**Comment by saviola777** [comment]
If this happens you did not return `false` from the `onPlayerChat` handler.
