### ISSUE TITLE
Getting "Master connection error" when trying to join other rooms etc.

### ISSUE THREAD

**Issue by daklaj** [haxball/haxball-issues#95]
As the title says i keep getting this error when trying to join any room. The rooms I host don't appear on public list and I'm even unable to get a direct link to my room cause when I try i got this message: "Waiting for link" instead of the link.
I have inspected the network activity and it seems like whenever I try to join a room I'm receiving a code 500 reponse to `GET http://p2p2.haxball.com/client?id=XYZ` so I believe the problem is not on my side.
I have tried different browsers and did the reverse connection thing.

**Comment by basro** [comment]
Hello, do you know if you are behind a proxy?
Please tell me if you can connect and send messages in this site: http://demos.kaazing.com/echo/

**Comment by basro** [comment]
Hello, is it possible that

**Comment by daklaj** [comment]
> Hello, do you know if you are behind a proxy?
I'm not behind a proxy. I'm connecting to the Internet via local academic network.
> Please tell me if you can connect and send messages in this site
Uhh, I'm not even able to connect.

**Comment by basro** [comment]
@daklaj, please open and run this JSFiddle: https://jsfiddle.net/qvrqmv83/1/

The bottom right panel should print:
```
attempting to connect
connected
Received echo: hi
```

**Comment by daklaj** [comment]
> Please tell me if it does or doesn't print that.

It does.

**Comment by basro** [comment]
Ok.. you are probably behind a crappy proxy that breaks WebSocket connections when they are not through a secure channel.
I'll see if I can implement SSL for haxball websockets, that would fix this problem for you.

**Comment by gavin0266** [comment]
Hi basro, I'm getting this same error message. I am able to connect & follow instructions for both of the links above but still aren't able to connect to any server. As far as I'm aware of I'm not behind any proxy/vpn at all. However sites like http://amibehindaproxy.com/ do suggests that I am behind some kind of proxy (which i'm not aware of).

**Comment by basro** [comment]
@gavin0266, I still haven't implemented SSL but when I do (soon tm) I'll post here and hopefully you can tell me if it fixes it for you.

**Comment by basro** [comment]
I appologize for the long wait, I've now released an SSL enabled version of haxball that probably fixes this issue.
