### ISSUE TITLE
System of Register and Login

### ISSUE THREAD

**Issue by kauanmity** [haxball/haxball-issues#950]
``I was wondering if anyone could help me make a registration and login system, I've been looking for this for a while, and honestly, I have no idea how it's done.``

**Comment by kauanmity** [comment]
@basro 
@saviola777

**Comment by alebcj** [comment]
Hi @kauanmity  there are several ways of making account systems. Search github for headless haxball scripts and u could extract some of there, in case you don´t know how to make them.

**Comment by kauanmity** [comment]
`read the issue` **#955**
@alebcj
