### ISSUE TITLE
An example of a goal message with distance

### ISSUE THREAD

**Issue by wohSi** [haxball/haxball-issues#952]
An example of a goal message with a function of distance from the ball to the goal like "Goal Red............... from 20M", do not know how I can start the feature.

**Comment by Raamyy** [comment]
Keep track of the distance of the ball from the two goals on every ball touch and when ```onGoalScored``` event is triggered you get the ball distance for the scored goal.

I think that there is ball position attributes that you can use to measure the ball distance from the goals.
