### ISSUE TITLE
spawnDistance explanation ?

### ISSUE THREAD

**Issue by Wazarr94** [haxball/haxball-issues#964]
Hello, i am looking at haxball physics, and I have trouble understanding how spawnDistance works. I had expected that a spawnDistance of 170 put you at a distance of 170 from the center of the ball, but I observe a distance of 277.5.

If you could explain precisely how that works, I'd appreciate.

**Comment by Leo-MapCreator** [comment]
"spawnDistance" : x, 
gives a distance of x to the center of the ball for each team, every player will spawn in the same x, for different y, spaced of 50 or 55 if im not mistaken

**Comment by Wazarr94** [comment]
Problem being that it's not the case.

Look at the position of the players in Classic. We have a spawnDistance of 170, yet the players spawn at x = +-277.5

**Comment by Leo-MapCreator** [comment]
That does not happen, they spawn at 170 for "classic" and 350 for "big"

**Comment by Leo-MapCreator** [comment]
Maybe there is something wrong with your code or you are measuring it differently

**Comment by Wazarr94** [comment]
Please check using headless, after starting a game in Classic, the players spawn at x: -277.5.

Thanks for your time anyway

**Comment by Leo-MapCreator** [comment]
Measure using segments in the map

Create a segment with both vertex at x = 170 and opposite y's
You will see the player is at the middle of the segment

**Comment by Wazarr94** [comment]
OK, I found the issue.

The Classic Map has a spawnDistance of 227.5 for some reason, which was not the case some time ago.
My apologies.
