### ISSUE TITLE
Deleted.

### ISSUE THREAD

**Issue by gama1016** [haxball/haxball-issues#966]

**Comment by sublime801** [comment]
Buy a virtual server with DDOS protection.

**Comment by HonestSquare** [comment]
> Buy a virtual server with DDOS protection.

LOL

**Comment by Ansu1Fati** [comment]
Hi idk if its ddos but i have allot of red lines while my ping is good i rlly hope u will reply soon bcs i play in leagues and it can be bad for my reputation
