### ISSUE TITLE
Mentioning players?

### ISSUE THREAD

**Issue by axandrew** [haxball/haxball-issues#975]
This is probably a really simple question: how can I program Headless Host to mention a player?
(tag them using "@<name>", will result in different sound effect and bolded text). Thank you!

**Comment by Raamyy** [comment]
I think @{player.name} will do the work

**Comment by axandrew** [comment]
> I think @{player.name} will do the work

So I think the problem I am encountering is when a username has spaces in between, the bold + mention sound effect doesn't trigger. For instance, "@username" works but "@user name" does not. Is there any workaround for this?

**Comment by Raamyy** [comment]
You should join it with underscores

for example if somebody's name is ```I am Andrew```

The mention should be **@I_Am_Andrew**

**Comment by axandrew** [comment]
> You should join it with underscores
> 
> for example if somebody's name is `I am Andrew`
> 
> The mention should be **@I_Am_Andrew**

Perfect, thank you!
