### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ToderitaGeorgeCristian** [haxball/haxball-issues#976]
Hi !
Was trying to use puppeteer with : 
const Sequelize = require('sequelize');

I guess only vanilla js is allowed in headless ?

My goal was to have a common sqlite.database and use it with a discord bot for registrations etc ...
On top of my head, I could somehow use express on same-origin and exchange data, but it overcomplicates things...

Any ideeas on a different approach ?

**Comment by Wazarr94** [comment]
require is from nodejs.

maybe you could use nodejs, it could be easier

**Comment by ToderitaGeorgeCristian** [comment]
@Wazarr94 
It is from Nodejs surely.
Problem is we cannot expose node_modules through puppeteer, which is normal.
But this forces to use some other cumbersome approach in headless script to connect with a databse.

Would've been easier with an SQL module, but now I have to go around using Fetch.
Hopefully it works.
Any other ideeas would be helpful :)

P.S : Does anyone know how I could expose the puppeteer page console so I could have control over room ?

**Comment by Wazarr94** [comment]
I dealt with that by doing the database stuff on the nodejs side, and then using evaluate so the room loads the database into the localStorage.

Also, I had managed to load Discordjs with express, but I think it is too annoying to do, you need to use some dirty tricks to go around CORS.

**Comment by ToderitaGeorgeCristian** [comment]
@Wazarr94 
localStorage has limited space and capabilities...
I used it for a limited time and let it aside.

Can you add me on discord ? 
drtoothy#3486

**Comment by ToderitaGeorgeCristian** [comment]
Closing this thread as it is not an issue per se
