### ISSUE TITLE
Street Race 4000 Bug and distortonated images

### ISSUE THREAD

**Issue by IronCroos** [haxball/haxball-issues#979]
So when I load the MC street race maps and laser race map from haxmaps the game gets distortonate d and buggy at some portions then i loads well. The maps worked well in the past. The balls moving around leaves traces and the race gets pixaled and unplayeble. However after you get past that portion with buggy obstacoles if you manage around then the map is allright. Also some other maps seem not to work anymore. Must be from an uptade?

Note that the maps are loaded and fine into haxpuck.

**Comment by IronCroos** [comment]
manage to fix the maps by switching from hockey b to grass b. It is still weird bug since the maps worked well before in hockey mode as they we're designed. The grass background teleports the players instantly on the starting lane when loading map. But in hockey mode the map goes from center to way back to the starting lane and it ruins the maps with traces and shadows of balls and lines.

**Comment by basro** [comment]
Please give a link or attach the maps in question

**Comment by IronCroos** [comment]
the maps are on haxmaps.com. Very easy to find. They are called street_racing 30000

**Comment by basro** [comment]
This should be fixed now.
