### ISSUE TITLE
[HELP] Error on Code

### ISSUE THREAD

**Issue by wohSi** [haxball/haxball-issues#981]
Greetings I am getting a strange error on my code.

`room.onTeamVictory = function (scores) {
...
if (scores.blue > scores.red) {`

Says -> **Uncaught TypeError: Cannot read property 'blue' of null**

_In other code works but in this it's not working_

**Comment by Wazarr94** [comment]
I believe the game is stopped before or as the event is called, causing scores to be null.
Or there's an earlier error messing things up.

**Comment by wohSi** [comment]
@Wazarr94 wanna see it?

**Comment by Wazarr94** [comment]
Sure

**Comment by Raamyy** [comment]
Can you post the whole function?

**Comment by ToderitaGeorgeCristian** [comment]
@wohSi share all code to see posibile errors

**Comment by wohSi** [comment]
@Raamyy @ToderitaGeorgeCristian already fixed, thanks anyways!
